ScoopInstaller/Extras

bucket/powertoys.json

powertoys@0.66.0: Add arm64

---

bucket/autohotkey.json

Relates to https://github.com/ScoopInstaller/Extras/commit/3bdc740916fbb64121df51b2bcc051501e9bd6f6#commitcomment-95121357

autohotkey@2.0.2: Path escape 

---

bucket/thisiswin11.json

thisiswin11: folder in .zip fix

---

bucket/homebank.json

homebank: download path has moved

---

bucket/springboot.json

Closes #10188
https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023

springboot: Switch to 'Maven Central'

---

bucket/rancher-desktop.json

Closes #10114
No more `install-wsl.ps1` file is present in the Setup EXE file, but a `elevated-install.ps1` file seems to have replaced it:
in its header
```
```
and mandatory `InstallDir` param to provide, given
```
param(
[ValidateSet("Initial", "Kernel")] $Stage = "Initial",
$InstallDir
)
```

rancher-desktop: Fix installation and Update `notes`

---

bucket/keepass-plugin-keetheme.json

Adds the manifest for the keepass plugin [keetheme](https://github.com/xatupal/KeeTheme)
Closes #9996

keepass-plugin-keetheme: Add version 0.10.1

---

bucket/sidekick-browser.json

- Update to version 108.34.1.29019-b885871
- Update checkver and autoupdate
Closes #10223

sidekick-browser: Update manifest

---

bucket/autohotkey.json

Shortcuts created via installs sub-versions will not be re-created. e.g. ahk2exe
Relates to https://github.com/ScoopInstaller/Extras/pull/10185#issuecomment-1373627847

autohotkey: Persist subversions

---

bucket/sunshine.json

sunshine@0.17.0: add new folder for config files

---

bucket/opennbs.json

opennbs: Add version 3.10.0

---

bucket/termius.json

termius@7.55.2: Fix url

---

bucket/tla-plus-toolbox.json
bucket/tlaplus-toolbox.json

tlaplus-toolbox: Add version 1.7.1

---

bucket/kiwix.json

kiwix: Add version 2.3.1

---

bucket/lively.json

A free and open-source software that allows users to set animated desktop wallpapers and screensavers.

lively: Add version 2.0.5.0

---

bucket/4gb-patch.json

4gb-patch: Add version 1.0.0.1

---

bucket/quickcpu.json

quickcpu: Add version 4.5.2.0

---

bucket/rambox.json

Update URLs for homepage and license.

rambox@2.0.9: Update urls

---

bucket/natscli.json

Closes https://github.com/ScoopInstaller/Main/issues/4267

natscli: Add version 0.0.35

---

bucket/popcorn-time.json

popcorn-time: Add version 0.4.9

---

bucket/onionshare.json

onionshare@2.6: Update manifest for latest version

---

bucket/android-sdk.json

android-sdk@4333796: Add more packages to persist.

---

bucket/ddu.json

ddu@18.0.6.0: remove extract_dir

---

bucket/fancontrol.json

fancontrol: Fix `url`, and `regex`

---

bucket/inkscape.json

inkscape: Fix `checkver.script` & Update to version 1.2.2_2022-12-09_732a01da63

---

bucket/lazy-posh-git.json

Adds lazy-posh-git version 0.1.0

lazy-posh-git: Add version 0.2.0

---

bucket/ddu.json

- revert `extract_dir`
- remove install script
Closes #XXXX

ddu@18.0.6.0: Fix installation

---

bucket/emeditor.json

emeditor: Update to version 22.2.0

---

bucket/mpv.net.json

mpv.net: Update to version 6.0.3.0

---

bucket/roam-research.json
bucket/roamresearch.json

roamresearch: Add version 0.0.15

---

bucket/nordpass.json

nordpass: Add version 4.36.24

---

bucket/feem.json

feem: Add version 4.3.0

---

bucket/thisiswin11.json

thisiswin11: remove extract_dir

---

bucket/pdfsam.json

pdfsam: extract_dir fix

---

bucket/pdfsam.json

pdfsam: fix `extract_dir`

---

bucket/fu.json

A modern `du` replacement, with new features and a better output, written in rust

add fu 1.0.1

---

bucket/netbeans.json

- Add `suggest`
- Add `post_install` for pre-configuration
- Add `bin` for cli
Closes #10393

netbeans: Improvement manifest

---

bucket/rssguard.json

rssguard: Fixed checkver and autoupdate properties 

---

bucket/ariang-native.json

ariang-native: Add Version 1.3.2

---

bucket/whkd.json

whkd: Add version 0.1.0

---

bucket/komac.json

The Kotlin manifest creator for WinGet

komac: Add version 1.0.1

---

bucket/sunshine.json

All configs are now in the `configs` folder.

sunshine: Update `pre_install`

---

bucket/discrakt.json

Easy to Use Trakt/Plex Discord Rich Presence

discrakt: Add version 2.2.4

---

bucket/mpv-git.json
bucket/mpv.json

mpv(-git): Update `notes`

---

bucket/ani-cli.json

Basic metadata description update
Closes #10443

ani-cli: Update description

---

bucket/ani-cli.json

ani-cli: Update dependencies, Rearrange fields

---

bucket/tinynvidiaupdatechecker.json

Fixing TinyNvidiaUpdateChecker URL and updating its version
Closes #XXXX

tinynvidiaupdatechecker: Fix url

---

bucket/transmission.json

transmission: Update to version 4.0.0

---

bucket/usbimager.json

usbimager: Add version 1.0.9

---

bucket/capframex.json

update capframex to version 1.7.1

---

bucket/saber.json

saber: Add version 0.9.2.9020
https://github.com/adil192/saber

saber: Add version 0.9.2.9020

---

bucket/butterfly.json

butterfly: Add version 1.6.1
https://docs.butterfly.linwood.dev/

butterfly: Add version 1.6.1

---

bucket/retroarch.json

retroarch: Add `downloads` to `persist`

---

bucket/filezilla-server.json

filezilla-server: Update to version 1.6.6

---

bucket/sublime-merge.json

sublime-merge: Better checkver

---

bucket/librewolf.json

remove LibreWolf-WinUpdater

---

bucket/chatgpt.json

chatgpt: Update to version 0.11.0 and fix checkver

---

bucket/mp3tag.json

mp3tag: Add 64-bit support

---

bucket/libreoffice.json

Relates to: updating LibreOffice to 7.5.0.3 (latest version)

libreoffice: Update to version 7.5.1.1

---

bucket/sunshine.json

sunshine: Update to version 0.18.4, Fix autoupdate

---

bucket/icnsify.json

CLI to easily convert `.jpg` and `.png` to `.icns` and vice versa

icnsify: Add version 2.2.1

---

bucket/cutter.json

cutter@2.2.0: Fix extract_dir

---

bucket/icnsify.json

`icnsify` has switched to zip archives

icnsify: Update to version 2.2.4, Fix urls

---

scripts/harmonoid/install-harmonoid-associations.ps1

Relates to https://github.com/ScoopInstaller/Extras/pull/10637

harmonoid: Fixed install-harmonoid-associations.ps1 so it can correctly install associations.

---

bucket/winsshterm.json

winsshterm: Update to version 1.25.1 and fix manifest

---

bucket/wingetui.json

wingetui: Fix checkver

---

bucket/coreftp.json

coreftp: Use https

---

koodo-reader.json

koodo-reader: Add version 1.5.2

---

bucket/multicommander.json

multicommander: Use https

---

bucket/responsively.json

responsively: Update to version 1.1.0

---

bucket/openai-translator.json

openai-translator: Add version 0.0.23

---

bucket/speccy.json

speccy: Update to version 1.32.803 and add autoupdate

---

bucket/imhex.json

Fixed it so that it only removes the context menu when the user passes the **uninstall** parameter.

imhex: Fixed `pre_uninstall`, `checkver`, and `autoupdate.url`.

---

bucket/lwp.json

Adds LWP: https://github.com/jszczerbinsky/lwp

lwp: Add version 1.5

---

bucket/prusaslicer.json

- Update checkver (passing alpha releases)
- Update *.extract_dir
Closes #10889

prusaslicer: Update manifest

---

bucket/wechat.json

wechat: Update Version 3.9.2.23

---

bucket/wechat.json

Edit scripts to adapt for new installer file contents
Closes #10897

wechat: Fix installation scripts

---

bucket/vncviewer.json

vncviewer@7.0.1: Fix url

---

bucket/cudatext.json

- Fix checkver, autoupdate
- Update to version 1.190.0.0
Closes #10831

cudatext: Update manifest

---

bucket/antidupl.net.json

antidupl.net@2.3.11: Fix `bin`, `shortcuts`

---

bucket/dadroitjsonviewer.json

dadroitjsonviewer: Update to version 2.0.1.845 and fix auto-update

---

bucket/nilesoft-shell.json

nilesoft-shell: Update to version 1.8.1 and fix autoupdate

---

bucket/librewolf.json

librewolf: Update to version 111.0.1-1 and fix autoupdate

---

bucket/chatterino7.json

chatterino7: Add version 7.4.2

---

bucket/twitchdownloader.json

Fixed TwitchDownloader Shortcut
Fixed Shortcut (Added WPF)
No Issues
- [V] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Fixed TwitchDownloader Shortcut

---

bucket/clash-mini.json

clash-mini: Update to version 0.2.2 & fix autoupdate

---

bucket/64gram.json

64gram: Update to version 1.0.70 & drop 32bit support

---

bucket/appflowy.json

appflowy: Update to version 0.1.0 & fix autoupdate

---

bucket/opentrack.json

opentrack: Update to 2022.3.2 & fix autoupdate

---

bucket/ngspice.json

ngspice: Update to version 39 & fix autoupdate

---

bucket/pwsafe.json

pwsafe: Update to version 3.62.0 & fix autoupdate

---

bucket/clash-verge.json

clash-verge: Add Version 1.2.3

---

bucket/kate.json

kate: Update to version 22.12.3 and fix autoupdate

---

bucket/okular.json

okular: Update to version 22.12.3 and fix autoupdate

---

bucket/elisa.json

elisa: Update to version 22.12.3 and fix autoupdate

---

bucket/extraterm.json

extraterm: Update to version 0.71.0 and fix autoupdate

---

bucket/filelight.json

filelight: Update to version 22.12.3 and fix autoupdate

---

bucket/cdburnerxp.json

cdburnerxp: fix download url & checkver

---

bucket/v2rayn.json

v2rayn: *Major* Update to 6.21

---

bucket/usbimager.json

Relates to https://github.com/ScoopInstaller/Extras/actions/runs/4665444978/jobs/8258824959#step:3:642

usbimager: Fix checkver

---

bucket/virt-viewer.json

virt-viewer: Fix checkver

---

bucket/xmind.json

 xmind: Update to version 22.11.3656 and fix checkver 

---

bucket/win-gpg-agent.json

Remove automatic update checks as the upstream software repository has been put into a read-only archive state.

win-gpg-agent: Remove autoupdate

---

bucket/stremio.json

stremio: Update to version 4.4.159 and fix checkver

---

bucket/tomcat.json

tomcat: Update checkver

---

bucket/so.json

so: Fix checkver

---

bucket/saber.json

saber: Update to version 0.11.4.11040 and fix autoupdate

---

bucket/switchhosts.json

switchhosts: Update to version 4.1.2.6086 and fix autoupdate

---

bucket/resource-hacker.json

resource-hacker: Update to version 5.1.7 and fix checkver

---

bucket/pencil.json

pencil: Update to version 3.1.1 & drop 32bit support

---

bucket/prime95.json

prime95: Fix checkver

---

bucket/neovide.json

neovide: Update to version 0.10.4 and fix autoupdate

---

bucket/nekoray.json

nekoray: Update to version 2.24

---

bucket/nheko.json

nheko: Update to version 0.11.3 and fix autoupdate

---

bucket/magicavoxel.json

magicavoxel: Fix checkver

---

bucket/kid3.json

kid3: Update to version 3.9.3-1 and fix checkver

---

bucket/liteide.json

liteide: Update to version 38.2 and drop 32bit support

---

bucket/meshroom.json

meshroom: Update to version 2023.1.0 and fix autoupdate

---

bucket/kiwi-for-gmail.json

kiwi-for-gmail: Update to version 3.6.2 and fix autoupdate

---

bucket/coppeliasim.json

coppeliasim: Update to version 4.5.1 and fix autoupdate

---

bucket/mindforger.json

mindforger: Fix checkver

---

bucket/soundswitch.json

soundswitch: Update to version 6.6.0 & fix autoupdate

---

bucket/skype.json

skype: Update to version 8.96.0.207 and fix checkver

---

bucket/postman.json

Closes #8973
Relates to #9582
Every time Postman is upgraded, it must call Update.exe from the previous directory to perform some post-update actions. An attempt has been made to create a fake Update.exe to trick Postman but it doesn't work.
So this pull request solves the problem of Postman not starting after each update by putting the main application in the app folder and update in the root directory.
The old error message reported:
```
1681030524998 main info "@postman/app-updater: version Updated", "10.9.4", "10.12.0"
1681030525007 main info "UpdateHandler~app-update-events - Received event",{"name": "electronVersionUpdated", "namespace": "appUpdate"," data":{"lastKnownVersion": "10.9.4", "currentVersion": "10.12.0"}}
Error: spawn C:\Users\Kevin\scoop\apps\postman\Update.exe ENOENT …
```

postman: Fixing an issue that prevents opening after an update

---

bucket/treesize-free.json

Added:
```json
"persist": [
"GlobalOptions.xml",
"RibbonOptions.xml"
],
```
Closes #XXXX

Persist TreeSize-Free settings

---

bucket/pencil.json

Relates to https://github.com/ScoopInstaller/Extras/pull/10979#issuecomment-1503787643

pencil: Fix installation

---

bucket/librewolf.json

librewolf: Remove ScheduledTask

---

bucket/yed.json

Fixes broken UI with at least graalvm and zulu-jre Java runtimes
Closes #10779

yed@3.x: provide jvm options in the start script to fix broken UI rendering

---

bucket/musicbee.json

musicbee: Update to 3.5.8447 and improve checkver

---

bucket/cuetools.json

cuetools: update persist options

---

bucket/foxmail.json

foxmail: Add version 7.2.25.213 with new checkver

---

bucket/privatezilla.json

privatezilla: Add scripts download url

---

bucket/languagetool.json

languagetool: update to windows desktop version 1.0.10

---

scripts/windows-terminal/install-context.reg

windows-terminal: Fix install-context script

---

bucket/paperwork.json

Also change `checkver`, and fixed `autoupdate`.
Closes #9908

paperwork: Add `architecture`, fixed `url`, fixed `hash`

---

bucket/robocopy-gui.json

robocopy-gui: Use archived link

---

bucket/umbrello.json

umbrello: Update homepage

---

bucket/chromium.json

Relates to https://github.com/ScoopInstaller/Extras/actions/runs/4673276062/jobs/8276331773#step:3:397

chromium: Fix checkver

---

bucket/notesnook.json

notesnook: Add arm64 architecture and fix checkver

---

bucket/kopiaui.json

Relates to https://github.com/ScoopInstaller/Extras/actions/runs/4682555879/jobs/8296555601#step:3:469

kopiaui: Fix checkver, update `hash` and `url`, remove `pre_install`

---

bucket/firefox-eme-free.json

Fixes checkver as it's likely been broken since FF reached 100

firefox-eme-free: Update to version 110.0.1

---

bucket/hibit-startup-manager.json

Now the settings folder will persist between updates.

hibit-startup-manager: Add `persist`

---

bucket/synfig-studio.json

Closes #11032
If the version number is still reused in the future, then consider adding the date to the version string.

synfig-studio: Fix url

---

bucket/imo-messenger.json

imo-messenger: Update to version 1.4.8.3 and fix checkver

---

bucket/jexiftoolgui.json

jexiftoolgui: Update to version 2.0.2.0 and fix checkver

---

bucket/puttie.json

puttie: Update to version 20230219-1bfd0b26 and fix autoupdate

---

bucket/todolist.json

todolist: Fix checkver

---

bucket/librewolf.json

- Update to version 112.0-1
- Add 32bit support
- Update (un)install scripts
- Update checkver, autoupdate
- Remove `LibreWolf\defaults\prefs` from persist (Wrong path)
Closes #11050 #11049 #11031

librewolf: Update manifest

---

bucket/smartsvn.json

smartsvn: Update to version 14.3.0 and fix checkver

---

bucket/msedgeredirect.json

msedgeredirect: Drop architecture select

---

bucket/3d-fix-manager.json

3d-fix-manager: Fix download url and homepage

---

bucket/pspad.json

pspad: Add 64bit architecture support

---

bucket/fmedia.json

fmedia: Update to version 1.30 and fix autoupdate

---

bucket/seafile-syncing-client.json

seafile-syncing-client: Add version 7.0.9

---

bucket/antares.json

Closes #9328
config location: $env:AppData/Antares

antares: Add version 0.5.17

---

bucket/dfu-programmer.json

Added dfu-programmer.json to the bucket

dfu-programmer: Add version 0.7.2

---

bucket/pianobar-windows.json
bucket/pianobar.json

pianobar: Add version 2022.10.09

---

bucket/game-editor.json

game-editor: Add version 1.4.0

---

bucket/mullvad-browser.json

mullvad-browser: Add version 12.0.4

---

bucket/processing4.json

processing4: Add version 1292-4.2

---

bucket/sniffnet.json

sniffnet: Add version 1.1.2

---

bucket/tev.json

tev is a image viewer and comparison tool for HDR images (high dynamic range)
https://github.com/Tom94/tev has 777 stars and 80 forks
Closes #XXXX

tev: Add version 1.25

---

bucket/dbxcli.json

dbxcli - A command line client for Dropbox

Add dbxcli 3.0.0

---

bucket/raven-reader.json

raven-reader: Add version 1.0.78

---

bucket/lbry.json

lbry: Add version 0.53.9

---

bucket/swyh.json

swyh: Add version 1.5.0

---

bucket/tiled.json

tiled: Add version 1.9.2

---

bucket/regiontoshare.json

regiontoshare: Add version 1.3.5651

---

bucket/adventuregamestudio.json

adventuregamestudio: Add version 3.6.0.47

---

bucket/chart-geany.json

chart-geany: Add version 6.3.2

---

bucket/focus.json

Relates to https://github.com/ScoopInstaller/Extras/issues/10369#issue-1563736866

focus: Add version 1.3.0

---

bucket/yapa.json
bucket/yapa2.json

yapa2: Add version 2.0.190

---

bucket/swyh-rs.json

Use swyh-rs branch instead of master branch
Closes #10723

swyh-rs: Add version 1.6.1

---

bucket/xc.json

xc: Add version 0.0.159

---

bucket/xplorer.json

xplorer: add version 0.3.1

---

bucket/blobsaver.json

blobsaver: Add version 3.5.0

---

bucket/lark.json

Closes https://github.com/ScoopInstaller/Extras/issues/10253
Related https://github.com/ScoopInstaller/Extras/issues/10272

lark: Add version 6.1.7

---

bucket/bloop.json

Bloop - fast code search engine written in Rust.

Add bloop 0.3.3

---

bucket/debugtron.json

debugtron: Add version 0.5.0

---

bucket/marble.json

marble: Add version 2.2.0

---

bucket/foxit-pdf-reader.json

- [X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
copied from foxit-reader.json
/Verify

foxit-pdf-reader: Fix url

---

bucket/magpie.json

magpie: Add version 0.10.1

---

bucket/wavosaur.json

wavosaur: Add version 1.7.0.0

---

bucket/subsync.json

subsync: Add version 0.17.0

---

bucket/labplot.json

labplot: add version 2.10.0

---

bucket/gridplayer.json

gridplayer: Add version 0.4.3

---

bucket/neoray.json

Simple and lightweight GUI client for Neovim

neoray: Add version 0.2.5

---

bucket/avogadro.json
bucket/avogadro2.json

avogadro(2): Add manifests

---

bucket/duality.json

 duality: Add version 3.0

---

bucket/zsharp.json

zsharp: Add version 2.1.3

---

bucket/frostwire.json

frostwire: Add version 6.9.9

---

bucket/firefoxpwa.json

add the firefox pwa installer to scoop
Closes #9531

firefoxpwa: Add version 2.5.0

---

bucket/win-vind.json

win-vind: Add version 4.3.3

---

bucket/kde-dolphin.json

kde-dolphin: Add version 22.12.2-1828

---

bucket/metasploit-framework.json

metasploit-framework: Add version 6.3.13-20230414153155

---

bucket/neoaxis-engine.json

neoaxis-engine: Add version 2023.1.2

---

bucket/beebeep.json

BeeBEEP: Add version 5.8.6

---

bucket/eraser.json

Eraser: Add version 6.2.0.2993

---

bucket/squirreldisk.json

squirreldisk: Add version 0.3.4

---

bucket/usb-image-tool.json

usb-image-tool: Add version 1.90

---

bucket/azd.json

azd: Add version 0.7.0-beta.1

---

bucket/effekseer.json

effekseer: Add version 170b

---

bucket/bluetooth-cli-tools.json

bluetooth-cli-tools: Add version 1.2.0.56

---

bucket/bytecode-viewer.json

bytecode-viewer: Add version 2.11.2

---

bucket/monitorprofileswitcher.json

The Monitor Profile Switcher creates files in `%appdata%\\MonitorSwitcher`. Should I add a `post_uninstall` to remove them?

MonitorProfileSwitcher: Add version 0.7.0.0

---

bucket/fastcopy.json

- Use script instead of `persist` to avoid error.
Closes #XXXX

fastcopy: Fix persistence

---

bucket/okular.json

okular: Fix checkver & Update to version 22.12.3-1357

---

bucket/celestia.json

celestia: Update to version 1.6.3 and fix autoupdate

---

bucket/anaconda3.json

anaconda3: Fix checkver and autoupdate

---

bucket/koboldcpp.json

koboldcpp A simple one-file way to run various GGML models like LLAMA, ALPACA, VICUNA

koboldcpp: Add version 1.10

---

bucket/firefox-esr.json

firefox-esr: Add arm64 architecture

---

bucket/windterm.json

windterm: couldn't match '(?<tag>[\d.]+)\/WindTerm_([\d.]+)_Windows_Portable_x86_64.zip' in https://github.com/kingToolbox/WindTerm/releases

windterm: Fix checkver

---

bucket/android-sdk.json

android-sdk: Add `notes` about `android-clt`

---

bucket/syncplay.json

syncplay: Update to version 1.7.0 and fix autoupdate

---

bucket/ferdium.json

ferdium: Add version 6.2.6

---

bucket/flutter.json

- Update description
- Remove `depends`, Update `suggest`
- Stop using external setup script, the scirpt assumes users are developing for Android. (https://flutter.dev/multi-platform)
- Update `checkver` and `autoupdate`
Closes #11019, #10413, #10765, #3148

flutter: Update manifest

---

bucket/stremio.json
scripts/stremio/install-context.reg
scripts/stremio/uninstall-context.reg

stremio: Add scripts for URL:Stremio Protocol

---

bucket/qalculate.json

qalculate: Add shortcut for `qalculate-qt.exe`

---

bucket/vcredist.json
bucket/vcredist2022.json

vcredist & vcredist2022: Update to version 14.34.31938.0

---

bucket/deew.json

deew: Add version 3.0.1

---

bucket/office-tool-plus.json

office-tool-plus: Update to version 10.1.7.0 and add more architecture

---

bucket/tor-browser.json

tor-browser: Update installation

---

bucket/dbvis.json

dbvis: Update to version 23.1 and Fix checkver

---

bucket/dismplusplus.json

dismplusplus@10.1.1002.1B fix version conflict

---

bucket/winmerge.json

winmerge: Add arm64 architecture

---

bucket/hideul.json

Add: hideul 1.0

---

bucket/windowsdesktop-runtime-lts.json
bucket/windowsdesktop-runtime.json

- Simplified hash extraction using the provided checksum file: https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.5/7.0.5.md#downloads
- Updated license to MIT: https://github.com/dotnet/runtime/blob/main/LICENSE.TXT

windowsdesktop-runtime: Update manifests

---

bucket/spotify.json

spotify: Fix installer error

---

bucket/dngrep.json

dngrep: Added `pre_uninstall`, edited `persist`, and edited `pre_install`

---

bucket/dn-famitracker.json

Add: dn-famitracker 0.5.0.1

---

bucket/peazip.json

peazip: fix persist configuration

---

bucket/vscodium.json

Relates to https://github.com/ScoopInstaller/Extras/actions/runs/4967831077/jobs/8890068173#step:3:601

vscodium: Removed 32bit, fixed url's and hash's.

---

bucket/icechat.json

Add: Icechat 9.53

---

bucket/anaconda3.json

anaconda3: Update to version 2023.03-1 and fix checkver

---

bucket/roundedtb.json

- Repo has moved to https://github.com/Erisa/RoundedTB
- Remove unnecessary notes

roundedtb: Update `url`, Remove `notes`

---

bucket/wonderpen.json

1. fixed autoupdate
2. added arm64 arch
Closes #11287

Wonderpen@2.3.1: Update urls

---

bucket/gitextensions.json

gitextensions: Update to version 4.1.0.16698

---

bucket/saber.json

saber: Update to version 0.12.6

---

bucket/mqttx.json

mqttx: Add arm64 architecture

---

bucket/iphone-sms-backup-and-restore.json

iphone-sms-backup-and-restore: Fix typos

---

bucket/sidekick-browser.json

- updated manifest
- updated checkver and autoupdate
Closes #11324

sidekick-browser@112: updated manifest

---

bucket/activitywatch.json

Add the ActivityWatch app to the bucket
Closes https://github.com/ScoopInstaller/Extras/issues/10647

activitywatch: Add version 0.12.1

---

bucket/v2rayn.json

v2rayn: Add `architecture`

---

bucket/vcredist2005.json
bucket/vcredist2008.json
bucket/vcredist2010.json
bucket/vcredist2012.json
bucket/vcredist2013.json

vcredist20(05|08|10|12|13): Update manifest

---

bucket/qflipper.json

qflipper: Add version 1.3.1

---

bucket/anaconda3.json

anaconda3: Fix installation on PowerShell Core(7.x)

---

bucket/everything.json

everything: Check service's BINARY_PATH_NAME

---

bucket/avidemux.json

This fix depends on https://github.com/ScoopInstaller/Main/pull/4844
Closes #9689

avidemux: Fix installation

---

bucket/localsend.json

localsend: Update to version 1.10.0

---

bucket/syncthingtray.json

syncthingtray: Fix pre_install

---

bucket/universal-android-debloater.json

universal-android-debloater: Add version 0.5.1

---

bucket/fluidsynth.json

fluidsynth: Add version 2.3.3

---

bucket/milkytracker.json

milkytracker: add 1.03.00

---

bucket/carapace-bin.json
bucket/carapace.json

carapace-bin: Add version 0.24.5

---

bucket/adguardian.json

adguardian: add version 1.6.0

---

bucket/netradio.json

netradio: Add version 2.4

---

bucket/gpg4win.json

installer pop-up without any operation, before:
Closes #11131 in same time

gpg4win: Fix installation in powershell 5.x

---

bucket/sonic-pi.json

sonic-pi: Add version 4.3.0

---

bucket/flowgorithm.json

flowgorithm: Add version 3.4.2

---

bucket/wiliwili.json

Add wiliwili v1.0.1
Relates to #11447
- [*] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Wiliwili: Add version 1.0.1

---

bucket/ilspy.json

Note that I updated version and hash manually, as autoupdate does not work, but I have no clue how to fix it

ilspy: Update to version 8.0.0.7345

---

bucket/discordchatexporter.json

discordchatexporter@2.40: Fixes crash on start

---

bucket/teamviewer.json

Checkver regex needed to be updated to match new current version DOM.

teamviewer: Update to version 15.43.6 and fix checkver

---

bucket/wizmouse.json

Current `homepage` url still works but redirects to up-to-date page.

wizmouse: Update homepage

---

bucket/rustdesk.json

rustdesk: Update to version 1.2.0

---

bucket/lenovolegiontoolkit.json

Per version 2.0 it uses the dotnet6 sdk: https://github.com/BartoszCichecki/LenovoLegionToolkit/commit/78fc6c1b18f760ab9a2f8641ec469740f33168f1
Closes #11565

lenovolegiontoolkit@2.14.3: fix dotnet dependency

---

bucket/steam-desktop-authenticator.json

steam-desktop-authenticator: add version 1.0.13

---

bucket/sniffnet.json

sniffnet: Update to version 1.2.1 and fix autoupdate

---

bucket/komga.json

see https://komga.org/docs/guides/webui

komga@1.2.1: fix: incorrect default port

---

bucket/forkgram.json

update forkgram to 4.8.6

---

bucket/forkgram.json

forkgram: update to 4.8.7

---

bucket/brave.json

Closes https://github.com/ScoopInstaller/Extras/issues/11654

brave: Update checkver

---

bucket/buildcache.json

buildcache: Add version v0.28.4

---

bucket/revouninstaller.json

revouninstaller: Update to version 2.4.5

---

bucket/qview.json

qview: Update to version 6.1 and Update persistence

---

bucket/mpv.net.json

mpv.net: Update to version 6.0.4.0

---

bucket/privacy.sexy.json

privacy.sexy@0.12.1: Fix url (Close ScoopInstaller#11764)

---

bucket/nosleep.json

- Resolves #10469
Lightweight Windows utility to prevent screen locking

nosleep: Add version 1.2.0

---

bucket/peazip.json

peazip@9.4.0: Switch to github release

---

bucket/opentabletdriver.json

Makes the program fully portable
Closes #11784

opentabletdriver: add userdata persist

---

bucket/qutebrowser.json

Qutebrowser@ manifest adapted to version 3.0.0 /no win-32 support anymore

---

bucket/qalculate.json

qalculate: Fix `-gtk` rename

---

bucket/tor-browser.json

Fix `tor-browser` download URLs

Fix "tor-browser" download URLs

---

bucket/mcomix.json

mcomix@3.0: Remove trailing commas

---

bucket/reaper.json

Reaper@7.05: Remove Reamote shim and shortcut

---

bucket/blender-launcher.json

Since development of blender launcher has stopped, we will switch to a fork site.
Development of blender-launcher by developer @DotBow has almost stopped.
https://github.com/DotBow/Blender-Launcher/discussions/188
Currently, @Victor-IX has forked and provides binaries, so we will switch to that.
https://github.com/DotBow/Blender-Launcher/issues/245#issuecomment-1825163084

blender-launcher: switch home url

---

bucket/pacaptr.json

pacaptr: Update to version 0.20.1

---

bucket/converseen.json

Fix Converseen checkver

---

bucket/dxwnd.json

dxwnd@2.06.00: fix the url

---

bucket/session.json

Closes #11848
Relates to #11847

session@1.11.4: url fix (#11848)

---

bucket/naps2.json

Updated application to a newer version v7.1.2
Closes #XXXX

naps2: Update to version 7.1.2

---

bucket/nilesoft-shell.json

nilesoft-shell: Fix config file name

---

bucket/ddu.json

moved `checkver` to the official AssemblyInfo file
moved `url` to a mirror due to Cloudflare cookie and js requirements
changed `homepage` due to checkver errors

ddu: Update to version 18.0.6.9

---

bucket/imagine.json

imagine: Update to Version 1.3.1

---

bucket/neovide.json

Update urls for homepage and github.

neovide@0.11.2: Update links

---

bucket/knime.json

Update knime.json to 5.1.1 and fix auto-update

---

bucket/marktext.json

marktext@0.17.1: Update homepage link

---

bucket/sqlitespy.json

Update manifest for version 1.9.19.

sqlitespy: Update to version 1.9.19

---

bucket/microsoft-teams.json
bucket/teamspeak3.json

teamspeak3: Update to Version 3.6.2

---

bucket/linqpad.json

Closes #12253
Closes #12258
Closes #12299
Closes #12305

linqpad@8.0.17: Try to fix frequent hash failures

---

bucket/smplayer.json

smplayer@23.6.0.0: Fix autoupdate URLs

---

bucket/resource-hacker.json

resource-hacker: Update URLs to HTTPS

---

bucket/steamcmd.json

steamcmd.json: fix URLs

---

bucket/pe-bear.json

pe-bear: Update to version 0.6.6

---

bucket/musikcube.json

musikcube: Update to version 3.0.2 and fix autoupdate

---

bucket/qtemu.json

Attempt to fix issue 12366.
Closes #12366

qtemu@2.1: Fix urls

---

bucket/qutebrowser.json

Fix qutebrowser archive extraction

---

bucket/windowsdesktop-runtime.json

windowsdesktop-runtime@8.0.0: fix description

---

bucket/logitech-omm.json

Fixed checkver url and normalize download filename

logitech-omm: Update to 2.0.1639

---

bucket/wechat.json

Update WeChat version to 3.9.8.15

WeChat@3.9.8.15:Update WeChat version to 3.9.8.15

---

bucket/strawberry.json

updated to new download location, updated to new version, added back 32-bit version
Closes #12392

strawberry@1.0.21 update to new download location, update current version, add back 32 bit version

---

bucket/php-nts-xdebug.json
bucket/php-xdebug.json

php(-nts)-xdebug@3.3.0-8.3: update to work with PHP 8.3

---

bucket/zim.json

Fixes #12231
Supersedes #9845
This manifest properly configures the application for portable use.

Zim: Add version 0.75.2

---

bucket/qq.json
bucket/sidekick-browser.json

Fix QQ checkver fail, and upgrade QQ URL.

Fix QQ checkver failure

---

bucket/avspmod.json

avspmod: fix manifest

---

bucket/dbvis.json

- Fix checkver.
- Update to version 23.2.5.

dbvis: Update to version 23.2.5, fix checkver

---

bucket/protonmail-bridge.json

The file name should be proton-bridge.exe

protonmail-bridge: fix shortcuts

---

bucket/lorien.json

Add Lorien whiteboard application: https://github.com/mbrlabs/Lorien

lorien: Add version 0.6.0

---

bucket/sabnzbd.json

Fix hashes v4.2.1 sabnzbd.json

---

bucket/zrok.json

zrok: Add version 0.4.20

---

bucket/magpie.json

https://github.com/Blinue/Magpie/releases/tag/v0.10.4

magpie: fix url and persist

---

bucket/otvdm.json

Relates to [#12533](https://github.com/ScoopInstaller/Extras/issues/12533)

otvdm: Add version 0.9.0

---

bucket/moosync.json

Add [Moosync](https://moosync.app/) - yet another customizable desktop music player with a clean interface.
Closes #12340.
Relates to Moosync/Moosync#136.

moosync: Add version 10.2.0

---

bucket/mayo.json

Add bucket for [Mayo](https://github.com/fougue/mayo) application

Mayo: add version 0.8.0

---

bucket/rimage.json

rimage: add version 0.10.2

---

bucket/retrobar.json

retrobar: Add version 1.14.11

---

bucket/sasm.json

Simple crossplatform IDE for NASM, MASM, GAS and FASM assembly languages

sasm: Add version 3.14.0

---

bucket/kicad.json

kicad: Add shortcuts

---

bucket/pycharm-professional.json
bucket/webstorm.json

Updating the persistence of PyCharm Professional and WebStorm.
Closes #11864

pycharm-professional@2023.3.2-233.13135.95: Update persistence

---

bucket/clashtui.json

clashtui: Add version 0.1.0

---

bucket/plantuml.json

plantuml: Update to version 1.2023.12 & Fix checkver

---

bucket/focus-editor.json

Added new manifest for Focus-Editor: A simple editor whose goal is to get out of your way and let you do work.
Closes #12551

Focus-Editor: Added version 0.3.0

---

bucket/umi-ocr-paddle.json

Umi-OCR-Paddle: Add version 2.0.2

---

bucket/bifrost.json

Bifrost: Add version 1.16.14

---

bucket/orcaslicer.json

Closes https://github.com/ScoopInstaller/Extras/issues/12201

orcaslicer: Add version 1.7.0

---

bucket/windhawk.json

https://windhawk.net/: The customization marketplace for Windows programs.
By the creator of 7+ Taskbar Tweaker ([7tt.json](https://github.com/ScoopInstaller/Extras/blob/master/bucket/7tt.json)).

windhawk: Add version 1.4.1

---

bucket/opensca-cli.json

opensca-cli: Add version 3.0.4

---

bucket/esearch.json

eSearch: Add version 1.11.0

---

bucket/ip2location-io-cli.json

ip2location-io-cli: Add version 1.1.0

---

bucket/vrcx.json

vrcx: Add version 2023.09.18

---

bucket/ayugram.json

AyuGram: Add version 4.14.3

---

bucket/quickinstaller.json

[QuickInstaller](https://quickinstaller.net/) v0.2

QuickInstaller: Add version 0.2.8748.37063

---

bucket/claws-mail.json

claws-mail: Update to version 4.2.0-1

---

bucket/rnote.json

rnote: add 0.9.4

---

bucket/sublime-merge.json
scripts/sublime-merge/install-context.reg
scripts/sublime-merge/uninstall-context.reg

Add a contextual menu in Windows’ File Explorer on a directory, and background of a directory.
Relates to #3080

sublime-merge@2091: add contextual menu

---

bucket/thorium.json

Thorium: add version 117.0.5938.157

---

bucket/updatehub.json

[UpdateHub](https://github.com/NexovaDev/UpdateHub) v2

UpdateHub: Add version 2.3.4

---

bucket/tortoisesvn.json

tortoisesvn: Fix download url

---

bucket/tad.json

Tad: Add version 0.13.0

---

bucket/amber.json

Added `amber` search/replace command line tool.
Relates to #12609

amber: add version 0.6.0

---

bucket/stirling-pdf.json

Stirling-PDF: Add version 0.20.0

---

bucket/linux-reader.json

Closes #12634
Relates to #4797
Supersedes #11957

linux-reader: Add version 4.19

---

bucket/kicad.json

KiCad@7.0.10: Add shortcuts

---

bucket/libreoffice.json

* fixes #12652
* update to version 7.6.4
* update download urls to use stable
* update checkver regexp
* update autoupdate urls
Closes #XXXX

libreoffice: fix to use stable version

---

bucket/cefflashbrowser.json

CefFlashBrowser: Add version 1.0.8

---

bucket/floorp.json

Adds Floorp Browser (Note: does not impede on the work of the previous floorp pr, this PR is based on another sub-project of the browser for portable installs.)
Closes #12645

Floorp: Add Version 11.7.1

---

bucket/space.json

space@1.0.1: Fix hash autoupdate

---

bucket/steamguard-cli.json

steamguard-cli: Add version 0.9.7

---

bucket/gramps.json

Gramps: A genealogy program that is both intuitive for hobbyists and feature-complete for professional genealogists.
Add a new manifest version 5.1.6
Closes #11705

Gramps: add version 5.1.6

---

bucket/firefox.json

firefox: Update checkver regex

---

bucket/delapp.json

delapp: Add version 1.0.2

---

bucket/litedb-studio.json

This PR adds LiteDB.Studio which is a GUI tool for viewing and editing documents for LiteDB v5.
Closes #11725

litedb-studio: Add version 1.0.3

---

bucket/windows-virtualdesktop-helper.json

Scoop package initial commit for Scoop Extras (by community request) (via https://github.com/dankrusi/WindowsVirtualDesktopHelper/issues/86)

Windows Virtual Desktop Helper: Add version 1.16

---

bucket/labplot.json

Labplot changes its naming rule
Relates to #6845

labplot: Update to 2.10.1

---

bucket/otvdm.json

otvdm@0.9.0: Fix nested directory installation problem

---

bucket/gitkraken.json

Switch from win64 -> windows
Closes #12735

gitkraken: Update to version 9.11.1

---

bucket/hexo-client.json

hexo-client@1.3.6: Switch to 64bit version

---

bucket/lunarvim.json

Lunarvim: Add version 1.3.0

---

bucket/threema.json

Hash needs to be updated too.
Closes #XXXX

threema: Update to version 1.2.40, fix checkver

---

bucket/wxformbuilder.json

This PR adds wxFormBuilder. Do I really have to open a separate issue for this? Will do so if required.

wxFormBuilder: Add version 4.0.0

---

bucket/clever-ffmpeg.json

clever-ffmpeg: Add version 3.2.3

---

bucket/nmkoder.json

nmkoder: Add version 1.10.0

---

bucket/free42.json

free42: Add version 3.1.4

---

bucket/ab-av1.json

ab-av1: Add version 0.7.14

---

bucket/recyclarr.json

recyclarr: Add version 6.0.2

---

bucket/restic-browser.json

restic-browser: Add version 0.3.0

---

bucket/swift-mesonlsp.json

swift-mesonlsp: Add version 3.1.3

---

bucket/gossip.json

gossip: Add version 0.9.0

---

bucket/scrawler.json

scrawler: Add version 2024.1.26.0

---

bucket/tomboy-ng.json

Tomboy-ng: Add version 0.36

---

bucket/chatall.json

chatall: Add version 1.17.10

---

bucket/icecast.json

icecast: Update to 2.4.4, fix checkver

---

bucket/komorebi.json

Updates the notes, adds a new bin and adds whkd as a suggestion.

komorebi@0.1.20: Update notes, bin and suggest

---

bucket/sonic-visualiser.json

This PR adds a manifest file for Sonic Visualiser.
Closes #12284

sonic-visualiser: Add version 4.5.2

---

bucket/miniconda3.json

miniconda3@23.11.0-2: update url of checkver & hash

---

bucket/mediaelch.json

mediaelch: Add version 2.10.6

---

bucket/gptscript.json

Adds gptscript to Extras
cc @ibuildthecloud

gptscript: Add version 0.1.1

---

bucket/lunarvim.json

lunarvim: Update persist

---

bucket/fwup.json

fwup: Add version 1.10.1

---

bucket/bzip3.json

bzip3: Add version 1.4.0

---

bucket/goldendict.json

goldendict@1.5.0: Update homepage, fix checkver and autoupdate

---

bucket/deeplx.json

deeplx: Add version 0.8.8

---

bucket/irfanview-lean.json
bucket/irfanview.json

irfanview@4.66: persist Toolbars directory

---

bucket/sam.json

sam: Add version 1.5.3.2

---

bucket/foxmail.json

foxmail@7.2.25.245: Update pre_install script

---

bucket/bforartists.json

Bforartists is a fork of the popular 3D software Blender, with the goal to improve the UI.
Homepage
https://www.bforartists.de/
Download Link(s)
https://www.bforartists.de/download/
https://github.com/Bforartists/Bforartists/releases
Some Indication of Popularity/Repute
391 stars, 64 forks
Closes #10296

Bforartists: Add version 4.0.2

---

bucket/foxit-pdf-reader.json
bucket/foxit-reader.json

foxit-(pdf-)reader: Update to version 2024.1.0

---

bucket/classic-volume-mixer.json

classic-volume-mixer: Add version 2.4

---

bucket/tidal.json

tidal: Add version 2.36.2

---

bucket/git-tower.json

The latest Git-Tower have different folder/file structure.
Closes #12945

git-tower@6.0.474: Fix extraction

---

bucket/ffmpeg-batch.json

ffmpeg-batch: Update to version 3.0.5, fix autoupdate

---

bucket/affine.json

affine: Add version 0.13.1

---

bucket/godot-version-manager.json

Download, install and manage any version of Godot Engine from a simple app.
This is an application similar to `godot-manager`.

godot-version-manager: Add version 1.16.1

---

bucket/yesplaymusic.json

yesplaymusic: Update to version 0.4.8, fix autoupdate

---

bucket/persepolis.json

persepolis: Update to version 4.0.1.0, deprecate 32bit version

---

bucket/tabby.json

tabby@1.0.207: Fix existing data may be overwritten when update

---

bucket/tts-voice-wizard.json

tts-voice-wizard: Add version 1.6.7.1

---

bucket/vipsdisp.json

Add vipsdisp. Thanks to @aliesbelik for the help in <https://github.com/ScoopInstaller/Extras/issues/13051#issuecomment-2037948274>. :)
Closes #13051

vipsdisp: Add version 3.0.4

---

bucket/vtm.json

Adds **vtm**, desktop environment but for terminals.
Closes #13065

vtm: Add version 0.9.77

---

bucket/helm-ls.json

See https://github.com/mrjosh/helm-ls

helm-ls: Add version 0.0.14

---

bucket/gopeed.json

Gopeed About:
A modern download manager that supports all platforms. Built with Golang and Flutter.

gopeed: Add version 1.5.6

---

bucket/debugviewpp.json

Add shortcuts for GUI application DebugView++.
Closes #13006

debugviewpp: Add shortcuts

---

bucket/uninstalr.json

uninstalr: Add version 2.3

---

bucket/doublecmd.json

- Closes #2181
- Closes #10849

doublecmd: Use portable edition

---

bucket/mpc-be.json

Official links have been updated from SourceForge to GitHub due to the increased activity of the official developer on the latter platform.
Closes #XXXX

mpc-be@1.7.0: Switch to github releases

---

bucket/rio.json

Closes https://github.com/ScoopInstaller/Extras/issues/11772

rio: Add version 0.0.36

---

bucket/godots.json

Ultimate go-to hub for managing your Godot versions and projects!
https://github.com/MakovWait/godots
This is an application similar to `godot-manager`.
Relates to #13095

Godots: Add version 1.3

---

bucket/lenovolegiontoolkit.json

Closes [#13110](https://github.com/ScoopInstaller/Extras/issues/13110)

lenovolegiontoolkit@2.21.1: update dotnet dependency

---

bucket/gitbutler.json

gitbutler: Add version 0.11.1

---

bucket/cactusviewer.json

CactusViewer is "A small single file image viewer written in C/C++.".
Closes #13116

CactusViewer: Add version 2.1.4

---

bucket/duckdns.json

Added DuckDNS client
Closes https://github.com/ScoopInstaller/Extras/issues/13128

duckdns: Add version 2.2b

---

bucket/tsukimi.json

tsukimi: Add version 0.4.7

---

bucket/hourglass-godot.json

hourglass-godot: Add version 0.9.4

---

bucket/openai-translator.json

openai-translator: Update to version 0.4.3

---

bucket/supermium.json

supermium: Add version 122.0.6261.85

---

bucket/gitu.json

Gitu is a TUI Git client inspired by Magit
Closes #13195

gitu: Add version 0.19.2

---

bucket/android-line-transfer.json
bucket/android-sms-backup-and-restore.json
bucket/filezilla-server.json
bucket/filezilla.json
bucket/iphone-sms-backup-and-restore.json
bucket/krita.json
bucket/lantern-client.json
bucket/linphone.json
bucket/linux-reader.json
bucket/pidgin.json

- Closes #12853 
- Closes #13237
- Relates to https://github.com/ScoopInstaller/Scoop/pull/5294

(chore): Stop removing '*.nsis'

---

bucket/7tt.json

7tt: Using extraction instead of portable install

---

bucket/airdroid.json

airdroid: Fixed spelling mistakes in the description property

---

bucket/GUI.for.Clash.json
bucket/gui-for-clash.json

GUI.for.Clash: Add version 1.6.7

---

bucket/tsukimi.json

tsukimi: Update to version 0.4.10 and fix autoupdate

---

bucket/beeref.json

Close: https://github.com/ScoopInstaller/Extras/issues/12974
BeeRef: A Simple Reference Image Viewer

beeref: Add version 0.3.3

---

bucket/quicklook.json

QuickLook: enable it to call from cli

---

bucket/cyberchef.json

Closes #13337
a web app for encryption, encoding, compression and data analysis
with 25.7k Github Stars https://github.com/gchq/CyberChef

cyberchef: Add version 10.18.6

---

bucket/pineflash.json

I had this in my personal bucket for a long time, didn't realize there was a request here :P.
Closes #12471

pineflash: Add version 0.5.5

---

bucket/spotube.json

I updated the website link to the new one, because it's not on netlify anymore.

spotube: Update website link

---

bucket/geogebra.json

geogebra: Update to version 6.0.843.0

---

bucket/otadump.json

otadump: Add version 0.1.2

---

bucket/orange.json

new manifest for orange.
https://orangedatamining.com/
https://github.com/biolab/orange3
CLoses #13178

orange: Add version 3.36.2

---

bucket/neeview.json

neeview: Add version 41.2

---

bucket/picview.json

picview: Add version 2.2.7

---

bucket/g-helper.json

Closes #11306 and relates to #11307
PS. I own a compatible laptop, so I tried out a bit and looks quite promising indeed.

g-helper: Add version 0.173

---

bucket/speccy.json

Downloaded several times to make sure the hash is consistent.

speccy@1.33.75: Fix hash

---

bucket/ffmpeg-batch.json

ffmpeg-batch: Update to version 3.0.7, fix autoupdate

---

bucket/clash-nyanpasu.json

clash-nyanpasu: Add Version 1.5.1

---

bucket/librewolf.json

librewolf: Remove unnecessary updates files

---

bucket/qucs-s.json

qucs-s: Add version 24.2.1

---

bucket/musescore.json

musescore: Update to version 4.3.2.241630831, fix checkver and autoupdate

---

bucket/extraterm.json

extraterm: Update to version 0.78.1, fix checkver

---

bucket/siyuan-note.json

- Add `arm64` architecture
- Add `hash`
- Update `description`

siyuan-note: Add arm64 architecture and autoupdate.hash

---

bucket/powertoys.json

* Fix `checkver`
* Fix `autoupdate`
Closes #XXXX

powertoys: Update to version 0.82.1

---

bucket/umi-ocr-paddle.json
bucket/umi-ocr.json

Rename after downloading is complete
Closes #13615

umi-ocr(-paddle)@2.1.2: Fix download and autoupdate urls

---

bucket/komorebi.json

Fix hash for v0.1.28
Closes #XXXX

komorebi@0.1.28: Fix hash

---

bucket/jellyfin-media-player.json

jellyfin-media-player: Add version 1.11.1

---

bucket/ntlite.json

ntlite: Add version 2024.7.9999

---

bucket/ultravnc.json

ultravnc: Update to version 1.4.3.6

---

bucket/everything-powertoys.json

everything-powertoys: Add arm64

---

bucket/omenmon.json

omenmon: Add version 0.61.1

---

bucket/localsend.json

Closes https://github.com/ScoopInstaller/Extras/issues/13646

localsend@1.15.1: Fix persist settings

---

bucket/altus.json

altus: Add version 5.2.0

---

bucket/sourcegit.json

Add sourcegit - Opensource GUI client for git users.
Closes #13534

sourcegit: Add version 8.21

---

bucket/furnace.json

Add new app: the [furnace](https://github.com/tildearrow/furnace) chiptune tracker
Closes #11495

furnace: Add version 0.6.5

---

bucket/sqlitebrowser.json

---
* Add a `v` to the version in the file name
* Update `checkver` to look for the latest GitHub release

sqlitebrowser: Update to version 3.13.0

---

bucket/sqlitebrowser.json

sqlitebrowser@3.13.0: Remove `extract_dir`

---

bucket/blender.json

blender@4.2.0: Add persist

---

bucket/winsshterm.json

- add junction to "PUTTYGEN.EXE" if it exists
Closes #13754

winsshterm@2.37.0: add junction to "PUTTYGEN.EXE" if it exists

---

bucket/pixelorama.json

Slightly changed the files naming scheme to fix autoupdates and bumped up version to `1.0.1`.
Closes #13767

pixelorama: Update to version 1.0.1

---

bucket/moonlight.json

add moonlight.exe to bin
Closes #13775

moonlight@6.0.1: add moonlight.exe to bin

---

bucket/moar.json

moar: Move 'url' under 'arch.64bit'

---

bucket/nvcleanstall.json

This PR fixes downloading and installing nvcleanstall.
Closes #13133, closes #12694

nvcleanstall@1.16.0: Fix download link

---

bucket/explorerplusplus.json

Update checkver section
Enable portable mode by creating a expandable config file
Persist config file

explorerplusplus@1.4.0: Make it portable

---

bucket/reqable.json

https://github.com/reqable/reqable-app/
Closes https://github.com/ScoopInstaller/Extras/issues/13806

reqable: Add version 2.21.4

---

bucket/ab-download-manager.json

ab-download-manager: Add version 1.0.7

---

bucket/w64devkit.json

w64devkit: Update to version 2.0.0, fix autoupdate

---

bucket/pragtical.json

pragtical: Add version 3.4.1
Closes #13764

pragtical: Add version 3.4.2

---

bucket/xl-converter.json

xl-converter: Add version 1.0.2

---

bucket/beaver-notes.json
bucket/sidekick-browser.json

beaver-notes: Add version 3.5.0

---

bucket/laigter.json

laigter: Add version 1.11.0

---

bucket/rustrover.json

rustrover: Add version 2024.1.5-241.17890.39
Closes  #13372

rustrover: Add version 2024.1.5-241.17890.39

---

bucket/rider.json

Updating the persistence of Rider.
Closes #13807

rider@2024.2.2-242.20224.431: Update persistence

---

bucket/kanri.json

kanri: Add version 0.7.1

---

bucket/flclash.json

Adds flclash, a multi-platform proxy manager
Closes #13744

flclash: add version 0.8.56

---

bucket/hoppscotch.json

hoppscotch: Add version 24.7.1-0

hoppscotch: Add version 24.8.1-0

---

bucket/binance.json

binance: Add version 1.53.0

---

bucket/wasabi-wallet.json

wasabi-wallet: Add version 2.1.0

wasabi-wallet: Add version 2.1.0

---

bucket/datovka.json

Closes [#13938](https://github.com/ScoopInstaller/Extras/issues/13938)

Datovka: Add version 4.24.2

---

bucket/mission-planner.json

mission-planner: Add version 1.3.82

---

bucket/dovi-tool.json

dovi-tool: Add `autoupdate` `hash`

---

bucket/foxe.json

foxe: Change to HTTPS and add shortcut

---

bucket/ddu.json

---
Also downgrades the version because a [version bump occurred in the `AssemblyInfo.vb` file](https://github.com/Wagnard/display-drivers-uninstaller/commit/ac6b602ceecb94c3886e47acf8ff874002f198e8#diff-9b447640bc5ff3c0d7e2040e6d88bb0cf28e6bc6c962cd35af50efbb79b8606e), but a binary hadn't been released yet.
<details>
<summary>Update error log after <a href="https://github.com/ScoopInstaller/Extras/commit/2f2c533abd97bdf4b4f64781f851228b6bf70b12">#2f2c533</a></summary>
```bash
Updating 'ddu' (18.0.8.0 -> 18.0.8.1)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: b29a1f|OK  | …
```

ddu: Change `checkver` to mirror

---

bucket/slack.json

Closes #14033
Relates to #14003

slack: Fix autoupdate

---

bucket/moonlight.json

Notes:
> 32-bit versions of Windows are no longer supported

moonlight: Update to version 6.1.0

---

bucket/snipaste.json

snipaste: fix checker and update to 2.10.2

---

bucket/komf.json

Closes #XXXX
Fix run command
```
java komf.jar --config-dir="..."
```
```
14:19:12.451 [main] ERROR snd.komf.app.Application -- Failed to start the app
java.nio.file.InvalidPathException: Illegal char <:> at index 14: --config-dir="..."
```
```
java komf.jar "..."
```
```
14:23:56.783 [main] INFO io.ktor.server.Application -- Autoreload is disabled because the development mode is off.
14:23:56.898 [main] INFO io.ktor.server.Application -- Application started in 0.13 seconds.
14:23:56.924 [DefaultDispatcher-worker-2] INFO io.ktor.server.Application -- Responding at http://127.0.0.1:8085
```

komf: fix run command

---

bucket/dra.json

dra: Add version 0.6.2

---

bucket/regedix.json

I needed a alternative to regedit with path navigation, and I found this useful app with additional features.
It also have a portable version, free and under GNU license.

regedix: Add version 2.0.0.0

---

bucket/netbird.json
bucket/termius.json

add bin Netbird 0.29.3
fix version and hash

netbird: Add version 0.29.4

---

bucket/fricas.json

Added FriCAS version 1.3.11 to Extras bucket

fricas: Add version 1.3.11

---

bucket/angr-management.json

Added angr-management to Extras bucket

angr-management: Add version 9.2.119

---

bucket/sshs.json

sshs: Add version 4.5.1

---

bucket/headlamp.json

headlamp: Add version 0.25.1

---

bucket/bulk-rename-utility.json

bulk-rename-utility: fix download URL

---

bucket/crystaldiskinfo.json

crystaldiskinfo: Changed checkver regex to not include prereleases

---

bucket/msrt.json

Closes [#13953](https://github.com/ScoopInstaller/Extras/issues/13953)

Msrt: Add version 5.127

---

bucket/parsec.json

Closed #13414 
Portable version.

parsec: Add version 150-95e

---

bucket/window-switcher.json

window-switcher: Add version 1.10.1

---

bucket/metasploit-framework.json

metasploit-framework: Update to version 6.4.26-20240910103727

metasploit-framework: Update to version 6.4.31-20241016103548

---

bucket/mullvad-browser.json

mullvad-browser@13.5.7: Fix shortcut

---

bucket/ocauxiliarytools.json

ocauxiliarytools: Add version 20240004

---

bucket/meld.json

meld@3.22.2: add MeldConsole.exe binary

---

bucket/xcas.json

Added xcas version 1.9.0_2024_05 to Extras bucket

xcas: Add version 1.9.0_2024_05

---

bucket/hwinfo.json

* Add arm64 architecture
* Fix `autoupdate`
Closes #XXXX

hwinfo: Update to version 8.14-5580

---

bucket/qbittorrent-enhanced.json

qbittorrent-enhanced: Update to version 5.0.0.10, no more 32-bit

---

bucket/betterbird.json

betterbird: Add version 115.17.0-bb35

---

bucket/komorebi.json

komorebi@0.1.30: Add arm64 version

---

bucket/abricotine.json

abricotine@1.1.4: Fix homepage, add EOL note

---

bucket/crip.json

crip: Add version 2.3.0

---

bucket/innounpacker.json

GUI edition of Innounp Unicode, also bundled with latest version of Innounp Unicode edition.

innounpacker: Add version 1.10.0

---

bucket/treesheets.json

TreeSheets: Add version 11693219263

---

bucket/msiafterburner.json

Until PR merge, use this to install msiafterburner:
```
scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/bfd10e410228a5db3441997dfa92ca3bcc9d6430/bucket/msiafterburner.json
```
Fix #13851, fix #14204, fix #14186, fix #13671, fix #13579, fix #14254, fix #14293, fix #14353, fix #14353, fix #14385

msiafterburner@4.6.5: Fix install

---

bucket/kubespy.json

kubespy: Add version 0.6.3

---

bucket/keyguard.json

Closes https://github.com/ScoopInstaller/Extras/issues/13476
- [+] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

keyguard: Add 1.6.4-20241102

---

bucket/signal.json

signal@7.33.0: Fix download/autoupdate urls

---

bucket/positron.json

What is Positron?
- A next-generation data science IDE built by [Posit PBC](https://posit.co/)
- An extensible, polyglot tool for writing code and exploring data
- A familiar environment for reproducible authoring and publishing

positron: Add version 2024.11.0-140

---

bucket/sirikali.json

sirikali: Update to version 1.7.1

---

bucket/sucrose.json

sucrose: Update to version 24.11.8.0

---

bucket/wealthfolio.json

wealthfolio: Add version 1.0.21

---

bucket/abdownloadmanager.json

https://github.com/amir1376/ab-download-manager/issues/13#issuecomment-2495516676

abdownloadmanager: Update to version 1.4.3

---

bucket/hiddify-next.json
bucket/hiddify.json

hiddify: Add version 2.5.7

---

bucket/v2rayn.json

Future-proofing, see https://github.com/ScoopInstaller/Versions/issues/1936
Fixes #14083.

v2rayn: Create Xray folder in installation script

---

bucket/dual-monitor-tools.json

dual-monitor-tools: Update to version 2.11

---

bucket/vscode.json

Closes https://github.com/ScoopInstaller/Extras/issues/14427
Relates to #14439, #14442.
Relates to https://github.com/ScoopInstaller/Versions/blob/master/bucket/vscode-insiders.json

vscode: fix update check

---

bucket/novelwriter.json

Add novelwriter version 2.5.2
Closes #11168

novelwriter: Add version 2.5.3

---

bucket/photodemon.json

photodemon@2024.12: Fix extract_dir.

photodemon@2024.12: Fix extract_dir

---

bucket/nekoray.json

nekoray: Update executable names from nekoray to nekobox

---

bucket/nosleep.json

nosleep: Update to version 1.3.0

---

bucket/codesnap.json

codesnap: add version 0.8.3

---

bucket/hekasoft-backup-restore.json

hekasoft-backup-restore: fix manifest extract_dir

---

bucket/memreduct.json

memreduct@3.5: Update to version 3.5

---

bucket/advancedrenamer.json

advancedrenamer: Update to version 4.06

---

bucket/sd-card-formatter.json

sd-card-formatter: Extract instead of execute

---

bucket/windowsdesktop-runtime.json

windowsdesktop-runtime: Update to `latest Version 9.0.0` and `checkerver`

---

bucket/mp3tag.json

mp3tag@3.28: Persist entire data directory

---

bucket/floorp.json

Floorp@11.20.0: Fix cleanup command deletes Floorp profile

---

bucket/stirling-pdf.json

stirling-pdf: Update to version 0.36.5

---

bucket/controlprinters.json

Relates to #13952
- [ Yes] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

controlprinters: Add version 0.1

---

bucket/losslesscut.json
scripts/losslesscut/install-associations.reg
scripts/losslesscut/uninstall-associations.reg

Add `losslesscut` file associations

losslesscut: Add file associations

---

bucket/prusaslicer.json

prusaslicer: Update to version 2.9.0

---

bucket/onthespot.json

Adds onthespot, a music downloader for spotify and soundcloud
Closes #14488

onthespot: Add version 1.0.6

---

bucket/easytier.json

Easytier, a simple, decentralized mesh VPN with WireGuard support.
Closes #14582

easytier: Add version 2.1.1

---

bucket/terminal-parrot.json

Closes #14620
One quick question - are emojis allowed in manifests? I think it should be, as to respect the author's original description, so asking just in case.

terminal-parrot: Add version 1.2.0

---

bucket/odict.json

Closes #14625
> One quick question - are emojis allowed in manifests? I think it should be, as to respect the author's original description, so asking just in case.

odict: Add version 2.0.0

---

bucket/didder.json

didder: Add version 1.3.0

---

bucket/eask-cli.json

For https://github.com/emacs-eask/cli.

eask-cli: Add version 0.10.3

---

bucket/mpc-be.json

The favorites list was not added to the persistent storage. This fixes that.

mpc-be@1.8.2: Add favorites.mpc_lst to persist

---

bucket/ddu.json

ddu: Update download url

---

bucket/identme.json

Add version 0.1 of identme.
Closes #14828

identme: Add version 0.1

---

bucket/git-graph.json

git-graph: Add version 0.6.0

---

bucket/lively.json

lively@2.1.0.8: Add 'lively' binary to PATH

---

bucket/openfreebuds.json

openfreebuds: Add version 0.16.2

---

bucket/anki.json

anki: Remove `vcredist` suggest

---

bucket/winrar.json

winrar: Update to version 7.10

---

bucket/cartero.json

Closes [#14890](https://github.com/ScoopInstaller/Extras/issues/14890)

cartero: Add version 0.1.5

---

bucket/pdfsam.json

pdfsam: Update to version 5.3.0, fix update url and path

---

bucket/spotify.json

- Update to the latest version.
- Add separate 64bit/arm64 options.
- Deprecate 32bit version.
Closes #14900

spotify: Update to version 1.2.57.463.g4f748c64

---

bucket/logitech-omm.json

Update logitech-omm to version 2.3.2055, fix checkver & homepage

logitech-omm: Update to version 2.3.2055, fix checkver & homepage

---

bucket/rune.json

rune: Add version 1.1.0

---

bucket/tracker.json

This pull request adds a new configuration file for the [tracker] application. The new file includes metadata for versioning, description, licensing, and download details.
Key changes:
* Added `bucket/tracker.json` to provide configuration for the `tracker` application, including version `0.1.1`, description, homepage, license, and architecture-specific download URLs.
[tracker]: https://github.com/ShenMian/tracker

tracker: Add version 0.1.1

---

bucket/wave-terminal.json

wave-terminal: Add version 0.11.1

---

bucket/warp-terminal.json

warp-terminal: Add version 0.2025.02.24.20.50.stable_04

---

bucket/positron.json

positron: Update to version 2025.03.0-116

---

bucket/musicbee.json

musicbee@3.5.8698: update download link

---

bucket/trae.json

Trae, an AI-powered IDE that makes programming more enjoyable and efficient.
By ByteDance, freeware now.

trae: Add version 1.0.8276

---

bucket/homebank.json

homebank: Update to version 5.8.6

---

bucket/apifox.json

- Closes #15050
Fix download url.

apifox: Update to version 2.7.0

---

bucket/zed-opengl.json
bucket/zed.json

zed@0.176.3: add manifest for vulkan and opengl alternative

---

bucket/unicodia.json

unicodia: Add version 2.10.1

---

bucket/babelmap.json
bucket/babelpad.json

babelpad: Add version 16.0.0.6

---

bucket/kubevpn.json

- update homepage from `kubevpn.cn` to `kubevpn.dev`

kubevpn: update homepage from .cn to .dev

---

bucket/yoke.json

Adds yoke to the bucket [yoke](https://github.com/yokecd/yoke)
Docs: https://yokecd.github.io/docs/

yoke: Add version 0.11.0

---

bucket/gimp.json

- Fixes #13413
- Fixes #15096
- Fixes #15097
- Fixes #15098
- Fixes #15103
- Fixes #15104
- Fixes #15105
- Fixes #15112
- Fixes #15121
- Fixes #15122
- Fixes #15132
- Fixes #15144
- Closes #15101
- Closes #15116
- Closes #15120

gimp@3.0.0: Fix manifest and add ARM64

---

bucket/xan.json

Added xan manifest.
Relates to #15174

xan: Add version 0.48.0

---

bucket/smartcontextmenu.json

SmartContextMenu adds a context menu to all windows in the system. This program is enhanced version of [SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu).

SmartContextMenu: Add version 1.6.0

---

bucket/yasb.json

This PR adds YASB Reborn - A highly configurable status bar for Windows.

yasb: Add version 1.6.8

---

bucket/picocrypt.json

Add hash extraction for picocrypt.

picocrypt: Add hash extraction

---

bucket/gg.json

GG is a UI for the Jujutsu (JJ) Version Control System.
JJ itself is already part of the `main` repo, so GG would be a nice addition.

gg: Add version 0.23.0

---

bucket/zed-opengl.json
bucket/zed.json

zed + zed-opengl: update download url + add hash autoupdate url

---

bucket/diskcheckup.json

diskcheckup@3.6.1000: Fix shortcuts

---

bucket/wechat.json

Closes #15226 #15225
this manifest use my own [bucket](https://github.com/cscnk52/wechat-windows-versions) to get version information and download installer, which is accessible by HUMORCE in https://github.com/ScoopInstaller/Extras/pull/15226#issuecomment-2797230186

wechat: update to 4.0.3.36

---

bucket/cheat-engine.json

- Closes https://github.com/ScoopInstaller/Binary/issues/26
- Closes #11963

cheat-engine: Update to version 7.6

---

bucket/carapace-bin.json

carapace-bin: Update URL

---

bucket/quicklook.json

The old homepage isn't working anymore.
Propose to use the GitHub repo page instead.

quicklook: update homepage

---

bucket/single-file-cli.json

Add manifest for SingleFile CLI.
Closes #15282

single-file-cli: Add version 2.0.75

---

bucket/datagrip.json

Updating the persistence of DataGrip.
Closes #15153

datagrip@2024.3.5-243.24978.79: Update persistence

---

bucket/triliumnext.json

Adds new app for notes - [triliumnext](https://github.com/TriliumNext/)

triliumnext: Add version 0.93.0

---

bucket/opentrace.json

OpenTrace@v1.4.3.0: Add version 1.4.3.0
Closes #13930

OpenTrace: Add version 1.4.3.0

---

bucket/treex.json

New scoop manifest for https://github.com/shiquda/treex

treex: Add version 0.0.3

---

bucket/folo.json

Closes #15355
Relates to #15255
https://github.com/RSSNext/Folo/pull/3518

folo: Add version 0.4.4

---

bucket/spotify-qt.json

Relates to https://github.com/ScoopInstaller/Versions/pull/2281, to any maintainers that see this, please also merge the versions PR.

spotify-qt: Update to version 4.0.0

---

bucket/beyondcompare.json

beyondcompare@5.0.7.30840: Persist license key file

---

bucket/deluge.json

deluge@2.2.0: Added 64-bit version

---

bucket/nomeiryoui.json

nomeiryoui: Add version 3.4.0

---

bucket/mpls.json

mpls: Add version 0.14.0

---

bucket/escrcpy.json

escrcpy: Add version 1.29.6

---

bucket/walksnail-osd-tool.json

Add Walksnail OSD Tool.
Closes #15405

walksnail-osd-tool: Add Version 0.3.0

---

bucket/gitkraken.json

gitkraken: Fix download and update URL

---

bucket/uefitool.json

https://github.com/ScoopInstaller/Extras/issues/15419

UEFITool: add version A71

---

bucket/ifrextractor-rs.json

https://github.com/ScoopInstaller/Extras/issues/15420

IFRExtractor-RS: add version 1.6.0

---

bucket/freelens.json

freelens: Add arm64 binary

---

bucket/ifrextractor-rs.json

ifrextractor-rs: remove shortcut as it is a console app

---

bucket/spacesniffer.json

spacesniffer: Update download URL and drop x86 support

---

bucket/komorebi.json

komorebi@0.1.37: add komorebi-shortcuts.exe binary to path

---

bucket/snipaste.json

Snipaste's binaries will no longer be hosted on Bitbucket.

snipaste: update download links

---

bucket/w10privacy.json

w10privacy: Update to version 5.2.0.1

---

bucket/deskflow.json

deskflow: Add version 1.21.2

---

bucket/gitify.json

gitify@6.4.0: fix filename after it has changed

---

bucket/picview.json

picview@3.1.3: persist Config

---

bucket/lunatranslator.json

lunatranslator: Add version 10.3.3

---

bucket/cherrytree.json

cherrytree: fixes #15589

---

bucket/vipsdisp.json

vipsdisp: Update to 4.0.0, fix autoupdate

---

bucket/ldplayer.json

update to new version of ldplayer

ldplayer: Update to version 9.1.49.2

---

bucket/simplyserial.json

Closes #15678
https://github.com/fasteddy516/SimplySerial?tab=readme-ov-file#global-settings

simplyserial: Add persistent settings.cfg

---

bucket/paraview.json

paraview@5.13.3: update to include the patch version

---

bucket/diffpdf.json

Host now accepts HTTPS connections

diffpdf: update manifest to support HTTPS

---

bucket/aegisub.json

aegisub: upgrade homepage to HTTPS

aegisub: upgrade homepage to HTTPS

---

bucket/deskflow.json

This Added arm64 for deskflow
Closes #15872

deskflow@1.23.0: Add arm64 version

---

bucket/exeinfo-pe.json

exeinfo-pe: Fix homepage & license urls

---

bucket/gifcam.json

gifcam: Upgrade all URLs to HTTPS

gifcam: Upgrade all URLs to HTTPS

---

bucket/fsviewer.json

fsviewer: Upgrade download and update URLS to HTTPS

fsviewer: Upgrade download and update URLS to HTTPS

---

bucket/freerapid.json

freerapid: Upgrade homepage to HTTPS

freerapid: Upgrade homepage to HTTPS

---

bucket/fnr.json

fnr: Upgrade download and autoupdate URLs to HTTPS

fnr: Upgrade download and autoupdate URLs to HTTPS

---

bucket/euler.json

euler: Upgrade homepage to HTTPS

euler: Upgrade homepage to HTTPS

---

bucket/eac.json

eac: Upgrade all URLs to HTTPS

eac: Upgrade all URLs to HTTPS

---

bucket/docear.json

docear: Upgrade all URLs to HTTPS

docear: Upgrade all URLs to HTTPS

---

bucket/dngrep.json

dngrep: Upgrade homepage to HTTPS

dngrep: Upgrade homepage to HTTPS

---

bucket/diffmerge.json

diffmerge: Upgrade all URLS to HTTPS

diffmerge: Upgrade all URLS to HTTPS

---

bucket/dhcp-server.json

dhcp-server: Upgrade all URLs to HTTPS

dhcp-server: Upgrade all URLs to HTTPS

---

bucket/detect-it-easy.json

detect-it-easy: Update redirecting HTTP homepage URL to HTTPS target

detect-it-easy: Update redirecting HTTP homepage URL to HTTPS target

---

bucket/amp-winoff.json

amp-winoff: Upgrade all URLs to use HTTPS

amp-winoff: Upgrade all URLs to use HTTPS

---

bucket/anyburn.json

anyburn: Upgrade all URLs to use HTTPS

anyburn: Upgrade all URLs to use HTTPS

---

bucket/aurora.json

aurora: Upgrade homepage to use HTTPS

aurora: Upgrade homepage to use HTTPS

---

bucket/babelmap.json

babelmap: Upgrade all URLs to use HTTPS

babelmap: Upgrade all URLs to use HTTPS

---

bucket/babelpad.json

babelpad: Upgrade all URLs to use HTTPS

babelpad: Upgrade all URLs to use HTTPS

---

bucket/color-cop.json

color-cop: Upgrade all links to HTTPS

color-cop: Upgrade all links to HTTPS

---

bucket/checksum-compare.json

checksum-compare: Upgrade homepage to HTTPS, fix download URL (using good mirror)

checksum-compare: Upgrade homepage to HTTPS, fix download URL (using good mirror)

---

bucket/flow-control.json

Add version 0.3.3
Closes #14865

flow-control: Add version 0.5.0

---

bucket/zen-browser.json

I notice Zen browser was missing from scoop and there was a PR made to add Zen to scoop but it's inactive. #14899 
So I decided to fix raise an active PR to get Zen added into Scoop.
Closes #13888

zen-browser@1.14.9b | feat: add Zen Browser support on Scoop

---

bucket/xpipe.json

xpipe@17.4: Add arm64 architecture builds

---

bucket/termite.json

termite: Add version 3.4

---

bucket/r3dfox.json

r3dfox: Add version 140.0.4
