bucket/dreamset.json
Dreamset is a settings editor for digital satellite receivers.
=> dreamset: Add version 2.4.13

bucket/asciidocfx.json
[AsciidocFX](https://github.com/asciidocfx/AsciidocFX)
>Asciidoc FX is a book / document editor to build PDF, Epub, Mobi and HTML books, documents and slides.
=> asciidocfx: Add version 1.7.3

bucket/nwjs-sdk.json, bucket/nwjs.json
=> nwjs(-sdk): Fix conflict with native scoop files

bucket/freac.json
- Closes #4517
Updates the freac download url
=> freac@1.1.2: Fix url

bucket/deadlock.json
Don't know if the text should be ascii but it was displaying incorrectly for me
=> deadlock: Fix manifest

bucket/googlechrome-portable.json
Add persistent configuration for googlechrome
=> googlechrome-portable: Add version 84.0.4147.135

bucket/firefox-esr-portable.json
Add persistent configuration for firefox-esr
=> firefox-esr-portable: Add version 78.1.0

bucket/bes.json
=> bes: Add version 1.7.7

bucket/balabolka.json
=> balabolka: Add version 2.15.0.751

bucket/real.json
Note: "bin" and "shortcuts" done nothing while I've tested.
=> real: Add version 0.2.0

bucket/firefox-portable.json
Add persistent configuration for firefox
=> firefox-portable: Add version 79.0

bucket/ytmdesktop.json
Adds the well known 3rd party desktop client for Youtube Music
* https://ytmdesktop.app/
* https://github.com/ytmdesktop/ytmdesktop
=> ytmdesktop: Add version 1.12.1

bucket/mozbackup.json
Add [MozBackup](http://mozbackup.jasnapaka.com/).
It backs up profiles from Mozilla programs.
=> mozbackup: Add version 1.5.1

bucket/silentcmd.json
Changes applied according to #4689
=> silentcmd: Add version 1.4

bucket/darktable.json
Script to cope with new NSIS exe, some hints :  
- NSIS executable command-line arguments: /S for silent install and /D= for destination folder
- RunAsInvoker to avoid the elevation asked by the NSIS setup
- pipe to Out-Null to force to wait for the end of the installation
Also re-added checkver and autoupdate
=> Update darktable.json with latest NSIS exe file

bucket/wexond.json
Corrections to the wexond repository name and download files have been made
=> wexond: Fix manifest

bucket/qv2ray.json
- Disable automatic update check
- Fix potential config error
=> qv2ray: pre_install tweaks

bucket/flyctl.json
flyctl is a deployment management client for fly.io
=> flyctl: Add version 0.0.143

bucket/dosbox-x.json
=> dosbox-x@0.83.6: Fix URL

bucket/material-maker.json
=> material-maker@0.93: Fix extract_dir

bucket/android-studio.json
=> android-studio: Update to version 4.1.0.19

bucket/ccextractor.json
https://github.com/ScoopInstaller/Main/pull/1509#issuecomment-712931892
=> ccextractor: Add version 0.88

bucket/musescore.json
=> musescore@3.5.2.311459983: Fix URL

bucket/t-clock.json
=> t-clock: Fix uninstaller.script

bucket/libreoffice-fresh.json
=> libreoffice-fresh: Fix shortcuts

bucket/archwsl.json
Fixes #3800 (i haven’t tested it, but it should work)
=> archwsl: Don’t erase file system on upgrades

bucket/fontforge.json
This enables CLI usages for FontForge.
=> fontforge: Add binary

bucket/shutter.json
=> shutter: Add version 4.4

bucket/netch.json
Missing initial field settings causes app exception.
=> netch: Fix default configuration

bucket/chipmunk.json, bucket/firefox-beta.json
chipmunk is a fast logfile viewer that can deal with huge logfiles (>10 GB). It powers a super fast search and is supposed to be a useful tool for developers who have to analyze logfiles.
=> chipmunk: Add version 2.9.0

bucket/xmousebuttoncontrol.json
=> xmousebuttoncontrol: Update to version 2.19.2

bucket/chatty.json
=> chatty: Add version 0.13.1

bucket/zeplin.json
I had to create this manifest to use Zeplin via Scoop so I thought I should publish it so others could benefit, too. 😃
=> zeplin: Add version 5.1.1

bucket/freetube.json
FreeTube is a free and open source YouTube client that uses the Invidious API to browse for videos without any trackers.
=> freetube: Add version 0.9.2

bucket/crystaldiskinfo.json
=> crystaldiskinfo: Persist 'Smart' folder

bucket/windiff.json
Moving from https://github.com/ScoopInstaller/Main/pull/1612
=> windiff: Add version 2.1.0

bucket/vroid-studio.json
I added VRoid Studio as the portable zip version.
It's a free 3D Tool to create Avatars made by the company pixiv.
Website: [https://vroid.com/en/studio/](https://vroid.com/en/studio/)
=> vroid-studio: Add version 0.11.3

bucket/civo.json
As this is not really that popular I didn't put on main repo, let me know if it should change.
=> civo: Add version 0.6.42

bucket/openwithplusplus.json
=> openwithplusplus: Add version 3.8.0.0

bucket/workspacer.json
a tiling window manager for Windows 10
=> workspacer: Add version 0.9.9

bucket/cura.json, bucket/kitty.json
=> cura@4.8.0: Fix URL

bucket/nexusfont.json
- Closes #5348
- Closes #5347
- Closes #5346
=> nexusfont: Update to version 2.6.2

bucket/okular.json
Added kde okular package.
Okular is a pdf document viewer.
=> okular: Add version 20.08.3-478

bucket/super-productivity.json
=> super-productivity: Add version 6.1.2

bucket/vcredist.json
Just fix the description to mention that this package installs all the redists, not just the latest one
=> vcredist: Adjust description (#5413) [scoop skip]

bucket/dotPeek.json
Removed unused space cleaner look of dotPeek.json
=> dotPeek: Minor fix [scoop skip]

bucket/pencil2d.json
Add Pencil2d manifest https://www.pencil2d.org/download/
=> pencil2d: Add version 0.6.5

bucket/alacritty.json
- Alacritty has moved to an organization, updated URL
- File has also changed from zip to one exe
- Closes #5234
=> alacritty: Update to version 0.7.1

bucket/onlyoffice-desktopeditors.json
=> onlyoffice-desktopeditors: Update to version 6.1.0.90

bucket/dockercompletion.json
This can be use to enable docker auto-completion for PowerShell
=> dockercompletion: Add version 1.2010.0.201211

bucket/zoom.json
Fixes Zoom regex to correctly detect the latest version.
=> zoom: Update to version 5.5.2

bucket/amfora.json, bucket/notion.json
https://github.com/makeworld-the-better-one/amfora
=> amfora: Add version 1.8.0

bucket/insomnia-designer.json, bucket/insomnia.json
=> insomnia: Update to version 2021.1.1

bucket/openark.json
[OpenArk](https://openark.blackint3.com/) is an open source anti-rookit(ARK) tool for Windows. Ark is Anti-Rootkit abbreviated, it aimmed at reversing/programming helper and also users can find out hidden malwares in the OS.
=> openark: Add version 1.1.0

bucket/retroarch.json
- Closes #5943
- Closes #5937
- Closes #5932
- Closes #5931
- Closes #5923
- Closes #5926
=> retroarch@1.9.1: Fix installation

bucket/centertaskbar.json
=> centertaskbar: Add version 1.92

bucket/netch.json
=> netch@1.8.2: Fix installation

bucket/tomcat.json
* Closes #5988
* Related: ScoopInstaller/Versions#280
=> tomcat: Update to version 10.0.5

bucket/wezterm.json
=> wezterm: Use wezterm-gui as shortcut

bucket/ddc-toolbox.json
[Homepage](https://github.com/ThePBone/DDCToolbox)
=> ddc-toolbox: Add version 1.4

bucket/hasher.json
Based on the app manifest "renamer.json" (software by the same publisher, follows the same patterns).
=> hasher: Add version 4.1

bucket/resizer.json
Based on the app manifest "renamer.json" (software by the same publisher, follows the same patterns).
=> resizer: Add version 2.1

bucket/logseq.json
=> logseq: Add version 0.0.17

bucket/nvcleanstall.json
- Closes #5955 
- Closes #5959
=> nvcleanstall@1.9.0: Fix URL

bucket/terminalpp.json
=> terminalpp: Add version 0.8.3

bucket/github.json
- Corrects autoupdate and download URL.
- Verified that checkver follows the same structure as before.
Closes #6125
=> github@2.8.0: Fix URL

bucket/picard.json
Unnecessary folder $PLUGINSDIR deleted.
=> picard: Remove not needed directories

bucket/diskgenius.json
To change app language from CN to EN
=> diskgenius@5.4.1.1178: Fix URL

bucket/logseq.json
=> logseq: Update to version 0.1.4

bucket/workspacer.json
Change brought with https://github.com/workspacer/workspacer/issues/211
=> workspacer@0.9.10: Update URL

bucket/smartsvn.json
=> smartsvn@14.1.0: Fix manifest

bucket/playnite.json
As of version 8.12, the author is no longer distributing the updates through the main site. The latest version does include a github release, but the previous 2 don't and the original update url is still being used and will likely be more reliable, so I left that as-is.
See https://playnite.link/forum/thread-613-post-3925.html#pid3925
=> playnite: Update to version 8.14

bucket/advancedrenamer.json
The program stores both the default and user-created presets in this directory.
=> advancedrenamer: Persist BatchMethods

bucket/windterm.json
* [Homepage](https://github.com/kingToolbox/WindTerm)
* Is there a way to create different shortcuts depending on `[System.Environment]::OSVersion.Version.Build`?
=> windterm: Add version 2.1.0

bucket/plantuml.json
=> plantuml: Remove graphviz dependency

bucket/confuser-ex.json
https://github.com/mkaring/ConfuserEx
=> confuser-ex: Add version 1.5.0

bucket/regexp.json
Registry Explorer - enhanced Registry editor/viewer
=> regexp: Add version 0.7

bucket/butane.json
This pull request adds an app manifest for [Butane](https://github.com/coreos/butane), a config transpiler for [Fedora CoreOS](https://docs.fedoraproject.org/en-US/fedora-coreos/) configs.
=> butane: Add version 0.13.0

bucket/blender.json
=> blender@2.93.2: Fix extract_dir

bucket/audacity.json
- Closes #6546
Update audacity to version 3.0.3 and add autoupdate
=> audacity: Update to version 3.0.3

bucket/rbtray.json
=> rbtray: Update to version 4.11

bucket/electron-fiddle.json
=> electron-fiddle: Add version 0.26.0

bucket/tageditor.json
=> tageditor: Add version 3.4.2

bucket/locale-emulator.json
=> locale-emulator@2.5.0.0: Fix installation

bucket/flutter.json
Tracked because the URL of Flutter has changed
Signed-off-by: kokkiemouse <kokkiemouse@fascode.net>
=> flutter: Update to version 2.2.3

bucket/expresso.json
Downgraded version so it auto updates correctly.
=> expresso@3.1.7917: Adjust URL

bucket/kdenlive.json
=> kdenlive: Update to version 21.08.1

bucket/vnote.json
=> vnote: Update to version 3.7.0

bucket/powertoys.json
=> powertoys: Fix autoupdate

bucket/imhex.json
close https://github.com/ScoopInstaller/Extras/issues/6652 https://github.com/ScoopInstaller/Extras/pull/6654
=> imhex: Update to version 1.10.1 and fix autoupdate

bucket/hwinfo.json
=> hwinfo@7.14-4610: URL and 32bit pre_install fix

bucket/diagram-designer.json
Supercedes #6975
[Diagram Designer](https://logicnet.dk/DiagramDesigner/) is a **vector graphics editor** for creating flowcharts, UML class diagrams, illustrations and slide shows.
=> diagram-designer: Add version 1.29.5

bucket/youtubedownloader.json
=> youtubedownloader: Add version 1.8.3

bucket/firefox-beta.json, bucket/firefox-developer.json, bucket/firefox-esr-portable.json, bucket/firefox-esr.json, bucket/firefox-nightly.json, bucket/firefox-portable.json, bucket/firefox.json
related:
https://support.mozilla.org/en-US/kb/customizing-firefox-using-policiesjson
https://github.com/mozilla/policy-templates/blob/master/README.md
=> Firefox*: persist 'distribution' folder

bucket/makehuman.json
Update makehumain to 1.2.0 , update checkver and add autoupdate
=> Update makehuman manifest 

bucket/tomcat.json
=> tomcat: Persist conf and webapps folders

bucket/notepadplusplus.json
Fixes #5432
Also persists nativeLang.xml so that the chosen UI language is saved with each update
=> notepadplusplus: Persist nativeLang.xml and shortcuts.xml

bucket/gimp.json
I need to fix the hash but gimp should be updated
=> gimp: Update to version 2.10.28

bucket/foxit-pdf-reader.json
Deprecation note added in #6584
=> foxit-pdf-reader: Add version 11.0.1.49938

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Package_request.md, .github/issue_template.md, .github/pull_request_template.md
=> Add issue/PR templates

bucket/capframex.json
@404NetworkError could you please help us out in fixing CapFrameX?
Is this fix correct?
Is the application 32 bit or 64 bit?
=> CapFrameX: fix autoupdate extract_dir

bucket/q-dir.json
When running the app it's currently reporting v9.97 which also coincides with the information on the app's homepage, hence why I'm updating that part of the manifest.
=> Update q-dir.json - correcting version to 9.97 

bucket/qbittorrent.json
Fix https://github.com/ScoopInstaller/Extras/issues/5845
=> Merge qbittorrent-portable into qbittorrent

bucket/siyuan-note.json
Fix issues.
Click to see detail: [Pull Request #7251 · ScoopInstaller/Extras](https://github.com/ScoopInstaller/Extras/pull/7251)
=> siyuan-note: Add version 1.4.8

bucket/jcpicker.json
=> jcpicker: Add version 5.6

bucket/mpv.json
Update urls for mpv-0.34.0.
Closes #7270
=> mpv: Update URL

bucket/kitty.json
=> kitty: Update homepage in manifest.

bucket/netron.json
=> netron: Update homepage 

bucket/ungoogled-chromium-portable.json
=> ungoogled-chromium-portable: Fix manifest and update

bucket/powertoys.json
=> powertoys: update to 0.49.1

bucket/lazygit.json
Updated lazygit to version 0.31.3 and added 32bit version
=> lazygit: Update to version 0.31.3

bucket/ventoy.json
Updated ventoy to version 1.0.59
=> ventoy: Update to version 1.0.59

bucket/fvim.json, bucket/neovim-qt.json
Neovim GUI client - like https://github.com/ScoopInstaller/Extras/blob/master/bucket/fvim.json
=> neovim-qt: Add version 0.2.16.1

bucket/mpc-hc-fork.json
Updates the manifest to v1.9.17.
=> mpc-hc-fork.json: Update to 1.9.17

bucket/xmind8.json
=> xmind8: Update to version 3.7.9

bucket/ventoy.json
=> Update Ventoy to 1.0.60

bucket/synology-surveillance-station.json
Add Synology Surveillance Station client
=> synology-surveillance-station: Add version 1.2.11-2181

bucket/ventoy.json
=> Ventoy: Update to 1.0.61

bucket/x64dbg.json
Relates to #7198
Closes #7275
Closes #7276
=> x64dbg: Update to version 2021-11-03_11-01

bucket/adwcleaner.json
Added AdwCleaner 8.2:
* Not sure about the license, should I just add "Freeware"?
* Couldn't find a way to download a specific version, rather the link will always download the latest version.
=> adwcleaner: Add version 8.2

bucket/mitmproxy.json
=> mitmproxy: add missing executable

bucket/zoom.json
- add registry keys post-install
- remove these during uninstallation
Fixes: #4573
Related: lukesampson/scoop#3944, lukesampson/scoop#3412
=> zoom: register/unregister zoommtg:// protocol handler

bucket/xnconvert.json
- Closes #7011
- Closes #5925
- Closes #6019
=> xnconvert: Add version 1.94

bucket/rocketchat-client.json
=> update rocket-chat desktop client to 3.6.0

bucket/telegram.json
=> Telegram: Update to version 3.2.5

bucket/msiafterburner.json
=> msiafterburner@4.6.4.16094: Hash fix

bucket/banana-cake-pop.json
- Update autoupdate url URL
- Update to version 1.0.0-preview.14
I have searched. No other PRs exist.
Is an issue required for a version update PR?!
=> banana-cake-pop: Update to version 1.0.0-preview.14

bucket/revouninstaller.json
supersedes #5205, #562
[RevoUninstaller](https://www.revouninstaller.com/) is a tool for uninstalling programs including a file scan for leftovers after uninstallation.
=> revouninstaller: Add version 2.3.5

bucket/logseq.json
=> logseq: update to 0.4.9

bucket/vscodium-portable.json, bucket/vscodium.json
Just updating my favorite IDE, nothing much else to say.
=> vscodium, vscodium-portable: update to 1.62.3

bucket/msiafterburner.json
=> msiafterburner: Update to version 4.6.4.16117

bucket/taskbarx.json
Updated taskbarx to version 1.7.3.0
=> taskbarx: Update to version 1.7.3.0

bucket/featherwallet.json
Feather: a free Monero desktop wallet
https://featherwallet.org/
https://docs.featherwallet.org/guides/portable-mode
=> featherwallet: Add version 1.0.1

bucket/scratch.json
* added winrar as a depenceny
* fixes #7338
* This is a workaround
=> scratch: use winrar to extract nsis sfx

bucket/horcrux.json
https://github.com/jesseduffield/horcrux
- Closes #4910
=> horcrux: Add version 0.2

bucket/logseq.json
=> logseq: update to 0.5.0

bucket/trilium.json
- Closes #4822 
1. Update to the latest version (not sure why it wasn't already..)
2. Add persistent data as per [their wiki](https://github.com/zadam/trilium/wiki/Data-directory#changing-the-location-of-data-directory) and attempt to migrate existing configuration from AppData\Roaming to $persist_dir
Also I feel like renaming the existing `trilium-data` folder in AppData\Roaming to `trilium-data.old` or something like that to prevent possible confusion. It's not a big deal though. Thoughts?
=> trilium: Add persistent data

bucket/logseq.json
=>  logseq: update to 0.5.1

bucket/adwcleaner.json
Updates version and corresponding hash to 8.3.1.
=> Update adwcleaner.json: v8.3.1

bucket/lazygit.json
Updated lazygit to version 0.31.4
=> lazygit: Update To version 0.31.4

bucket/shotcut.json
=> shotcut: update to v21.10.31

bucket/shotcut.json
=> Shotcut: Fix install

bucket/pcem.json
=> pcem: Change to http URLs

bucket/deskreen.json
=> deskreen: Add version 1.0.11

bucket/vscode-insiders-portable.json, bucket/vscode-insiders.json, bucket/vscode-portable.json, bucket/vscode.json, bucket/vscodium-portable.json, bucket/vscodium.json
=> vscode: Prevent shim errors in WSL

bucket/prusaslicer.json
As commented on #7438 , keeping only the console in the bin parameter
=> PrusaSlicer

bucket/superslicer.json
Used the prusaslice.json as a base to add the superslicer.json as the later is a fork of the former.
Used checkver.ps1 to check for hash and update url
It only has a 64 bit version no win32.
=> Adding SuperSlicer

bucket/tachidesk-server.json
=> Update tachidesk-server.json and change autoupdate logic

bucket/renderdoc.json
=> renderdoc: update to 1.17

bucket/tachidesk-jui.json
https://github.com/ScoopInstaller/Java/pull/299#issuecomment-899494876
=> tachidesk-jui: Add version 1.2.0

bucket/micswitch.json
- Closes #5755
MicSwitch is a tool which allows you to mute/unmute your microphone using a predefined hotkey
=> micswitch: Add version 1.0.217

.github/workflows/issue_comment.yml, .github/workflows/issues.yml, .github/workflows/pull_request.yml
The SSL errors on running commands such as `/verify` do not occur on Windows runners. See here - https://github.com/rashil2000/Extras/pulls
=> chore(ci): Use Windows Actions to avoid SSL errors

bucket/solvespace.json
Closes #7456
No architecture section because app is 32-bit.
=> Add SolveSpace version 3.0

.github/workflows/excavator.yml
See https://github.com/ScoopInstaller/Main/pull/2871
cue @r15ch13
=> chore(ci): Add excavator workflow

bucket/gopher360.json
Continuation of https://github.com/ScoopInstaller/Main/pull/3046
=> gopher360: add manifest

bucket/monero.json
=> Monero: Fix hash

bucket/sdl2.json
=> sdl2: update to 2.0.18

bucket/mucommander.json
muCommander is an open source, dual-pane file manager
=> mucommander: Add version 0.9.7-1

bucket/microsoft-teams.json
This basically adds the manifest provided by @FriendlyNeighborhoodShane in #3595 + Autoupdate.
I tested the install and it works on my machine ™
Closes #3595
=> Add Microsoft Teams

bucket/msiafterburner.json
- Updates version described in the manifest to the current which is 4.6.4.16255
=> Update msiafterburner.json: Corrects version in the manifest

bucket/webcopy.json
[WebCopy](https://www.cyotek.com/cyotek-webcopy)  is a free tool for automatically downloading the content of a website onto local device.
=> webcopy: Add version 1.8.0.652

bucket/libresprite.json
Closes #7522
No persist because portable app as far as I can tell.
=> LibreSprite: Add version 1.0

bucket/onecommander.json
=> onecommander: add version 3.4.2.0

bucket/standardnotes.json
This is a redo of PR#7470
Closes #7469
=> Switch standardnotes to x64

bucket/integerscaler.json
Closes #7451
I hope "Freeware" is okay for the following license:
> This software is free and provided with no warranty. Its author is not responsible for consequences of using it. You are allowed to use and/or distribute it as long as original author's files are unchanged and this readme file is provided together with files of the product itself.
=> IntegerScaler: add version 2.18

bucket/mtuner.json
mtuner: Add version 4.4.8
Closes #5356
=> mtuner: Add version 4.4.8

bucket/gsmartcontrol.json
Add new package GSmartControl
Closes #7497
=> GSmartControl: add version 1.1.3

appveyor.yml
Change to appveyor settings to the same as Main bucket
=> feat(chore): Update appveyor powershell names

bucket/renamer.json
close https://github.com/ScoopInstaller/Extras/issues/7189
=> renamer: Fix license

bucket/tinymediamanager.json
tinymediamanager: Version up to 4.2.4, fix download url, add autoupdate.
=> tinymediamanager: Version up to 4.2.4, fix download url, add autoupdate.

bucket/zoom.json
=> zoom: Update to version 5.9.0.2481

bucket/w64devkit.json
=> w64devkit: Add version 1.10.0

bucket/activemq.json
Add new activemq version 5.16.2 with autoupdate.
=> activemq: Add version 5.16.2

bucket/superf4.json
Force quit apps by pressing Ctrl-Alt-F4.
=> superf4: Add version 1.4

bucket/video-compare.json
=> video-compare: Add version 20211223

bucket/schismtracker.json
=> schismtracker: Update to version 20211116

bucket/wsa-pacman.json, scripts/wsa-pacman/install-associations.reg, scripts/wsa-pacman/uninstall-associations.reg
[wsa_pacman](https://github.com/alesimula/wsa_pacman) is a GUI package manager and package installer for Windows Subsystem for Android (WSA).
Note:
I used the  portable package but did not find the configuration file. @alesimula, can you help with this question?
Relates to https://github.com/alesimula/wsa_pacman/issues/10
=> wsa-pacman: Add version 1.1.1

bucket/vidcoder.json
=> VidCoder: fixes a no-longer-available VidCoder configuration option

bucket/aws-session-manager-plugin.json
I add a new bucket for  a AWS-CLI session manager plugin.
I hope you can merge this pull request.
Closes #6215
=> aws-session-manager-plugin: Add version 1.2.54.0

bucket/syncplay.json
- Closes #2730
syncplay allows far away friends to sync their media players
=> syncplay: Add version 1.6.9

bucket/fileoptimizer.json
=> fileoptimizer@15.20.2657: Fix hash

bucket/thisiswin11.json
*ThisIsWin11 lets you customize Windows 11 all in one place. It is slowly expanded as a practical all-rounder for Windows 11, similar to Microsoft PowerToys.*
Closes #7604
=> thsiswin11: Add version 1.0.50

bucket/biblioteq.json
Add an installer for BiblioteQ (a library management app).
=> biblioteq: Add version 2021.02.12

zerobrane-studio.json
Adds [ZeroBrane Studio](https://studio.zerobrane.com/), a popular IDE for Lua.
=> zerobrane-studio: Add version 1.80

bucket/uget-portable.json
`share\locale` for storing translated documents
=> uget-portable:Add persistence

bucket/red.json
- Closes #7618
- Will need to be updated when 2.3 releases with separate releases for 32bit and 64bit.
=> red: add version 2.2

bucket/roslynpad.json
> A cross-platform C# editor based on Roslyn and AvalonEdit
- https://roslynpad.net/ 
- https://github.com/aelij/RoslynPad
=> roslynpad: Add version 15.1

bucket/netbeans.json
=> netbeans: Update to version 12.6

bucket/ubports-installer.json
Supersedes #5199. (see old PR for more details)
upstream discussion: https://github.com/ubports/ubports-installer/issues/1592
=> ubports-installer: Add version 0.9.1-beta

bucket/xmlnotepad.json
A XML editor provided by Microsoft.
Homepage: https://microsoft.github.io/XmlNotepad/
=> xmlnotepad: Add version 2.8.0.52

bucket/buckets.json
=> buckets: Add version 0.63.2

bucket/jpegview.json
Supersedes #2723 (see old PR for more details)
=> jpegview: Manually persist 'ParamDB.db'

bucket/trillian.json
Trillian
https://www.trillian.im
=> trillian: Add version 6.4.0.5

bucket/manifold.json
=> manifold: fix autoupdate

bucket/manifold-viewer.json
manifold-viewer: fix autoupdate
=> manifold-viewer: fix autoupdate

bucket/toggl.json
Modify checkver according to @niheaven's comment at #4311
=> toggl: Update to version 7.5.445, fix checkver

bucket/p4v.json
Closes #7639
* Added an auto updating manifest for Helix Visual Client (P4V).
=> p4v (Helix Visual Client): Add version 2021.4-2227050

bucket/freecad.json
=> freecad: Fix autoupdate and update to latest

bucket/jstock.json
Adding the JStock app scripts. ;)
=> jstock: Add version 1.0.7.45

bucket/coreftp.json
[coreftp](http://www.coreftp.com/) is a free FTP client.
=> coreftp: Add version 2.2

bucket/detect-it-easy.json
https://github.com/horsicq/Detect-It-Easy
=> detect-it-easy: Add version 3.03

bucket/docear.json
[docear](http://www.docear.org/) is a unique solution to academic literature management
=> docear: Add version 1.2

bucket/paint.net-plugin-boltbait.json
Supersedes #4266 (see old PR for more details)
This adds paint.net plugin pack by BoltBait (https://boltbait.com/pdn).
=> paint.net-plugin-boltbait: Add version 5.1

bucket/runcat.json
A cute running cat animation on your windows taskbar (based on CPU load).
https://github.com/Kyome22/RunCat_for_windows
=> RunCat: Add version 1.10

bucket/ontopreplica.json
[OnTopReplica](https://github.com/LorenzCK/OnTopReplica): A real-time always-on-top “replica” of a window.
=> ontopreplica: Add version 3.5.1-fix

bucket/copyq.json
=> copyq: Update to version 6.0.1

bucket/ccextractor.json
=> ccextractor: Update to version 0.94

bucket/dbvis.json
=> dbvis: Update to version 12.1.5 & add autoupdate

bucket/streamlabs-obs.json
=> streamlabs-obs: Update to 1.6.4 and fix checkver

bucket/chromium.json
Closes #XXXX 
Relates to #7292 
- List of files can be found here: https://github.com/LazyGeniusMan/Sc00p-Test/runs/4697216768?check_suite_focus=true#step:3:3
- Should I also add bin & scripts that's used in `ungoogled-chromium` ?
=> chromium: Update to 96.0.4664.93-r929512 and switch to new URL

bucket/hakchi2-ce.json
Adds this application 
Closes #7666
=> Add hakchi2 ce

bucket/foobar2000.json
Closes #7675
Additionally adjust fields order
=> Foobar2000: fix conflicts when renaming 'playlists' folder

bucket/p4v.json
=> Include bin statements in p4v

bucket/ffdec.json
=> ffdec: Add version 15.0.0

bucket/postman.json
Closes https://github.com/ScoopInstaller/Extras/issues/7693
=> postman: fix autoupdate

bucket/siyuan-note.json
=> siyuan-note: Update to version 1.6.3

bucket/masvis.json
=> masvis: Add version 1.2

bucket/firemin.json
close #6256
[Firemin](https://www.rizonesoft.com/downloads/firemin/) is a utility to reduce the memory usage of Firefox or other browsers.
Notes:
* **license** info can be found in the "about" dialog of the software.
Screenshots:
=> firemin: Add version 8.2.3.5338

bucket/whatsapp.json
=> whatsapp: Manually create shortcut w/o junction

bucket/webex.json
Closes #5167
* Added auto updating manifest for Cisco Webex
=> webex: Add version 41.12.0.20899

bucket/dngrep.json
I apologize for the last PR, had trouble with the old repository, deleted and re-forked.
Tested installation, uninstallation, and autoupdate.
The file `dnGREP.Settings.dat` is generated only after opening settings menu for the first time, and adding it to Persist will create a new empty folder with the same name, thus ignored.
Closes #7719
=> add dngrep.json

bucket/flow-launcher.json
[Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher) is a quick search and app launcher tool that helps Windows users navigate around the OS.
Tested installing, uninstalling and updating with this manifest
=> Flow Launcher: Add version 1.9.1

bucket/compactor.json
=> compactor: Add version 0.10.1

bucket/tinymediamanager.json
tinymediamanager: Update version to 4.2.5.1, fix checkver url and regex
=> tinymediamanager: Update version to 4.2.5.1, fix checkver url and regex

bucket/keenwrite.json
=> keenwrite: Add version 2.5.1

bucket/qview.json
=> qview@5.0: Fix extract_dir

bucket/gcc-arm-none-eabi.json
=> gcc-arm-none-eabi@10.3-2021.10: update url

bucket/beeftext.json
=> beeftext: Add version 13.0

bucket/opentrack.json
=> opentrack: Update to version 2022.1.0

bucket/macast.json
Closes to #7758
- [-] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> Macast: Add version 0.7

bucket/opentrack.json
=> opentrack: Use portable configuration

bucket/strawberry.json
=> strawberry: Add version 1.0.1 and fix autoupdate

bucket/silex-desktop.json
- Closes #7762
- Nothing to persist, settings stored in `AppData\Roaming\silex-desktop`
- Parent project has 1.2k stars so probably worth adding
=> silex-desktop: add version 2.7.27

bucket/apkeep.json
- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> Add apkeep

bucket/qtemu.json
=> qtemu: Add version 2.1

bucket/virt-viewer.json
=> virt-viewer: Update to version 11.0-1.0 and add autoupdate

bucket/kodi.json
Relates to https://github.com/ScoopInstaller/Versions/pull/393#issuecomment-1015642455
=> kodi: add hash extraction

bucket/skype.json
=> skype: Update to version 8.79.0.95 and fix checkver URL

bucket/postman.json
=> postman: Use 'nupkg' to simplify script

bucket/kryptor.json
=> Kryptor: Add version 3.1.0

bucket/pwtech.json
Need help with extraction and autoupdate
=> Add Password Tech

bucket/pure-data.json
=> pure-data: Added version 0.52-1

bucket/megabasterd.json
=> megabasterd: Add version 7.49

bucket/secureuxtheme.json
=> secureuxtheme: Add version 2.1.2

bucket/musicplayer2.json
=> MusicPlayer2: Add version 2.73

bucket/notepad3.json
=> Notepad3: Update to 5.21.1129.1 & add autoupdate

bucket/mdloader.json
=> mdloader: Add version 1.0.6

bucket/smartsystemmenu.json
=> SmartSystemMenu: Add version 2.18.0

bucket/kopiaui.json
Data is stored in `%appdata%/kopia-ui`
=> KopiaUI: Add version 0.10.1

bucket/youtube-dl-gui.json
Just updated the package, this version had a name change in the .msi and was not being auto updated, I am not entirely sure if I got the `checkver` and `autoupdate` syntax correct, so pls lmk
Closes #7815
=> Updated youtube-dl-gui to v1.8.3

bucket/wonderpen.json
I wonder if there's a better regular expression in `autoupdate` 🤔
No persist file.
=> Wonderpen: Add version 2.0.5

bucket/propertree.json
=> Propertree: Add version 0.2022.01.22

bucket/cheat-engine.json
=> cheat-engine: Undeprecate manifest

bucket/fastcopy.json
close https://github.com/ScoopInstaller/Extras/issues/7829 https://github.com/ScoopInstaller/Extras/pull/7830
=> fastcopy@4.0.2: Fix install scripts

bucket/musicbee.json
- Fix checkver
- Update to version 3.4.8033
close https://github.com/ScoopInstaller/Extras/issues/7823
=> musicbee: Update manifest

bucket/komorebi.json
There is still a problem with this manifest, `komorebi.exe` does not work when launched from the shim, although it works when launched directly. I hope someone here can help with that. 
Related issue: https://github.com/LGUG2Z/komorebi/issues/95
=> komorebi: Add version 0.1.8

bucket/fastcopy.json
- Update install scripts
- Add shortcut for setup.exe
Closes #7850
=> fastcopy: Update manifest

bucket/xdman.json
- Update to version 7.2.11
- Update homepage url
- Update license
- Add suggest
- Use standalone jar instead MSI installer
- Add checkver
- Update autoupdate
Closes #7859
=> xdman: Update manifest

bucket/languagetool.json
=> languagetool: Fix checkverr

bucket/ani-cli.json
ani-cli : A cli to browse and watch anime. This tool scrapes the site gogoanime.
=> ani-cli: Add version 1.6

bucket/vcredist2022.json
=> vcredist2022: Update to version 14.31.31103.0

bucket/vcredist.json
=> vcredist: Update to version 14.31.31103.0

bucket/cutter.json
Closes N/A (Can open one if needed), related to ScoopInstaller/main#3268
=> cutter: Add cutter v2.0.5 (Moved from main)

bucket/musicplayer2.json
powershell syntax error
[foreach-object](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object)
=> musicplayer2@2.73: Update pre_install

bucket/thunderbird.json
forgot to add this in the previous commit
=> thunderbird: persist `distribution`

bucket/winmerge.json
Upstream has moved from Sourceforge to Github
---
=> winmerge: Update to version 2.16.18

bucket/win-gpg-agent.json
=> win-gpg-agent: Add version 1.5.0

bucket/psiphon3.json
=> psiphon3: Add checkver

bucket/choeazycopy.json
Added ChoEazyCopy version 1.0.0.23
~Its a neutal application~
32bit application
Closes #7936
=> choeazycopy: Add version 1.0.0.23

bucket/trafficmonitor-lite.json
=> trafficmonitor-lite: Add version 1.83

bucket/ytsubconverter.json
Added YTSubConverter version 1.6.0
Closes #7966
=> ytsubconverter: Add version 1.6.0

bucket/mqttx.json
=> mqttx: Add 32-bit architecture.

bucket/mobalivecd.json
=> mobalivecd: Add version 2.1

bucket/miniconda3.json
With updates of activating under powershell.
Closes #XXXX
=> miniconda3: Update notes

bucket/waterfox.json
add Waterfox Portable
Closes #6956
=> waterfox: Update manifest

bucket/waterfox.json
Reverts ScoopInstaller/Extras#7976
=> Revert "waterfox: Update manifest"

bucket/waterfox-classic.json
=> waterfox-classic: Update manifest

bucket/ventoy.json
=> ventoy: Add VentoyPlugson and VentoyVlnk as shortcuts

bucket/discordchatexporter.json
=> discordchatexporter: Add version 2.32

bucket/ventoy.json
Follow up of #7993
Closes #XXXX
=> ventoy: VentoyVlnk.exe -s the save as file path.

bucket/raylib-mingw.json, bucket/raylib.json
- Closes #7927
- Installer/uninstaller heavily based on https://github.com/ScoopInstaller/Extras/blob/master/bucket/sdl2-image.json
=> raylib: add version 4.0.0

bucket/micaforeveryone.json
=> micaforeveryone: Add version 0.0.4.1

bucket/mendeley.json
close #8014
[Mendeley](https://www.mendeley.com/download-reference-manager/windows) is a useful reference manager which is used to manage and share research papers and generate bibliographies for scholarly articles.
**NOTES**:
* persist is not needed because config is at `$Env:AppData\Mendeley Reference Manager`.
=> mendeley: Add version 2.66.0

bucket/terminal-icons.json
=> terminal-icons: Add version 0.9.0

bucket/psfzf.json
=> psfzf: Add version 2.4.0

bucket/terminal-icons.json
=> terminal-icons: Add Nerd Font note

bucket/psfzf.json
=> psfzf: Add fzf suggest

bucket/marktext.json
=> marktext: Fix can't shim 'MarkText.exe'

bucket/deadbeef.json
=> deadbeef: Update to 1.8.8

bucket/MSEdgeRedirect.json
Closes #7572 
Generated file based on the file used for #7866 
If anything is wrong let me know :)
=> MSEdgeRedirect: Add version 0.6.2.0

bucket/git-aliases.json
=> git-aliases: Add version 0.3.5

bucket/posh-git.json
=> posh-git: Use PSGallery as source

bucket/shawl.json
Related: https://github.com/mtkennerly/shawl/issues/20
=> shawl: Add version 1.1.0

bucket/mpv-git.json
=> mpv use yt-dlp now

bucket/mpv.json
=> Mpv now use yt-dlp

bucket/xdman.json
=> xdman: Fix shortcut

bucket/sunshine.json
=> sunshine: Add version 0.12.0

bucket/moonlight.json
=> moonlight: Add version 3.2.0

bucket/choeazycopy.json
See https://github.com/Cinchoo/ChoEazyCopy/commit/88833961b955afb1d5bbfd6e17a3811cc640061c
Closes #XXXX
=> choeazycopy: Update license

bucket/ventoy.json
=> add Ventoy2Disk.ini on persist

bucket/vitomu.json
No persist and no bin. It's a standard Electron-based app.
=> Vitomu: Add version 2.1.0

bucket/tb-vol-scroll.json
Added tb-vol-scroll application which allows to control volume by scrolling in taskbar area
Closes #XXXX
=> tb-vol-scroll: Add version 4.1.1

bucket/sunshine.json
=> sunshine: Persist credentials folder

bucket/geany-plugins.json, bucket/geany.json
- geany: Add installer.script for geany-plugins
Closes #7952
=> geany-plugins: Add version 1.38

bucket/streamwriter.json
Current version is 5.5.1.1 (since some months)... so it seems like the autoupdate is not working.
This change simplifies the regex _AND_ is proved to work...
=> streamwriter: Fix checkver

bucket/xournalpp.json
=> xournalpp: Update to version 1.1.1

bucket/sioyek.json
- Closes #8098
- Persists user config and last opened file
- Should we suggest vcredist & delete it from `$dir`? It is included in the portable zip and is 24MB.
=> sioyek: add version 1.1.0

bucket/battery-care.json
Add BatteryCare v0.9.36 app manifest
=> BatteryCare: Add version 0.9.36

bucket/firefox.json
=> firefox: Fix checkver

bucket/rtlutility.json
Add RTL Utility 1.0.3 from Oblique Audio https://oblique-audio.com/rtl-utility.php
Please let me know if there's a better way to do the `pre` and `post` scripts to make the shortcuts work.
=> rtlutility: Add version 1.0.3

bucket/reaper.json
Closes #3350
Change suggested by jarosz and simplified by Ash in the PR above.
=> reaper: fix default theme not loading

bucket/spotify.json
=> spotify: Add version 1.1.80.699.gc3dac750

bucket/foxit-pdf-reader.json
also change download package to international language version
- [ X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=>  pdf-foxit-reader: fix autoupdate url

bucket/mpv.net.json
Updated license https://github.com/stax76/mpv.net/commit/3f137474139d3721c3b8dd0b264bb76ceba36004
Updated to 64bit only
Updated checkver, autoupdate
Closes #XXXX
=> mpv.net: Update to version 5.7.0.0

bucket/godot.json
=> godot: Update shortcut

bucket/godot-mono.json
=> godot-mono: Update shortcut

bucket/apache-tinkerpop-gremlin-console.json, bucket/apache-tinkerpop-gremlin-server.json
- Updates to latest version
- Fixes `checkver`
=> apache-tinkerpop-gremlin-*: update to v3.5.2

bucket/appium.json
- Updated to latest version
- Added autoupdate
- Update shortcut to new name
- No hash available
=> appium: update to version 1.22.2, add autoupdate

bucket/nswagstudio.json
Also changed the version regex and changed to zip release
=> NSwagStudio update to 13.15.10

bucket/logisim-evolution.json
=> logisim-evolution: Add version 3.7.2

bucket/capframex.json
=> capframex: remove extract directory

bucket/barrier.json
Adds vcredist2019 as dependancy for barrier
Closes #8155
=> Add vcredist2019 as dependancy for barrier

bucket/kui.json
=> kui: Add version 11.4.4

bucket/lavape.json
**LavaPE** ([homepage](http://lavape.sourceforge.net/)) ([Wikepedia](https://en.wikipedia.org/wiki/Lava_(programming_language))) is the interpreter/programming environment for the Lava language, an object-oriented rapid application development (RAD) language with type parameters (virtual types), refactoring, and extensive static checks.
**NOTES**:
* *persist* is not needed because user config is at `$Env:LocalAppData\lavadoc`.
* *autoupdate* is not needed because last update was in 2013.
=> lavape: Add version 0.9.4

bucket/irfanview.json
- Closes #8175
- Adds autoupdate, a bit messy but the hashes are spread across many pages, not much we can do
=> irfanview: Update to version 4.60, add autoupdate

bucket/micaforeveryone.json
=> micaforeveryone: Update to version 1.0.5.0

bucket/avrdudess.json
Adds https://github.com/ZakKemble/AVRDUDESS a GUI for programming AVR microcontrollers.
=> avrdudess: Add version 2.13

bucket/ani-cli.json
=> ani-cli@1.9: Suggest mpv instead of depending

bucket/sirikali.json
=> sirikali: Add version 1.5.0

bucket/hysteria.json
=> hysteria: Add version 1.0.1

bucket/yesplaymusic.json
closes #8202
[YesPlayMusic](https://music.qier222.com/) is a cloud music player based on [NetEase Player](https://chrome.google.com/webstore/detail/netease-music/fogcjafchgdhdoieggbeldnckbghdpkn), featuring more elegant UI.
**NOTES**:
* The app is built in 64-bit.
* *persist* is not needed because config is at `$Env:AppData\yesplaymusic`.
=> yesplaymusic: Add version 0.4.3

bucket/wsltty.json
=> wsltty: Make installation portable

bucket/quassel.json
=> quassel: Add version 0.14.0

bucket/sumatrapdf.json
Use download links from official website @ https://www.sumatrapdfreader.org/download-free-pdf-viewer
=> sumatrapdf: Link fix

bucket/twinkle-tray.json
=> twinkle-tray: add version 1.13.11

bucket/g-assist.json
Closes https://github.com/ScoopInstaller/Extras/issues/8173
- [ x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> added google assistant

bucket/calibre.json
resolve the Windows path is too long bug
Closes #XXXX
=> calibre: Resolve 'path too long' bug

bucket/advanced-ip-scanner.json
Relates to Excavator checkver not working: https://github.com/ScoopInstaller/Extras/runs/5750830616?check_suite_focus=true#step:3:193
=> advanced-ip-scanner: Fix checkver

bucket/dadroitjsonviewer.json
Relates to Excavator checkver failing due to change to website layout: https://github.com/ScoopInstaller/Extras/runs/5750830616?check_suite_focus=true#step:3:202
=> dadroitjsonviewer: Update to v1.5.2153, fix urls

bucket/gcc-arm-none-eabi.json
=> gcc-arm-none-eabi@11.2-2022.02: use new location

bucket/dxwnd.json
Relates to Excavator checkver issue: https://github.com/ScoopInstaller/Extras/runs/5750830616?check_suite_focus=true#step:3:212
=> dxwnd: Update to version 2.05.82, fix checkver

bucket/winspy.json
=> winspy: add version 1.0.3

bucket/rocketchat-client.json
=> rocketchat-client: Fix installer exe name

bucket/psreadline.json
Adds PSReadLine PowerShell module
=> psreadline: add version 2.2.2

bucket/blender-launcher.json
=> Blender Launcher: Add version 1.14.1

bucket/blender-launcher.json
=> Blender Launcher@1.14.1: add alias for bin with no whitespace

bucket/jameica.json
Relates to Excavator checkver unable to find latest version: https://github.com/ScoopInstaller/Extras/runs/5816231900?check_suite_focus=true#step:3:269
=> jameica: Fix checkver

bucket/cruft.json
Add a manifest for https://github.com/cruft/cruft
=> cruft: Add version 2.10.1

bucket/cookiecutter.json
Add a manifest for [cookiecutter/cookiecutter](https://github.com/cookiecutter/cookiecutter)
=> cookiecutter: Add version 1.7.3

bucket/webcord.json
Added webcord, a discord client.
Closes #8272
=> webcord: Add version 3.1.3

bucket/kibana.json
=> kibana: Fix extract_dir

bucket/notepadnext.json
A cross-platform reimplementation of Notepad++
=> notepadnext: Add version 0.4.9

bucket/mindforger.json
Relates to Excavator unable to update due to change in release file naming: https://github.com/ScoopInstaller/Extras/runs/5954605801?check_suite_focus=true#step:3:262
=> mindforger: Update to version 1.54.0, fix checkver

bucket/ccleaner.json
=> ccleaner: Fix bin and shortcuts

bucket/nexusfont.json
Relates to Excavator checkver failing: https://github.com/ScoopInstaller/Extras/runs/5986438568?check_suite_focus=true#step:3:251
=> nexusfont: Update homepage & license

bucket/dopamine.json
=> dopamine: Persist settings file (Solve #4327)

bucket/xdelta3-cross-gui.json
=> Update download URL and filename format

bucket/mpv-git.json
Multiple downloads confirm the hash is wrong.
=> mpv-git@20220417: Fix hash

bucket/vcredist-aio.json
=> vcredist-aio: Add version 0.60.0

bucket/infekt.json
=> infekt: Add version 1.2.0

bucket/audmes.json
=> audmes: Add version 20211104

bucket/tabby.json
=> (chore)tabby: Fix url for download&autoupdate

bucket/min.json
=> min: Add version 1.24.0

bucket/crunchyroll-go.json
Added an app manifest for the crunchyroll-go CLI tool.
App can be found here https://github.com/ByteDream/crunchyroll-go
Closes #XXXX
=> crunchyroll-go: Add version 2.1.0

bucket/sonixd.json
=> sonixd: Add version 0.15.1

bucket/googlechrome.json
=> googlechrome: set CHROME_EXECUTABLE env variable

bucket/windjview.json
This pull request adds the WinDjView djvu reader to the bucket.
=> WinDjView: Add version 2.1

bucket/gittyup.json
=> gittyup: add version 1.1.0

bucket/datagrip.json, bucket/dataspell.json, bucket/goland.json, bucket/idea-ultimate.json, bucket/idea.json, bucket/phpstorm.json, bucket/pycharm-professional.json, bucket/pycharm.json, bucket/rubymine.json, bucket/webstorm.json
Persist jetbrains *.exe.vmoptions
=> Persist jetbrains *.exe.vmoptions

bucket/ffmpeg-batch.json
A real nice gui for ffmpeg.
64bit only for now, for some reason the 32bit release is distributed in an exe, haven't had any luck with extracting it yet.
=> ffmpeg-batch: Add 2.7.6

bucket/gnucash.json
- version: fix correct version
- bin: use bin\gnucash-cli.exe
- persist: persist etc\gnucash\environment.local
- checkver: find correct version
=> gnucash: Update manifest

bucket/moneymanagerex.json
[MoneyManager Ex](https://moneymanagerex.org/) is a open-source, cross-platform, software that helps you organize your finances and keep track of where, when and to who the money goes.
=> moneymanagerex: Add version 1.5.14

bucket/nirlauncher.json
=> Nirlauncher: Add new apps in 1.23.60

bucket/010Editor.json
Added 010 Editor.
This is paid software so you get a 30 day trial. After that we must buy a copy on the website.
This can be done [here](https://www.sweetscape.com/store/?010editor). More information for it can be found on their [website](https://www.sweetscape.com/store/?010editor).
This is a normal editor as well as a Hex editor. It is made by the [Sweetscape Software](https://www.sweetscape.com/) company.
Version 12.0.1 was released on October 7, 2021. Check [release notes](https://www.sweetscape.com/010editor/release_notes.html) for more info.
Feature list can be found on their [Features Page](https://www.sweetscape.com/010editor/features.html).
Closes #4290
=> 010 Editor: Add version 12.0.1 (Closes #4290)

bucket/synctoy.json
closes #2073
**SyncToy** ([Wikipedia](https://en.wikipedia.org/wiki/SyncToy)) is a free application **developed by Microsoft** that synchronizes files and folders between locations. Typical uses include sharing files, such as photos, with other computers and creating backup copies of files and folders.
**NOTES**:
* This package uses `ScoopInstaller/Binary` because Microsoft does not provide the file anymore.
(the binary is taken from snapshots in `archive.org`)
* *license* can be found in `SyncToy_RULA.rtf` within the archive.
=> synctoy: Add version 2.1

bucket/losslesscut.json
- Update download url, remove `installer`
- Update license
Closes #XXXX
=> losslesscut: Update manifest

bucket/polsedit.json
=> polsedit: Add version 1.0.0.5

bucket/abricotine.json
Relates to #8539, just noticed they provide hashes in `latest.yml` 😅
=> abricotine: Add autoupdate hash extraction

bucket/qalculate.json
=> (fix)qalculate: Fix 'bin'&'shortcuts'

bucket/jmeter.json
=> jmeter@5.4.3: Add start menu shortcuts

bucket/midicsv.json
=> midicsv: Add version 1.1

bucket/mpc.json
=> mpc: Add version 0.22

bucket/ncmpc.json
=> ncmpc: Add version 0.20

bucket/notion-enhanced.json, bucket/notion-repackaged.json
Repackaged notion with notion-enhancer embedded.
=> notion-enhanced: Add version 2.0.18-1

bucket/webpicmd.json
=> webpicmd: Update homepage

bucket/todolist.json
=> todolist@8.1.2: Use Github as file source

bucket/megabasterd.json
=> megabasterd: Add shortcut icon

bucket/total-registry.json
https://i.imgur.com/jevOHiT.png
Closes #XXXX
=> Wrong hash.

bucket/goneovim.json
update to version 0.6.1
update download url and extract_dir
=> goneovim@0.6.1: Update download url and extract_dir

bucket/ipfs-desktop.json
=> ipfs-desktop: Add builtin ipfs cli shim

bucket/fsviewer.json
Full name is helpful when searching apps. Type “FastStone”, the most obvious thing, at htps://scoop.sh, and you’re not gonna find it.
Closes #XXXX
=> (chore): Full name of the app

bucket/sublime-text.json
=> sublime-text: Migrate uninstall.script to pre_uninstall

bucket/nilesoft-shell.json
=> nilesoft-shell: Persist shell.shl

bucket/windows-terminal.json, scripts/windows-terminal/install-context.reg, scripts/windows-terminal/uninstall-context.reg
=> windows-terminal@1.13.11431.0: Add context menu

bucket/opennetmeter.json
Added OpenNetMeter. 
A simple program to monitor your network/data usage.
Stores settings at `%localappdata%\OpenNetMeter`
Supports 32bit and 64bit 
Closes #XXXX
=> opennetmeter: Add version 0.10.0

bucket/explorer-suite.json
**[Explorer Suite](https://ntcore.com/?page_id=388)** is a suite of tools including a PE editor called CFF Explorer and a process viewer.
**NOTES**:
* config location: `HKCU:\SOFTWARE\NTCore`.
**SCREENSHOTS**:
=> explorer-suite: Add version III

bucket/perfview.json
This PR adds manifest for [PerfView](https://github.com/Microsoft/perfview).
=> PerfView: Add version 3.0.1

bucket/picocrypt.json
* closes #8700
* **[PicoCrypt](https://github.com/HACKERALERT/Picocrypt)** is a small encryption tool with a focus on security, simplicity, and reliability.
**NOTES**:
* The app does not require config files.
=> picocrypt: Add version 1.29

bucket/unsubscan.json
=> unsubscan: Add version 0.1.2

bucket/vcredist2022.json
Update vcredist2022 to 14.32.31326
=> vcredist2022: Update to version 14.32.31326

bucket/stremio.json
=> stremio: Add version 4.4.142

bucket/vcredist2022.json
=> vcredist2022: Update version info

bucket/plex-mpv-shim.json
Closes #XXXX
- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> plex-mpv-shim: Add version 1.10.3

bucket/kawaii-player.json
=> kawaii-player: Add Version 5.0.0-1

bucket/armcord.json
=> armcord: Add version 3.0.7

bucket/kotatogram.json
=> kotatogram : Add Version 1.4.8

bucket/msklc.json
- The only available tool (aside from [KbdEdit](http://kbdedit.com/)) to create and modify keyboard layouts on Windows
- Abandonware since 2007, no autoupdate
=> msklc: Add version 1.4

bucket/nohboard.json
=> nohboard: Add version 1.3.0

bucket/64gram.json
=> 64gram: Add version 1.0.39

bucket/forkgram.json
=> forkgram: add version 4.0.0

bucket/stash.json
=> stash: Add version 0.15.0

bucket/jackett.json
=> jackett: add version 0.20.1211

bucket/sleek.json
- Closes #8766
- Uses Setup.exe rather than zip due to larger download and lack of automatic hash extraction
- Preferences stored in `user-preferences.json`
=> sleek: Add version 1.2.1

bucket/teamviewer-qs.json
* closes #8763
* **[TeamViewer QuickSupport](https://www.teamviewer.com/en/info/quicksupport/)** is a light version of Teamviewer, which enables a support technician to remotely access, remotely control, and remotely view your computer or mobile device for fast troubleshooting.
**NOTES**:
* I couldn't find the **changelog** for this app, but `TeamViewerQS.exe`'s file signature says version `15.30.3`, which is **identical to the latest version of Teamviewer**.
* The app is built in **32-bit.**
* config location: Both `$Env:AppData\TeamViewer` and `$Env:LocalAppData\TeamViewer`.
=> teamviewer-qs: Add version 15.30.3

bucket/typioca.json
=> typioca: Add version 2.0.0

bucket/trzsz.json
=> trzsz: Add version 0.1.8

bucket/meshroom.json
=> meshroom: Add version 2021.1.0

bucket/caesium-image-compressor.json
Signed-off-by: Kyle Yue <sevenbookyue@gmail.com>
Closes #8793
=> caesium-image-compressor: Add version 2.1.0

bucket/mpv-easy-player.json
=> mpv-easy-player: add version 0.34.0.6

bucket/bomi.json
=> bomi: Add version 0.9.11

bucket/selene.json
A blazing-fast modern Lua linter written in Rust
=> selene: Add version 0.19.1

bucket/ds4windows.json
- Additional persist files
- Add note for ViGemBus
- Suggest .NET Core Runtime
=> ds4windows: Additional persist files, add ViGemBus note, add .NET Core suggest

bucket/coder.json
* closes #8778
* **[Coder](https://coder.com/)** is a tool that creates remote development machines so your team can develop from anywhere.
**NOTES**:
* This is a command-line tool. It is added to `Extras` due to **popularity issues**.
* ~config location: `$Env:AppData\coderv2`~
=> coder: Add version 0.7.6

bucket/waifu2x-extension-gui.json
=> waifu2x-extension-gui: Add version 3.92.01

bucket/nefcon.json
Windows device driver installation and management CLI tool.
- No persist files
- Would need this for a Nonportable manifest soon
=> nefcon: Add version 1.3.0

bucket/runcat.json
https://github.com/Kyome22/RunCat_for_windows/issues/86
=> runcat: Update depends

bucket/copytranslator.json
[copytranslator](https://copytranslator.github.io/)
Foreign language reading and translation assistant based on copy and translate
Github 14k stars
=> copytranslator: Add version 10.0.1

bucket/rife-ncnn-vulkan.json
https://github.com/nihui/rife-ncnn-vulkan
342 stars
the Author `nihui`'s other repo has 2.1k stars and merged in https://github.com/ScoopInstaller/Main/blob/master/bucket/waifu2x-ncnn-vulkan.json
=> rife-ncnn-vulkan: Add version 20220330

bucket/fontcreator.json
FontCreator for Windows - the most popular font editor
code modified from [BluYous/ScoopBucket](https://github.com/BluYous/ScoopBucket/blob/master/bucket/FontCreator.json)
=> fontcreator: Add version 14.0.0.2862

bucket/ds4windows.json
I forgot to put `.xml` in the end.
=> ds4windows: Fix OutputSlots typo

bucket/apache-tinkerpop-gremlin-console.json, bucket/apache-tinkerpop-gremlin-server.json
Fix bin for apache-tinkerpop-gremlin(-console)(-server) with @issaclin32 's  suggestions.
Relates to #8842
- [*] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> apache-tinkerpop-gremlin(-console)(-server)@3.6.0: Fix bin

bucket/qbittorrent-enhanced.json
=> qbittorrent-enhanced: Update to version 4.4.3.12

bucket/ffqueue.json
=> ffqueue: persist ffqueue.cfg

bucket/mediainfo.net.json
=> MediaInfo.Net: add version 7.3.0.0

bucket/librespeed-cli.json
- Closes #8833
- Nothing to persist as far as I can tell
=> librespeed-cli: Add version 1.0.10

bucket/everything.json
- Filters.csv
- Search History.csv
=> everything: add persist files

bucket/foobar2000.json
=> foobar2000: Update official url

bucket/foobar2000-encoders.json
=> foobar2000-encoders: Update official url

bucket/wechat.json
Closes #7160 
code modified from [kidonng/sushi](https://github.com/kidonng/sushi/blob/master/bucket/wechat.json) 
**p.s.** *WeChat* is the **most popular instant messenger** app in China.
=> wechat: Add version 3.7.5.23

bucket/miru.json
=> miru: Add version 2.10.0

bucket/houdoku.json
=> houdoku: add version 2.9.2

bucket/wechat.json
wechat: Persist `WeChat Files`
Closes #8900
=> wechat@3.7.5.23: persist "WeChat Files"

bucket/qrscan.json
Scan a QR code in the terminal using the system camera or a given image.
=> qrscan: Add version 0.1.6

bucket/xnview.json
Closes #8905
**p.s.** XNViewMP ([extras/xnviewmp](https://github.com/ScoopInstaller/Extras/blob/master/bucket/xnviewmp.json)) is forked from this app, but this app still receives updates.
This PR is heavily inspired by https://github.com/ScoopInstaller/Extras/blob/master/bucket/xnviewmp.json
=> xnview: Add version 2.51.0

bucket/gimp.json, scripts/gimp/default.env
=> GIMP: fix the manifest to enable  the console for python-fu

bucket/komokana.json
=> komokana: add version 0.1.0

bucket/guiscrcpy.json
=> guiscrcpy: add version 2022.7.1

bucket/vosviewer.json
=> vosviewer: add version 1.6.18

bucket/sbom-tool.json
Adds sbom-tool from https://github.com/microsoft/sbom-tool
=> sbom-tool: Add version 0.1.7

bucket/snipaste.json
=> snipaste@1.16.2: fix persisting of config.ini

bucket/sunshine.json
GitHub repo moved over to @LizardByte
=> sunshine: Update links

bucket/nilesoft-shell.json
=> nilesoft-shell: Fix `pre_install`

bucket/fontforge.json
=> fontforge: Fix `shortcuts` and `bin`

bucket/podman-desktop.json
Closes #8848
config location: $Env:UserProfile\\.podman-desktop
config location: $Env:APPDATA\\.local\share\containers
=> podman-desktop: Add version 0.0.5

bucket/ignoreit.json
=> ignoreit: Add version 2.4.6

bucket/scoop-completion.json, scripts/ModifyPSProfile.psm1, scripts/scoop-completion/append-to-profile.ps1, scripts/scoop-completion/remove-from-profile.ps1
- Add a function module to modify PS profile
- Auto-import scoop-completion module to PS profile 
- Remove residual folder
Referenced from dorado bucket. I'm not familiar with function modules for PowerShell, edits from old hands would be appreciated. : )
=> scoop-completion: add auto-import scripts

bucket/thorium-reader.json
Closes #8991
config location: $env:APPDATA\EDRLab.ThoriumReader
=> thorium-reader: Add version 2.0.0

bucket/publii.json
=> publii: Add version 0.40.2

bucket/f3d.json
fixes path to executable
Closes #8998
- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> f3d@1.2.1: fix paths to executable

bucket/jaspersoft-studio.json
=> jaspersoft-studio: Update to version 6.20.0

bucket/ytdlp-interface.json
=> ytdlp-interface: Add version 1.5.1

bucket/ezunlock.json
A simple GUI application for deleting stuck/stale/undeletable files, open sourced alternative to IOBit Unlocker. https://github.com/demberto/EzUnlock
=> ezunlock: Add version 0.1

bucket/ezunlock.json
=> ezunlock: fix typo

bucket/vscodium.json
revert parts of a21c876c80e86588ffcc7258698eb199e2308db4
Relates to #9013
=> vscodium.json: Add 32bit again

bucket/ignoreit.json
Fixed issues regarding templates not being found
=> ignoreit: Update to version 2.4.7

bucket/filelight.json
=> filelight: Update to version 22.04.3

bucket/librewolf.json
also fixed minor mistake in hash
Those config files/dirs are required by userchrome configurations, so it makes sense to persist them
=> librewolf: added extra config files to persist, and minor hash fix

bucket/foobar2000-encoders.json
=> foobar2000-encoders: Fix notes field name

bucket/komorebi.json
=> komorebi: update post-install notes

bucket/via.json
Reference: https://github.com/the-via/releases/blob/master/LICENSE
=> via: Add license and update install scripts

bucket/kavita.json
=> kavita: Add version 0.5.5

bucket/hekasoft-backup-restore.json
Closes #8897
config location: $env:LOCALAPPDATA/Hekasoft
=> hekasoft-backup-restore: Add version 0.95

bucket/converseen.json
Closes #7103
config location: $env:LocalAppData/converseen
=> converseen: Add version 0.9.9.6

bucket/legendary.json
=> legendary: Add version 0.20.27

bucket/folder-painter.json
=> folder-painter: Add version 1.3

bucket/konversation.json
=> konversation: Add version 22.08.0-1220

bucket/vortexdm.json
=> VortexDM: Add notes (VortexDM only work on 64 bit Windows 10+)

bucket/npiperelay.json
=> npiperelay: Add version 0.1.0

bucket/so.json
=> so: fix autoupdate url

bucket/hydrus-network.json
=> hydrus-network@493: change zip name to the qt6 based release

bucket/vortexdm.json
=> vortexdm: Update url

bucket/igdm.json
Closes #7151
config location: $env:AppData/IGdm
=> igdm: Add version 3.0.4

bucket/trayweather.json
=> trayweather: Add version 1.24.0

bucket/tanoshi.json
=> tanoshi: Add Version 0.29.2

bucket/webcamoid.json
=> webcamoid: Add version 9.0.0

bucket/weylus.json
Use your tablet as graphic tablet/touch screen on your computer.
=> weylus: Add version 0.11.4

bucket/smuxi.json
=> smuxi: Add version 1.1

bucket/weylus.json
=> weylus: Remove trailing comma

bucket/mangal.json
=> mangal: add version 3.5.0

bucket/mcomix.json
=> mcomix: Update to version v2.0.2

bucket/ratiomaster.json
=> RatioMaster: Add version 0.43

bucket/teamviewer.json
=> teamviewer uninstall: Replaces ACLs with default inherited ACLs for rolloutfile.tv13

bucket/obs-studio.json
=> obs-studio: Update to version 28.0

bucket/umlet.json
Add lightweight UML tool "Umlet" in most recent stable version (15.0.0).
Closes #9152
=> Umlet: Add version 15.0.0

bucket/oras.json
=> oras: add version 0.14.0

bucket/foxit-pdf-reader.json
- [ X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> foxit-pdf-reader: update autoupdate url, update to version 12.0.1.12430

bucket/brave.json
Closes #9169 
- I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> Brave: Update to v1.43.89, Add checkver script

bucket/nheko.json
=> nheko: Add version 0.10.1

bucket/contour.json
=> contour: add version 0.3.3.204

bucket/sd-card-formatter.json
=> sd-card-formatter: Add version 5.0.2

bucket/f3d.json
=> f3d@1.3.1: remove "extract_dir"

bucket/elasticsearch.json
=> elasticsearch: Add missing shims

bucket/wechat.json
wechat: Update to 3.7.6.44 / Fix checkver and autoupdate
Closes #XXXX
=> wechat: Update to 3.7.6.44 / Fix checkver and autoupdate

bucket/restish.json
=> restish: Add version 0.14.0

bucket/cider.json
=> cider: Add version 1.5.6

bucket/ani-cli.json
=> ani-cli: update to 3.4

bucket/btop4win.json
=> btop4win: Add version 1.0.2

bucket/openlens.json
Closes #9177
onfig location: $env:AppData/OpenLens
=> openlens: Add version 6.0.1

bucket/ani-cli.json
=> ani-cli: Update depends and suggest

bucket/moar.json
=> moar: Add version 1.9.7

bucket/prusaslicer.json
=> prusaslicer: Update 2.5.0, checkver, Remove 32bit

bucket/capframex.json
=> capframex: add back extract directory

bucket/wxdfast.json
=> wxdfast: Add version 0.70.4

bucket/sorayomi.json
Flutter Gui for Tachidesk-Server
=> sorayomi: Add version 0.2.3

bucket/audacity.json
=> audacity@3.2.0: fix extract_dir

bucket/renpy.json
=> renpy: Fix hash

bucket/arduino.json
Updated version for Arduino IDE
Closes #9267
=> arduino: Update to version 2.0.0

bucket/scoop-sd.json
Done this way because the version scheme was weird, and it seems to have a typo, grammar in the description was wrong, so I fixed that as well
@grisha765 Would you mind mirroring the fixed description?
Closes #8127
=> scoop-sd: Add version 0.3

bucket/backup-start-menu-layout.json, bucket/desktop-ini-editor.json, bucket/drive-letter-changer.json, bucket/easy-context-menu.json, bucket/host-editor.json, bucket/network-profile-name-changer.json, bucket/reicon.json, bucket/runastool.json, bucket/sendto-menu-editor.json, bucket/show-disk-partition-style.json, bucket/webcam-on-off.json, bucket/windows11-classic-context-menu.json
=> adding more Sordum apps to the official bucket

bucket/spotify-qt.json
Apart of some batch PRs for some personal manifests
Relates to https://github.com/ScoopInstaller/Versions/pull/672
=> spotify-qt: Add version 3.9

bucket/powertoys.json
=> powertoys: Fix dll hardlinks required since 0.63.0

bucket/everything.json
=> everything: Uninstall if service is not installed

bucket/nefcon.json
=> nefcon: Add arm64 architecture

bucket/typioca.json
=> typioca: Add arm64 architecture

bucket/moonlight.json
=> moonlight: Add arm64 architecture

bucket/archisteamfarm.json
It is a CLI app, so make sense to have a shim for it.
Closes #XXXX
=> archisteamfarm: Add shim

bucket/zoom.json
Closes #9487, Closes #9486, and Closes #9482
Relates to #9485
=> zoom: Add a different `pre_install` script for each architecture

bucket/hydrus-network.json
=> hydrus-network: Update to version 502

bucket/strokesplus.net.json
=> strokeplus.net: Fix pre_install and persist

bucket/qrscan.json
Closes #9321
Forgot to add it to autoupdate
=> qrscan: Fix `extract_dir` error

bucket/youtube-music.json
Closes #9324
Still new to contributing, please correct me.
=> youtube-music: Fix url and autoupdate

bucket/avidemux.json
=> avidemux: Update to version 2.8.1

bucket/veusz.json
=> veusz: Fix `pre_install` script error. Also fix `checkver`

bucket/nekoray.json
=> nekoray: Add version 1.13

bucket/nirlauncher.json
=> nirlauncher: Add new apps

bucket/nekoray.json
=> nekoray: Fix persist

bucket/ungoogled-chromium.json
- New upstream
- 32/64-bit
- Remove script of migration
Closes #9479
=> ungoogled-chromium: Update manifest

bucket/aegisubdc.json
=> aegisubdc: Update to version 9215 and fix checkver

bucket/handbrake.json
=> handbrake: Remove unneeded `"depends"` property

bucket/spotube.json
=> spotube: Fix `autoupdate.url` and `autoupdate.hash.regex`

bucket/pacaptr.json
Relates to ScoopInstaller/Main#4040
=> pacaptr: Add version 0.16.1

bucket/cinny.json, bucket/x64dbg.json
=> cinny: Add version 2.2.2

bucket/logitech-omm.json, bucket/onboard-memory-manager.json
=> onboard-memory-manager: Add version 1.1.6805

bucket/catalyst.json
- Closes https://github.com/ScoopInstaller/Main/pull/4052
- Closes https://github.com/ScoopInstaller/Main/discussions/4053
BTW, @JaydenDev, when Catalyst is opened (v3.2.2), it reported that it's outdated and needs to update to 3.1.10 which is a bug.
=> catalyst: Add version 3.2.2

bucket/slskd.json
Adding [slskd](https://github.com/slskd/slskd), a client of Soulseek network written in C# (with React WebUI). Some GUI clients have been included by this bucket already:
* [SoulseekQt](https://github.com/ScoopInstaller/Extras/blob/master/bucket/soulseekqt.json)
* [Nicotine+](https://github.com/ScoopInstaller/Extras/blob/master/bucket/nicotine-plus.json)
=> slskd: Add version 0.16.24

bucket/famistudio.json
=> famistudio: Add version 4.0.4

bucket/horizon-eda.json
=> horizon-eda: Add version 2.4.0

bucket/armips.json, bucket/spotube.json
=> armips: Add version 0.11.0

bucket/openrgb.json
Now it's back to the old URLs
Reverts ScoopInstaller/Extras#9428
=> openrgb: Revert "Fix download and autoupdate URLs"

bucket/nwjs-sdk.json
=> nwjs-sdk@0.69.1: Fix `bin`

bucket/privacy.sexy.json
=> privacy.sexy: Update `audoupdate`

bucket/tutanota.json
=> tutanota: Update `autoupdate`

bucket/space-radar.json
=> space-radar: Add version 5.1.0

bucket/renamer.json
=> renamer: fix persist and pre_install sections

bucket/hydrus-network.json
=> hydrus-network: Fix `autoupdate` & update to version 504

bucket/dbvis.json
=> dbvis: Drop 32bit arch, update 64bit url and hash,

bucket/zaproxy.json
As per the title ;)
https://www.zaproxy.org/download/
Closes #9586
=> Update to ZAP 2.12.0

bucket/tabby.json
Closes #9590
I still do not think config/data migration is required, even I did this PR.
=> tabby@1.0.185: Fix `post_install` and `autoupdate.hash.url`

bucket/sfss.json, bucket/zaproxy.json
=> sfss: Add version 1.0.0

bucket/powertoys.json
=> powertoys@0.64.0: Fix DLL hardlinks

bucket/nexttrace.json
=> nexttrace: Add version 0.2.3

bucket/psiphon3.json
=> psiphon3: Fix Hash

bucket/bt.json
=> bt: Add `pre_install` & `persist`

bucket/vcredist.json, bucket/vcredist2022.json
=> vcredist & vcredist2022: Update to version 14.34.31931.0

bucket/vscode.json
=> vscode: Add arm64 architecture

bucket/firefox.json
=> firefox: Add arm64 architecture

bucket/windowsdesktop-runtime.json
=> windowsdesktop-runtime: Update description

bucket/wing-101.json
- Relates to https://github.com/ScoopInstaller/Scoop/discussions/5241
=> wing-101: Add version 9.0.0.6

bucket/xdman.json
Change the description according to its Github page (https://github.com/subhra74/xdm)
Relates to ScoopInstaller/Versions#735
=> xdman: Change description

bucket/obsidian.json
=> obsidian: Add arm64 architecture

bucket/reduce-memory.json
Closes https://github.com/ScoopInstaller/Extras/issues/9660
Relates to https://github.com/ScoopInstaller/Extras/pull/9701
=> reduce-memory: add version 1.6

bucket/restart-explorer.json
it was missing extract_dir
Closes #9660
Relates to https://github.com/ScoopInstaller/Extras/pull/9701
=> restart-explorer: fix extract_dir

bucket/freetube.json
=> freetube: Update to version 0.18.0-beta, and fix `architecture` property

bucket/ipfilter-updater.json
=> ipfilter-updater: Fix homepage

bucket/openvpn.json
Changed checkver to take into account different version names
Closes #9736
Relates to #9736
=> openvpn: Update to version 2.5.8 and fix checkver

bucket/authy.json
=> authy: Change URL

bucket/stellarium.json
=> stellarium: Update to version 1.1, fix checkver, autoupdate

bucket/shadowsocks-qtun-plugin.json
=> shadowsocks-qtun-plugin: Add version 0.2.0

bucket/biblioteq.json, bucket/sdl2-image.json, bucket/sdl2-mixer.json
Removed extra whitespace in some manifests.
=> (chore): remove extra whitespace

bucket/openlens.json
=> openlens@6.2.0: Fix hash & Update `autoupdate.hash`

bucket/wechat.json
=> wechat: Update to version 3.8.0.41

bucket/yubioath.json
Closes #9814 
update fields:
- `version`: `6.0.0`
- REF: [Release Yubico Authenticator 6.0.0 · Yubico/yubioath-flutter · GitHub](https://github.com/Yubico/yubioath-flutter/releases/tag/6.0.0)
- `description`: `Yubico Authenticator for Desktop (Windows, macOS and Linux) and Android`
- REF: [GitHub - Yubico/yubioath-flutter](https://github.com/Yubico/yubioath-flutter)
- `homepage`: `https://developers.yubico.com/yubioath-flutter/`
- REF: [yubioath-flutter](https://developers.yubico.com/yubioath-flutter/)
- `license`: `Apache-2.0`
- REF: [yubioath-flutter/LICENSE at main · Yubico/yubioath-flutter · GitHub](https://github.com/Yubico/yubioath-flutter/blob/main/LICENSE)
- `bin`: `authenticator.exe`
- `checkver`
- REF: https://developers.yubico.com/yubioath-flutter/Releases/
- `autoupdate`
- …
=> yubioath: Update to version 6.0.0

bucket/armcord.json
=> Armcord: Fix Hash

bucket/godot-mono.json, bucket/godot.json
Closes https://github.com/ScoopInstaller/Extras/pull/9772#issuecomment-1324452921
=> godot(-mono): Fix 'pre_install' script

bucket/openlens.json
=> openlens: Fix `hash`

bucket/youtube-dl-gui.json
=> youtube-dl-gui: Update to version 1.8.4, and fix `checkver`

bucket/diskspd.json
=> diskspd: Add version 2.1

bucket/rtss.json
=> rtss: Fix `pre_install` and `persist`

bucket/context-menu-manager.json
A free and open source app that is a great open source alternative to **easy-context-menu**.
=>  context-menu-manager: Add version 3.3.3.1

bucket/dart-sass-embedded.json
=> dart-sass-embedded: Add version 1.56.1

bucket/w10privacy.json
Update SHA256-Hash from official website download page.
=> Update w10privacy Hash / Fix Hash check failed!

bucket/foxit-pdf-reader.json
- [ X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
Autoupdate is Ok
/verify
=> foxit-pdf-reader: update autoupdate url, update to version 12.0.2.12465

bucket/dopamine.json
=> dopamine: Fix `url`, Fix `checkver`, and Fix `autoupdate`

bucket/qbittorrent.json
=> qbittorrent: Update to version 4.5.0, no more 32-bit version

bucket/moderndeck.json
=> moderndeck: Add version 9.4.5

bucket/upscayl.json
=> upscayl: Add version 1.5.5

bucket/raspberry-pi-imager.json
=> raspberry-pi-imager@1.7.3: Change the executable name

bucket/vesta.json
=> vesta: Fix `pre_install` and `checkver` properties

bucket/gitextensions.json
=> gitextensions: Update to version 4.0.0

bucket/windowtextextractor.json
WindowTextExtractor is an absolutely free and simple in use system tool to:
* Extract text from modal windows, buttons, textboxes, lists, etc
* Show passwords stored behind asterisks (*****) from most of the windows apps
* Show detailed window and process information 
* Show process environment variables
* Show or hide almost any desktop window
* Take a window screenshot
* Record window stream in avi file
* OCR support (including text, bar codes and QR codes) for Windows 10, 11
=> WindowTextExtractor: Add version 1.15.0

bucket/teamviewer-qs.json, bucket/teamviewer.json
=> teamviewer-qs: Update to version 15.35.9

bucket/teamviewer.json
=> teamviewer: Update to version 15.36.9

bucket/houdoku.json
Fixes https://github.com/ScoopInstaller/Extras/pull/8887#discussion_r1034279768
=> houdoku: Fix arch

bucket/translucenttb.json
- Use portable version. Config files are persisted under `settings.json`.
- Add arm64 arch
=> translucenttb: Update to version 2022.1

bucket/airdroid.json
=> airdroid: Fix `checkver`

bucket/godot-manager.json
A project, version, and addons/plugins manager for Godot.
Config and engines stored in `AppData\Roaming\Godot-Manager`.
=> godot-manager: Add version 0.2.1

bucket/qbittorrent-enhanced.json
=> qbittorrent-enhanced: Update to v4.5.0.10 and fix

bucket/openvpn.json
- Update to version 2.5.8-I604
- Update `checkver` and `autoupdate`
Closes #9906
=> openvpn: Update manifest

bucket/w10privacy.json
=> W10Privacy@4.1.1.0: Update hash, try to fix hash compute failed.

bucket/gdevelop.json
=> gdevelop: Add version 5.1.151

bucket/audacity.json
- Fix `checkver`, `autoupdate`
- Update to version 3.2.2
Closes #9928
=> audacity: Update manifest

bucket/autohotkey.json
This PR implements auto creation of `AutoHotkeySC.bin` file.
Closes #9895
=> autohotkey: auto create "AutoHotkeySC.bin"

bucket/gitnuro.json
config location: $env:LocalAppData/D3DSCache
Closes #9894
=> gitnuro: Add version 1.1.1

bucket/vscodium.json
=> vscodium: Add ARM64 support

bucket/syncthingtray.json
update syncthingtray to v1.3.1-1
Closes #9995
=> update syncthingtray to v1.3.1-1

bucket/rstudio.json
=> rstudio: Fix url

bucket/baregrep.json
=> baregrep: Add version 3.50a

bucket/threema.json
=> threema: Add version 1.2.25

bucket/nunustudio.json
=> nunustudio: Add version 0.9.6

bucket/php-nts-xdebug.json, bucket/php-xdebug.json
=> php(-nts)-xdebug: Update to version 3.2.0-8.2

bucket/cascadeur.json
=> cascadeur: Add version 2022.3.58

bucket/gtk-sharp.json
=> gtk-sharp: fix `url`

bucket/dasel.json
=> dasel: Add 32bit version

bucket/mkcert.json
=> mkcert: Add arm64 architecture

bucket/rstudio.json
=> rstudio: Fix bin path

bucket/musescore.json
- Update license
- Remove 32bit
- Fix url
- Update checkver and audotupdate
Closes #10018
=> musescore: Update manifest

bucket/ghidra.json
=> ghidra: Update to version 10.2-20221101, and fix `checkver`

bucket/status.json
=> status: Update to version 0.8.1-2356ac. Fix `url`, `hash`, installer type, and add `checkver`.

bucket/foxit-pdf-reader.json
- [X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
/Verify
=> foxit-pdf-reader: update autoupdate url, update to version 12.1.0.15250

bucket/autohotkey.json
=> autohotkey@2.0.0: Add `notes` and Update `bin`

bucket/keyviz.json
A free and open-source tool to visualize your keystrokes in real-time.
Settings are stored in `$env:APPDATA\com.example\keyviz\shared_preferences.json`.
=> keyviz: Add version 1.0.6

bucket/freac.json
=> freac@1.1.6: Fix "extract_dir"

bucket/mcomix.json
follow-up fix for https://github.com/ScoopInstaller/Extras/commit/0a668e0c76f7a73038409d0b7ff9277ffe5b6a01
=> mcomix@2.1.0: Fix `extract_dir`

bucket/twitchdownloader.json
=> twitchdownloader: Add version 1.51.1

bucket/servicebusexplorer.json
added config file to be persisted in updates
Relates to #1313
=> servicebusexplorer: persist config file

bucket/eclipse-java.json
Update to new version of Eclipse-java
Not related to any open issues or pull requests
=> eclipse-java: Update to version 2022-12

bucket/ctypes.json
=> ctypes: Add version 2.6.5

bucket/rawtherapee.json
=> rawtherapee: Fix url

bucket/rawtherapee.json
=> rawtherapee: Add `pre_install`

bucket/telegram-downloader.json
=> telegram-downloader: Update to version 0.6.0-beta

bucket/upscayl.json
=> upscayl: Fix download URLs

bucket/sfsu.json
=> sfsu: Fix binaries

bucket/freedownloadmanager.json
=> freedownloadmanager: Fix checkver

bucket/obsidian.json
=> obsidian: Add 32bit version

bucket/threema.json
=> threema: Fix `pre_install` for PowerShell 5

bucket/obsidian.json
=> obsidian@1.1.9: Update install script

bucket/winrar.json
Added WinRar.ini and Themes folder to the persisted items
Closes #XXXX
Relates to #9978
=> winrar: Persist WinRar.ini and Themes

bucket/winrar.json
Extra comma on line 22
Closes #10142
=> winrar: resolve JSON syntax error

bucket/powertoys.json
Reverts ScoopInstaller/Extras#10177
=> powertoys: Revert #10177

bucket/powertoys.json
- Remove `notes`
- Sort object items(dirs)
- dotnet hardlinks
Relates to #10177
=> powertoys@0.66.0: Update manifest
