git-flow.json

I recently had to reinstall git-flow and it wasn't working. 
They migrated their installer to use the linux only `install` command. I've simply replaced it with cp.

Fixed git-flow not installing

---

nircmd.json

I had to change the extraction folder to `.` to make nircmd install. Possibly vendor changed the layout of the ZIP archive?
C:\Users\frank\AppData\Local\scoop\cache> unzip -l nircmd#2.75#http_www.nirsoft.net_utils_nircmd.zip
Archive:  nircmd#2.75#http_www.nirsoft.net_utils_nircmd.zip
Length      Date    Time    Name
---------  ---------- -----   ----
44032  11.08.2013 15:41   nircmd.exe
43520  11.08.2013 15:40   nircmdc.exe
45977  11.08.2013 15:43   NirCmd.chm
---------                     -------
133529                     3 files

Fixed extraction folder for nircmd

---

elasticsearch.json

Kibana 4 need ELS 1.4.4 or later, so time for an upgrade.

Upgrade ELS to 1.4.4

---

rust-nightly.json

Urls were 404ing as the filenames were changed.

Fix rust-nightly urls

---

ninja.json

The ninja buildsystem meets all the requirements in order be placed into the main bucket, so a pull request has been made to add the ninja buildsystem to the main bucket and this request removes ninja  from the extras bucket.

Remove ninja buildsystem

---

cpu-z.json

New version of cpu-z is out and old link was broken.

Update cpu-z to latest version

---

git-preview.json

I opted to use the version name from `git version` instead of the filename.

Update git-preview to 2.3.7.windows.1

---

dartium.dart

Dartium is a build of Chrome with a built-in Dart VM. Useful for development.

add dartium

---

ragel.json

Ragel compiles executable finite state machines from regular languages.
Read more at http://www.colm.net/open-source/ragel/
This is a pre-built binary from https://github.com/eloraiby/ragel-windows

Add Ragel 6.9

---

webstorm
webstorm.json

I have 2 open points before merging my pull-request
- how to tag a proprietary license in the manifest
- the uninstallation gives following error:
```couldn't remove ~\appdata\local\scoop\apps\webstorm\11.0.3: it may be in use```
I don't know if the root cause is scoop or not

webstorm 11.0.3

---

fciv.json

FCIV can compute MD5 or SHA-1 cryptographic hash values for specified files.

Add Microsoft's FCIV (File Checksum Integrity Verifier)

---

scripts/sourcetree.ps1
sourcetree.json

I've run into a few issues with SourceTree needing admin rights in order to be installed. I took a gander at this repository:
https://github.com/cosmomill/SourceTreePortable
And attempted to refactor it into a PowerShell script. My PowerShell is weak, but the user is not promoted with a UAC prompt. Is there a better way to this>

UAC-free Sourcetree installer

---

atom.json
eclipse-ee.json
eclipse.json
sourcetree.json

Added shortcuts to:
- Atom
- SourceTree
- Eclipse and Eclipse for JavaEE
Bumped Atom from 1.4.0 to 1.4.3. 
Added Eclipse for JavaEE as an option in addition to Eclipse classic.

Version updates and added shortcuts

---

conemu.json

Moves to the latest (stable) version of ConEmu: 150813g, also using the GitHub download site, since the main site (powered by fosshub, doesn't have an accessible download URL).

update to latest stable conemu

---

atom.json
oraclejdk.json

Updated Atom to `1.5.3` and Oracle JDK 8 to `1.8.0_u74`

Version bumps for Atom and OracleJDK

---

sysinternals.json

Currently `scoop install sysinternals` returns the following error output
```
PS>scoop install sysinternals
installing sysinternals (0.2016.01.04)
downloading https://download.sysinternals.com/files/sysinternalssuite.zip...The remote server returned an error: (404) Not Found.
```
It appears that the letter-casing in the URL being lower case causes this. After modifying this line locally to the following casing scoop can successfully download the sysinternals suite.

Update sysinternals URL to have correct case.

---

xmllint.json

Hey there, here is a PR for [xmllint](http://xmlsoft.org/xmllint.html) 
Each of the 7z files that the manifest calls out have a bunch of extra supporting folders in them that aren't needed for xmllint.exe to run properly (`lib/`, `share/`, `include/`, etc). The only stuff that needs to be part of this are the dlls in the `bin/` folder in each 7z archive. 
I tried to exclude the unneeded stuff in the manifest via the `extract_dir` element but I couldn't get it to work. So as it is now, when you install you'll get all 23mb of stuff that's in these 7z's as opposed to the ~8 that's actually needed.

Add xmllint

---

vscode.json

Incorrect URL was being used for the 1.2.0 zip.

Fix vscode (1.2.0)

---

whois.json

Previous hash for the zip download was wrong.

Fixed hash for whois.exe

---

vscode.json

I think we need a better strategy for detecting available updates for VS Code, because the current one isn't working. Maybe we could check their GitHub releases page?

Update VS Code to 1.5.1

---

tomcat.json

I have upgraded tomcat as old version looks like broken:
```
λ scoop install tomcat
installing tomcat (8.0.2.6)
downloading http://apache.uberglobalmirror.com/tomcat/tomcat-8/v8.0.26/bin/apache-tomcat-8.0.26-windows-x64.zip...The remote server returned an error: (404) Not Found.
```

upgrade tomcat to 8.5.5

---

ngrok.json

The download link always points to the latest stable version (today it's 2.1.14).

Update ngrok to stable

---

notepadplusplus.json

Notepad++ now has a x64 version.
I simply copied the SHA1 hashes from the download page, as I'm too lazy to download the files myself. Ping me if I should change them to SHA256.

Update Notepad++ to 7.0

---

emacs.json

- Emacs for Windows now has a x64 version.

Update Emacs to 25.1

---

notepad2-mod.json

**notepad2-mod** is an improved version of **notepad2** (already included into Extras Bucket).
It provides additional features such as code-folding and improved syntax highlighting, I personally prefer using it to the regular notepad2.
https://github.com/XhmikosR/notepad2-mod#notepad2-mod

Add notepad2-mod

---

gvim.json

This updates the `gvim` manifest to refer to the latest build of VIM 8.0, as per the https://groups.yahoo.com/neo/groups/vimannounce/conversations/messages/244
Note: The files at the URLs that the manifest originally used (ending `gvim80.zip`, and `vim80rt.zip`) have also been updated with the same content, so either way the hash value is out of date and needs updating :)

update gvim to version 80-069

---

sourcetree.json

Note, with 1.9.10.0 the first time running will prompt you with setup wizard. I don't think this is avoidable since it ask for your Atlassian Id (as part of Atlassian's SSO consolidation of all bitbucket Ids into Atlassian Id).

upgraded sourcetree to 1.9.10.0

---

gcc-arm-none-eabi.json

From https://developer.arm.com/open-source/gnu-toolchain/gnu-rm:
"These toolchains are based on Free Software Foundation's (FSF) GNU
Open source tools and newlib.
​The toolchains support ARM Cortex-M0, Cortex-M0+, Cortex-M3, Cortex-M4, Cortex-M7, Cortex-R4, Cortex-R5, Cortex-R7, Cortex-R8 processors and ARMv8-M Baseline and Mainline architectures."

Add cross compiler for ARM targets

---

RapidEE.json

Added `checkver` and `autoupdate`.
I couldn't figure out another way to make checkver + autoupdate happy, using build number seemed best compromise.

RapidEE update. Switched version to build number.

---

speedcrunch.json
tidy.json

Merge only if you also merge my other pull request here (or get rid of the URL check as suggested by rrelmy):
https://github.com/lukesampson/scoop/pull/1333
as SpeedCrunch is hosted on bitbucket.
If you would rather not do that I can move HTML tidy onto a different branch and open a PR for that alone.

Adds SpeedCrunch and HTML tidy to extras bucket

---

sourcetree.json

I came across some issues with this upgrade. 
I believe the script `https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/sourcetree.ps1` needs to be updated, but have no idea what to update. Please assist?
At the moment the installation just hangs at the step `Checking hash of sourcetree.ps1... ok.`

upgrade sourcetree to 1.10.20.1

---

emacs.json

The Emacs project proposes a bundle of dependencies to install alongside emacs.  Using these instead of the gnutls zip file originally in the app manifest enables more functionality, e.g.
- eww (a web browser in Emacs) because libxml2 can now be found
- inline image display because the image libraries can now be found
- probably others
Note that the same binaries as those contained in the gnutls zip are also included, so that dependency/download was dropped.

Use official Emacs dependencies -> enables eww, image display etc

---

eclipse-android.json
eclipse-automotive.json
eclipse-committers.json
eclipse-cpp.json
eclipse-dsl.json
eclipse-ee.json
eclipse-javascript.json
eclipse-modeling.json
eclipse-parallel.json
eclipse-php.json
eclipse-platform.json
eclipse-rcp.json
eclipse-reporting.json
eclipse-scout.json
eclipse-sdk.json
eclipse-testing.json
eclipse.json

A rather big commit with all Eclipse projects added.
The Eclipse project uses “release trains” for its packaging project, and since the Europa release (3.3), the packaging project is named after the train, replacing all version numbers. For the main Eclipse project, a drop structure is used, with build id in its path. There are a couple of sources of information needed to do the mapping:
1.	The Oomph product map (http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/org.eclipse.products.setup)
2.	The Simultaneous Release Schedule (https://wiki.eclipse.org/Simultaneous_Release)
3.	The Eclipse Project’s archived releases (http://archive.eclipse.org/eclipse/downloads/)
4.	The Eclipse Packaging Project’s archived releases (https://wiki.eclipse.org/Older_Versions_Of_Eclipse)
To …

All Eclipse Packaging projects plus SDK and platform

---

emacs.json

No threat detected for x86_64 binary by the 57 scanners at VirusTotal
One of 57 scanners at VirusTotal reported Trojan.Script.Vbs-heuristic.druvzi
for the i686 binary

Update emacs to 25.2

---

atom.json

In atom.json I have changed atom.exe to atom.cmd. atom.exe blocks the command line, while atom.cmd does not.

Changed atom.exe to atom.cmd

---

go-ipfs.json

i got the version check regex to work but i'm not sure if my regex is too much or not. 
this is what i currently have for the regex
`"data-id=\"go-ipfs\" data-version=\"(?<version>[^\\ ]+)\""`
its meant to extract the version from this html element `<a class="d-component-download-btn btn btn-primary" data-id="go-ipfs" data-version="v0.4.8" href="go-ipfs/v0.4.8/go-ipfs_v0.4.8_windows-amd64.zip">Download go-ipfs</a>` this element is the blue Download go-ipfs button on the page.
i feel like this is dirty and could be done a better way but if it can't then this is merge ready

add auto update function to go-ipfs

---

vscode.json

Maybe we need to find a better way to check for updates, the VS Code guys often forget to make a proper GitHub release.

Update VS Code to 1.12.1

---

love.json

I also added to the notes a link to a bucket that has alternate versions of the LÖVE engine. It's helpful when working on it to test code in multiple versions of the engine since there are significant changes between even patch releases.
I would submit those instead to the versions bucket, but as they are not popular-dev-tool related, I do not feel they are appropriate, and there is no scoop-extras-versions bucket.
If this is unacceptable, let me know and I will make another commit to remove the note.

Added love, a 2D lua-based gaming engine

---

moonscript.json

[The author does use GitHub releases](https://github.com/leafo/moonscript/releases), however there is a hash value (I believe a commit hash) used on the download URLs so I'm not sure how to properly set up autoupdate on this one.

Added MoonScript, a language that compiles to Lua

---

mkvtoolnix.json
sublime-text.json
vlc.json

While installing apps via Scoop, I noticed some missing start menu shortcuts.
I also changed `subl.exe` to `sublime_text.exe` to prevent the flashing cmd from opening before starting Sublime Text.

add some missing start menu shortcuts

---

mancy.json

The 32 bit version is broken just now because one of the JS files isn't packaged.

Added Mancy

---

rstudio.json

Created a manifest for RStudio, an IDE for the R language.
post_install script creates an initial R Studio config file that connects the IDE to the R package which should already have been installed by scoop. The user can easily change which R package to use from within the IDE, but this post_installer provides a sensible default so that no further configuration is required to get going.
"scoop install rstudio && rstudio" should just work (tm)

Added R Studio

---

atom.json

The previous version of atom.json had the same download link and hash for both the 64bit and 32 architectures. This commit corrects this issues by updating the download link and adding its hash.

Update atom.json to correct 64bit download w/ hash

---

atom.json

After the 64bit architecture was fixed, there was an issue where the 64bit download would extract to "Atom x64", not "Atom" as the original extract_dir held. I localized the extract_dir property to each architecture and update the 64bit one accordingly.

Fix extract_dir for 64bit

---

vscode.json

The archive format changed slightly.
We also have to watch out for the 64 Bit build of VS Code. AFAIK they wanted to enable it for Windows in this release, but I didn't find anything in the release notes.

Add extract_dir property to VS Code manifest

---

vlc.json

I updated the autoupdate regex for vlc to check the http://www.videolan.org/vlc/download-windows.html page instead of the previously used page

updated the vlc version regex

---

tomcat.json

Tomcat Archive does not always carry the latest versions of Tomcat. This commit reuses the official [Dockerfile](https://github.com/docker-library/tomcat/blob/5ac222d258dc70c77bb3a9a4fab81ea286c9abd1/8.5/jre8/Dockerfile#L49) way.

Use same approach for download URL as official Docker images for Tomcat

---

dhcp-server.json

Minor change. `echo $null >> $dir\\dhcpsrv.ini` creates `dhcpsrv.ini` with BOM, replaced it with `Add-Content`.

Create initial dhcpsrv.ini without BOM

---

love.json

Was recommending use of an unnecessary (and deprecated) bucket.
Left over from when I first added it and hadn't added the other versions to the versions bucket.

update love.json note

---

stone-soup-tiles.json
stone-soup.json

This adds manifests for the ASCII version and graphical version of the roguelike [Dungeon Crawl Stone Soup](https://crawl.develz.org/).

Add dungeon crawl stone soup tiles and console version.

---

netbeans.json

This adds the full version of Netbeans. But, no automatic URL updating for version changes (fortunately it only updates about once a year).
&nbsp;
The official Netbeans website has some interesting design choices; you need JS enabled to view the downloads page.
Unfortunately, the download link not only requires the version, it also requires the build number. While I managed to scrape the latest version from the release notes, I could not find a non-JS page to scrape both version and build number in one go.
And, again, unfortunately, the Mercurial tags on the official Netbeans repo not only do not always list the releases (802 is missing), but they also do not list the build number or offer any helpful information to derive the build number from.
Interestingly, though, the build numbers …

Add Netbeans IDE

---

openresty.json

As requested, submitting to extras instead of the main bucket because of the niche-ness of it.
Also, as I mentioned in another pull on the main bucket, I can't figure out how to use autoupdate on stuff. This version is actually out of date, and I will run that on it as soon as I know how to.

Added OpenResty, a fork of NGINX for writing webapps with Lua

---

irfanview.json

Adds IrfanView - an old, fairly lightweight, and powerful alternative to the built-in Windows photo viewer. 
Note: this manifest uses multiple URLs. So, while version checking works, there is no auto update. On the bright side, updates aren't so common.

Add IrfanView

---

nteract.json

This pull request adds [nteract](https://nteract.io), which is a desktop tool for writing and running Jupyter notebooks.

Add nteract version 0.2.0.

---

emacs.json

This pull request just adds a shortcut to `runemacs.exe` in the `emacs.json` manifest.

Add shortcut to emacs manifest.

---

foobar2000.json

Adds Foobar2000 - a very popular and powerful music player.
Using Videhelp as a mirror because the official site uses a timed hash to prevent hotlinking.

Add Foobar2000

---

vcxsrv.json

For some reason the hash values were incorrect in the latest autoupdate. Fixed with checkver -u.

vcxsrv: Fixed incorrect hash

---

whois.json

Noticed it was missing while installing a bunch of packages.

added hash to whois

---

greenshot.json

Added [Greenshot](http://getgreenshot.org/). References portable version, no installation.

Add Greenshot

---

appengine-go.json

SHA1 hash copied from Google's download page.

Update appengine-go to version 1.9.58

---

fscapture.json

FastStone Capture is an easy and leightweight tool for taking snapshots and editing them. This is version 5.3 from 2007, the last freeware version. Since version 5.4 it's only a 30 days trial before one has to pay for it.
Don't know why AppVeyor fails to build :/ I tested it on my machine and it worked.

added faststone capture v5.3 (fscapture) (last freeware verrsion)

---

jpegview.json

Added [JPEGView](http://jpegview.sourceforge.net/), a lean, fast and highly configurable viewer/editor for JPEG, BMP, PNG, WEBP, TGA, GIF and TIFF images with a minimal GUI.
I had to include `extract_dir` in the autoupdate section, even though they are static. Otherwise, they are reset during auto update (bug?).

Added JPEGView

---

arduino.json

Added [Arduino 1.8.4](https://www.arduino.cc/en/Main/Software), the official open source IDE for writing programs for the Arduino board.

Add Arduino IDE

---

reaper.json

This adds the digital audio workstation, Reaper. 
Technically it's an evaluation version for 60 days but the evaluation version is actually just the full version with a popup on startup and it doesn't get crippled after 60 days either. It's similar to WinRAR in that sense.

Add reaper DAW version 5.51.

---

idea-community.json
idea-ultimate.json
idea.json

Added Community Edition of IntelliJ IDEA.
How about using the current idea.json for the Community edition instead. We can create an idea-ultimate.json for the Ultimate edition.

Add IntelliJ IDEA Community

---

oraclejdk.json

JDK install bombs out with error code -80 if there is a space in the directory. Adding escaped quotes to JSON to be passed to the program arguments as is done on the ADDLOCAL line above.

Update oraclejdk.json to account for Directories with spaces

---

keepass.json

Fix `checkver`, now using sourceforge homepage
Update to version 2.37

Update KeePass to version 2.37

---

azure-cli.json

Fix `checkver`, now using the GitHub API to load releases. This project has a high volume of [releases](https://github.com/Azure/azure-cli/releases) and most of them are for sub-modules. The releases page only shows 10 so the release we are looking for is often off the first page and is missed. The API returns 30 results, increasing the odds of finding a version.
Update version to 2.0.19.

Update Azure CLI to version 2.0.19

---

ZeroNet.json

Implement `autoupdate` - the dist link always points to latest
Update to version 0.6.0

Update ZeroNet to version 0.6.0

---

dartium-dev.json
dartium.json
dartium_content_shell-dev.json
dartium_content_shell.json

These 4 manifests are at their __final__ version. Removing `autoupdate` since the checks are no longer valid. The two dev manifest are currently failing autoupdate and the stable manifest will start failing once 2.0 is released. 
The next stable release will be Dart 2.0 which will no longer include Dartium. All dev releases are now onto 2.0 with no ongoing work on 1.x.
>Dartium is going away in Dart 2.0 
> we don’t plan to release a 1.25 Dart SDK on the stable channel
More info can be found on Dart's [install](https://www.dartlang.org/install) page.

dartium*: remove autoupdates

---

hack-font.json

Update `autoupdate` to match current release url.
Update to 1.4.1

Update hack-font to version 1.4.1

---

CSharp-SnippetCompiler.json

This project no longer exists and is uninstallable via this manifest.

csharp-snippetcompiler: remove defunct project

---

godot.json

This PR adds [Godot](https://godotengine.org/), an open source game engine.

Add Godot Engine

---

consolez.json

Hello, I have added a manifest for [ConsoleZ](https://github.com/cbucher/console). This is an excellent actively developed fork of Console 2. I think the original Console 2 should be removed, development stopped in 2011.

add JSON manifest for ConsoleZ

---

pandoc.json

Hello,
I tried installing pandoc 2.0 and scoop started installing miktex. MiKTeX is a huge download 191 MB and an *optional* dependency and I already have it installed.
I changed MiKTeX from a dependency to a suggestion.

pandoc: remove optional dependency on latex, add suggestion instead

---

diffpdf.json

I have added a manifest for the latest open source version of [DiffPDF](http://soft.rubypdf.com/software/diffpdf). Later versions are closed source.

add manifest for DiffPDF

---

calibre-normal.json

This commit adds a normal nonportable version of Calibre.
* The portable Scoop version of Calibre does not use the settings and the library of the Calibre version that I had installed.
* Scoop Calibre keeps the settings and the library outside of the Calibre folder. This is a good thing, but it keeps them in a non-standard location which can lead to all kinds of other problems. It can happen that this location is not backed up for example.

add normal nonportable calibre

---

nteract.json

This removes the miniconda3 dependency and replaces it with the default python manifest from the main scoop bucket. 
This also adds a note explaining where to find more kernels and instructions on how to download them.

Update nteract manifest.

---

now-cli.json

Add [now](https://zeit.co/now) CLI

Add now-cli version 8.4

---

UniversalPauseButton.json

- Update to version `1.0.3`
- Add architecture specific bins
- Add shortcuts
- Add checkver and autoupdate

Update universalpausebutton to version 1.0.3

---

LinqPadLess.json

- Update to version `1.1.0`
- Implement checkver / autoupdate

Update linqpadless to version 1.1.0

---

ditto.json

This commit adds a normal nonportable version of Ditto. There are multiple problems with the portable version:
* when you update Ditto you lose your settings and the clipboard history
* after installation the portable version does not use the settings and clipboard history of the nonportable Ditto that I had installed

add normal nonportable Ditto

---

openhardwaremonitor.json

Open Hardware Monitor is a free open source software that monitors temperature sensors, fan speeds, voltages, load and clock speeds of a computer.

add openhardwaremonitor 0.8.0

---

logexpert.json

I've added LogExpert, a Windows tail program and log file analyzer.
While testing autoupdate, I found that either the file name or the packaged directory is different with each release. Because of this inconsistency, I left it out.
I think no autoupdate is better than an autoupdate that probably won't work, but feel free to add it if you think differently.

Add LogExpert version 1.6.6

---

xmllint.json

I couldn't get scoop to download the files via ftp (timeout or file-not-found), but http seemed to work fine.

xmllint: Download via http rather than ftp

---

keepass.json

I've made the KeePass plugin dir persistent, to keep installed plugins when updating.
The plugin dir is initially empty, and KeePass plugins are installed by placing them there.

Make KeePass plugin dir persistent

---

rainmeter.json

I've added Rainmeter, a desktop customization tool.
The package is an NSIS executable installer, and contains both 32 and 64 bit versions.
It's unpacked with 7Zip, and it works on my 64 bit Windows, but I don't know if it will work in a 32 bit environment.
If not, it should probably use the installer instead.

Add Rainmeter

---

telegram.json

As `scoop which telegram` finds the telegram.cmd in the shims folder, I get the following error with the https://gist.githubusercontent.com/deevus/3fbc29bddca4d39ad9c7/raw/4433c3ea3ea34f76652b3f576de6063d6bb75978/telegram.ps1 script:
````
./Telegram.exe : The term './Telegram.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a pat
included, verify that the path is correct and try again.
At C:\Users\ross\scoop\apps\telegram\current\telegram.ps1:3 char:1
+ ./Telegram.exe
+ ~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (./Telegram.exe:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
````
The included script works:
```
push-location $PSScriptRoot
./Telegram.exe …
```

telegram: Fix inability to run executable

---

hwmonitor.json

"Expected" values cause hash check failed error! "Actual" value fixed it.
```
Expected:
6615ad87048ccc9d3cc9ec57445c9a22ce31b5568e2a234ec0be0e44e116d677
Actual:
bbaac4657e4c2725d1c491b5b0bdf2d250d3f79e1232e39b07ae0e44523fd714
```

Hwmonitor hash problem fixed!

---

mpv.json

Installing mpv get me this message:
Installing 'mpv' (2017-12-25) [64bit]
mpv-x86_64-20171225.7z (14.4 MB) [============================================================================] 100%
Checking hash of mpv-x86_64-20171225.7z... Hash check failed for 'https://mpv.srsfckn.biz/mpv-x86_64-20171225.7z'.
Expected:
64a0505f5d58ed13b8417f9ed2399df13cf64ddc936e1489c136dbd8ec9ce141
Actual:
d402f9a90c034117fdfad5a3a1de04fa66795b94b34a514edc3d316020863819

change mpv 64 bit hash

---

miniconda3.json

See [#1926](https://github.com/lukesampson/scoop/pull/1926). Besides, we persist `envs` folder to keep conda's envs.

Add miniconda3.json

---

elasticsearch.json

Version:
6.1.1
Release date:
December 19, 2017

Update Elasticsearch to version 6.1.1

---

jpegview.json

Turns out the problem in #725 wasn't a wrong hash, but a wrong download url, resulting in a different hash each time.
The wrong url returned 404 as expected, shouldn't Scoop report that instead of a hash mismatch?

Fixed JPEGView download url

---

enpass.json

- Update to use URL from `checkver` source
- Update to version 5.6.5

Update enpass to version 5.6.5

---

godot.json

This fixes a PowerShell error when installing Godot. This also renames `Godot.exe` to `godot.exe` and adds it to the PATH, as calling it from the command line can be useful.

Fix pre-install command in godot.json

---

depends.json

This adds dependency walker version 2.2, which lets you view the dependencies of executables and assemblies.

Add dependency walker version 2.2.

---

ccleaner.json

It seems the hash value was not updated with the last version update [commit](https://github.com/lukesampson/scoop-extras/commit/0e824a59f091ac78530294f4efef86773ddbb190) which keeps the latest version from being installed.
Cheers!

Fix ccleaner version 5.39.6399 hash value

---

php-xdebug.json

As we provide php 7.2 in the main repo, we have to provide the xdebug dll for the correct version
Superseeds #747 
@lukesampson could you give me write access to the extras repo too?

Update xdebug to version 2.6 for php 7.2

---

ShareX.json

This file constains the path setting, which tells ShareX where to save configuration files and such.

Persist personal path setting for ShareX

---

foobar2000.json

The foobar2000 installer file don't work to enclose output path in double quotes.
This commit remove double quotes around `$dir` .

Fix installer args, remove double quotes in foobar2000

---

mkvtoolnix.json

MKVInfo GUI is no longer included; installation errors with "Can't shim 'mkvinfo-gui.exe': File doesn't exist".

mkvtoolnix: Remove mkvinfo-gui

---

imageglass.json

Added ImageGlass v4.5.11.27!
Is `extract_dir` can take `$version` variable? When zip file downloaded it has main folder named with version number.
```
┌[⚡ yigit] [17:22]
└[~\scoop\cache]> zipinfo -1 .\imageglass#4.5.11.27#https_github.com_d2phap_ImageGlass_releases_download_4.5.11.27_ImageGlass_4.5.11.27.zip
ImageGlass_4.5.11.27/
ImageGlass_4.5.11.27/default.png
ImageGlass_4.5.11.27/DefaultTheme/
...
...
```

Added ImageGlass v4.5.11.27!

---

logexpert.json

The logexpert package structure changed (again).
As I noted in #657, maybe we're better off with no autoupdate than an autoupdate that breaks the install on every update.
I see the author added a .nupkg. Maybe it will be more stable?

Fixed logexpert extract_dir

---

ccleaner.json

This is a simple hash update for the new version of ccleaner.
PS: Quick question, if you define a non-version specific download path (as is the case with ccleaner), won't the package break for everyone everytime a new version is available? Is that the best approach?

Fix ccleaner 5.41.6446 hash

---

pwsh.json

Changed the homepage to a PowerShell Core specific page (the github repo seems best) rather than the generic MS powershell site.
Also it's not going to be "PowerShell 6" forever so changed the shortcut name to "PowerShell Core"

pwsh: Shortcut name & website change

---

inkscape.json
inkscape32bit.json

The old autoupdate didn't catch this version, as the site structure has changed, but the old page used in `checkver` is still available, listing the old version.
Autoupdate is not possible with the current site structure. The links to the .7z files can not be constructed from the version number alone, and the URL to the page where they can be parsed from, contains the version number.
I've updated both `inkscape` and `inkskape32bit`, but I've also added the 32 bit version to inkscape.
The architectures were split to make autoupdate work, but it won't work anyway now, so I think the manifest should follow best practice.

Update Inkscape to 0.92.2 and remove autoupdate

---

netlifyctl.json

the hash for the v0.3.2 version was incorrect:
```
C:\Users\klauer
λ  scoop install netlifyctl
Installing 'netlifyctl' (0.3.2) [64bit]
netlifyctl-windows-amd64-0.3.2.zip (6.5 MB) [==================================================================================================================================================] 100%
Checking hash of netlifyctl-windows-amd64-0.3.2.zip... Hash check failed for 'https://github.com/netlify/netlifyctl/releases/download/v0.3.2/netlifyctl-windows-amd64-0.3.2.zip'.
Expected:
89ebbe29d597d1e111c736c7d3d9395e37da1f38f8a8fa8ed2cd87d475c3550e
Actual:
5b004752270bbcf319f675bb2e65087a97daa768f7f6b1b03a1213ce15e8a1a0
```

update netlifyctl to correct hash

---

lili.json

Adds lili version 2.4.9, a tool for creating bootable USB drives from Linux ISOs.

Add Linux Live USB creator.

---

windirstat.json

The address of `https://windirstat.net/wds_current_setup.exe` is probably redirecting to SourceForge.
```
┌[⚡ yigit] [ windirstat-fix ≢] [18:01]
└[~\gitforks\scoop-extras]> scoop install .\windirstat.json
Installing 'windirstat' (1.1.2) [64bit]
wds_current_setup.exe (215.4 KB) [===================================================================================================================] 100%
Checking hash of wds_current_setup.exe... Hash check failed for 'https://windirstat.net/wds_current_setup.exe#/dl.7z'.
Expected:
6fa92dd2ca691c11dfbfc0a239e34369897a7fab
Actual:
68100fbdd2330622ea31fa15b4cfd38347390fab
```

Fixing WinDirStat Address!

---

mp3tag.json

current version is v2.87a and current download url is:
https://download.mp3tag.de/mp3tagv287asetup.exe

mp3tag: add regex match word char to fix wrong download url

---

mc.json

Before link change (look at the file size):
```
┌[⚡ yigit] [ mc-hashfix ≢] [x] [14:56]
└[~\gitforks\scoop-extras]> scoop install .\mc.json
Installing 'mc' (4.8.19) [64bit]
mcwin32-build204-bin.zip (198.3 KB) [===================] 100%
Checking hash of mcwin32-build204-bin.zip... Hash check failed for 'https://sourceforge.net/projects/mcwin32/files/mcwin32-build204-bin.zip'.
Expected:
ee48adb6718d414a043a2b4a30c7cc69dc68d77c
Actual:
```
After link change:
```
┌[⚡ yigit] [ mc-hashfix ≢ ~1 -0 !] [x] [15:01]
└[~\gitforks\scoop-extras]> scoop install .\mc.json
Installing 'mc' (4.8.19) [64bit]
mcwin32-build204-bin.zip (4.9 MB) [====================] 100%
Checking hash of mcwin32-build204-bin.zip... ok.
Extracting... done.
Linking ~\scoop\apps\mc\current => ~\scoop\apps\mc\4.8.19
Creating shim …
```

Fixing MC SourceForge Address!

---

xmedia-recode.json

Xmedia Recode v3.4.3.0 fails to install. The name of the inner dir to copy was changed.
Will have to see if this change is permanent or if they go back to the old scheme in the next version.

xmedia-recode 3.4.3.0: extract_dir changed

---

love.json

Love fails to install.
Replaced `love-11.1-winXX` with `love-11.1.0-winXX`. Zip and directory don't follow the same version scheme in 11.1, for 11.0.0 both zip and dir have the same versions.

Fix for love extract_dir

---

springboot.json

Auto-Update rolled it back to 1.5.12 because it was published after 2.0.1 https://github.com/spring-projects/spring-boot/releases

Update Spring Boot CLI to 2.0.1

---

gimp.json

GIMP 2.10 is out. Updated the manifest to the new version.
It seems that there's only a 64bit build, so I've added an `architecture` tag. I don't know if that will cause problems when updating.

Update GIMP to version 2.10.0

---

xmedia-recode.json

Following on from #890, the naming scheme for the inner dir was reverted back again in v3.4.3.4

XMedia-Recode: extract_dir name was reverted

---

mobaxterm.json

Changes:
- update to v10.5
- remove 'v' from version
- add `checkVer` for automatic update checks
- remove non-existing MobaXterm Customizer (not delivered anymore)
- persist backups of configuration file changes
I removed the `v` from the `version` tag because it seems to be the usual to not use the prefix, please correct me if I'm wrong.

Update MobaXterm to v10.5

---

wireshark.json

These executables were removed from the Wireshark PortableApps build in change [25291](https://code.wireshark.org/review/#/c/25291/). This broke the package installation, as scoop tried to shim them.

Remove nonexistent executables from wireshark

---

ipscan.json

The `64bit` URL is for users that have 64-bit Java installed and the `32bit` URL is for users with the 32-bit version.  However, users with a 64-bit OS might have the 32-bit version of Java installed and be unable to use the binary at the `64bit` URL.
Java's architecture can be detected with the commands: `java -d64 -version` and `java -d32 -version`, and they should yield a non-zero return code when their respective versions are not installed.
Does any of you know how to add some simple logic to select the proper URL based on the user's Java architecture?

WIP: Add Angry IP Scanner

---

kibana.json

* Update Kibana to 6.2.4 so that it use the same version with Elasticsearch
* Fix autoupdate fail due to url changed

Update Kibana to 6.2.4 and fix autoupdate

---

rufus.json

Manually downloading the [Rufus executable](https://rufus.akeo.ie/downloads/rufus-3.0p.exe) over a TLS connection and computing its sha256 hash produces the hash prior to #960, so the PR likely made a simple mistake.  This PR changes the hash back to its original value

Fix Rufus hash

---

winpython.json

Not really sure if this belongs here, but since some people (me included) had trouble with the Python installer not being always handled properly by Scoop and/or not installing some .dll files and libraries even when installed manually (https://github.com/lukesampson/scoop/issues/504, https://github.com/lukesampson/scoop/issues/324, https://github.com/lukesampson/scoop/issues/2290, https://github.com/lukesampson/scoop/issues/856), I thought a 100% portable and working Python distribution could be useful for many.
I made it so that only Python is extracted, while the GUI tool developed by winpython is not, so no 3rd party software will be extracted (no launchers, no configuration tools other than Scoop).
I hope you'll find this useful.

Add winpython manifest

---

autohotkey-installer.json
autohotkey-reg.json

I use autohotkey a lot and was a bit frustrated by the original scoop install. After readings i propose this manifest as a new type of AHK installation using their installer and its command line options to get a more complete installation with shell menu entries.
Please consider adding it if you dont see too many mistakes, i am quite new in this.

add autohotkey-installer

---

winmerge2011.json

Maintainer also changed to CPL file format as the only download option, but it can still be extracted with 7-Zip. Details: https://bitbucket.org/jtuc/winmerge2011/downloads/Rationale_for_using_CPL_as_an_installer_format.txt
First contrib, so please let me know if I should do anything different in the future.

Update winmerge2011 to version 0.2011.008.226

---

pandoc.json

Update to the newer github autoupdate mechanism.
Support new 64-bit pandoc releases.
Update to 2.2.1

pandoc: Update mechanism and version

---

WinCompose.json

A handy tool sitting in the system tray, adding the possibility to write accented characters (or any Unicode pattern) from a hot key.

Add WinCompose: easily write special characters

---

gimp.json

Previous installer is broken due to an error. See below:
https://gitlab.gnome.org/GNOME/gimp/issues/1789

changed url for new installer

---

nomacs.json

Nomacs seems to have changed folder structure. Executable now resides in bin subfolder upon extraction.
```powershell
PS > scoop install nomacs
Installing 'nomacs' (3.10.2) [64bit]
Loading nomacs-3.10.2.zip from cache
Checking hash of nomacs-3.10.2.zip... ok.
Extracting... done.
Linking ~\scoop\apps\nomacs\current => ~\scoop\apps\nomacs\3.10.2
Creating shim for 'nomacs'.
Can't shim 'nomacs.exe': File doesn't exist.
```
Both bin and shortcut needs to be changed accordingly.

Fix Nomacs shim and shortcut binary path

---

textadept.json

This adds [Textadept](https://foicica.com/textadept/) to scoop-extras.
I couldn't figure out automatic updates here, since the download URL only has "LATEST" in it (and not the actual version number).

Add Textadept version 9.6

---

audacity.json
bleachbit.json
ccleaner.json
everything.json
mpv-git.json
mpv.json

Makes audacity and mpv portable since they will read/write settings from persistent directory instead of %AppData%.
See:
+ https://wiki.audacityteam.org/wiki/Portable_Audacity
+ https://mpv.io/manual/master/#files-on-windows

Add persist to audacity, mpv, bleachbit, and ccleaner. Fix Everything config

---

x64dbg.json

plugins should remain after an x64dbg update

Update x64dbg json

---

lunacy.json
simplewall.json
sqlitebrowser.json
wox.json

I don't believe electron apps are able to auto update with the previous manifest format right? So add extract_dir since we don't need the other nupkg files.

Cleanup wox directory and update sqlitebrowser to use portable release

---

tor-browser.json

Adds [Tor Browser](https://www.torproject.org/) to the extras bucket.

Add Tor Browser version 7.5.6

---

gcloud.json

`git-credential-gcloud.cmd` and `docker-credential-gcloud.cmd` made available on user's PATH.
Hope this is done correctly, it's my first PR to Scoop (extras).

Add two more gcloud shims

---

ddu.json

> Driver removal utility that can help you completely uninstall AMD/NVIDIA graphics card drivers and packages from your system, without leaving leftovers behind (including registry keys, folders and files, driver store)

Add DDU - Display Driver Uninstaller

---

peerblock.json

Previous wrong `checkver` regrex had autoupdater modified `version` by error.

PeerBlock: fix version

---

nsis.json

The URL is currently static. However, this will (still) not work with major updates. But I guess it's by design that automatic updates are limited to minor updates.

Use $majorVersion in autoupdate URL

---

ocenaudio.json

This pull request adds Ocenaudio into the scoop-extras bucket. It's a free single-track audio editor where you can record and edit audio or just view the waveform of an audio track. There's also a spectrum viewer so you can analyze if a lossless audio file is truely lossless.
I use this program frequently so i want this program in the bucket so i don't have to update manually from time to time.
This is also my first app manifesto. I've tested the auto-update feature which works. It also install and uninstall the application without any errors.

Add Ocenaudio

---

xx-net.json

```powershell
❯ scoop install xx-net --global
Installing 'xx-net' (3.12.11) [64bit]
XX-Net-3.12.11.7z (9.3 MB) [===============================================================================] 100%
Checking hash of XX-Net-3.12.11.7z ... ok.
Extracting XX-Net-3.12.11.7z ... done.
Linking C:\ProgramData\scoop\apps\xx-net\current => C:\ProgramData\scoop\apps\xx-net\3.12.11
Creating shim for 'XX-Net'.
Creating shortcut for XX-Net (start.bat) failed: Couldn't find icon C:\ProgramData\scoop\apps\xx-net\current\$dir\code\default\launcher\web_ui\favicon.ico
Persisting data
'xx-net' (3.12.11) was installed successfully!
```

XX-Net: fix shortcut icon

---

xx-net.json

`start.bat` is for convenience to create shortcut on desktop, with ability to "Run as Administrator" from context menu. Use `start.vbs` instead, which is actually run by `start.bat`

XX-Net: Improve shim and shortcut

---

xx-net.json

Due to shortcuts limit, only able to set target inside `$dir`, unable to call `wscript.exe`

XX-Net: fix shortcuts

---

kid3.json

Don't know if there is a better way to fix this or not (such as removing the extra folder).

fix kid3 bin and shim paths

---

knime.json

extract_dir was at the root level rather than inside the respective architecture elements, and was therefore not being updated to the correct value upon a checkver update, preventing the installation from completing successfully

Fix extract_dir for auto updates

---

pandoc.json

The extraction directory in Pandoc's pre-built zip-files has changed and is now architecture dependent.
This addresses issue #1238.

pandoc: Fixed extract_dir (#1238)

---

aida64extreme.json

Also change URL to official ones.
Checkver could be changed to official, but complicated option, maybe it could be simplified, but you know. It's working, so do not touch 😂: 
```json
"checkver": {
"url": "https://www.aida64.com/downloads",
"re": "<a href.*>AIDA64 Extreme\\s+</a></span><span.*ZIP package</span></td>\\s+<td class=\"version\">((\\d+)\\.(\\d+)\\.(\\d{4}))"
},
```

aida64extreme: Create and persist config / license

---

lightbulb.json

LightBulb is an opensource alternative to f.lux. It's a bit more customizable than f.lux and should also be more "gaming-friendly" as the author of the program explains it here: https://old.reddit.com/r/osugame/comments/5rpq1q/lightbulb_gamingfriendly_flux_alternative/
The app manifest is based on the portable version of the progam. I've added notes that the program needs .Net framework, Run a registry key if changing the gamma doesnt work correctly (the readme file advises to run it at least once) and that you need to run the bat file inside the folder of the program to enable portable mode, which the created shortcut already does.
I'm not sure if the notes can be shorter or anything can be removed from it. Otherwise the app manifest works perfectly for me. It also allows to install …

Add lightbulb@1.6.4

---

slack.json

File hash for Slack package v3.3.3 (https://downloads.slack-edge.com/releases_x64/slack-3.3.3-full.nupkg) was invalid.

Fix invalid hash value for Slack v3.3.3 64bit

---

pandoc.json

This change would add pandoc-citeproc (the citation-processor-filter for pandoc) to the system PATH so it can be easily used as a pandoc filter

Add pandoc-citeproc to PATH when installing pandoc

---

ungoogled-chromium.json

- Closes #1284
Autoupdate for 32bit is disabled due to unavailable binaries.
There is  problem, that binaries are deployed to different github accounts.
There are 2 steps needed for acquiring everything needed. Get version (as in manifest) and then go to that relase page and find user (not possible now; basicly same as hash)

Add ungoogled-chromium

---

rambox.json

- Respec repository URL change
- Change download file
- Bump to 0.6.1 version
WIP: Since ramiro changed it's version number last minute, and there are no non windows binaries yet.
UPDATE: Version 0.6.1 was taken down and it's only draft until all packages are up.
As we changed builder from squirell to NSIS, installation could be changed to something like:
```json
"url": "https://github.com/ramboxapp/community-edition/releases/download/0.5.18/Rambox-0.5.18-win.exe"
"extract_dir": "\\$PLUGINSDIR",
"pre_install": "Get-ChildItem \"$dir\" -Exclude 'app-64.7z', 'app-32.7z' | Remove-Item -Force -Recurse",
"architecture": {
"64bit": {
"installer": {
"script": "extract_7zip \"$dir\\app-64.7z\" \"$dir\""
}
},
"32bit": {
"installer": {
"script": "extract_7zip \"$dir\\app-32.7z\" …
```

Rambox: tweaks

---

crystaldiskinfo.json
crystaldiskmark.json

CrystalDiskInfo is a HDD/SSD utility software which supports S.M.A.R.T and a part of USB-HDD.
CrystalDiskMark is a disk benchmark software.

CrystalDiskInfo CrystalDiskMark

---

debugviewpp.json

This PR adds an app manifest for [`debugview++`](https://github.com/CobaltFusion/DebugViewPP).
- Releases from GitHub
- Binaries: `DebugView++.exe`, `DebugViewConsole.exe`
Moved from lukesampson/scoop#2697, thanks @r15ch13.

Add DebugView++

---

hwmonitor.json

Confirmed correct URL and version, downloaded zip manually, and manually confirmed different hash.

hwmonitor: hash fix (closes #1344)

---

altools.json

Resubmitting the pull request after adding shortcuts, license, and changing to 7-zip extraction over the native installer. These are a small collection of tools from Microsoft that are used for troubleshooting account lockouts. In particular, I use lockoutstatus.exe and nlparse.exe on a daily basis.

Add ALTools version 1.0

---

franz.json

Franz is a free messaging app for services like WhatsApp, Slack, Messenger and many more. Similar to Station and Rambox.

Add Franz version 5.0.0-beta.18

---

picotorrent.json

Set encoding to ditch powershells default UTF-16 encoding

Picotorrent: Tweaks

---

rxrepl.json

This PR adds [rxrepl](https://sites.google.com/site/regexreplace/), a windows tool similar to `sed -i` or `perl -pi`.
I'm honestly not sure about the license with this one. I couldn't find an online version, so i had to upload it to hastebin. Please advise.

Add rxrepl

---

joplin.json

Adds manifest for the open source multi-platform note-taking app Joplin. 
Configuration and content are stored at $env:userprofile\\.config\\joplin-desktop, so no persistence needed.

Add Joplin

---

paint.net.json

Paint.net is actually on version 4.1.4, not 4.1.3, but when you download 4.1.3 from the URL, it actually downloads 4.1.4. I have updated the version, URL, and hash after manually verifying the package. Closes [#1397](https://github.com/lukesampson/scoop-extras/issues/1397).

Fix Paint.net package; resolves #1397

---

jigsaw.json

- Fix checkver
- Fix hash extraction
I am not sure why this manifest have shortcuts. It's just scripts, which has no "gui". Just status terminal window.
Maybe move to main bucket?

Jigsaw: tweaks

---

mpc-be.json

- Bumped to 1.5.2
- Add autoupdate
- Remove `extract_dir`
- Simulate it in `post_install` (=> Able to update using Excavator without errors)

mpc-be: Tweaks

---

libreoffice-fresh.json

The previous https performs a redirect to http which doesn't like powershell(6)

Fix: libreoffice-fresh - changed urls from https to http

---

archi.json

Archi is an archimate enterprise architecture tool that can be
downloaded from www.archimatetool.com.

Add manifest to install Archi

---

snipaste.json

snipaste now has two version: one for Desktop and another for Windows Store. I change checkver's regex to only check Desktop version.
Before:
```PowerShell
scoop-extras master % = $ .\bin\checkver.ps1 snipaste
snipaste: 2.1.3 (scoop version is 1.16.2) autoupdate available
```
After:
```PowerShell
scoop-extras master *% = $ .\bin\checkver.ps1 snipaste
snipaste: 1.16.2
```

Update snipaste's checkver.

---

cmake-rc.json

Fixed broken `checkver `to find the latest release candidate version

cmake-rc: fix checkver to find the latest rc version

---

peerblock.json

Fix `checkver`:
- to be consistent with homepage
- to match with latest mirror from `scoopinstaller/binary-mirror`

peerblock: Fix checkver

---

etcher-cli.json
etcher.json

Adjust to changes on etcher-side:
- `resin-io` was renamed to `balena-io`
- `etcher` was renamed to `balenaEtcher`
- `etcher-cli` was renamed to `balena-etcher`
and added hash urls.

etcher and etcher-cli: Update to 1.4.7 and adjust to renamings

---

wavebox.json

- Removed 32bit version
- No need to change filename since, nupkg is extracted automatically after lukesampson/scoop@2224da82f8a786b8ae9c203c67924b4c6ef2c652
> We're hoping to move over to just 64-bit having seen quite a big drop in 32-bit users over the last year.

Wavebox: Bumped to 4.5.0

---

franz.json

I've added the "architecture" section differentiating the pre-install script between 32 bit and 64 bit
fixes #1486

Franz: Support for 32 bit architecture

---

vscode-insiders-portable.json
vscode-insiders.json
vscode-portable.json
vscode.json

This makes it possible to select the whole path by double-clicking it, then run it by pasting the path as-is in cmd.exe or PowerShell.
The official name for Visual Studio Code is also now used.

Use double quotes for the registry file in VS Code notes

---

sysinternals.json

Installing `sysinternals` returns the following error.
```
Installing 'sysinternals' (December.13.2018) [64bit]
Loading SysinternalsSuite.zip from cache
Checking hash of SysinternalsSuite.zip ... ok.
Extracting SysinternalsSuite.zip ... done.
Linking ~\scoop\apps\sysinternals\current => ~\scoop\apps\sysinternals\December.13.2018
Creating shim for 'accesschk'.
Can't shim 'accesschk64.exe': File doesn't exist.
```

Sysinternals - Specify extract dir

---

eclipse-committers.json
eclipse-cpp.json
eclipse-dsl.json
eclipse-java.json
eclipse-javascript.json
eclipse-jee.json
eclipse-modeling.json
eclipse-parallel.json
eclipse-php.json
eclipse-platform.json
eclipse-rcp.json
eclipse-reporting.json
eclipse-rust.json
eclipse-scout.json
eclipse-sdk.json
eclipse-testing.json

- Fixed download and hash url
- Removed 32-bit
- Added eclipse-rust
Closes #1544 
Also closes #1548, fixes #1549 and resolves #1550.

Eclipse 2018-12

---

cheat-engine.json

Removed the v prefix in the auto-update key because it only works with `v6.8.1`. See https://github.com/cheat-engine/cheat-engine/issues/477

Updated CheatEngine 6.8.1 -> 6.8.2

---

typora.json

Add Typora v0.9.9.60, a truly minimal markdown editor.
- Name: Typora
- Description: A powerful wysiwyg markdown editor.
- Version: 0.9.9.60
- Homepage: https://typora.io
- Note: typora.io built Typora as a Commercial software. FREE during beta.

Add typora v0.9.9.60

---

wslgit.json

This is a small executable that forwards all arguments to git running inside Bash on Windows/Windows Subsystem for Linux (WSL)

add wslgit 0.6.0

---

notepadplusplus.json

Npp can save config to cloud folder, like Dropbox or Google Drive, this setting should be persisted as well.

Add cloud directory to npp persist

---

ditto.json

Current manifest of Ditto is a broken one, it's not portable and the `persist` is wrong.
The fixes are:
- Change `url` from installer to portable zip
- `homepage` move to new one
- Add `autoupdate.hash`
- Fix `persist` by some slightly complicated hardcode (start ditto.exe, wait until it created ditto.db, kill ditto.exe)
Now it works fine, at least for me.

Ditto: Fix manifest

---

weasel-pageant.json

Hey,
I added the tool weasel-pageant which allows you to use your ssh keys from pageant in WSL directly. I already tested the installation once. You don't need any environment variables or something, but you have to add the following command to your personal .bashrc / .bash_profile:
`eval $(/mnt/c/Users/$USER/scoop/apps/weasel-pageant/current/weasel-pageant -r)`
Kind regards

Add weasel-pageant 1.2

---

php-nts-xdebug.json
php-xdebug.json

- Xdebug has its own license name and edition ([The Xdebug License, version 1.01](https://xdebug.org/license.php)) and is based on ["The PHP License", version 3.0](https://spdx.org/licenses/PHP-3.0.html). Change `license.identifier`.
- Add `autoupdate.hash`

Add autoupdate.hash and change license.identifier

---

bucket/irfanview.json

The 4.51 URL doesn't exist anymore and thus fails on installation.
I also have an autoupdate for IrfanView ready, once lukesampson/scoop#2803 is merged.

Update IrfanView to v4.52

---

bucket/atom.json

- Using nupkg instead of zip
- Using `$version` in regex to find hash in github `RELEASE` file.(https://github.com/lukesampson/scoop/commit/3a22526554d368edbd4f7aa177540ee749c32e72)

atom: Modify autoupdate.hash

---

bucket/stunnel.json

- move to `arch.64bit`
- add `uninstaller.script`
- add `notes` that `stunnel549` is the latest version that support win32

Fix stunnel

---

bucket/meld.json

The download URL has changed with the latest version [(`3.20.0`)](https://download.gnome.org/binaries/win32/meld/3.20/Meld-3.20.0-mingw.msi) and it's been updated to the correct one.

Meld: Update download URL and version

---

bucket/notable.json

- Move to arch.64bit
- Change `.zip` to `.exe` since smaller download size and `latest.yml` hash extraction

notable: Move to arch.64bit, modify url and autoupdate.hash

---

bucket/boostnote.json

- Move to `arch.64bit`
- Change setup to nupkg so as to simplify installation and have a native hash extraction

boostnote: Move to arch.64, change to nupkg and add hash extract

---

bucket/vscode-portable.json
bucket/vscode.json
scripts/vscode-install-context.reg

Inserting `&` in key name doesn't set shortcut key for menu item, it's only a visual change. To set shortcut, one should set default value.
https://docs.microsoft.com/en-us/windows/desktop/shell/context-menu-handlers

vscode: fix context menu shortcut

---

bucket/conemu.json

According to https://conemu.github.io/en/ConEmuFolders.html, plugins directory
is needed for Far Manager only. It's added as plugins source when Far is run from
ConEmu, therefore it should be updated with ConEmu and shouldn't be persisted.

conemu: Remove plugins from persisted data

---

bucket/telegram.json

telegram.com is blocked by some Russian internet providers.
GitHub.com seems to be more appropriate source.

telegram: change url to github

---

bucket/streamlink-portable.json

No need for manually build exe files as in #1680
Sidenote: Should not be streamlinks moved into main bucket? It's only command line tools, which spawn player

Add Streamlink portable

---

bucket/github.json
bucket/gitkraken.json
bucket/hyper.json
bucket/insomnia.json
bucket/netron.json
bucket/sourcetree.json
bucket/terminus.json

- github: Add `description`, move to `arch.64bit`, simplify `checkver` and `au.hash` url
- gitkraken: Add `description`, simplify `url`
- hyper: Add `description`, move to `arch.64bit`
- insomnia: Add `description`, move to `arch.64bit`
- netron: Move to `arch.64bit`, mod `installer.script`
- sourcetree: Add `description`, `extract_dir`
- terminus: Add `description`, move to `arch.64bit`

Fix apps based on Electron (add description, move to 64bit, etc.)

---

bucket/motrix.json

- Name: Motrix
- Description: A full-featured download manager.
- Homepage: https://motrix.app
- Version: 1.1.3
- License: MIT

Motrix: Add manifest v1.1.3

---

bucket/alacritty.json

Alacritty is now published in a different way, bundled in a zip file along with the `winpyt-agent` binary, which was before installed as a dependency and copied over into the working directory.
Now, scoop only needs to extract the zip archive and apply the shortcut.

Updates based on how Alacritty is published

---

bucket/dbeaver.json

URL:         https://dbeaver.io/files/5.3.5/dbeaver-ce-5.3.5-win32.win32.x86_64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    955a68184003ce6cdbf9dedb5fbc9d7b30c34af9e3a31d6a3548fcb5175e8b32
Actual:      8dbef4ef88e1117100adbef763b76f8efabb7c64a09e15bd00c469ea4dfdcb27

dbeaver.json has invalid hash

---

bucket/megasync.json

When megasync's hash changes, one should check if its version number has changed... MEGAsync's sourcecode in github may change after its binary changes.

MEGAsync: Update to 4.0.2

---

bucket/ilspy.json

According to [update log](https://scoop.r15.ch/extras/mud-20190221-160001.log) **ilspy** update was failing.
**checkver** pattern was greedy and matched more than it should. It was supposed to
match versions like `3.0-final`, but **ilspy** author doesn't use versions like this for
release anymore.

ilspy: Fix checkver pattern and autoupdate url

---

bucket/clingo.json

Since [clingo](https://github.com/potassco/clingo/releases) v5.2.3, `clingo-python.exe` and `gringo-python.exe` are no longer included in its binary releases.

Fix clingo.json for v5.3.0

---

bucket/gitextensions.json

Download url was changed, but autoupdate url wasn't.
Also pattern in checkver matched wrong version. Official version on github release
page is semver compatible, so it shouldn't include build number.
Fix #1753.

gitextensions: Fix checkver pattern and autoupdate url

---

bucket/notepadplusplus.json

Removed `notepadplusplus-pm` suggestion.
Related to #1695.

notepadplusplus: Removed plugin manager suggestion

---

bucket/keepass-plugin-keepassrpc.json

RPC plugin for [Kee](https://addons.mozilla.org/firefox/addon/keefox/) browser extensions.

Add KeePassRPC version 1.8.0 (plugin for KeePass 2.x)

---

bucket/keepass-plugin-keetraytotp.json

`-Beta` part of the version should be optional, to support feature stable releases.

keetraytotp: Fix checkver pattern

---

bucket/keepass-plugin-sequencer.json

https://github.com/fireout/keepasssequencer
One and only version of this plugin. As there is no other versions since 2016, I don't think it needs **autoupdate** section.
As it's not `.plgx` plugin, so I create directory on install to collect all the files needed to run it.

Add KeePassSequencer version 0.1.1 (KeePass 2.x plugin)

---

bucket/musescore.json

https://ftp.osuosl.org/pub/musescore/releases/MuseScore-3.0.4/MuseScore-3.0.4.msi
or
https://ftp.osuosl.org/pub/musescore/releases/MuseScore-3.0.4/
do not exist. MuseScore release manager made the installers available at GitHub

musescore@3.0.4.5763 URL change

---

bucket/miniconda3.json

Conda will complain about SSL errors if you do not have `Library/bin` in the path. There is an upstream issue here (link directly to working solution):
https://github.com/conda/conda/issues/6064#issuecomment-453147166
The maintainers write it should be fixed in a future Python build, but when testing the build linked it still doesn't work so this workaround is clean and works well.

Fix missing path in Miniconda3

---

painter.json

Add [painter](https://github.com/lptstr/painter), a tool to manage the Windows desktop wallpaper from the terminal.

Add painter v1.0.0

---

bucket/brave.json

Hey, it's my first PR here. I think scoop is very cool, thanks for that! :heart: 
Updated the Brave Browser to version 0.60.48. Refers to #1728. Some changes had to be made because Brave is now based on Chromium and moved to another Git repository.

brave: Update to version 0.60.48

---

bucket/sql-workbench-dev.json

After 124.2 has `ext` folder to persist
After 124.3 has `sha1` file to get checksum
For `sql-workbench`, need wait for version `125`

Added persist for sql-workbench-dev

---

bucket/sts.json

Close #1782 
Version 4 is only 64bit, for latest 32bit, see versions/sts396 (https://github.com/scoopinstaller/versions/pull/121) (v3.9.7 is 64bit only too).

sts: Update to 4.1.2

---

bucket/love.json

- Fix shortcut to "LOVE" to avoid shortcut creating error
- Change checkver to download page to ensure windows version is released

LOVE: Fix shortcut and checkver

---

bucket/weasel-pageant.json

Since the autoupdate url didn't seem to work I updated the url and now the autoupdate feature should work as intended.
```PS1
weasel-pageant: 1.3 (scoop version is 1.2) autoupdate available
Autoupdating weasel-pageant
Downloading weasel-pageant-1.3.zip to compute hashes!
weasel-pageant-1.3.zip (98,2 KB) [===============================================] 100%
Computed hash: 1f8ed0448cd2e7559f5d9bab860713c1f4c82518cdb2000b5d511cecb9dcbf06
Writing updated weasel-pageant manifest
```
Has the github release url schema been changed in the past? :S

Update weasel-pageant 1.3

---

bucket/spytify.json

And fixed regex to discard the zero number in version
Example:
1.1.4 -> Spytify-v1.1.4.zip
1.2.0 -> Spytify-v1.2.zip
1.2.1 -> Spytify-v1.2.1.zip

spytify: Update to version 1.2.0

---

bucket/rbtray.json

[RBTray](https://github.com/benbuck/rbtray) is a background application making it possible to minimize any window by right-clicking its Minimize button (there are other shortcuts available too). This manifest refers to an updated fork which supports modern Windows versions better.
As stated in [Installing](https://github.com/benbuck/rbtray#installing), we should document how to run it when the user logs in (as the application itself can't do that). What should we write in the `notes` section?

Add RBTray version 4.8

---

bucket/zeal.json

The scoop install process currently creates a directory for Zeal's preferences file. This PR adds a "pre_install" script to the Zeal recipe to create an empty preferences file, for the install process to link to.
This should fully close  #1481

Add Zeal pre-install script to create zeal.ini file

---

bucket/notable.json

- Change license from "MTI" to "AGPL-3.0"
- Change url to "https://github.com/notable/notable"

Notable: Fix license and change url

---

bucket/dupeguru.json

I don't know about autoupdate url, because of different version in the file name.
`https://github.com/arsenetar/dupeguru/releases/download/$version/dupeGuru_win64_$version.exe#/dl.7z`
On the second place, it should be `4.0.3` instead of `4.0.3-InstallFix`.

Add dupeGuru 4.0.3

---

bucket/database.net.json

Close #1917
`md5` in `https://fishcodelib.com/version.xml` is not a md5 hash string, it's 29bit or 31bit, need further conversion.

database.net: fix hash

---

bucket/veonim.json

There is `zip` version for Windows, but this `exe` version has smaller file size. (53.9MB vs. 81.8MB)

Veonim: Add version 0.14.0

---

bucket/inno-setup.json

Add `env_add_path` option to allow for access to `iscc.exe` from the command line.

Access exe of inno-setup from command line

---

bucket/miniconda3.json

To have a proper portable and more CI-orientend installation it would be best to add the installer argument `/NoRegistry=1` , which basically prevents registry modification as well as displaying miniconda among the installed programs in the control panel. Tested on my system, working as intended.
FYI, this is also mentioned in conda/conda#1977. Apparently, this option is documented in the help message (when running the installer with `/?`) but not in the official documentation.
EDIT: I take the chance to ask: since miniconda meets all the [criteria ](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket)to be included in the main bucket, shoul it be moved there? It could be redundant to have yet another Python distribution, but it's actually more than …

miniconda3: install with no registry edits

---

bucket/inno-script-studio.json

- Forget to change `innosetup` to `inno-setup` in https://github.com/lukesampson/scoop-extras/pull/1901
- Delete added registry item during uninstall

Inno Script Studio: Fix manifest

---

bucket/winfetch.json

As of release v1.1.0, Winfetch now requires Imagemagick for certain features to be enabled, e.g. printing images in the terminal.

winfetch: update dependencies

---

bucket/beaker.json

beaker browser is 64-bit only. Should `"architecture"` be used in `"autoupdate"` ?

add beaker

---

bucket/testcentric.json

New NUnit GUI, it could find scoop installed NUnit extensions automatically.
It will be released on Chocolatey, if so, the manifest will change url and au.hash.

TestCentric: Add version 1.0.0-alpha4

---

bucket/rainmeter-portable.json

There was a problem with unpacking different architectures in https://github.com/lukesampson/scoop-extras/pull/694. Looking for input on this solution: it works, persistence isn't trivial here, but to my knowledge I managed to persist everything.
`"if((Get-Content \"$dir\\Rainmeter.ini\") -eq $Null) { Copy-Item \"$dir\\Defaults\\Layouts\\illustro default\\Rainmeter.ini\", \"$dir\\Defaults\\Skins\", \"$dir\\Defaults\\Layouts\" \"$persist_dir\" -Force -Recurse | Out-Null }",` makes default welcome skins appear on new installation.
`"if(Test-Path \"$dir\\Plugins.original\") { Copy-Item \"$dir\\Plugins.original\\*\" \"$persist_dir\\Plugins\" -Force -Recurse; Remove-Item \"$dir\\Plugins.original\" -Force -Recurse | Out-Null }",` updates default plugins in case of an update.

Add rainmeter-portable: feedback needed

---

bucket/obs-studio.json

The automatic update using `checkver` will fail because the new version doesn't have the `.0` in the file name in the [download URLs](https://github.com/obsproject/obs-studio/releases/download/23.1.0/OBS-Studio-23.1-Full-x64.zip) from [the Github releases page](https://github.com/obsproject/obs-studio/releases).

obs-studio: Update to version 23.1.0

---

bucket/terminus.json

Using `terminus-$version-portable.exe` for smaller download size (70MB vs. 140MB).

terminus: Use portable version

---

bucket/calibre-normal.json
bucket/calibre.json

FossHub is more stabler and faster than GitHub.

Calibre: Change URL to fosshub

---

bucket/hashcheck.json

Close https://github.com/lukesampson/scoop/issues/3038.
Please MERGE AFTER https://github.com/lukesampson/scoop/pull/3411

HashCheck: Add version 2.4.0

---

bucket/rstudio.json

Change checkver to "github" to be able to detect again new versions. Small change to autoupdate url.

Fix RStudio checkver and autoupdate

---

bucket/flutter.json

Dart should not be listed as a dependency because last versions of
flutter already have dart-sdk packaged in the bin/cache directory
(merging this should close #2079)

flutter: remove dart from dependencies

---

bucket/dupeguru.json

This should close #2152.
Instead of trying to create shortcuts and shim for `dupeguru.exe`, it uses `dupeguru-win32.exe` or `dupeguru-win64.exe`

dupeguru: Fix shim problem and add 32bit arch

---

bucket/grafana.json

- Return to stable version
- Hash, download, version now come from a single source (previously 3)
- Current download link is broken because of the split-sources

grafana: Stable version, unify hash and download check

---

bucket/msiafterburner.json

msi afterburner requires vcredist2008 otherwise it won't start, complaining about side-by-side configuration if started as admin and silently crashing if started as user

msiafterburner: add vcredist2008 suggestion

---

bucket/waterfox.json

```
$ scoop update waterfox
waterfox: 56.2.9 -> 56.2.10
Updating one outdated app:
Updating 'waterfox' (56.2.9 -> 56.2.10)
Downloading new version
Downloading https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2056.2.10%20Setup.exe#/dl.7z (72.0 MB)...
Checking hash of Waterfox%2056.2.10%20Setup.exe ... ERROR Hash check failed!
App:         extras/waterfox
URL:         https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2056.2.10%20Setup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    39b567f1ffe420571e9420cdbf5d6408f6f63446dac686be9fb3998ef55a7fee
Actual:      11a6283ea313b15c460c445c686c25e2fcd0bf392045d306a01bf5eed99c9d7b
```

waterfox@56.2.10: hash check failed

---

bucket/cru.json

Custom Resolution Utility (CRU) allows to apply EDID overrides via registry.
https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU

Add Custom Resolution Utility (cru) version 1.4.1

---

bucket/emule-community.json
bucket/emule.json

As eMule hasn't updated for years, I add not only eMule but also eMule-community which is a more up-to-date version.
The [eMule download page](https://www.emule-project.net/home/perl/general.cgi?l=42&rm=download) tells that "All community releases and source code are available on [GitHub](https://github.com/irwir/eMule/releases/)". But there is a newer version 0.51d on [GitHub](https://github.com/irwir/eMule/releases/) than the lastest version 0.51c on [eMule download page](https://www.emule-project.net/home/perl/general.cgi?l=42&rm=download) and hence I am not sure is it OK to download from [GitHub](https://github.com/irwir/eMule/releases/).

Add eMule and eMule-community.

---

bucket/openocd.json

OpenOCD is a tool used to program and debug a bunch of Microcontrollers using JTAG.

Add OpenOCD version 0.10.0

---

bucket/filezilla.json

Various settings can be configured in fzdefaults.xml, it would be convenient if this config file is persisted across version upgrades.

filezilla: persist fzdefaults.xml and improvments

---

bucket/streamlink-twitch-gui.json
bucket/streamlink.json

fix #1972
A new terminal window will get opened when Streamlink Twitch GUI calls (scoop-managed) VLC player by shim.
It could be avoided with setting `player` to the real executable.

Add Streamlink Twitch GUI

---

bucket/shiba.json

I added a markdown live preview app.
I did not use `extract_dir` because the working directory of the binary file Shiba.exe must be an actual directory instead of a symbolic link.

Add Shiba version 1.2.1

---

bucket/musescore.json

Currently published MuseScore manifest has invalid download links (for both 32bit and 64bit images). This prevents latest MuseScore from being installed:
It looks like the [MuseScore 3.1 release assets](https://github.com/musescore/MuseScore/releases/tag/v3.1) didn't follow the expected pattern defined in `musescore.json/autoupdate`. This PR manually fixes the links.

Fix MuseScore download links

---

bucket/vcredist.json
bucket/vcredist2008.json
bucket/vcredist2010.json
bucket/vcredist2012.json
bucket/vcredist2013.json
bucket/vcredist2015.json
bucket/vcredist2017.json
bucket/vcredist2019.json

Fix #2261 
Use repair instead of install, i.e., do nothing while same version of vcredist is installed.

vcredist: Update 2019 to 14.21.27702.2 and modify installer args

---

bucket/soapui.json

This directory can be used by users to drop jars that will be added to the classpath at runtime (like JDBC drivers). Persisting this folder makes it possible to not lose these additional jars when new versions of SoapUI are installed.

SoapUI: persist bin/ext

---

bucket/jetbrains-toolbox.json

- Use jsonpath for checkver
- Do not install. Extraction is enough
- Create default configuration file if there is none.
- Old implementation was completely nonsense
- It was basically adding install_location all the time even when that file exists.
- So it override user setting
- This is unacceptable since it break if user change this location in GUI

Move jetbrains-toolbox from Main

---

bucket/fsviewer.json

The excavator log has been showing:
```
fsviewer: The operation has timed out.
URL http://www.faststone.org/FSViewerDetail.htm is not valid
```
for days

fsviewer: Update to 7.2 (manually)

---

bucket/kitty.json

I used the code in https://github.com/lukesampson/scoop/pull/3518 (but this is not dependent on #3518 first being merged in)
Fixes #2263 
Fixes #2330 
Fixes #2334

kitty: Update to version 0.71.0.4 (manually)

---

bucket/uniextract2.json

Official homepage for UniExtract2: https://github.com/Bioruebe/UniExtract2

uniextract2: Add version 2.0.0-rc.2

---

bucket/onefetch.json

Fixes `onefetch: 1.5.4 (scoop version is 1.0.0)` in https://scoop.r15.ch/extras/mud-20190624-020001.log

onefetch: Add autoupdate

---

bucket/telegram.json

Fixes `telegram: 1.7.9 (scoop version is 1.7.7) autoupdate available` in https://scoop.r15.ch/extras/mud-20190624-020001.log

telegram: Fix autoupdate url

---

bucket/wsl-ssh-pageant.json

This adds a tool I have written - wsl-ssh-pageant - it is used for interfacing a Putty style ssh agent with either ssh under WSL or now the native OpenSSH on Windows.
It can be found at https://github.com/benpye/wsl-ssh-pageant - it's fairly popular with nearly 100 stars on Github.

Add wsl-ssh-pageant version 20190513.14

---

bucket/tor-expert.json

Fixes:
tor-expert: couldn't match 'torbrowser/(?<browser>[\d.]+)/tor-win32-(?<version>[\d.]+)\.zip' in https://www.torproject.org/download/download.html.en
in https://scoop.r15.ch/extras/mud-20190624-210001.log

tor-expert: Fix checkver.url, add description

---

bucket/cpu-z.json

fix issue #2360
`cpu-z` has a minor update that is not listed in the version history. From its [previous version history details](https://www.cpuid.com/softwares/cpu-z.html#version-history), this seems to be a rare case. I suggest we just *modify the hash value* to solve the problem for now.

cpu-z: fix hash

---

bucket/pwsafe.json

#2308
The `1.xBETA` versions are built for linux.
It could be skipped by extracting versions directly from filenames of windows-specific `msi` installer.

pwsafe: Fix checkver

---

bucket/fritzing.json

#2308 
The next expected version is 0.9.4b. (https://github.com/fritzing/fritzing-app/issues/3443)

fritzing: Fix checkver

---

bucket/zmc.json

#2308
- update version to [GA](https://www.azul.com/press_release/azul-systems-announces-general-availability-zulu-mission-control-v7-0/ ) version 7.0.0.49
- update description from [FAQ](https://www.azul.com/products/zulu-mission-control/zulu-mission-control-faq/)
- add `bin` field
P.S. I'm really puzzled about `ca` in the filename `zmc7.0.0.49-ca-win_x64.zip`.

zmc: update to 7.0.0.49

---

bucket/islc.json

Fix https://github.com/lukesampson/scoop-extras/issues/2397
But I bump into another error
```
Installing 'islc' (1.0.1.2) [64bit]
ISLC%20v1.0.1.2.exe (338.8 KB) [===================================================================] 100%
Checking hash of ISLC%20v1.0.1.2.exe ... ok.
Extracting dl.7z ... Could not find 'ISLC v1.0.1.2'! (error 16)
所在位置 D:\scoop\apps\scoop\current\lib\core.ps1:506 字符: 9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Could not find ....2'! (error 16):String) [], RuntimeExcep 
tion
+ FullyQualifiedErrorId : Could not find 'ISLC v1.0.1.2'! (error 16)
```
Relpace `extract_dir` with `installer`  works well
```
"installer": …
```

ISLC: Fix hash

---

bucket/fmedia.json

For 32bit, see https://github.com/ScoopInstaller/Versions/pull/161

fmedia: Remove 32bit and update to 1.9

---

bucket/streamlabs-obs.json

There are too many `0.16.0-previewXX` in release page...

streamlabs-obs: Fix checkver

---

bucket/ocenaudio.json

Fix #2419
I seems that the developer of `oceanaudio` has modified some content, and repacked the file without updating the version number.

Ocenaudio: fix hash, modify script (description, checkver, au.hash)

---

bucket/teraterm.json

close #2416.
**Tera Term** is a terminal emulator for ssh/telnet/serial connection.
Homepage: https://osdn.net/projects/ttssh2/

Teraterm: Add version 4.103

---

bucket/playnite.json

mentioned in **Outstanding Excavator issues**(#2308).
The reason causing 404 error is that **Playnite 5.x is currently only available for patreons(paid subscribers)** (see https://github.com/JosefNemec/Playnite/releases)
This fixes the problem by modifying `checkver` to use regex to match downloadable files only, rather than using Github's version idendifiers.

playnite: fix checkver

---

bucket/praat.json

mentioned in **Outstanding Excavator issues** (#2308)
The file name for praat version 6.1 is **praat6100_win64.zip** rather than **praat61_win64.zip**.
This fixes the problem by matching file name using regex.

praat: Fix checkver and autoupdate

---

bucket/onefetch.json

mentioned in Outstanding Excavator issues (#2308).
The problem is caused by that only some of the release versions has a Windows version of it (v1.5.4 has Windows version, but v1.5.5 does not) (see: https://github.com/o2sh/onefetch/releases)
This fixes the problem by manually matching "release files with Windows version" with regex.

onefetch: Fix checkver

---

bucket/libreoffice-stable.json

Only stable version has portable version. There is only a x86 version. I don't want to add so many shortcuts, maybe we can remove them except the libreoffice?

Libre Office Stable: Add version 6.2.5

---

bucket/ios-webkit-debug-proxy.json

Simply extract version numbers from the latest .zip file to skip some versions without windows build.
https://github.com/google/ios-webkit-debug-proxy/issues/316

ios-webkit-debug-proxy: Fix checkver

---

bucket/uget-portable.json
bucket/uget.json

The official websit haven't update
Note: There is a locale package. After https://github.com/lukesampson/scoop/pull/3518 is merged we could add it.

uget: Update to 2.2.2 , and add au.hash

---

bucket/richcopy.json
bucket/robocopy-gui.json

Add two old files copy tools: Robocopy GUI and RichCopy, made by Microsoft staff, and all are provided as-is, and not supported by Microsoft.

richcopy & robocopy-gui: Add two old files copy tools

---

bucket/pureref.json

https://www.pureref.com/
PureRef is a freeware (no license restrictions) tool for artists to visualize and organize their reference images on a board.
You can add images through drag-and-drop and pasting.
I could not find any page that references the hashes for the executables so I'm leaving it to scoop to calculate them.
I tested this locally and it works fine.
If anything else is needed, please tell.

Add PureRef 1.9.2

---

bucket/fiddler.json

There are two installers inside `$PLUGINSDIR`, not sure how to handle these, opening this PR for some feedback, suggestions

fiddler: Extract instead of installation

---

bucket/gnucash.json

Hi, 
The original manifest points to the sourceforge repository so I changed the url field to the gnucash github repository for convenience.
I also added :
- A bin field to allow scoop to create a shim
- A checkver field pointing to the github repository
- A hash field to grab the latest version hash with a regex

Improve gnucash manifest

---

bucket/mupdf.json

Fix #2515.
It looks like that the developers of **mupdf** has modified the file (a minor update/fix?) without updating the version number.

mupdf: fix hash

---

bucket/testcentric.json

Fixes:
```
testcentric: 1.0.0 (scoop version is 1.0.0-beta4)
Autoupdating testcentric
DEBUG[1564236017] $substitutions (hashtable) -> /root/scoop/lib/autoupdate.ps1:181:5
DEBUG[1564236017] $substitutions.$dashVersion                   1-0-0
DEBUG[1564236017] $substitutions.$cleanVersion                  100
DEBUG[1564236017] $substitutions.$majorVersion                  1
DEBUG[1564236017] $substitutions.$basename                      testcentric-gui.1.0-1.0.0.nupkg
DEBUG[1564236017] $substitutions.$url                           https://github.com/TestCentric/testcentric-gui/releases/download/1.0.0/testcentric-gui.1…
DEBUG[1564236017] $substitutions.$match1                        1.0.0
DEBUG[1564236017] $substitutions.$underscoreVersion             1_0_0
DEBUG[1564236017] …
```

testcentric: Fix au.url

---

bucket/gimp.json

Close #1369 
Please consider merging https://github.com/lukesampson/scoop/pull/3204, current `unpack_inno` crashed occasionally (due to `Move-Item` for huge amount of files).

GIMP: Using installer.script instead of original installer

---

bucket/octant.json

octant is an augmented [kubectl](https://github.com/ScoopInstaller/Main/blob/master/bucket/kubectl.json) that provides detailed information about a Kubernetes cluster in a browser. Since it is not strictly a CLI tool, this PR is made to the extra rather than main bucket.
Let me know if this change can be made against main instead so that related tooling can installed from a single bucket.

octant: Add version 0.4.1

---

bucket/codeblocks-mingw.json
bucket/codeblocks.json

**Code::Blocks** ([homepage](http://http://www.codeblocks.org)) is an open-source C/C++/Fortran IDE.
Notes:
* licenses: I marked the license as `GPL-3.0-only` according to https://github.com/lukesampson/scoop/issues/3546 (**Calinou**'s comment) and [the licensing page](http://www.codeblocks.org/license) from Code::Block's official site.

CodeBlocks: Add version 17.12

---

bucket/netbeans.json

This matches the section under "Apache NetBeans Releases" (the green box) instead of the top section of the page (the red box).
It looks like that the top section can be used by some other notifications (other than version update), which may lead to `checkver` error in the future.

NetBeans: modify checkver

---

bucket/flashplayer-sa.json

close #2533.
This is the standalone version of **Adobe Flash Player**.
([download page](https://www.adobe.com/support/flashplayer/debug_downloads.html))
Notes:
* The filename flashplayer_**32**_sa.exe denotes **version 32** rather than 32-bit. See [archived download page from 2016](https://web.archive.org/web/20160217151701/https://www.adobe.com/support/flashplayer/debug_downloads.html) for example.
* Adobe only provides 32-bit standalone binaries for Windows.

flashplayer-sa: Add version 32.0.0.223

---

bucket/vboxvmservice.json

As a side note, the project moved to Github last year:
from https://sourceforge.net/projects/vboxvmservice/
to https://github.com/onlyfang/VBoxVmService/
I didn't manage to disable the installer's shortcut creation so those two shortcuts
are removed in the post_install script.

Add VBoxVmService (a Virtualbox-related tool)

---

bucket/texmacs.json

```
Download: Status Legend:
Download: (OK):download completed.
Checking hash of TeXmacs-1.99.11-installer.exe ... ERROR Hash check failed!
App:         extras/texmacs
URL:         http://www.texmacs.org/Download/ftp/tmftp/windows/TeXmacs-1.99.11-installer.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    205a55196191cdf826f83d83976fb2c71033fcc604679c12f94cc27b24322704
Actual:      e979a8995ad893fc208c091f0f5cd34740f3d4a4fd052bae5665c8976dc67f7d
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=texmacs%401.99.11%3a+hash+check+failed
```
I have downloaded twice to make sure it isn't corrupted.

TeXmacs 1.99.11: fix hash

---

bucket/ccleaner.json
bucket/defraggler.json
bucket/recuva.json
bucket/speccy.json

I'm not sure if this will fix Piriform apps' hash errors...
- Change URLs to ccleaner.com
- Modify `checkver` and download URLs and download filenames (change to filename returned by URL)
- Add `persist` (and switch off autoupdate)

Piriform Apps: Change URLs, add persist, modify checkver

---

bucket/texmaker.json

It seems that texmaker will just delete the symlink and create a new file so persistence does not work. Before the persistence code rework is complete, this is a temporary solution.

Texmaker: fix persist

---

bucket/bpgconv.json

**BPGconv** ([homepage](http://www.romeolight.com/products/bpgconv/)) is a batch conversion tool for [BPG images](https://en.wikipedia.org/wiki/Better_Portable_Graphics).
Notes:
* The `BSD-2-Clause` license is contained in `license.txt`.
* The config file is named as `Romeolight BPGconv_2.5.0.0.config`. I could not find a simple way to "persist" the config file (other than using install/uninstall script, which can be very messy.)
* The website(www.romeolight.com) does not support HTTPS.

BPGconv: Add version 2.5

---

bucket/geekbench.json

**GeekBench** ([homepage](https://www.geekbench.com/)) is a CPU/GPU benchmark software.
Notes:
* Executable names are originally `geekbench4.exe` (console version) and `GeekBench 4.exe` (GUI version). I renamed them as `geekbench.exe` and `geekbench_gui.exe` to avoid error when major version changes (4.x -> 5.x).
* GeekBench is not a free software, but users can still perform benchmarks in "tryout mode". (paid version supports more features)
* I marked the license as **proprietary**. Is this correct?

GeekBench: Add version 4.4.1

---

bucket/todotxt-net.json

Closes https://github.com/ScoopInstaller/Main/issues/277.
**todotxt.net** ([homepage](http://benrhughes.github.io/todotxt.net/)) is an implementation of *todo.txt* for Windows using the .NET framework.

todotxt-net: Add version 3.3.0

---

bucket/prime95.json

Tested and working locally.
Fixes:
```
URL https://www.mersenne.org/ftp_root/gimps/p95v298b5.win32.zip is not valid
Could not find hash!
ERROR Could not update prime95 32bit

prime95: Fix checkver & au.*

---

bucket/dbgl.json

Requested in #2162.
**DBGL** is an open-source frontend for DOSBox.
Homepage: http://members.quicknet.nl/blankendaalr/dbgl/
~The `post-install` section will check whether JRE is installed. (by checking env variable `JAVA_HOME`), and prompt the user to install it if JRE is not detected.~ (suggest user to install Java instead)

DBGL: Add version 0.82

---

bucket/archi.json

https://www.archimatetool.com/downloads/What's%20New%20in%20Archi.pdf
Starting from 4.5, Archi supports only 64-bit versions.
#2308

Archi: Update to 4.5.1 & remove 32bit

---

bucket/dbgl.json

mentioned in #2308 (Outstanding Excavator issues).

DBGL: fix checkver

---

bucket/prusaslicer.json

mentioned in #2308 (Outstanding Excavator issues)
**PrusaSlicer** now put alpha, beta and rc versions in their release tags.
(see: https://github.com/prusa3d/PrusaSlicer/releases)
~This modifies `checkver` to **check all releases** (rather than checking only the latest), so that it will only match the **latest stable release**.~
This modifies `checkver` to allow alpha and RC releases.

prusaslicer: Fix checkver

---

bucket/bulk-crap-uninstaller.json

bulk-crap-uninstaller: Change download.url to FossHub

---

bucket/cherrytree.json

After persitence tweaks now nested files are created in correct subdirectories instead of root of persist.
Also webpage is not updated with hashes for latest file for some reason.

cherrytree: fix persist check

---

bucket/ddu.json

```
Download: (OK):download completed.
Checking hash of DDU%20v18.0.1.7.exe ... ERROR Hash check failed!
App:         extras/ddu
URL:         https://www.wagnardsoft.com/DDU/download/DDU%20v18.0.1.7.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    20591a49debfa6aa3eb6e3f72323c6ad05a3498f
Actual:      ee61b693543b277cb24dedd35542c35eb6748c40
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=ddu%4018.0.1.7%3a+hash+check+failed
```
https://www.wagnardsoft.com/content/display-driver-uninstaller-ddu-v18017-released
```
ChangeLog:
-Fixed the cleaning of the "OpenGLShExt" and "NvAppShExt" happening when it's not expected
Known issues:
-
For a guide , check : Guide
SHA1: …
```

DDU@18.0.1.7: update hash

---

bucket/octant.json

Right now shim creation fails for Octant because the binary is contained within a subdirectory. Specify `extract_dir` to work around that.
```
~> scoop install octant                                                                                                 
Installing 'octant' (0.6.0) [64bit]                                                                                     
octant_0.6.0_Windows-64bit.zip (21.1 MB) [====================================================================] 100%    
Checking hash of octant_0.6.0_Windows-64bit.zip ... ok.                                                                 
Extracting octant_0.6.0_Windows-64bit.zip ... done.                                                                     
Linking ~\scoop\apps\octant\current => …
```

Extract octant.exe from ZIP file subdirectory

---

bucket/fastcopy.json

close #2732
FastCopy has modified its license terms on its [official website](https://fastcopy.jp/help/fastcopy_eng.htm#license).
> ~This program is free software. You can redistribute it and/or modify it under the GNU General Public License version 3.~
(Due to various circumstances, distribution of the source code is temporarily suspended ... Please use FastCopy as freeware with no guarantee)
This modifies **FastCopy**'s license from `GPL-3.0-only` to `Freeware`.

FastCopy: modify license to Freeware

---

bucket/notable.json

close #2766
**Notable** has changed its license terms. See #2766 for more details.

Notable: modify license to "Freeware"

---

bucket/altair.json

I confirmed the `artifactName` config in [electron-builder.yml](https://github.com/imolorhe/altair/commit/cbf8594eb7e674a6e621e4feb711a9e6540f71fc#diff-16c2a798a0e2b6675d5675ff89ece034R21) has changed.

altair: Fix url

---

bucket/mobaxterm.json

$ex is an absolute path of mobaxterm*.exe, so ‘Rename-Item’ will throw an error.
```
Rename-Item : Cannot find path 'D:\local\scoop\apps\mobaxterm\12.1\D:\local\scoop\apps\mobaxterm\12.1\MobaXterm_Personal_12.1.exe' because it does not exist."
```

MobaXterm: Fix path of mobaxterm.exe

---

bucket/chromium.json

#2308 (Outstanding Excavator Issues)
Notes:
* Modify download URL from https://github.com/henrypp/chromium/ to https://github.com/macchrome/winchrome/.
* Track new versions from https://github.com/macchrome/winchrome/ (remove dependency of API from https://chromium.woolyss.com)
Some issues for `-dev`, `-nosync` and `-dev-nosync` packages:
* For `chromium-nosync`, [the release channel](https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=stable-codecs-nosync&out=string) is empty. (maybe discontinued?) Should we replace it by the **Ungoogled** version from https://github.com/macchrome/winchrome/releases ?
* For `chromium-dev-nosync`, [the 64-bit version and 32-bit version are released separately](https://github.com/RobRich999/Chromium_Clang/releases/) (they will not have the same …

Chromium: Fix checkver/autoupdate

---

bucket/krita.json

exe file is smaller (104M/140M) and need less time to unzip.

Krita: Change to exe

---

bucket/foobar2000-encoders.json
bucket/foobar2000.json

Persist playlist-v1.4.
Persist theme.fth after first run.
encoders need to be reinstall after foobar update. Maybe just install encoder in foobar manifest is better.
It seems that bucket in depends won't effect.
Didn't see https://github.com/lukesampson/scoop-extras/pull/2076 before...

foobar2000: portable and no privilege

---

bucket/gcloud.json

I propose to remove the `post_install` script for Google Cloud SDK mainly for two reasons:
1. Avoid re-initializing Cloud SDK on each update
Currently the init process must be done on each update otherwise scoop marks the app installation as failed;
2. Allow installing Cloud SDK in an unattended way
This change allow installing Cloud SDK without user interaction, the user is still able to initialize it manually afterwards with their credentials and settings.
I also added `notes`  field as it is in Git in the main repository.

gcloud: Remove post_install and add notes for init

---

bucket/pencil.json

https://pencil.evolus.vn/  
_(https://github.com/evolus/pencil)_
Pencil is built for the purpose of providing a free and open-source GUI prototyping tool that people can easily install and use to create mockups in popular desktop platforms.
Successfully tested locally with both 64-bit and 32-bit.
Might need a quick check with the hashing for the `autoupdate` part. 
Otherwise, the pattern worked properly on a RegExp sandbox <sup>(https://regex101.com/)</sup>.

Add Pencil 3.0.4

---

bucket/dropit.json

sorry...
I accidentally closed this PR (#2805) when I rebase the commit
auto-update work fine
And the download path has been corrected
```json
{
"version": "8.5.1",
"homepage": "http://www.dropitproject.com/",
"description": "Personal assistant to automatically manage your files",
"license": "GPL-3.0-only",
"url": "https://downloads.sourceforge.net/project/dropit/DropIt/v8.5.1/DropIt_v8.5.1_Portable.zip",
"hash": "sha1:882c765830b307d8b2d90b4411e061d39d79a28c",
"pre_install": "if (!(Test-Path \"$persist_dir\\settings.ini\")) { New-Item \"$dir\\settings.ini\" -Force | Out-Null }",
"extract_dir": "DropIt_v8.5.1_Portable",
"shortcuts": [
[
"DropIt.exe",
"DropIt"
]
],
"persist": [
"Profiles",
"settings.ini"
],
"checkver": "Latest Version: v([\\d.]+)",
"autoupdate": {
"url": …
```

dropit: add a new app

---

bucket/libreoffice-fresh.json

It seems that libreoffice is the only manifest using metalink. `$url.sha256` is more clear. We can deprecate metalink mode.

libreoffice: Extract hash from $url.sha256

---

bucket/firefox-esr.json

Because sometimes there are two latest version of firefox esr, we shouldn't checkver from release note. Maybe the A/B test problem can be solved by autoupdating checkver.

Firefox ESR: fix checkver

---

bucket/fvie.json

File VersionInfo Editor - edits EXE/DLL/SYS metadata.
There is no autoupdate URL field since seemingly the download endpoint is independent of the version (https://www.carifred.com/fvie/FVIE.exe)

Add FVIE (v1.5.0.0)

---

bucket/msiafterburner.json

- Remove RivaTuner Statistics Server
- Use guru3d.com download providing a newer version
- Add script to migrate profiles from old persist structure
- Add missing quotes in scripts

msiafterburner: Update to version 4.6.1 and decouple RTSS

---

bucket/lunacy.json

Lunacy manifest has been broken for several months.
It should use architecture-specific files as explained by @Ash258 
- closes #2426

fix(lunacy): Use architecture-specific files

---

bucket/now-cli.json

See https://github.com/zeit/now/issues/3074#issuecomment-536098630
Should we add a note or remove this manifest?

Now-cli: remove autoupdate

---

bucket/chromium-dev-nosync.json

Repository for this app changed to https://github.com/macchrome/chromium.
Owner of the new repo uses different naming scheme for releases.
Changed checkver to use JSON API, instead of raw string parsing.
Removed 32-bit version because only 64-bit builds are available now.
Related: #2308.

chromium-dev-nosync: fix autoupdate issues

---

bucket/ccleaner.json
bucket/defraggler.json
bucket/recuva.json
bucket/speccy.json

Fix #2951 
Piriform has changed its download url, and portable archives are not found anymore.

piriform: Fix download.url and checkver

---

bucket/keepass-plugin-YetAnotherFaviconDownloader.json
bucket/keepass-plugin-yafd.json

Added https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases to the list of keepass plugin extras.

keepass-plugin-yafd: Add version 1.2.2.0

---

bucket/foobar2000-portable.json
bucket/foobar2000.json

tl; dr; It's not enough to persist `configuration`, `index-data` and `library`
folders. This persistence creates more problems than it solves.
foobar2000 config shouldn't be persisted that way. Entire config folder should
be included in persisted folders, because plugins use that folder to store
their files as well.
But this isn't possible, because "portable mode" for foobar2000 means moving
`$APPDATA/Roaming/foobar2000/*` to location where foobar2000 installed, and this
in return means you can't persist contents of every folder because you
don't know beforehand what to persist.

foobar2000: partial revert of recent "improvements" (add portable)

---

bucket/transgui.json

Fix download URL error (original name transgui-5.18-setup.exe which lost ".0")

transgui: fix download URL

---

bucket/skaffold.json

Seems to be the incorrect hash for this version.

Update skaffold with correct hash

---

bucket/snappy-driver-installer-origin.json

Note that unlike many apps that claim themselves to be a driver installer, SDIO is actually legit.

snappy-driver-installer-origin: Add version 1.5.6.705

---

bucket/winauth.json

WinAuth is a portable, open-source authenticator for Windows that provides counter or time-based RFC 6238 authenticators and common implementations. Autoupdate is not necessary as the project is no longer active.

Add WinAuth

---

bucket/teamspeak3.json

"Team Speak" is wrong, the correct name is "TeamSpeak"

Fix TeamSpeak shortcut

---

bucket/mp3directcut.json

Hello,
After first run, the process create mp3DirectCut.ini file that could be persistable. I tried with the persist feature but it creates it as a folder, Any idea how to implement it properly ?

mp3directcut: Add version 2.25

---

bucket/butterflow-ui.json

butterflow-ui is a graphical user interface for [butterflow](https://github.com/ScoopInstaller/Main/pull/491). It comes packaged with butterflow, so butterflow does not need to be installed separately.

Add butterflow-ui

---

bucket/linqpad.json

Fixes error `Can't shim 'lprun.exe': File doesn't exist.`

linqpad: fix file names

---

bucket/sagemath-installer.json

The second step of post_install was failing, as it was using UNIX-style paths, that were misinterpreted as relative to current directory `scoop install` was ran from.

sagemath-installer: fix post_install

---

bucket/persepolis.json

the persepolis release file version part changed from underscored to dotted for 3.2.0, and the hashes were incorrect
- Closes #2923
- Closes #2855
- Closes #2920
- Closes #2925

persepolis: Fix manifest

---

bucket/altair.json

The file name in altair is different from v2.3.5 and 2.3.6. This fixes that.

Fixed altair config

---

bucket/azuredatastudio-insiders.json

URL was pointing to the stable version of Azure Data Studio. Updated to correctly download the Insiders edition and updated file and shortcut names as appropriate.

azuredatastudio-insiders: download nightly instead of stable

---

bucket/tixati.json

Tixati is very stubborn and disregards current working folder, randomly dropping config files around the .exe as you edit settings. Creating empty files in their place does not work, as Tixati errors out on loading an empty config file.
Thus this solution just copies the .exe file into the persisted folder and runs it from there.

tixati: Add version 2.64

---

bucket/ao.json

Ao is an elegant Microsoft To Do desktop app. I wasn't sure if I should wrap the installer script in `architecture`.

ao: Add version 6.9.0

---

bucket/altools.json

Microsoft seems to have modified the self-extractor (license terms perhaps?) but have validated the files it contains are all the same. I have updated the hash to match.
- Closes #3084

altools@1.0: Hash fix

---

bucket/onlyoffice-desktopeditors.json

[Onlyoffice desktop editors](https://github.com/ONLYOFFICE/DesktopEditors/releases/) now put hyphens in their version tags. (such as ver `5.4.1-2`).

onlyoffice-desktopeditors: Update to 5.4.1-2 (Manually)

---

bucket/ydl-ui.json

**ydl-ui** has changed its file name pattern from *YDL_UI_v**xxx**_Portable* to *YDL-UI_Portable_v**xxx***.

ydl-ui: update to version 2.6.1 (manually)

---

bucket/waterfox-current.json
bucket/waterfox.json

**Waterfox** has [split their development into 2 branches](https://www.waterfox.net/blog/waterfox-2019.10-release-download/).
The **classic** branch is the legacy branch that supports all the old standards (it will not be retired, and will be actively maintained). The **current** branch introduces new features and options that the classic version does not support.
https://www.waterfox.net/ has a **download button** on its homepage, and it leads to the classic branch. 
Therefore, I tend to link `waterfox` package to the **classic branch**, and add another `waterfox-current` package for **current branch**. So that users using the `waterfox` package can keep their software updated.
Please tell me if there is a better idea. Thanks!

waterfox: use "classic" branch, add waterfox-current package for "current" branch

---

bucket/zettlr.json

Fix #3112
It seems like developer change original file.
https://scoop.r15.ch/extras/mud-20191101-150001.log
https://github.com/Zettlr/Zettlr/releases/download/v1.4.3/SHA256SUMS.txt

zettlr: Fix hash

---

bucket/dbvis.json

[DBVis](https://www.dbvis.com/download/10.0) added `-x32` to the filename of their 32-bit releases.

dbvis: Update to version 10.0.24 (manually)

---

bucket/potplayer.json

close #3129
Also see https://github.com/lukesampson/scoop-extras/pull/3056#pullrequestreview-306571407
> Maintaners be aware that lots of hash check fail issues will be opened after each release. Usually the release file is chaning twice a day for 4-5 days after release.

potplayer: fix hash

---

bucket/ydl-ui.json

* [ydl-ui](https://github.com/Maxstupo/ydl-ui/releases) changed their file name back to the original pattern. This fixes the download URL.
* This also adds `download-list.json` and `ydl-ui.json` to *persist*.
* The *installer.script* will modify `ydl-ui.json` to disable update. (if previous persist data does not exist)

ydl-ui: Update to version 2.6.2 (manually)

---

bucket/losslesscut.json

[Lossless Cut](https://github.com/mifi/lossless-cut/releases/) now use installers instead of ZIP archives.
Also modified `description` to make it more brief.

losslesscut: Update to version 2.6.2 (manually)

---

bucket/firefox-nightly.json

https://github.com/lukesampson/scoop-extras/pull/3073#event-2774649732
~~It seems that the update url for nightly version is broken. Checking update in app is also broken. Just wait until it's fixed upstream.~~
Support specifing verison.
close https://github.com/lukesampson/scoop-extras/pull/2124
close https://github.com/lukesampson/scoop-extras/issues/1140

firefox-nightly: fix checkver

---

bucket/todotxt-net.json

The last version of Todotxt.NET changed the filename of the zip, which breaks the current JSON.
Maybe the author should be asked if it was done by accident?
Here is the release page:
https://github.com/benrhughes/todotxt.net/releases

todotxt-net: Fix version 3.1.1 URL

---

bucket/cura.json

Correct download path with
#2308

cura: Update to 4.4.0

---

bucket/playnite.json

(binaries no longer hosted on github)
#2308

playnite: update to 6.2, fix autoupdate

---

bucket/psiphon3.json

It's not a nightly app but we can't find its version on website. Change the version to nightly can help users update it.

psiphon3: fix version

---

bucket/wincompose.json

Fixes #1512 like #1852, by preempting folder creation with a file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lukesampson/scoop-extras/3261)

wincompose: Create settings.ini for persist

---

bucket/wincdemu.json

Closes #3273 
Download was removed from the main site, just redirects to github instead.
Unfortunately, the portable version used in the manifest is on 4.0 and is under the 4.1 tag on releases.
This breaks the checkver and autoupdate, but it is likely safe to remove them anyway, since the last commit is almost 1 year old.

Wincdemu: fix download link, remove autoupdate & checkver (development dead)

---

bucket/ds4windows.json

Also added the license.
Users that picked %appdata% to keep their settings will be prompted by the program to move the settings files, and others who picked the program folder will notice their profiles now stick, or do not have to manually migrate them every update.

ds4windows: Persist profiles and settings

---

bucket/gatling.json

Adds gatling version 3.3.1
Closes #3217
Gatling DEPENDS on Java, but I added it as a "suggest" because it doesn't look like "depends" can allow the user to choose whether to use the oracle version or openjdk version.
Also, I've put it here in extras instead of main because gatling recorder is not a commandline tool and pops a window application open (unlike k6)

gatling: Add version 3.3.1

---

bucket/windows-terminal.json

- Closes #2921
- Closes #3320 
Adds Windows Terminal
Install script and autoupdate regex adapted from the unofficial chocolatey package.

windows-terminal: Add version 0.6.2951.0

---

bucket/dbeaver.json

dbeaver: Add correct hash from dbeaver.io for version 6.3.0

---

bucket/mkvtoolnix.json

- Closes #3323 
The previous link is deprecated. I also found a better place for the permanent resource link 
https://mkvtoolnix.download/windows/releases for all platforms, releases & versions. 
New json file is verified. Please see the following attachment.

mkvtoolnix@41.0.0: Change download URl

---

bucket/manictime.json

[ManicTime](https://www.manictime.com/): A time tracking software
License: Proprietary
There is a free plan, so we can use it freely with limited function.

manictime: Add version 4.4.4

---

bucket/archi.json

As the download path know seems to contain some unknowable hash, I've removed the `autoupdate` stanza

archi: Update to version 4.6.0

---

bucket/linqpad.json

linqpad: remove `depends` on dotnet-sdk

---

bucket/yapa.json

[YAPA](http://lukaszbanasiak.github.io/YAPA/): A minimalistic desktop timer app for Pomodoro Technique users
Github: https://github.com/lukaszbanasiak/YAPA
License: MIT
Although it's discontinued, but it still usefull.

yapa: Add version 1.2.0

---

bucket/geekbench.json

Fix #3337
Wildcard for `Rename-Item` does not work under **Powershell 5.1**. This fixes the problem.

geekbench: Fix installer

---

bucket/claws-mail.json

The update commit for claws-mail was missing the new url and file hash for the installer

claws-mail: Change download URL

---

bucket/inky.json

[Inky](https://www.inklestudios.com/ink/): is a editor for ink, inkle's markup language for writing interactive narrative in games, as used in 80 Days. 
Github: https://github.com/inkle/inky
License: MIT

inky: Add version 0.11.0

---

bucket/spek.json

close #3343
**Spek** ([homepage](http://spek.cc/)) is an acoustic spectrum analyser (helps to analyse your audio files by showing their spectrogram).
Notes:
* ~*Checkver* matches `xxxx.zip` in the homepage instead of using `github: xxx`, because for some versions (for example, version `0.8.3`) there is no Windows binary.~ Remove checkver/autoupdate since Spek has not been updated since 2016.
* Spek stores its user config under `$Env:AppData\Spek`, so there is no need to use *persist*.

spek: Add version 0.8.2

---

bucket/milton.json

`scoop install milton` failed. With this, it doesn't!

milton@1.9.1: Fix extraction

---

bucket/wumgr.json

The latest version is `1.1b`, but it is put under the tag `v1.1`.
See https://github.com/DavidXanatos/wumgr/releases and https://github.com/DavidXanatos/wumgr/compare/v1.1...master for details.

wumgr: Update to version 1.1b (manually)

---

bucket/chk.json

close #3198
**CHK** ([homepage](https://compressme.net/)) is an advanced hash tool with gui interface.
* `lang.txt` is the language pack file. If users want to use the language pack feature, they need to download the language pack, and put the `lang.txt` of their preferred language (e.g. Simplified Chinese) in the install directory.
(See "Download" -> "Language Packs" on https://compressme.net/)

CHK: Add version 3.21

---

bucket/infoqube.json

**infoqube** has changed the layout of their website, causing `checkver` to fail. This fixes the problem.
Also modified `description` to make it briefer.

infoqube: Update to version 0.9.114q (manually)

---

bucket/yatqa.json

**yatqa** now include letters (such as 3.9.8.3**b**) in the version number. Therefore `checkver` needs to be modified.

yatqa: Update to version 3.9.8.3b (manually)

---

bucket/windows-terminal.json

regular Windows Terminal install creates a `wt` shortcut, we should replicate this behavior
see e.g. [How to open Windows Terminal from command prompt or run](https://www.thomasmaurer.ch/2019/08/how-to-open-windows-terminal-from-command-prompt-or-run/)

windows-terminal: Add wt shim

---

bucket/gedit.json

close https://github.com/lukesampson/scoop-extras/issues/3384
> Warning: The latest official Windows binary is the version 3.20, and the latest official Mac binary is the version 3.2, however, the latest source releases should work. If you can help with building binaries of newer releases for either platform, please get in touch with us.
Last update of 64bit binary is 3 years ago and 32bit binary is even older so I only add 64bit. There are lots of cli tools in bin directory but they are not related to gedit's usage so I didn't add them.

gedit: Add version 3.20.1

---

bucket/launchy.json

Looks like the releases on github are more up to date, so let's switch over to them.
One issue I found while using it: (this is independent of the version update)
Looks like the persistence of `launchy.ini` is not working properly. I suspect the app deletes and recreates the file on every settings change leading to a decoupled file in the `persistent` folder and a regular, non-linked file in the app folder. Any suggestions about that? Should I file it in a separate issue?

launchy: Update to version 2.10.79

---

bucket/ngspice.json

**Ngspice** ([homepage](http://ngspice.sourceforge.net/)) is a SPICE simulator for electric and electronic circuits.
* Only the **64-bit** version is included because the 32-bit version is no longer updated (it stays at version 27).

ngspice: Add version 31

---

bucket/vidi.json

* **ViDi** has changed their file name patterns. ~Therefore `autoupdate` needs to be modified.~ Removing `autoupdate` since their latest version is marked as **experimental**.
* ~ViDi now depends on VCRedist 2015. (was VCRedist 2017 previously) (see: https://github.com/hasherezade/ViDi/releases)~
-> Visual C++ 2015, 2017 and 2019 all share the same redistributable files, therefore use `extras/vcredist2019` instead.

vidi: Update to version 0.2.5.5 (manually)

---

bucket/treesize-free.json

* They changed the layout of their website. Therefore `checkver` needs to be modified.
* The **download url** on `downloads.jam-software.com` is not working. Their website provides multiple download locations, but both *North America* and *Europe* leads to `downloads.jam-software.de`.
* Not sure why **hash** value changed. Probably due to some minor updates.

treesize-free: Fix url and checkver

---

bucket/openmpt.json

* Update download URL
* Modify `description` to make it briefer.

openmpt: Update to version 1.28.09.00 (manually)

---

bucket/palemoon-portable.json
bucket/palemoon.json

* **Pale Moon** now uses **7z** instead of zip. This fixes the problem.
* Re-formatting `palemoon` and `palemoon-portable` packages.

palemoon: Update to version 28.8.0 (manually)

---

bucket/typora.json

Fixes #3409
Apparently typora has removed the `bin/` folder as of 0.9.82 (though [the changelog](https://typora.io/windows/dev_release.html) doesn't mention it).
this PR changes the `bin` path to `Typora.exe`, the only executable that is left in the installation.

typora: Fix bin

---

bucket/video-thumbnails-maker.json

* **Video Thumbnails Maker** ([homepage](http://www.suu-design.com/projects_vtm.html)) is not a free software. However most of its features are available *without a premium license*.
* The number in the download URL (Files/VTM/**1414881427**/VideoThumbnailsMaker_Setup.zip) ~is constant (remains the same) in different sessions~ changes every time when the file is updated (for example, updating from version `14.0.0.0` -> `14.0.0.1`). Also, it is not related to actual version number, see [web archive](https://web.archive.org/web/20160310043804/http://www.suu-design.com/downloads.html) for example.
* **persist** is not needed because Video Thumbnails Maker stores its user settings under registry `HKCU:\Software\SUU Design\Video Thumbnails Maker`.

video-thumbnails-maker: Add version 14.0.0.0

---

bucket/gb-studio.json

* **gb-studio** has changed their file name pattern.
* Since *gb-studio* stores its user config in `$Env:AppData\GB Studio`, *persist* is not needed for this package.

gb-studio: Update to version 1.2.0 (manually)

---

bucket/foto-mosaik-edda.json

**Foto-Mosaik-Edda** ([homepage](https://fmedda.com/en/home)) is a software which allows you to create photo mosaic pictures (such as the picture below)
Notes:
* **license**: The pro version of Foto-Mosaik-Edda is proprietary, but standard version is **Free**.
* **Shortcut** is named as `Foto-Mosaik-Edda` (instead of `Foto Mosaik Edda`) according to the Window name.
* The **pre_install** script:
* Modifies the default language of `Rapid-Mosaic` from German to English (when  users start the program for the first time). 
* If users chooses their own language (e.g. Japanese) in Rapid-Mosaic's configuration, their settings will be preserved in `Data\Rapid-Mosaic.config`. Therefore the *pre_install* script will not modify the language back to English when users update the program through …

foto-mosaik-edda: Add version 7.7.18156.1

---

bucket/msxml4.json

**MSXML 4** ([Wikipedia](https://en.wikipedia.org/wiki/MSXML)) is the runtime library for Microsoft XML Core Services (MSXML) version 4. It is obsolete now, but some old applications/games (e.g. `Age of Mythology`, `Age of Empires 3`, `Rise of Legends`) still need it.
Notes:
* This manifest follows the pattern of [VCRedist packages](https://github.com/lukesampson/scoop-extras/blob/8a1d5cd2d16c5796a30e9f3e07eb755171c0463a/bucket/vcredist2013.json).
* See [this article from Microsoft](https://support.microsoft.com/en-us/help/269238/list-of-microsoft-xml-parser-msxml-versions) about version numbers and compatibility of MSXML.
* **Homepage**: The *MSXML homepage* link on Wikipedia leads to [the documentation](http://msdn.microsoft.com/en-us/library/ms763742.aspx). I guess Microsoft took down …

msxml4: Add version 4.30.2100.0

---

bucket/age.json

age ([homepage](https://age-encryption.org)) is a simple, modern and secure encryption tool with small explicit keys, no config options, and UNIX-style composability.
- Only a 64-bit version exists

age: Add version 1.0.0-beta2

---

bucket/tableplus.json

close https://github.com/lukesampson/scoop/issues/3095
**TablePlus** ([homepage](https://tableplus.com/)) is a relational database explorer.
Notes:
* *TablePlus* is not a free software. However its main features are available without a premium license.
> The free trial is limited to 2 opened tabs, 2 opened windows, 2 advanced filters at a time. We can change the limitations without any notifications in the future releases.
(https://tableplus.com/pricing)
* **pre_install**: The installer contains files for both *32-bit* and *64-bit*, and named them as `(something),1.(ext)`[32-bit] and `(something),2.(ext)`[64-bit], which is a common case ~for innosetup installers~. See [install script](https://github.com/lukesampson/scoop-extras/files/4008418/install_script.txt) for details.
* **persist** …

tableplus: Add version 3.1.0.112

---

bucket/batcodecheck.json

**BatCodeCheck** ([manual](https://www.robvanderwoude.com/helptext.php?src=batcodecheck_cs_help)) is a linter for Windows batch file **(.bat)**.
Notes:
* BatCodeCheck is a command-line tool. However it is **not suitable for the main bucket** since the author states that it is still in beta. (https://github.com/ScoopInstaller/Main/pull/687)
* The MD5 hash value comes from [the download page](https://www.robvanderwoude.com/csharpexamples.php).
* *BatCodeCheck* has not been updated since 2014. Therefore **checkver/autoupdate** is not needed. 
* **License** info can be found in the *Disclaimer* section of the homepage(https://www.robvanderwoude.com/).
> Unless stated otherwise, these pages, the scripts presented and their sources are copyrighted freeware.
You may modify them, as long as a …

batcodecheck: Add version 0.32.1

---

bucket/chk.json

* **CHK** loads the language pack file `lang.txt` from *current working directory*. Therefore language packs will not work when user starts the program **by shim-exes**. (reported by @niheaven at https://github.com/lukesampson/scoop-extras/pull/3378#issuecomment-568241863)  This fixes the issue.
* If users want to use the language pack feature, they need to download the language pack, and put the lang.txt of their preferred language (e.g. Simplified Chinese) in the install directory.
(See "Download" -> "Language Packs" on https://compressme.net/). This will **overwrite `$dir\lang.txt` (hardlink to `$persist_dir\lang.txt`) created by Scoop**, and *persist* will not be working after that.  The `uninstaller` script fixes the issue.
* Add description about language packs in `notes`.

chk: 'lang.txt' persist tweaks

---

bucket/haskellx.json

Installation currently fails with the following error:
```
Running post-install script...
mv : Cannot find path 'C:\Users\eirik\scoop\apps\haskellx\current\cabal' because it does not exist.
At line:1 char:1
+ mv "$dir\cabal" "$dir\bin\cabal.exe"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\eitsar...x\current\cabal:String) [Move-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
'haskellx' (7.8.3) was installed successfully!
```

haskellx@7.8.3: Fix installation

---

bucket/multicommander.json

The hashes advertised on multicommander.com do not match the hashes of the
downloaded files.  However, the downloaded files are 'clean' according to
virustotal.com

multicommander@9.5.3.2578: Fix hash

---

bucket/nettraffic.json

- Closes #3460 
[NetTraffic](https://www.venea.net/web/nettraffic): An essential network bandwidth usage monitor.
**Note:** 
- The official site does not provide a valid download url. So I open an issue #3460, thanks to @issaclin32, I use [TechSpot](https://www.techspot.com/downloads/6058-nettraffic.html) as the download service. 
- The official site offers a portable version, but we can not get it, so just use the installer.

nettraffic: Add version 1.64.0

---

bucket/authy.json

From https://github.com/Ash258/Scoop-Ash258/blob/master/TODO/AAAuthy.json
**Checklist:**
~~Should we import (as in preserve) Authy's existing `AppData`, or just perform a clean installation?~~

authy: Add version 1.7.2

---

bucket/syncbackfree.json

**SyncBackFree** ([homepage](https://www.2brightsparks.com/download-syncbackfree.html)) is a data backup and synchronize software.
Notes:
* *SyncBackPro* ([syncbackpro.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/syncbackpro.json)) has 32-bit and 64-bit versions, but **SyncBackFree** has only one application for both 32-bit and 64-bit.
> Windows 10, Windows 8, Windows 7 and Windows Vista. Both 32-bit and 64-bit versions of Windows are supported.
* **persist**: *SyncBackFree* does not provide the option for **custom backup profile location** like *SyncBackPro* does. Therefore the method used in [SyncBackPro package](https://github.com/lukesampson/scoop-extras/blob/master/bucket/syncbackpro.json) cannot be used here. I tried to put the content below in …

syncbackfree: Add version 9.2.30.0

---

bucket/xournalpp.json

Xournal++ is a handwriting notetaking software with PDF annotation support. Supports pen input from devices such as Wacom Tablets.
NOTE: There's [an issue](https://github.com/xournalpp/xournalpp/issues/1600) with Xournal++ 1.0.16 so I'm hereby make a PR with version 1.0.15

xournalpp: Add version 1.0.15

---

bucket/hwp-converter.json

Hanword HWP document converter for Microsoft Word is a tool which allows you to convert as DOCX files. Bulk converting by folder-bases is also allowed. It's a Microsoft's **official** tool!

hwp-converter: Add version 2.0

---

bucket/eac.json

A commonly-used audio CD grabber for accurate rip. [Website](http://www.exactaudiocopy.de/)

eac: Add version 1.3

---

bucket/imageglass.json

When updating from old version it does not work unless `igconfig.xml` is removed. This should be an upstream issue.

imageglass: Update to version 7.5.1.1

---

bucket/awake.json

Awake is not a command line program. Should remove `bin`, and add `shortcuts`.

awake: Add shortcuts

---

bucket/lighttable.json

Being a GUI Application, I feel like LightTable should be accessible from the start menu, even if its icon is just the default Electron one.

lighttable@0.8.1: Add Shortcuts

---

bucket/multicommander.json

Multicommander's website displays an older version than the latest version offered by MultiUpdate (companion tool of multicommander): by using the same version info download as MultiUpdate, we can track the latest version more closely.
I took the opportunity to update multicommander to the latest version at the same time.

multicommander: Update to version 9.6.1.2582

---

bucket/sql-workbench-dev.json
bucket/teamviewer.json

Files sqlwbconsole.exe and sqlwbconsole64.exe don't exist in version 125.5. Shims linked to sqlwbconsole.cmd.

sql-workbench-dev@125.5: Fix shim

---

bucket/flutter.json

- Closes #2439
- Closes #2526
- Closes #2770 
- Closes #2924
- Closes #3113
- Closes #3360
- Closes #3446 
- Closes #3490
As the flutter officially used `+` instead of `-` to concatenate `hotfix` in their version string since *2019/7/9* or before, the scoop version has stuck at `1.5.4-hotfix.2` yet the real-world version has already been advanced to `1.12.13+hotfix.5`.
So here is this PR.

flutter: Update to version 1.12.13-hotfix.7

---

bucket/fadetop.json

I added two apps to remind myself to take regular breaks.
Both have their quirks:
- FadeTop: is a portable app but I was unable to make the persist mechanism work because the Settings.xml is a file next to the executable, not in a directory next to the executable
- stretchly: is not really portable, it stores its settings in AppData\Roaming\stretchly

 fadetop: Add version 3.1.0.171

---

bucket/material-maker.json

Material Maker is an open source, extensible procedural material generation tool for use with physically-based rendering engines.

material-maker: Add version 0.8

---

bucket/notepadplusplus.json

Download from download.notepad-plus-plus.org wasn't working for me so I redirected the download to the project's GitHub releases page.

notepadplusplus: use GitHub release URLs

---

bucket/lantern-client.json

Fix #3581
The installer for version `5.8.1` cannot be properly extracted. Therefore we need to revert the package to version `5.5.6` and remove checkver/autoupdate.

lantern-client: Revert to version 5.5.6

---

bucket/deepl.json

This will probably update itself because there is no way to disable Squirrel ...
It will also download itself every time if it doesn't find a specific directory structure.
```
D:.
│
├───1.11.0
└───current
│
└───DeepL (has to be the top directory)
│   DeepL.exe (renamed `DeepL_ExecutionStub.exe`)
│
├───app-1.11.0 (has to contain the actual app)
│       DeepL.exe (actual exe)
│
└───packages (has to contain valid `RELEASES` file)
.betaId
RELEASES
```

deepl: Add version 1.11.0

---

bucket/pcmeter.json

**PCMeter** ([homepage](http://addgadgets.com/pc_meter/)) is a CPU and graphic card monitor.
Notes:
* **checkver/autoupdate** is not needed because *PCMeter* has not been updated since 2013.

pcmeter: Add version 0.4

---

bucket/nswagstudio.json

~~`NSwagStudio.*.nupkg` is built with this [NSwagStudio.nuspec](https://github.com/RicoSuter/NSwag/blob/master/src/NSwagStudio.Chocolatey/NSwagStudio.nuspec). It contains `NSwagStudio.msi` inside `tools\` and some chocolately ps1 files, and bunch of other files outside of the directory. That's why I've used `"extract_to"`.~~

nswagstudio: Add version 13.2.2

---

bucket/pageedit.json

pageedit is a companion app of sigil (en epub editor) and created when sigil decided to remove the xhtml visual editor.

pageedit: Add version 1.0.0

---

bucket/streamwriter.json

close #3466
**streamWriter** ([homepage](https://streamwriter.org/en/)) is an application that records music broadcasted by Internet radio stations.
Notes:
* **license**: The *GPL-3.0-or-later* license can be found in the "Application information" section of the main program.
* **pre_install**: The content written to `streamwriter_settings.ini` makes "search for updates" unchecked by default in the setup dialogs. (the setup dialogs will appear when users run the program for the first time)
* *StreamWriter* saves some of its data in `streamwriter_data.dat`.
~I tried to put the file in *persist*, but an empty streamwriter_data.dat will cause error messages to show up.~ Use "copy over method" to persist `streamwriter_data.dat`.
> If streamWriter is used in portable mode, all settings are …

streamwriter: Add version 5.5.0.0.788

---

bucket/openshot.json

close #3601
* **Openshot** now uses `launch-win.bat` (which sets the env variables needed by the main program `openshot-qt.exe`) instead of `launch.exe`.
* Modify *description*.
additional notes:
* The `settings` folder under installation path only stores default settings. User settings are actually stored at `$Env:USERPROFILE\.openshot_qt`.
* Running `openshot-cli.exe` will also start the regular(GUI) interface. `openshot-cli.exe` is used for debug purposes. (See https://github.com/OpenShot/openshot-qt/pull/3106)

openshot@2.5.0: Fix bin/shortcuts

---

bucket/wavebox10.json

Decided not to update the [wavebox.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/wavebox.json) to this version because it now is closed source and they moved from Electron to full Chromium.

wavebox10: Add version 10.0.69

---

.github/CODEOWNERS
.github/workflows/issue_comment.yml
.github/workflows/issues.yml
.github/workflows/pull_request.yml

Github actions hit 1.0.0 today and from my testing are capable of general repeated tasks.
There are totally use cases/actions/problems which I missed/cannot property test/need to implement, but in general they are working.
~~@r15ch13 I added your email, as you have push access to all scoop wide repositories. Please review it and if you have some problem with it, I can add myself or new machine user could be created.~~
Examples:
- Issues
- Hash check fails
- First issue: https://github.com/Ash258/GithubActionsBucketForTesting/issues/182
- Duplicated issue: https://github.com/Ash258/GithubActionsBucketForTesting/issues/184
- PR: https://github.com/Ash258/GithubActionsBucketForTesting/pull/183
- Download failed
- https://github.com/Ash258/GithubActionsBucketForTesting/issues/194
- …

feat(github): Present GithubActions

---

bucket/eagleget-portable.json

Remove `"extract_dir": "/"`, no need it.
```
Installing 'eagleget-portable' (2.1.5.10) [64bit]
Loading EagleGetProtable_2.1.5.10.zip from cache
Checking hash of EagleGetProtable_2.1.5.10.zip ... ok.
Extracting EagleGetProtable_2.1.5.10.zip ... done.
Running pre-install script...
Linking ~\scoop\apps\eagleget-portable\current => ~\scoop\apps\eagleget-portable\2.1.5.10
Creating shortcut for EagleGet (EagleGet.exe) failed: Couldn't find C:\Users\wenmin92\scoop\apps\eagleget-portable\current\EagleGet.exe
Persisting EagleGet\configs
The system cannot find the path specified.
Path not found - C:\Users\wenmin92\scoop\apps\eagleget-portable\current\EagleGet
Persisting EGDownloads
'eagleget-portable' (2.1.5.10) was installed successfully!
```

eagleget-portable@2.1.5.10: Fix installation

---

bucket/wizmouse.json

There's already a couple of antibody-software.com programs in this bucket, but it's missing this quite useful utility.
> WizMouse is a mouse enhancement utility that makes your mouse wheel work on the window currently under the mouse pointer, instead of the currently focused window. This means you no longer have to click on a window before being able to scroll it with the mouse wheel. This is a far more comfortable and practical way to make use of the mouse wheel.
>
> WizMouse can also optionally enable the mouse wheel in applications that don't support it. It does this by translating mouse wheel commands into scroll bar commands that all applications can understand and process.

wizmouse: Add version 1.7.0.3

---

bucket/potplayer.json

The checkver only checks main version, not build version, we should change the checkver more reliable.

potplayer@200317: Hash fix

---

bucket/ibmcloud-cli.json

Current manifest for 0.22.1 contains wrong hashes.

ibmcloud-cli@0.22.1: Fix hash

---

bucket/libreoffice-fresh.json

Newest version (6.4.2.2) moved many files into the folder "LibreOffice", including executables, so scoop gives an error when linking shortcuts to them.

libreoffice-fresh: Add extract_dir

---

bucket/sublime-text.json

- Use proper version instead of only build version
- Explaining shareware is not needed
- Simplify uninstall-context creation

sublime-text: Tweaks

---

bucket/obs-studio.json

#2308 
- Closes #3735 
- Uses CDN for download instead of Github.
- Uses download page for version regex, since CDN only have one version variable in download URL.

obs-studio: Use CDN download URL

---

bucket/vitrite.json

http://www.vanmiddlesworth.org/vitrite/
Vitrite is a small Windows utility that allows you to manually adjust the level of transparency for almost any visible window.
I didn't add checkver since I couldn't find a reliable version pattern on the homepage and the tool hasn't been updated since 2002.

vitrite: Add version 1.1.1

---

bucket/graphql-playground.json

GraphQL playground is a GUI that permit to query graphql endpoint
(was ScoopInstaller/Main#925)

graphql-playground: Add version 1.8.10

---

bucket/meshlab.json

Meshlab changed its archive format. Remove the "extract_dir" parameter.

meshlab: Fix installation

---

bucket/vscode-insiders-portable.json

If I execute: 
```cmd
dir /a %userprofile%\scoop\apps\vscode-insiders-portable\current
```
I will get:
```cmd
04/23/2020  11:28 AM    <JUNCTION>     data [C:\Users\somebody\scoop\persist\vscode-insiders-portable\data]
```
But the `notes` tell us to move to `"$env:USERPROFILE\\scoop\\persist\\vscode-insiders\\data\\extensions\"`, which in inconstant with the resulting directory of `persist`.

vscode-insiders-portable: Adjust notes

---

bucket/libreoffice-fresh.json

- Closes #3869
- Closes #3790
The latest msi installer of libreoffice-fresh doesn't create the "LibreOffice" top directory anymore.

libreoffice-fresh@6.4.3.2: Fix installation

---

bucket/sysinternals.json

- Closes #1751
The current version pattern of sysinternals `Month.day.year` doesn't allow most of the time to automatically upgrade.
I propose to change to `year.Month.day`. Since Month is still alphabetical name instead of a number it will still miss some update. However it will better than today, eg we can get the April 2020 update if we have the September 2019 version installed. Today it won't update since September > April in alphabetical order.
Note: there is an numeric version of the date in the [page](https://docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite) where it's extracted, but looking on webarchive it doesn't evolve consistently with the "Update: .... " (however currently it's aligned)

sysinternals: Change the version pattern

---

bucket/ventoy.json

[Ventoy](https://www.ventoy.net/en/index.html): is an open source tool to create bootable USB drive for ISO files. With ventoy, you don't need to format the disk again and again, you just need to copy the iso file to the USB drive and boot it.

ventoy: Add version 1.0.08

---

bucket/zoom.json

- Closes #3920 
[Zoom](https://zoom.com.cn/) is a video and audio conferencing, chat, and webinars service.
Note for `checkver`:
- The Zoom client has a "Check updates", but it's a post request.
- The Zoom [download page](https://zoom.com.cn/download) has other software, only using `Version ([\\d.]+)` is not strict.
- The Zoom [release notes page](https://support.zoom.us/hc/en-us/articles/201361953-New-Updates-for-Windows) may be better.

zoom: Add version 5.0.1

---

bucket/texstudio.json

Close https://github.com/lukesampson/scoop-extras/issues/4002.
Make the shortcut created by scoop be the same as that created by an installer.

texstudio: Rename the shortcut

---

bucket/mpv-git.json

- Closes #4047 
Currently it 404s:
```
Updating 'mpv-git' (20200426 -> 20200510)
Downloading new version
At C:\Users\Pedro\scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], WebException
+ FullyQualifiedErrorId : The remote server returned an error: (404) Not Found.
```

mpv-git@20200510: Fix URLs

---

bucket/openclosedriveeject.json

Used https://github.com/lukesampson/scoop-extras/blob/master/bucket/quicktextpaste.json as the base template.

openclosedriveeject: Add version 1.33

---

bucket/foxit-reader.json

- Closes #4000
- Closes #4005 
- Closes #4019
- Closes #4068
As the `foxit-reader` has been updated to the `10.x`, the `scoop update foxit-reader` suddenly could not work. And after some investigations, I found that the download `url` of this new `10.0.0` version does not conform the present **major.minor.patch** composing rule: 
It uses `10.0` instead of `10.0.0` as the *version number part* of the `url` and `FoxitReader100_enu_Setup_Prom.exe` instead of `FoxitReader1000_enu_Setup_Prom.exe` as the *filename part* of the `url`. 
But this **major.minor.patch** might still apply to future releases (*with non-zero minor version and non-zero patch version*) I assume.
So, rather than patching the *version number part* and the *filename part* of the `url` together using the matched version …

foxit-reader: Change the way the url was composed

---

bucket/onefetch.json

and fix `checkver` & `autoupdate`

onefetch: Update to version 2.2.0

---

bucket/hydrogen.json

I'm not using `checkver.github` because it seems to return the wrong version. Considering the latest non-beta version is almost four years old, I think 1.0.0-beta2 should be preferred.

hydrogen: Add version 1.0.0-beta2

---

bucket/flutter.json

- Closes #2238
The `dart` executable and all its util scripts reside in the bin folder rather than its home folder **now** ( *but don't know since when* ).

flutter: Add bin\cache\dart-sdk\bin to path

---

bucket/bulk-crap-uninstaller.json

Update links to download from https://github.com/Klocman/Bulk-Crap-Uninstaller/
- Closes #4173

bulk-crap-uninstaller@4.16: Fix URL

---

bucket/foobar2000-portable.json

Add `user-components` to the persist array within `foobar2000-portable` per issue #4044.
Tested this out locally and things seemed to work fine.
- Closes #4044

foobar2000-portable: Persist user-components

---

bucket/vuplayer.json

Portable mode can only read settings, but won't save settings to file. So I didn't make it portable.

vuplayer: add version 4.9

---

bucket/openmpt.json

This should hopefully fix the following error message:
```
Creating shortcut for OpenMPT (mptrack.exe) failed: Couldn't find D:\scoop\apps\openmpt\current\mptrack.exe
```
This is one of my first times doing a pull request. Hopefully I didn't do something really cringy or something.
I also couldn't test if this actually fixes the error, because even if I add my own fork as the extras bucket, it keeps giving me the same error message despite the app manifest being changed. I don't know why this is. Maybe I did something really cringy.

openmpt: Fix shortcut

---

bucket/handbrake.json

Handbrake no longer has the Handbrake subdirectory in the Portable EXE download in release 1.3.3

Handbrake: Update to version 1.3.3

---

bucket/windows-terminal.json

- Closes ScoopInstaller/Main#882
The profile icons were not displayed because in the archive the filename are URL encoded while it's not expected to be the case on the filesystem.
This fix takes care of the encoded { and } chars that are used for GUID-based icon file names.

windows-terminal: Fix profile icons filename encoding

---

bucket/pasteboard.json

This package provides two executables: `pbcopy.exe` and `pbpaste.exe` whose purpuses are the same as OSX's pbcopy/pbpaste.
Though `clip.exe` shipped with Windows works well, it seems Windows missed an utility to get contents from clipboard using CLI. One workaround is to use `powershell.exe -command Get-Clipboard`, but that's too slow on WSL. Another drawback is it cannot supporting converting Windows line break `\r\n` to UNIX line break `\n`.
The `pbpaste.exe` provided by this package runs faster than `powershell.exe -command Get-Clipboard`, and supports line break conversion.
So this package can provide some values to others.

Add pasteboard (pbcopy/pbpaste)

---

bucket/flutter.json

- Closes #4023
Also, change the `autoupdate` strategy to adapt the new versioning manner while keeping the compatibility with former versioning manners.
This is implemented by just make the matching of `delim` and `build` optional and incorporate the character `v` in the `version`.

flutter: Update to version 1.17.2

---

bucket/keepassxc.json

- Closes #4395 
Since version 2.6.0 KeePassXC stores its portable configuration in the 'config' folder. Which makes it very convenient to persist.

keepassxc@2.6.0: Persist config folder

---

bucket/pdfsam-visual.json

Hey guys. I add a new software pdfsam-visual. But when I install it, I encounter a problem below.
```
Installing 'pdfsam-visual' (2.1.7) [64bit]
Loading pdfsam-visual_2.1.7-windows_x64.zip from cache
Checking hash of pdfsam-visual_2.1.7-windows_x64.zip ... ok.
Extracting pdfsam-visual_2.1.7-windows_x64.zip ... done.
Linking ~\scoop\apps\pdfsam-visual\current => ~\scoop\apps\pdfsam-visual\2.1.7
Creating shim for 'PDFsam Visual'.
Can't shim 'PDFsam Visual.exe': File doesn't exist.
```
If you can help, please feel free to modify this PR.

pdfsam-visual: Add version 2.1.7

---

bucket/dnspy.json

dnspy was deprecated in 5743104bd3e8200cc29f6a28df3b5ff37ff2caa7 because version 6.1.5 was identified as a virus and therefore the downloads were removed, see https://github.com/0xd4d/dnSpy/issues/1493#issuecomment-654166657
Now, the new version 6.1.6 is back in the GitHub releases.
The dnSpy-netcore-win32.zip for version 6.1.6 file is flagged by Chrome as dangerous, though. :-/ The 64-bits version is OK.

dnspy: Update to version 6.1.6

---

bucket/MagicaVoxel.json

The **-alpha** had been dropped from the versioning for some time now.

MagicaVoxel: Update to version 0.99.6

---

bucket/chromium.json

The folder name seem to have changed as the -1 suffix was dropped in the latest version.

chromium@84.0.4147.125: Fix installation

---

bucket/standardnotes.json

The URL changed:
OLD: https://github.com/standardnotes/desktop/releases/download/v3.4.2/standard-notes-setup-3.4.2.exe
NEW: https://github.com/standardnotes/desktop/releases/download/v3.4.2/standard-notes-3.4.2-win.exe

standardnotes@3.4.2: Fix url

---

bucket/clumsy.json

clumsy makes your network condition on Windows significantly worse, but in a managed and interactive manner. 
Fantastic for network testing games or other software

clumsy: Add version 0.2

---

bucket/winsshterm.json

- Closes #4635
Starting with version 2.12.0, there is also a 64-bit version available. The architecture of WinSSHTerm must match the architecture of PuTTY.

winsshterm: Add 64-bit architecture

---

bucket/markdown-monster.json

Use the full installer and use official release Source location as well as an official release file.

markdown-monster: Update to version 1.23.17.3

---

bucket/authy.json

The package name is now authy-$version-full.nupkg, so I have changed the regex in checkver and the file name in urls in autoupdate and remived the unnecessary bin part.

authy: Update to version 1.8.3

---

bucket/deskpins.json

- Closes #4628
**DeskPins** ([homepage](https://efotinis.neocities.org/deskpins/)) is a tool used to make any application topmost, that is, to keep it above all other windows.
Notes:
* **license**: ~The MIT license can be found at `license.txt` of [the source code package](https://efotinis.neocities.org/downloads/efotinis-deskpins-e3caef22897e.zip)~. Use "Freeware" instead.
* **persist** is not needed because DeskPins stores its config data at `HKCU:\SOFTWARE\Elias Fotinis\DeskPins`.

deskpins: Add version 1.32

---

bucket/antidupl.net.json

- Closes #4579
**AntiDupl.NET** ([homepage](https://ermig1979.github.io/AntiDupl/english)) ([Github repo](https://github.com/ermig1979/AntiDupl)) is a utility for finding duplicate images.
Notes:
* **naming** of the package: I named the package as `antidupl.net`. (following the pattern of `paint.net` and `database.net`)

antidupl.net: Add version 2.3.10

---

bucket/windows95.json

* **"Windows95"** ([Github repo](https://github.com/felixrieseberg/windows95)) is a Windows 95 emulator running in an Electron app.
* **persist** is not needed because "Windows 95" stores its config data at `$Env:AppData\windows95`.

windows95: Add version 2.2.2

---

bucket/macintosh.js.json

* **macintosh.js** ([Github repo](https://github.com/felixrieseberg/macintosh.js)) is a Macintosh Quadra (1991) emulator.
* **persist** is not needed because *macintosh.js* stores its config data at `$Env:AppData\macintosh.js`.

macintosh.js: Add version 1.0.6

---

bucket/ytmdesktop.json

- Closes #4724
The author of ytmdesktop has apparently decided with version `1.13.0` (latest) to hyphenate the setup executable name.

ytmdesktop@1.13.0: Fix URL

---

bucket/android-studio.json

Now that ScoopInstaller/Main#1362 has been merged, we can suggest the new SDK instead.

android-studio: Suggest android-clt

---

bucket/structurizr-cli.json

Add manifest for [Structurizr CLI](https://github.com/structurizr/cli) v1.4.2
[Structurizr](https://structurizr.com/help/about) is a collection of tooling to create software architecture diagrams and documentation based upon the [C4 model](https://c4model.com/).
[Structurizr CLI](https://github.com/structurizr/cli) is a command line interface to push/pull workspaces to/from the Structurizr cloud service/on-premises installation, and export views to PlantUML, Mermaid, and WebSequenceDiagrams formats. 
Test results
:white_check_mark: Should install structurizr-cli from the manifest file (previous version).
```
> scoop install .\bucket\structurizr-cli.json
Installing 'structurizr-cli' (1.4.1) [64bit]
Loading structurizr-cli-1.4.1.zip from cache
Checking hash of structurizr-cli-1.4.1.zip ... …
```

structurizr-cli: Add version 1.4.2

---

bucket/qmk-toolbox.json

QMK toolbox is the main program used by newer users of the QMK firmware, who mainly just use a web interface to customize their keyboard layout, and then use qmk toolbox to flash this new firmware to their boards.

qmk-toolbox: Add version 0.0.20

---

bucket/q-dir.json

Opened tabs are stored in the file not listed in the persistent section.
Q-DIr is happy with the empty _start.qdr_ and at it's updated at the first start

q-dir: Persist start.qdr

---

bucket/fvim.json

This adds a frontend for neovim built with F# + Avalonia. I use this one a lot so I figured I'd add it to scoop to keep it updated more easily

fvim: Add version 0.2.277

---

bucket/vnote.json

The old homepage (https://tamlok.github.io/vnote/) is no longer available.

vnote: update homepage

---

bucket/cura.json

Somehow version numbers are weird in this release as "4.8" and "4.8.0" occurs in the URL. I think we will need to wait for the next release if this becomes the new norm, or if it was a one-time glitch. For now, I changed the link manually as autoupdate failed.

cura: Update to version 4.8.0

---

bucket/cfssl.json

- Closes #5104
The `cfssl` is really a suite of utilities including `cfssl-bundle`, `cfssl-certinfo`, `cfssl-newkey`, `cfssl-scan`, `cfssljson`, `mkbundle`, `multirootca`. I've include them all in the `url`, `bin`, and `hash`
However, `autoupdate` only recognizes and updates the hash for the base app `cfssl`, but not the other utilities, even thought they are in the `autoupdate.hash` file
Do I:
1. Make individual app manifest for each utility, and have them listed as `depends/suggest` on `cfssl`?
2. Is there a special configuration I am missing for this use case?

cfssl: Add version 1.5.0

---

bucket/anaconda3.json

- Closes #5168
- [https://repo.continuum.io](https://repo.continuum.io) redirects to [https://repo.anaconda.com](https://repo.anaconda.com) now. The latter should be more consistant.
- Installers are (no longer) ordered by released date on the [file index page](https://repo.anaconda.com/archive/). This made the manifest ["update" to `v2.0.0`](https://github.com/lukesampson/scoop-extras/commit/c8cc5073c24c09968072dda537832623c9721b85), which was released on 2014-05-27. Use the official document page instead.

anaconda3: Update to version 2020.11

---

bucket/deepgit.json

- Closes #5202 
The syntax error in the JSON file prevents installation.

deepgit: Fix manifest

---

bucket/geekbench.json

- Closes #5185
GeekBench only provides x64 and arm64 binaries now. The thing is that they share the same name when viewed by 7z, so normally arm64 binaries will overwrite x64 ones while extracting.

geekbench: Fix manifest

---

bucket/dukto.json

- Closes #5157
Provide no `autoupdate` as it is no longer maintained. ([homepage](https://www.msec.it/blog/dukto/))

dukto: Add version 6

---

bucket/playnite.json

The last few playnite version were not released on github. For this reason the version is lacking behind in this bucket. To fix this a changed the `checkver` url to the current release site and added the required regex

playnite: Update to version 8.10

---

bucket/panwriter.json

Note, technically pandoc is not required but [homepage](https://panwriter.com/) says
> You also have to install pandoc to export to most formats.
That's why I put pandoc in "depends', without it the app is not so useful.

panwriter: Add version 0.6.5

---

bucket/dasel.json

Use single selector DSL to query many of the data formats.
Demo:

dasel: Add version 1.8.0

---

bucket/meshlab.json

meshlabserver.exe is not in the released zip file.

meshlab@2020.12: Fix installation

---

bucket/imageglass.json

It seems that ImageGlass only provides 64bit builds since version 8, and the `32bit` key is preventing auto-update.

imageglass: Update to version 8.0.12.8

---

bucket/plantuml.json

- Closes #5336
- Closes #5335
- Closes #5332
- Closes #5331
When we use plantuml.cmd with command line option(s),
they will be added after an option for graphviz (dot).
If we use "-headless" option, it always shows
"Warning: -headless flag must be the first one in the command line".

plantuml: Fix shim parameters handling.

---

bucket/dont-sleep.json

Fixed hashes of [Don't Sleep](https://www.softwareok.com/?Download=DontSleep) v7.71 as reported by the author website.

dont-sleep: Hash fix

---

bucket/php-nts-xdebug.json
bucket/php-xdebug.json

Update php-xdebug to match PHP version in the main bucket. fixes #5269

php-xdebug: Update to version 3.0.1-8.0

---

bucket/darktable.json

Checked, seems to work okay, and the hash matches the one found in https://github.com/darktable-org/darktable/releases/tag/release-3.4.0

Update darktable to 3.4.0

---

bucket/workspacer.json

workspacer has moved to GitHub Actions.

workspacer: Update to version 0.9.10

---

bucket/winfetch.json

This PR fixes #5359.
The `winfetch.ps1` file was renamed to `posh-winfetch.ps1`.
It also downloads the `posh-winfetch.ps1` file directly as it is not dependent on anything else in the repo.

Fix winfetch.json

---

bucket/taskbarx.json

This also accounts for the split in the architecture of the new versions of the app. The auto-update URL has also been added to account for the different versions.

taskbarx: Update to version 1.6.3.0

---

bucket/jabref.json

jabref: Add version 5.1

---

bucket/openshot.json

Fix: https://github.com/lukesampson/scoop-extras/issues/5476
`launch-win.bat` uses for debug, see https://github.com/OpenShot/openshot-qt/blob/8dffb2cd507e93576d24b671927e247614264c02/freeze.py#L185-L186

openshot: Use native executable as shortcut target

---

bucket/jellyfin.json

Hi,
Jellyfin is a open source fork of Emby, a media server similar to Plex.
This is my first manifest, so I am happy about any feedback I can get.
Also, please squash and merge these changes (if you don't do this anyway) when ready, as my commits are small and many.

jellyfin: Add version 10.6.4

---

bucket/streamlink.json

I don't entirely understand what was going on previously with concatenating python and stuff together but the 2.0.0 zip file includes the needed .exe files so I have removed the concatenation.

streamlink: Update to version 2.0.0

---

scripts/tortoisesvn/tortoisesvn-install.reg.templ

TortoiseSVN installs TortoiseOverlays by default to `D:\scoop\apps\tortoisesvn\current\Common\TortoiseOverlays`, but the registry file that is generated points to `D:\scoop\apps\tortoisesvn\current\TortoiseOverlays`. This PR fixes that.

TortoiseSVN: Fix path to TortoiseOverlays

---

bucket/pskubectlcompletion.json

This can be use to enable kubectl auto-completion for PowerShell

pskubectlcompletion: Add version 1.0.4

---

bucket/darktable.json

3.4.1 is no longer valid.
https://github.com/darktable-org/darktable/releases/download/release-3.4.1/darktable-3.4.1-win64.exe - is no longer available.
```ERROR Download failed! (Error 3) Resource was not found```

darktable@3.4.1: Fix URL

---

bucket/musescore.json

- Closes #5684 
- Closes #5670
- Closes #5692 
- Closes #5721
autoupdate urls now use `$matchHead.`
I'm not 100% sure about how futureproof it's gonna be but it should work for conventional version numbers for now.

musescore@3.6.2.548021803: Fix URL

---

bucket/gpu-z.json

- Closes #5741
- Closes #5743
- Closes #5744 
- Closes #5745 
- Closes #5746
- Closes #5751
`nl1` doesn't work anymore (for some reason), but `us2` works.

gpu-z@2.37.0: Fix URL

---

bucket/aws-nosql-workbench.json

This PR adds a manifest for AWS's NoSQL Workbench application.
NoSQL Workbench is a 64-bit Electron-based desktop app (similar to [draw.io Desktop](https://github.com/lukesampson/scoop-extras/blob/master/bucket/draw.io.json)) that aids in designing and modeling NoSQL databases for the [Amazon DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/workbench.html) and [Amazon Keyspaces](https://docs.aws.amazon.com/keyspaces/latest/devguide/workbench.html) cloud database services.
The manifest has support for version detection, auto-update, and hash file parsing.

aws-nosql-workbench: Add version 2.2.0

---

bucket/kdiff3.json

The KDiff3 repository had been moved to KDE's GitLab.
Also, there was a download link for the stable version at `download.kde.org`, so I changed to download it from there.

kdiff3: Update to version 1.8.5

---

bucket/vieb.json

I'd like to add very promising browser [Vieb](https://vieb.dev/). I use that day to day and would be great to have Scoop packages for it. 
I have tested installation and update process with my own test bucket under https://github.com/run2cmd/scoop-test-bucket

vieb: Add version 4.0.0

---

bucket/quicktextpaste.json

Updated latest hash from https://www.softwareok.com/?Download=QuickTextPaste
ERROR:
Checking hash of QuickTextPaste_x64_Portable.zip ... ERROR Hash check failed!
App:         extras/quicktextpaste
URL:         https://www.softwareok.com/Download/QuickTextPaste_x64_Portable.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    c73e5b827ea64253caf190f1d558f1d65268e5ae4938db3e76c84a5b479e357b
Actual:      c79d6043307cb7fb6903195c70feb473de3751147501d865bb49bb1f5826c966
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=quicktextpaste%407.01%3a+hash+check+failed

quicktextpaste@7.01: hash fix

---

bucket/openclosedriveeject.json

Updated latest hash from https://www.softwareok.com/?Download=OpenCloseDriveEject.
ERROR:
Checking hash of OpenCloseDriveEject_x64.zip ... ERROR Hash check failed!
App:         extras/openclosedriveeject
URL:         https://www.softwareok.com/Download/OpenCloseDriveEject_x64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    ec16debb30c5d87c53496328d733ea61be9585d2a7a5774f9726f4085e78fcd3
Actual:      1e336e880e9b0e335858e3e9b3875e90e1b997da658fe551ebfd9f63b5903e0f
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=openclosedriveeject%402.12%3a+hash+check+failed

openclosedriveeject@2.12: hash fix

---

bucket/rtss.json

There is an OverlayEditor plugin in version 7.3.0 which saves overlays to `Plugins\Client\Overlays\` (even if you choose another directory). I've added it to persist.
Checkver was disabled in commit https://github.com/lukesampson/scoop-extras/commit/d1fa5192c3268bd9e3d130413de0521d0a532a0c. I didn't touch it.

rtss: Update to version 7.3.1

---

bucket/shadowsocks.json

Fix build number syntax in archive name

shadowsocks: Update to version 4.4.0.185

---

bucket/netch.json

- Closes #6016
In the netch v1.8.3 released archive, the top-level directory exists again.

netch@1.8.3: Fix installation

---

bucket/amazon-workspaces.json

This manifest installs amazon workspaces client.
Amazon unfortunately does not publish the full historic list of clients. so I scan for the version number change and then we just install the latest version downloaded from the same url.

amazon-workspaces: Add version 3.1.6.2064

---

bucket/flameshot.json

* Closes #5631
The portable archive name only has the format`flameshot_portable-$version-win64.zip` since `0.9.0`.
It had the format `flameshot-$version-win64.zip` in older versions, so it is uncertain that the format will remain the same in the future.

flameshot: Add version 0.9.0

---

bucket/nimbletext.json

This app currently fails to install. The manifest is broken in a few ways:
- Download URL no longer supports http. Must use https.
- Current downloadable version is 3.1.0.33266, not 3.1.0.17465 because....
- The version notes page used for checkver/autoupdate is broken (for quite a while), so useless.
This PR fixes the above issues.

nimbletext@3.1.0.33266: Adopt HTTPS urls

---

bucket/chatterino.json

The website had a redesign, <https://chatterino.com/download/> is now a page that only shows old versions, while the latest version is now visible on <https://chatterino.com/>

chatterino: Update to version 2.3.1

---

bucket/hydrus-network.json

Hydrus Version 441 moved "Hydrus Network" to a "windows" sub-directory.

hydrus-network@441: Fix installation

---

bucket/sublime-text.json

Few things going on here:
* `https://www.sublimetext.com/4` does not exist, hence why the `homepage` had to be changed
* It's not clear if they just haven't set this page up yet (v4 was released yesterday) or they will not create it
* `checkver` now grabs the latest version directly from `https://www.sublimetext.com/updates/4/stable_update_check`.
* The newest build 4107 doesn't have a "semver" compliant version
* The archives are now named differently on their fileserver

sublime-text: Update to version 4-4107

---

bucket/dbeaver.json

The older download URL targeting at `dbeaver.io/files` seems no longer valid

dbeaver@21.1.1: Fix URL

---

bucket/wsl-ssh-pageant.json

- Closes #3885
<https://github.com/benpye/wsl-ssh-pageant/releases/tag/20201121.2>

wsl-ssh-pageant: Update to version 20201121.2

---

bucket/interlink.json

Interlink is an email client based on the mozilla/xul platform.
By default it stores settings/accounts in appdata so don't see reason for persist.

interlink: Add version 52.9.7762

---

bucket/crystaldiskmark.json

Update the start menu shortcut name to be consistent with [scoop-extras/crystaldiskinfo](https://github.com/lukesampson/scoop-extras/blob/master/bucket/crystaldiskinfo.json)

crystaldiskmark: Adjust shortcut name

---

bucket/nicotine-plus.json

A "graphical client for the Soulseek file sharing network": https://github.com/nicotine-plus/nicotine-plus

nicotine-plus: Add version 3.1.1

---

bucket/actionlint.json

:octocat: Static checker for GitHub Actions workflow files.
It is useful for every GitHub Actions users and work well on Windows, too.

actionlint: Add version 1.5.3

---

bucket/sysinternals.json

to fix error when launch autoruns with shortcut:

sysinternals: Fix Autoruns shortcut

---

bucket/altair.json

- Closes #6882
This PR fixes the download URL for the altair windows executable which was renamed to include `_x64` in version `4.0.10`.
| Version| Filename |
| --- | ----------- |
| `<=4.0.9` | altair_4.0.9_win.exe |
| `>=4.0.10` | altair_4.0.10_x64_win.exe |
In addition, the repository has been moved from https://github.com/imolorhe to https://github.com/altair-graphql.

altair@4.0.11: Fix URL

---

bucket/tumblthree.json

fix https://github.com/ScoopInstaller/Extras/issues/7193
> Note: The zip files no longer contain a root folder.
https://github.com/TumblThreeApp/TumblThree/releases/tag/v2.2.0

tumblthree: Fix `extract_dir`

---

bucket/robo3t.json

- Sets `checkver` to check the Github repo and sets custom regex to capture the commit hash value.
- Update to 1.4.4

robo3t: update to 1.4.4

---

bucket/text-grab.json

[Text-Grab](https://github.com/TheJoeFin/Text-Grab) is a minimal Windows utility which makes all visible text available for copy and paste. It accomplishes this locally with the Windows 10/11 OCR API.

text-grab: Add version 2.3

---

bucket/foobar2000-portable.json

Foobar2000 version 1.6 introduced new 'profile' directory for portable mode. From changelog:
> New portable install puts all configuration data in 'profile' subfolder of install folder instead of saving in the installation folder directly. Doesn't affect upgraded installs or non-portable.
The playlist directory in current version is named 'playlists-v1.4', not 'playlist-v$shortVersion', so playlist migration is completely broken in current manifest.
In current PR I changed persist to use new 'profile' directory. Also in 'post_install' section after scoop will create 'profile' directory, I renamed playlists to 'playlists-v1.4' and moved all files to 'profile' directory. 'playlists' directory was always created, so it should be pretty reliable condition to trigger migration from previous …

foobar2000-portable: use profile for persist

---

bucket/grepwin.json

Noticed that grepWin didn't get updated for quite a while, probably due to missing checkver.
Wanted to automate this using the Github repository with a small change - this should pick up the correct hashes at next update cycle.

grepWin: Add checkver for automated updates

---

bucket/bitwarden.json

When an update is present and scoop is late, a popup propose to update bitwarden. But this installation will end in program files.... So not really what we want here.
The post install delete the file used to check if there is an update. So now, should use scoop to update. No more popup

Add postinstall to remove autoupdate file

---

bin/checkver.ps1

Reverts ScoopInstaller/Extras#7223

Revert "fix(checkver): use `scoop prefix` to correctly find scoop's path"

---

bucket/xampp.json

close #3570
**XAMPP** ([homepage](https://www.apachefriends.org/)) is an Apache distribution containing MariaDB, PHP, and Perl.
Notes:
* If there are more files that needs to be in *bin* / *shortcut* / *persist* , please tell me.
* The Portable Version **does not** contain *FileZilla FTP* and *Mercury Mail Server*. The service installations are also disabled. I tried to extract files from the non-portable installer, but the installer could not be properly extracted by *7-zip*, *innounp* or *Uniextract*.
* `vcredist2017` is required according to the readme file.
> PHP in this package needs the Microsoft Visual C++ 2017 Redistributable package from
http://www.microsoft.com/en-us/download/. Please ensure that the VC++ 2017 runtime
libraries are installed on your system.
Since Visual C++ …

xampp: Add version 8.0.12-0

---

bucket/foxit-reader.json

Foxit has renamed most of their products, see https://www.foxit.com/.
> Foxit has changed some product names. To learn more click here.
"Foxit Reader" is now called "Foxit PDF Reader". How are changes like this handled usually?
- create a separate manifest `foxit-pdf-reader.json`
- rename the manifest file
- just keep using the old manifest

foxit-reader: Deprecate manifest in favour of foxit-pdf-reader

---

bucket/capframex.json

Currently breaks with `Can't shim 'CapFrameX.exe': File doesn't exist.` because the files are now in a folder.

capframex: Add extract dir

---

bucket/ilspy.json

add missing autoupdate
close https://github.com/ScoopInstaller/Extras/issues/6293
@rubenprins could you check this once?
I personally don't use ILSPY

ilspy: update to 7.1.0.6543

---

bucket/retroarch.json

Fix hash for 1.9.13 to SHA256 digest. Verified new values against downloads.
Closes #7277

retroarch: hash fix

---

bucket/lazarus.json

Closes #7268
Tested on Windows 10.0.19042.1348 with system default PowerShell (5.1.19041 .1320)
I noticed the updater regex was also 64bit-only and changed it too. Since lazarus updates infrequently, this could only be tested at a PowerShell prompt, like so:
```powershell
$re = "lazarus-([\d.]+)-fpc-(?<fpc>[\d.]+)-win(64|32)\.exe"    
$urlx64 = "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Windows%2064%20bits/Lazarus%202.0.12/lazarus-2.0.12-fpc-3.2.0-win64.exe"
$urlx86 = "https://downloads.sourceforge.net/project/lazarus/Lazarus%20Windows%2032%20bits/Lazarus%202.0.12/lazarus-2.0.12-fpc-3.2.0-win32.exe"
$urlx64 -match $re                                                                                                                   
$urlx86 -match $re
```

lazarus: Don't hardcode path to fpcmkcfg.exe in post-install script

---

bucket/lite-xl.json
bucket/lite.json

Homepage:
- Lite: https://github.com/rxi/lite
- Lite XL: https://lite-xl.github.io
Lite's last release is 1.11, and has stopped development from July, 2020, so there is Lite XL, an enhanced version of Lite.
Closes #4494
Supercedes #4612

lite-xl: Add version 2.0.3

---

bucket/gimp.json

The installer script in this manifest has a broken regex. It currently leaves a broken path to the bundled python interpreter. This PR corrects the regex, at least for the latest version of GIMP's file.
This change has been tested locally.

gimp: Fix broken regex in installer script

---

bucket/gimp.json

GIMP 2.10 stores settings in %APPDATA%\GIMP, not in the "etc\gimp" and "share\gimp" folders. Scoop persists these folders, but user settings will never be stored in them. They merely hold the standard brushes, patterns, etc. They needn't and shouldn't be persisted.
The change presented in this PR should not break any existing user's install since GIMP will have been storing all their settings already in %APPDATA%.
I am hoping that GIMP one day offers a proper [portable ZIP archive](https://gitlab.gnome.org/GNOME/gimp/-/issues/2861) so that this rather inelegant manifest can be simplified...

gimp: Remove persisted folders

---

bucket/brave.json

Installing `brave` installs a 2 year old version of version where autoupdate is broken which is a potential security risk. Updated Brave to 1.31.87 which is the last version I found that can be installed as portable.

Update Brave Browser version

---

bucket/vscode-insiders.json

This PR corrects some old script URLs that pointed to the previous repos maintained by `lukesampson` to the current repo, which was causing installation to fail with a 404.
Might be worth doing a find-replace on all of the JSONs in this repository and making the same fix.

Fix old path in vscode-insiders.json that was blocking installation

---

bucket/colorcontrol.json

[ColorControl](https://github.com/Maassoft/ColorControl) is a useful tool to change NVIDIA display settings and control LG TV.

colorcontrol: Add version 4.1.0.0

---

bucket/firefox-beta.json

The firefox-beta version did not update anymore and the checkver URL showed no new builds. This PR should resolve the issue and provide the latest beta version as of now (95.0b7).
Closes #7342

Update the checkver URL for firefox-beta as no updates were available anymore

---

bucket/mpc-hc-fork.json

The active playlist file should carry over just like the other configuration files that are already persisted.

mpc-hc-fork: persist default.mpcpl like mpc-be.json does it

---

bucket/bat2exe.json

Makes [bat2exe](https://www.bat2exe.net/) ([github](https://github.com/islamadel/bat2exe)) available via scoop extras

bat2exe: Add version 2.0

---

bucket/bt.json

Makes [Browser Tamer](https://www.aloneguid.uk/projects/bt/) available via scoop extras.

bt (Browser Tamer): Add version 2.1

---

bucket/ghidra.json

Ghidra is a software reverse engineering (SRE) framework

ghidra: Add version 10.0.4-20210928

---

bucket/ghidra.json

Multiple modules collided with same name because of the persist dirs. Here is the error message:
```
Exception in thread "main" ghidra.util.exception.AssertException: Multiple modules collided with same name: Public_Release   
$dir\Ghidra\Configurations\Public_Release
$dir\Ghidra\Configurations.original\Public_Release
at utility.module.ModuleUtilities.findModules(ModuleUtilities.java:162)
at ghidra.GhidraApplicationLayout.findGhidraModules(GhidraApplicationLayout.java:210)
at ghidra.GhidraApplicationLayout.<init>(GhidraApplicationLayout.java:70)
at ghidra.GhidraLauncher.main(GhidraLauncher.java:52)
```

ghidra: Fix exited with error after update

---

bucket/linqpad.json

`autoupdate` will be valid in scoop core's new autoupdate feature.

linqpad: Update to 7.1.4

---

bucket/streamlink.json

Update [streamlink](https://streamlink.github.io/) to [3.0.1](https://github.com/streamlink/streamlink/releases/tag/3.0.1). (Previously it was [2.0.4](https://github.com/streamlink/streamlink/releases/tag/2.4.0))
Sorry. This pull request is not an existing issue. If I need to create an issue first, close this pull request.

streamlink: Update to version 3.0.1

---

bucket/flameshot.json

Seems like they changed the ZIP archive structure... so add the additional folder path...
Closes #7355

flameshot: Fix "extract_dir"

---

bucket/firefox.json

- Updates to version 94.0.2.
- Not fetched by checkver since Mozilla hasn't updated their release notes, but the news broke on the Neowin software page on nov 18th and it was added to the archive page used in the manifest in the evening of nov 19th.

Update firefox.json: v94.0.2

---

bucket/winrar-helper.json

Will be used in #7388. (as a workaround for the extraction failure mentioned in #7338)
This adds an **WinRAR** "helper" package, which is identical to `winrar` package, but without bin/shortcut.
This is an alternative to `"depends:extras/winrar"`, as it can avoid some confusing situations for end-users.
Most people have their WinRAR installed through other means. If we silently install another WinRAR without asking the user, people may complain about it.
(Why there are 2 WinRARs? Why my WinRAR suddenly turn into English rather than my localized version?)
With this helper package, we can extract the files using *WinRAR* without affecting the users, and always keep this "helper" WinRAR updated.

winrar: Add 'helper' package

---

bucket/touchcursor.json

[Touchcursor](https://martin-stone.github.io/touchcursor) is a hidden gem for windows programming productivity.
> **TouchCursor** lets you use the home keys as cursor keys – in all Windows programs – keeping your fingers in the best position for fast typing. It's free and open-source.
Let me know if you see something to change.

touchcursor: Add version 1.7.1

---

bucket/geogebra.json

Relates to https://github.com/ScoopInstaller/Versions/pull/323#issuecomment-976392477 where we discussed adding the current version of GeoGebra.
One caveat to the manifest - checkver will need to be edited once the next major release arrives (7.0) due to the way it gets the latest version from the website. The website also has "5-0-676-0" as the latest version for the 6.0 release (!!) so my regex should be able to adapt once they fix that (I sent them an email about it).

Add GeoGebra version 6.0.676.0

---

bucket/potplayer.json

Added Module Directory to persist.
Closes #6544

potplayer: Add 'module' folder to persist

---

bucket/imageglass.json

Used `checkver.ps1` ​from [autoupdate guide](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate) to update imageglass
Fixes: #7412

imageglass: Update to version 8.3.11.21

---

bucket/paperwork.json

`checkver` is a bit ugly because the jsonpath implementation does not allow selecting multiple fields which would make the regex simpler. Currently it heavily relies on the format of the Gitlab API response.

paperwork: Add version 2.0

---

bucket/sysinternals.json

sysinternals: fix disk2vhd in 64-bit architecture  installation

---

bucket/autohotkey2.json

Adds AutoHotkey v2 beta
I've copied&pasted the main AutoHotkey manifest, updated all the links to version 2 (with a nice bonus of not relying on GitHub) and tested via both installing `2.0-beta.2` and `2.0-beta.3` and autoupdating `2.0-beta.2` manifest to `2.0-beta.3` with checkver
To avoid conflict with v1 I've added a rename rule `AutoHotkey` `32`/`64` `.exe`→`autohotkey2.exe` to install a single executable without installing the original `32`/`64`, so you could have 
- `autohotkey` `32`/`64` `.exe` and `autohotkey.exe` from `autohotkey.json` manifest and
- `autohotkey2.exe` from this manifest,
though I guess in some distant future it should just override the first version and manifests be merged into one. Or maybe not since it's worthwile keeping both versions installed as you'll see …

autohotkey: add version 2.0-beta.3

---

bucket/dumo.json

The update to the latest version 2.24.1.119 in 8ed1c45433a1b1dd76d9b2e027da33c12f51b00c did not include the new hash and thus fails to install.

dumo: hash fix

---

bucket/playnite.json

Closes #7463
Relates to #4919, #5088, #5093
----
The issue raised by @Ash258 (https://github.com/ScoopInstaller/Extras/pull/5093#pullrequestreview-528583580) is no longer valid, as Playnite now has a fully working built-in extension update mechanism and UI.

playnite: Persist Extensions folder

---

bucket/wireshark.json

The autoupdate functionality in the Wireshark manifest is broken due to a filename change which now include "32" suffix to the  downloadable file.
This PR fixes the manifest and updates Wireshark to the latest version.

Fix Wireshark autoupdate and update version to 3.6.0

---

bucket/transmission.json

All of the command line utilities was missing from the manifest.
`checkver`  used Github to check for version change, but that is not reliable, when getting the hash from an external file, as they can update at different times. Change to use to the version time in the file where we get the hash for a more robust update approach.

transmission: Add CLI, update checkver

---

bucket/youtube-dl-gui.json

The current youtube-dl-gui release is very out of date, with the last release being from 2017. The maintained fork by @oleksis supports yt-dlp and has a lot more additional features, with the last release being yesterday.

Swapped yt-dlg to the maintained fork by @oleksis

---

bucket/glimpse.json

I don't know how to handle the `0.2` instances better in autoupdates (matching on GitHub version results?), but here's a patch anyways. (It's still correctly automatic on point releases, like the upcoming 0.2.1.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lukesampson/scoop-extras/4842)

glimpse: Add version 0.2.0

---

bucket/xnviewmp.json

Closes #7199
Back porting relevant parts from https://github.com/ScoopInstaller/Main/pull/2936

XnViewMP: Fix xnview.ini creation and persistence in certain cases

---

bucket/rtss.json

See https://github.com/ScoopInstaller/Extras/pull/7513
I added an autoupdate section with the given URL, updated the json to use the latest version of RTSS  and tested if everything works which it does.

rtss: Add autoupdate, Update to version 7.3.3

---

bucket/josm.json
bucket/pyzo.json

Review warranted as this is my first attempt at adding a package to Scoop. Local install of 64bit was successful on my machine with:
scoop install .\bucket\pyzo.json

Pyzo: Add version 4.11.7

---

bucket/php-nts-xdebug.json
bucket/php-xdebug.json

As #7526, updates xdebug to PHP8.1, since `php` version goes to 8.1 now.
Except this time from a branch, following feedback provided from @rashil2000, thanks!

php(-nts)-xdebug: Update to version 3.1.2-8.1

---

bucket/everything-lite.json
bucket/everything.json
scripts/everything/install-context.reg
scripts/everything/uninstall-context.reg

This enables user to right-click on folders to search files using **Everything**.
see [extras/grepwin](https://github.com/ScoopInstaller/Extras/blob/master/bucket/grepwin.json) for similar example.
**NOTE**: PR check will fail because the **.reg** files are not merged yet.

everything(-lite): Add right-click context menu

---

bucket/vcredist.json

This updates the package and adds **vcredist 2022** support.
**vcredist 2022** provides runtime support for VC 2015, 2017, 2019 and 2022. Therefore we only need to replace the 2019 package with the 2022 one.
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
> Visual Studio 2015, 2017, 2019, and 2022
This table lists the latest supported English (en-US) Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022. The latest supported version has the most recent implemented C++ features, security, reliability, and performance improvements. It also includes the latest C++ standard language and library standards conformance updates. We recommend you install this version for all applications created using Visual Studio 2015, …

vcredist: Update to vcredist2022

---

bucket/vcredist.json
bucket/vcredist2005.json
bucket/vcredist2008.json
bucket/vcredist2010.json
bucket/vcredist2012.json
bucket/vcredist2013.json
bucket/vcredist2015.json
bucket/vcredist2017.json
bucket/vcredist2019.json
bucket/vcredist2022.json

This adds **text for exit codes**, such as `A restart is required to complete the installation`, 
rather than just showing `ERROR: exit code is 3010`. 
This will be helpful for letting users know what is going on.

vcredist packages: Add text for exit codes

---

bucket/qt-creator.json

Latest versions of qt creator do not support x86 so removed the autoupdate
Closes #7548

qt-creator: Add version 6.0.1

---

bucket/autohdr.json

This is a manifest for the project AutoHDR by Codectory [here](https://github.com/Codectory/AutoHDR).
I wanted to create a pre-install section to persist UserSettings.json as a hardlink, but I didn't manage to do it by taking inspiration from [flycast.json](https://github.com/Calinou/scoop-games/blob/master/bucket/flycast.json) in the Scoop Games bucket and do something similar to:  
"pre_install": "if (!(Test-Path \"$persist_dir\\UserSettings.json\")) New-Item -ItemType File \"$dir\\UserSettings.json\" | Out-Null",
It's just throwing errors - so someone who knows better is most welcome to figure that one out with me.
Apart from that it should work just fine.

Create autohdr.json: For Codectory's AutoHDR project

---

bucket/cryptomator.json

Currently Cryptomator.cfg is being persisted, which should be altered on every new version from the looks of it.
The script is already updating the Cryptomator.cfg to read from just the ./data dir, and is stored there.
Fixes #7551

cryptomator: Remove Cryptomator.cfg from persist

---

bucket/gpxsee.json

As for config persistence, this project is using Qt5 and QSettings to store and manage user preferences. QSettings uses the Windows registry on Windows platforms which I am not able to capture in the manifest. The only other sort of persistence is the tile cache in AppData/Local (also not captured).

gpxsee: Add version 10.0

---

bucket/scoop-completion.json

This can be use to enable scoop auto-completion command for PowerShell

scoop-completion: Add version 0.2.3

---

bucket/compatibility-manager.json

A Windows app for bulk editing compatibility settings.

compatibility-manager: Add version 1.1.2

---

bucket/proxifier-portable.json

proxifier-portable: Update to version 4.07
The latest version of proxifier-portable is 4.07 and in bucket is 3.42. So, I updated it to the latest version.
Closes #7577

proxifier-portable: Update to version 4.07

---

bucket/inkscape.json

Closes #6912
- Updates to version 1.1.1
- Removes hash because it's not provided for compressed releases
- Fixes autoupdate using a script inspired by [Chocolatey's](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/inkscape/update.ps1)
- Changes 32bit from 7z to .paf.exe because compressed release not provided
---

Update Inkscape to 1.1.1 and fix autoupdate

---

bucket/cuetools.json

Bump to Version 2.1.9, download location changed to github as per http://cue.tools/wiki/CUETools_Download#Download

Cuetools: Update to version 2.1.9

---

bucket/ventoy.json

Also removed shim as it didn't work (and this is a GUI application.)

ventoy: Add 64-bit architecture, remove broken shim

---

bucket/ryzen-controller.json

close #7261
[Ryzen Controller](https://ryzencontroller.com/) is an open source utility that unleashes the power of AMD Ryzen™ laptops with an easy-to-use GUI. Tweaks can be saved as custom presets which can be enabled whenever you need extra power - or disabled when you want to keep things cool.
**NOTES**:
* This package has to be *updated manually* because the download URL is based on [Job IDs](https://gitlab.com/ryzen-controller-team/ryzen-controller/-/jobs/1710820449/artifacts/browse/dist/win/). The newly proposed *Update Handler* (#7096) may solve the problem.
* persist is not needed: config file is stored at `$Env:AppData\ryzen-controller`

ryzen-controller: Add version 2.5.4

---

bucket/gb-studio.json

- Manual changes to update to version 3.0.2
- Fixes `autoupdate` section.
Closes #7608

gb-studio: Update to version 3.0.2

---

bucket/beyondcompare.json
scripts/beyondcompare/install-context-32bit.reg
scripts/beyondcompare/install-context-64bit.reg
scripts/beyondcompare/uninstall-context.reg

Closes #1645 
* Added new reg files to associate Beyond Compare with the Windows explorer context menu based on content from the Beyond Compare support [website](https://www.scootersoftware.com/support.php?zz=kb_shellex).
* Modified installer script to notify the user about the new post install step and customize the reg file based on Scoop settings.

Added context menu items for Beyond Compare

---

bucket/impregnate.json

This pull request adds Impregnate (https://github.com/Cumcord/Impregnate), the installer for Cumcord (https://cumcord.com/).
Closes #7290

impregnate: Add version 1.2.2

---

bucket/ultravnc.json

This adds UltraVNC.
*UltraVNC Server and Viewer are a powerful, easy to use, free software that can display the screen of
one computer (Server) on the screen of another (Viewer). The program allows the viewer to use their mouse
and keyboard to control the Server Computer remotely.
UltraVNC is a VNC application that is tailored towards Windows PCs, with several features not found
in other VNC products.*
Closes #7560

ultravnc: Add version 1.3.6.0

---

bucket/keepass-plugin-keepasshttp.json

Notes:
* link to the binary is from the tree of the latest commit: https://github.com/pfn/keepasshttp/commit/b9a6813bfc9ccc9618938249c1bfff744a28ca44
* no auto update is set as author is not publishing binaries into releases
* License is GPL 3.0 but I do not know which format I should follow so I have copied it
* tested locally

keepass-plugin-keepasshttp: Add version 1.8.4.2

---

bucket/winscp.json

The `.exe` binary creates another command prompt instance while the `.com` one stays in the same one.

winscp: add commandline-friendly binary.

---

bucket/shadowsocks-v2ray-plugin.json

The very useful [v2ray plugin for shadowsocks](https://github.com/shadowsocks/v2ray-plugin).
Manually tested.

shadowsocks-v2ray-plugin: Add version 1.3.1

---

bucket/jmkvpropedit.json

JMkvpropedit is a batch GUI for mkvpropedit (part of MKVToolNix) written in Java.
Requires Java 8 or newer.
Source and downloads at:
https://github.com/BrunoReX/jmkvpropedit

JMkvpropedit: Add version 1.5.2

---

bucket/onecommander.json

Fixed license url, description, added Templates in persist, version checking improvement
Closes #7627

onecommander: Fix license URL and checkver and persist templates

---

bucket/dxwnd.json

supersedes #5015. (see old PR for more details)
**dxwnd** is Window hooker to run fullscreen programs in window and much more.
NOTES:
* Based on the content of `$dir\tweaks.ini`, I don't think this needs to be persisted.
```
[FixD3DWindowFrame]
help="Tries to prevent D3D from rendering on the whole window surface including the window border. It activates a small trick that cause the program to render to a child modal surface within the main window borders."
[NoD3DWindowMove]
help="Do not try to update the window position and size on D3D rendering. In some cases, the window may be movable but the rendering area does not move with it. In this case, avoid moving the window at all. It is an experimental feature and doesn't always work."
```
* `$dir\vcda\readme.txt` says:
```
copy to the …
```

dxwnd: Add version 2.05.78

---

bucket/totalcommander.json

Total Commander: update persistent files.
* **plugins**: default installation directory for plugins (e.g. if you open plugin archive, totalcmd by default installs it in this directory)
* **VERTICAL.BAR**, **vertical.br2**: vertical (between panels) button bar
* **contplug.ini**, **fsplugin.ini**, **lsplugin.ini**, **pkplugin.ini**: default config files for plugins settings (https://www.ghisler.ch/wiki/index.php/Ini-settings)
Unfortunately it's not the all possible files. Various plugins can use their own config files. For example SFTP plugin from Total Commander developer is using sftpplug.ini, his WebDAV plugin uses tcwebdav.ini and so on. It's the same problem as in foobar2000: #2884. So it could be better to split it to normal and portable version. But this PR should cover most cases.

totalcommander@9.51: Update persist

---

bucket/handbrake.json

This closes #3973, closes #3919
Prior to 1.1.1 the GUI version only came in exe.
Sometimes the data in the zip is in a Handbrake folder other times it's Handbrake $version, and with this release it's at the top level. It's a bit of a mess, maybe there's a more elegant way of handling it.
portable.ini might contain user settings hardware.enabled for example, and it looks like there's more planned, so that's persisted.
Not sure if I've gotten data migration right. ATM it moves data, but that might break separate non-portable installs so perhaps it should be copied instead. Temp data should only stick around if handbrake crashes, so it shouldn't need migration.

handbrake: Use portable configuration

---

bucket/youtube-dl-gui.json

close https://github.com/ScoopInstaller/Extras/issues/7494
```powershell
PS C:\Users\HUMOR> scoop config MSIEXTRACT_USE_LESSMSI false
'MSIEXTRACT_USE_LESSMSI' has been set to 'false'
PS C:\Users\HUMOR> scoop install youtube-dl-gui
Installing 'youtube-dl-gui' (1.8.2) [64bit]
Loading yt-dlg.msi from cache
Checking hash of yt-dlg.msi ... ok.
Running pre-install script...
Linking ~\scoop\apps\youtube-dl-gui\current => ~\scoop\apps\youtube-dl-gui\1.8.2
Creating shortcut for yt-dlg (yt-dlg.exe)
'youtube-dl-gui' (1.8.2) was installed successfully!
PS C:\Users\HUMOR> scoop config MSIEXTRACT_USE_LESSMSI true
'MSIEXTRACT_USE_LESSMSI' has been set to 'true'
PS C:\Users\HUMOR> scoop uninstall youtube-dl-gui
Uninstalling 'youtube-dl-gui' (1.8.2).
Removing shortcut …
```

youtube-dl-gui@1.8.2: Fix decompress error

---

bucket/playnite.json

The download URL for 9.12 is no longer works; is there a reason we're not downloading the GitHub releases?

playnite: Update 9.12 -> 9.14

---

bucket/inkscape.json
bucket/ultravnc.json
bucket/xmind.json

Closes https://github.com/ScoopInstaller/GithubActions/issues/3
Context:
> I think it's from `inkscape` checkver. it's using `$version` variable and the value is 1.1.1
Ok so this is the problem. changed it in dummy repo[^1], and then run the github action[^2], it's working[^3].
[^1]: https://github.com/LazyGeniusMan/Scoop-Test/commit/b249b7ba19186cf9da6a86beb0e79a3848fd54fa
[^2]: https://github.com/LazyGeniusMan/Scoop-Test/actions/runs/1645606185
[^3]: https://github.com/LazyGeniusMan/Scoop-Test/commits/master

inkscape, ultravnc, xmind: Change checkver conflicted variable

---

bucket/banana-cake-pop.json

Closes #XXXX
Excavator for this manifest return error code 301, so I also changed the checkver URL to the source code of the webpage in github
```
banana-cake-pop: The remote server returned an error: (301) Moved Permanently.
URL https://chillicream.com/docs/bananacakepop is not valid
```

banana-cake-pop: Update to version 1.0.0-preview.18 and fix checkver

---

bucket/adwcleaner.json

Closes #XXXX
Switch to alt checkver URL because current URL is 403

adwcleaner: Switch to alt checkver URL

---

bucket/kdeconnect.json

close #7110
**KDEConnect** ([homepage](https://kdeconnect.kde.org/)) ([Wikipedia](https://en.wikipedia.org/wiki/KDE_Connect)) is a multi-platform application developed by **KDE**, which facilitates wireless communications and data transfer between devices over local networks.
NOTES:
* **persist** is not needed because config file is stored at `$Env:LocalAppData\kdeconnect\config`

kdeconnect: Add version 21.12.0-835

---

bucket/trojita.json

close #4680
[Trojitá](http://trojita.flaska.net/) is a IMAP e-mail client with lightweight GUI.
Notes:
* *checkver/autoupdate* is not needed because the app has not receive any update since 2016.
* *persist* is not needed because config is stored at `$Env:LocalAppData\flaska.net\trojita`
* The app is built in *32-bit*
```
> pelook trojita.exe
loaded "trojita.exe" / 5136851 (0x4E61D3) bytes
signature/type:       PE32 EXE image for i386
image checksum:       0x004F0018 (OK)
machine:              0x014C (i386)
subsystem:            2 (Windows GUI)
minimum os:           4.0 (Win95/NT4)
linkver:              2.25
timestamp:            06/15/2016 10:09:07am (0x57612943)
file alignment:       0x200
section alignment:    0x1000
preferred load base:  0x00400000
code entrypoint:      0x004014C0 -> …
```

trojita: Add version 0.7

---

bucket/http-downloader.json

Add "download_history" to the list of persisted files.
This file is used to show downloaded files in the downloads list across sessions (an advanced option which is disabled by default). If this file isn't persisted, each new Scoop update of the program will cause the new version to show a blank downloads list. Persisting "download_history" should fix this for those using the feature.

http-downloader@1.0.4.8: Persist "download_history" file

---

bucket/powertoys.json

PowerToys changes its installer in recent version and make current script stop working.
It is indeed a WIX installer, I'll finish the installer PR as soon as possible.
Relates to https://github.com/ScoopInstaller/Scoop/pull/3502

powertoys: Fix installer.script and add au.hash

---

bucket/advanced-ip-scanner.json

close #7100
[Advanced IP Scanner](https://www.advanced-ip-scanner.com/) is a network scanner that can analyse LAN, show network devices, and provide remote control via RDP and Radmin.
Notes:
* **license**: EULA can be found in the dialog of the installer.
* 7-zip did not put `qwindows.dll` and `windowsprintersupport.dll` in the right directory. Therefore need to be fixed in *pre_install*.
* **persist**: Advanced IP Scanner uses **binary files** to store its settings, therefore manual persist is needed.
* The **.msi** files under `$dir` is for user to install *Radmin* when needed.

advanced-ip-scanner: Add version 2.5.3850

---

bucket/imdone.json

Simple and powerful kanban board built on top of plain text markdown files or code.
Regarding the criteria for inclussion in the main bucket: this is not a developer tool, and it is GUI based which excludes it from main.
Hence, because the first criteria is not met, this is proposed for inclusion in extras.
The project does not publish hashes, if this is an absolute requirement for inclusion into extras please say so I can open an issue there.
Licensing is not clear, yet,  PR kept as draft until https://github.com/imdone/imdone/issues/109 is closed.
Closes #7170

imdone: Add version 1.23.2

---

bucket/yaffplayer.json

close #6335
[YAFFplayer](https://www.geeks3d.com/yaffplayer/) is a simple video player based on FFmpeg libraries.
Notes:
* EULA can be found in `$dir\eula.txt`.
* checkver url (https://www.geeks3d.com/dl/show/618) is consistent, see [web archive](https://web.archive.org/web/20210423072950/https://www.geeks3d.com/dl/show/618) for example.
* The software is built in 64-bit.
```
>pelook yaffplayer.exe
loaded "yaffplayer.exe" / 559616 (0x88A00) bytes
signature/type:       PE64 EXE image for amd64
image checksum:       0x000962BE (OK)
machine:              0x8664 (amd64)
subsystem:            2 (Windows GUI)
minimum os:           6.0 (Vista)
linkver:              Microsoft LINK 14.30
detected toolset(s):  <none>
timestamp:            01/06/2022 10:25:17am (0x61D6C38D)
```

yaffplayer: Add version 0.5.7.0

---

bucket/openvpn-connect.json

related: #6192
NOTES:
* *persist* is not needed because config is at `$Env:AppData\OpenVPN Connect\`.
* `$dir\snapshot_blob.bin` and `$dir\v8_context_snapshot.bin` is used by the chromium backbone.
* **per_install**: The app cannot work **under junctions**. Therefore we need to manually create the shortcut.
The script is taken from [lib/shortcuts.ps1](https://github.com/ScoopInstaller/Scoop/blob/master/lib/shortcuts.ps1#L30)
If there is a more simple/elegant way to solve the problem, please tell me.

openvpn-connect: Add version 3.3.4.2600

---

bucket/modernflyouts.json

close #3142
[ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts) is a replacement for the built-in audio flyout UI, with a Modern Fluent Design.
Notes:
* *persist* is not needed because config file is at `$Env:LocalAppData\ModernFlyouts_Community`.
* ~*autoupdate* cannot work properly without `"replace": "${version}"` in *checkver*.~ This is probably a bug in Scoop core. 
**UPDATE**: The problem no longer happens in this manifest.
It happens when the 2nd matchgroup is named as *version*. (e.g. `"regex": "(\\w+)\\.ModernFlyouts_(?<version>[\\d.]+)(\\w+)\\.Msixbundle"`)
*checkver* will be fine, but in *autoupdate*, $version becomes an empty string.
Screenshots:

modernflyouts: Add version 0.9.3.0

---

bucket/dosbox-staging.json

DOSBox Staging is DOS/x86 emulator focusing on ease of use. Based on DOSBox.
---
Tested first by running it separately outside of Scoop to figure out persist/portable mode.
Basically if you don't have a dosbox-staging.conf in your root, it will use Local AppData - whilst if you do have it, it will use the config in the root, and create folders for glshaders, mt32-roms, and soundfonts. So all of this is persisted in the manifest and the config file is created through pre install with an If statement.

dosbox-staging.json: Add version 0.78.1

---

bucket/win11dragdroptaskbarfix.json

- Closes #7490
- First try at using persist, is this the simplest way? The program creates a config file but only if you press "Configure..." in its tray menu. So I had to create it in pre_install, hope that's right.
- Also this is the shortest I could make the manifest name without leaving it unreadable/unsearchable.

win11dragdroptaskbarfix: add version 2.2.0.0

---

bucket/opentoonz.json

Closes #5270
Is it necessary to add a `post_install` script to delete the `unins000.exe` file?

opentoonz: add version 1.5.0

---

bucket/barrier.json

- Closes #7166
- Nothing to persist as config stored in registry at `Computer\HKEY_CURRENT_USER\Software\Debauchee\Barrier`
- `bin`s are CLI versions of the Client and Server parts of Barrier

barrier: add version 2.4.0

---

bucket/godot-mono.json
bucket/godot.json

godot/godot-mono: moved download location from tuxfamily.org (default dl location for godot engine) to official mirror at github.com (https://github.com/godotengine/godot/releases) for significantly increased download speeds
Closes #6862

godot/godot-mono@3.4.2: moved dl location to github

---

bucket/antimicro.json

Currently the manifest doesn't have a pre-install which makes the supposed INI file end up as a folder in the persist dir.

antimicro: Add pre-install for settings INI file

---

bucket/kodi.json

- Closes #7164
- Suggests vcredist2019 because it is included in the installer
- Persists `portable_data` and uses `-p` (portable) flag for shortcut as specified in the [wiki](https://kodi.wiki/view/Portable_mode)
- No proper CLI so no shims
- `post_install` removes rubbish left over from installer

kodi: add version 19.3

---

bucket/fatty.json

close #4932
[FaTTY](https://github.com/juho-p/fatty) is a Cygwin Terminal emulator **with tabs**.
Notes:
* FaTTY has not received any updates since ~2016~ Jan 2021. Therefore I think we can just compile from source, and stick with this version.
* The binary is compiled with Cygwin version 2.915 and the following packages:
Screenshots:

fatty: Add version 20210122

---

bucket/silex-desktop.json

- Relates to #7765
- @rashil2000 I searched the repo for other manifests using `latest.yml` and discovered you could use `$base64` in the regex

silex-desktop: add hash extraction

---

bucket/postman.json

The old checkver url (`https://dl.pstmn.io/changelog?channel=stable&platform=win64`) is not working properly anymore, it needs additional parameters to return the correct latest version number. 
Since the added extra parameter is user-associated, it was replaced with the url used in autoupdate (`https://dl.pstmn.io/RELEASES?platform=win64`), which currently works fine. 
Also, add the `from=$version` parameter to reduce the size of the data returned.

postman: fix checkver

---

bucket/rambox-pro.json

Rambox has dropped the "Pro" from the exe name, and now has added "-x64" to the file-name
Closes #7779

rambox-pro: Fix exe name and download link

---

bucket/lunacy.json

The regex used to find the .exe installer is no longer valid, as the link now says "Installer" instead of "here". So I updated it and ran checkver to update the manifest to the latest release.

lunacy: Update to version 8.1.0.0

---

bucket/webcopy.json

Closes #7797
In [Upcoming Changes](https://www.cyotek.com/cyotek-webcopy/upcoming-changes):
> Removed
> - The Link Checker (GUI and CLI), URI Tester and XPath Tester tools have been removed from distribution due to lack of use

webcopy: Remove 'Link Checker' and 'URI Tester'

---

bucket/hydrus-network.json

The normal autoupdate with '.\bin\checkver.ps1 hydrus-network -u' failed for version 470.
Stating the version explicitly '.\bin\checkver.ps1 hydrus-network -u -v "470b"' worked.
Looks like the script did not recognize v470b as a valid git version tag and tried to download the already removed release for v470 instead.

hydrus-network: update to 470b

---

bucket/fastcopy.json

FastCopy is updated with a major version bump (v4). It introduces exciting features such as a command line app. It also no longer releasing a zip archive for download. Instead, there is a installer with "extraction" option. So we need to change the script a bit.
Here is my attempt. I tested locally without problem. One small question: when the manifest has "installer/script" specified, the installer file is always kept? Anyways, I explicitly remove `$dir\$fname` at the end.

FastCopy: update to 4.0.2

---

bucket/firefox-esr.json
bucket/firefox.json
bucket/seamonkey.json
bucket/thunderbird.json

Closes https://github.com/ScoopInstaller/Extras/issues/7841 https://github.com/ScoopInstaller/Extras/issues/7827 https://github.com/ScoopInstaller/Extras/issues/7742 https://github.com/ScoopInstaller/Extras/issues/7773 https://github.com/ScoopInstaller/Extras/issues/6854 https://github.com/ScoopInstaller/Extras/issues/4935 https://github.com/ScoopInstaller/Extras/issues/4377 https://github.com/ScoopInstaller/Extras/issues/3531 https://github.com/ScoopInstaller/Extras/issues/7713 and more.
- Create Profile and point to `$dir\profile`
|App|Profile Name|Path|
|-|-|-|
|firefox|Scoop|$dir\profile (\<Scoop>\persist\firefox\profile)|
|firefox-esr|Scoop-ESR|$dir\profile (\<Scoop>\persist\firefox-esr\profile)|
|thunderbird|Scoop|$dir\profile (\<Scoop>\persist\thunderbird\profile)| …

Improvement for Firefox(-ESR), Thunderbird and SeaMonkey

---

bucket/autoclicker.json

Created a manifest for [Autoclicker ](https://sourceforge.net/projects/orphamielautoclicker/)
A full-fledged autoclicker with two modes of autoclicking, at your dynamic cursor location or at a prespecified location. The maximum amounts of clicked can also be set (or left as infinite).
Judging by weekly downloads, I'm surprised no one suggested it already:
https://sourceforge.net/projects/orphamielautoclicker/files/stats/timeline
Unsure if autoupdate is needed. What do you think?

Autoclicker: Add version 1.0.0.2

---

bucket/whynotwin11.json

Created a manifest for [WhyNotWin11](https://github.com/rcmaehl/WhyNotWin11)
This is a helpful utility to figure out **exactly** why your computer can't update to windows 11.
There is no need for `perist`, as this program keeps its data in `$Env:LocalAppData\WhyNotWin11`

whynotwin11: Add version 2.4.3.1

---

bucket/postman.json

This has been changed back and forth lately. Currently, the `changelog` check is more reliable than the `release` check as the latter one is not sorted reliably.
Relates to #7787 #7694

postman: fix checkver and update to 9.11.0

---

bucket/sdl2.json

They were added in #709 by @tresf as a guess, but as far as I can tell pthread.h & asound.h are not available on windows. And thus caused library not found errors.
Relates to #7867

SDL2: Remove unnecessary cflags

---

bucket/winrar.json

Fix the download link for 32bit and update to version 6.10

winrar: Update to version 6.10

---

bucket/godot-mono.json

Fix for issue #7902 - godot-mono shim overwrites the one fom the godot package

---

bucket/crystaldiskinfo.json

This is my attempt at updating the download links to improve the download speeds.
Shortlist of what's modified:
- URL
- Checkver
- Autoupdate
Since I don't comprehend regex and therefore did a copy-paste job hoping that Mark and Info follow the same structure, let's see.
Closes #7922

crystaldiskinfo: Update download links

---

bucket/clash-mini.json

[Clash.Mini](https://github.com/MetaCubeX/Clash.Mini) a simple GUI for [Clash](https://github.com/Dreamacro/clash).
Closes #7920

clash-mini: Add version 0.1.6

---

bucket/avidemux.json

- Closes #3691 and closes #4775
- Uses GitHub releases for download instead of sourceforge/fosshub, but no hash unfortunately
- CLI added and shortcuts for main program and the Jobs runner

avidemux: add version 2.8.0

---

bucket/freecad.json

Wrong extract directory for FreeCad package.

Fix extract_dir for FreeCad package.

---

bucket/kdiff3.json
bucket/thunderbird.json
bucket/vscodium.json

Version 1.9.4 has been published as 1.9.4b, thus the checkver regex needs to be updated to match the current version scheme.
See https://invent.kde.org/sdk/kdiff3/-/issues/30 for details.

kdiff3: Update checkver regex

---

bucket/wonderpen.json

The official domain name has been updated from `atominn.com` to `tominlab.com`  and the download links have been updated too.
The new autoupdate url has been tested with `/bin/checkver.ps1`.

Wonderpen@2.0.6: Update urls

---

bucket/draw.io.json

It seems like draw.io Desktop provides hash file, and its homepage has changed too.
BTW, the manifest name `draw.io` is an exception that it uses `.`, should we rename it to `drawio`?

draw.io: Add au.hash and change homepage

---

bucket/scidavis.json

closes #6846
[SciDAVis](http://scidavis.sourceforge.net/) is a aata analysis and visualization program aimed at high-quality plotting of scientific data.
**NOTES**:
* persist is not needed because config is at `HKCU:\SOFTWARE\SciDAVis`
* The program is built in **64-bit**.
```
>pelook scidavis.exe
loaded "scidavis.exe" / 73022283 (0x45A3B4B) bytes
signature/type:       PE64 EXE image for amd64
image checksum:       0x045AD4E3 (OK)
machine:              0x8664 (amd64)
subsystem:            2 (Windows GUI)
minimum os:           4.0 (Win95/NT4)
linkver:              2.37
timestamp:            02/02/2022 04:45:27am (0x61FA0C67)
```

scidavis: Add version 2.7

---

bucket/vieas.json

HTTP status code 307, and scoop cannot redirect url.

vieas: Change all download URLs to https

---

bucket/musicplayer2.json

New version added `global_cfg.ini`. Keep it empty and persistent and when Musicplayer2 is started for the first time, it will automatically write portable parameters in it.

musicplayer2@2.74: Update persist files

---

bucket/trafficmonitor.json

Need to persist `plugins`  folder since TrafficMonitor v1.82 has added plugins system.

trafficmonitor@1.83: persist plugins

---

bucket/alpinewsl.json

Add AlpineWSL 3.15.0-0 .
Manifest is directly modified from `ArchWSL`.

alpinewsl: Add version 3.15.0-0

---

bucket/another-redis-desktop-manager.json

- Closes #7982
- Nothing to persist as settings saved in `AppData\Roaming\another-redis-desktop-manager`

another-redis-desktop-manager: add version 1.5.2

---

bucket/firefox-esr.json
bucket/firefox.json
bucket/seamonkey.json
bucket/thunderbird.json
bucket/waterfox-classic.json
bucket/waterfox.json

use $persist_dir instead of $dir in profile path, then profile path can still be used in other versions after uninstalling the apps. (if it is compatible)
- this change only affects fresh installations.
- for users who have generated a scoop portable profile before this update, you will need to manually edit this file **OR** delete it and reinstall the application to change the profile path, if you want use uninstalled app's profile:
```
$HOME\AppData\Roaming\Mozilla\Firefox\profiles.ini
```

*mozilla: use $persist_dir instead of $dir in profile path

---

bucket/logseq.json

logseq@0.6.0: Update autoupdate hash

---

bucket/aircrack-ng.json

closes #7990
[Aircrack-ng](https://www.aircrack-ng.org/) is a suite of tools to assess WiFi network security.
**NOTES**:
* The binary is built in **64-bit**.

aircrack-ng: Add version 1.6

---

bucket/jexiftoolgui.json

closes #8007
[jExifToolGUI](https://hvdwolf.github.io/jExifToolGUI/) is a java/Swing graphical frontend for the command-line tool **ExifTool**.
**NOTES**:
* I chose the binary release with bundled JRE because it is less likely to have environment problems.
* **architecture**: Although the file is named as `win-x86_64`, the executable is built under 32-bit, and can work under 32-bit.
```
>pelook jExifToolGUI.exe
loaded "jExifToolGUI.exe" / 15225974 (0xE85476) bytes
signature/type:       PE32 EXE image for i386
image checksum:       0x00015C90 (MISMATCH / calc=0x00E8E1E8)
machine:              0x014C (i386)
subsystem:            2 (Windows GUI)
minimum os:           4.0 (Win95/NT4)
linkver:              2.26
timestamp:            11/13/2021 04:03:59pm (0x618FE1EF)
```
* **persist**: Besides …

jexiftoolgui: Add version 1.10.0.0

---

bucket/mumble-server.json
bucket/mumble.json

closes #7971
**NOTES**:
* persist is not needed for *client* because config is at `$Env:AppData\Mumble`.

mumble: Update to version 1.4.230, Add mumble-server

---

bucket/fysty.json

closes #8005
[Fysty](https://github.com/lalbornoz/FySTY) is a fork/patch of the SSH and Telnet client **PuTTY**.
**NOTES**:
* The app is built in **64-bit**.
* persist is not needed because config is at `HKCU\SOFTWARE\SimonTatham\PuTTY`.
* **checkver**: I involved **release date** in version because there will be problem checking which one is newer through **commits**. For example, `4c207368` comes after `a2404931`.
* **bin**: Command-line options for `putty.exe`, etc. can be found in [the manual](https://documentation.help/PuTTY/using-general-opts.html). Also see [extras/putty manifest](https://github.com/ScoopInstaller/Extras/blob/master/bucket/putty.json).

fysty: Add version 20220202-76f785d5

---

bucket/dopamine.json

GitHub releases are not updated, but there is a reminder within the software to update. so I found the official website already has the new version installed.
Also try updating checkver to keep up to date with the latest version.

dopamine: Update to 2.0.9 & Update checkver

---

bucket/firefox-esr.json
bucket/firefox.json
bucket/seamonkey.json
bucket/thunderbird.json
bucket/waterfox-classic.json
bucket/waterfox.json

USAGE:
Create a directory named **addition** in app's persist directory (e.g. ~\scoop\persist\firefox\addition), and put files/configs/etc. into the directory. 
Items of **addition** directory will be copied to app root directory by install script every install/update.
---
Any items that overwrite the original files are **NOT RECOMMENDED**.
see also: https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig
Closes #8016

*mozilla: Allow appending of Additional items

---

bucket/rancher-desktop.json

closes #7973
[Rancher desktop](https://rancherdesktop.io/) is a Kubernates container management tool that can build, push, and pull images and run containers.
**NOTES**:
* persist is not needed because config is at `$Env:LocalAppData\rancher-desktop`.
* **env_add_path**: Some of the binaries is intended to work under WSL (Linux), which cannot be properly shimmed, therefore `env_add_path` is needed here.

rancher-desktop: Add version 1.0.1

---

bucket/goldendict.json

According to goldendict>help>03_Portable_Mode, goldendict can be made portable if a folder named portable is under its dirertory, in which case the dictionaries must be stored within the program.

goldendict@1.5.0-RC2-372-gc3ff15f: make goldendict portable

---

bucket/nirlauncher.json

RunFromProcess.exe was previously identified as a GUI exe. This has been corrected in this release (though the .exe is still actually a GUI app).

nirlauncher: Update to version 1.23.57 (via nlp2json.py)

---

bucket/sunshine.json

Fixes https://github.com/SunshineStream/Sunshine/issues/70.

sunshine: Properly set working directory to executable path

---

bucket/fiji.json

closes #5813
[Fiji](https://fiji.sc/) is an image processing package — a "batteries-included" distribution of [ImageJ](https://imagej.net/), bundling many plugins which facilitate scientific image analysis.
**NOTES**:
* **checkver**: [Fiji's Github repo](https://github.com/fiji/fiji/tags) provides version names like `2.3.1`. However, from [their download archives](https://downloads.imagej.net/fiji/archive/), we can see there are actually more frequently updates. This will be a problem if we check version *via Github repo* and use `https://downloads.imagej.net/fiji/latest/fiji-win64.zip` as download url.
* shortcut name `(Fiji Is Just) ImageJ` is the window title of the app.
* persist is not needed because config is at `$Env:UserProfile\.imagej`

fiji: Add version 20220222-1217

---

bucket/webex.json

Closes #8057
The Webex URL that checkver uses has been updated to change the format of how they present the version from:
`Version: xx.x.x.xxxxx` to `Windows—xx.x.x.xxxxx`.
Note, there is a complication here due to how Scopp downloads the URL and processes the regex, pattern matching on the emdash character is not possible. This is because the UTF-8 website is being interpreted as Windows-1252. So the emdash actually reports as `â€”`. For reference this is a common encoding issue which you can read about [here](https://www.i18nqa.com/debug/utf8-debug.html).
I have not updated the version or hash at this time, I'll leave that for the automated process which should work as normal from now on.

Fixed Webex checkver regex to match updated website

---

bucket/mozregression-gui.json

closes #5625
[Mozregression](https://mozilla.github.io/mozregression/) is a tool **developed by Mozilla**. It is a regression range finder for Firefox and other Mozilla products, which helps determining a changeset range corresponding to when a problem was introduced.
**NOTES**:
* The app (and its dependent DLLs) are built in **32-bit**.
* Persist is not needed because config, firefox images, test datasets, etc. are stored at `$Env:UserProfile\.mozilla\mozregression`.

mozregression-gui: Add version 4.0.18

---

bucket/tsip.json

closes #5363
[tSIP](http://tomeko.net/software/SIPclient/) is a small, portable SIP softphone for Windows based on [re/rem/baresip](https://github.com/baresip/).
**NOTES**:

tsip: Add version 0.2.06

---

bucket/sunshine.json

I just noticed that sunshine_state.json persisted as a directory when nonexistent.

sunshine: Create sunshine_state.json if nonexistent

---

bucket/sunshine.json

Sunshine fails to write to `sunshine_state.json` when the content is invalid.

sunshine: Set sunshine_state.json to an empty json

---

bucket/rssguard.json

why use `data` not `data4`
from `data4`
https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#userd

persist data4

---

bucket/nvui.json

closes #8085
[nvui](https://github.com/rohit-px2/nvui) is a fast and feature-rich front-end for **neovim**.
**NOTES**:
* The app is built in 64-bit.
* **nvui** supports command-line arguments, see [readme](https://github.com/rohit-px2/nvui/tree/v0.2.1#readme) for examples.

nvui: Add version 0.2.1

---

bucket/laragon.json

closes #5267
[Laragon](https://laragon.org/) is a universal development environment for PHP, Node.js, Python, Java, Go, and Ruby.
**NOTES**:
* The app (and its dependent execuatables, DLLs) are built in **32-bit**.

laragon: Add version 5.0.0

---

bucket/wonderpen.json

The official 32-bit separate installation package is cancelled by the developer and now updated to a two-in-one installation package.
Also the url for checkver has been updated.

Wonderpen: Update to 2.0.8
