ScoopInstaller/Extras

- firefox.json
Installs Firefox (en-US culture). 
Installs no shortcuts on start menu or desktop.
Only adds shim for 'firefox.exe'
> Add Firefox install

- ec2-api-tools.json
Added ec2-api-tools https://aws.amazon.com/developertools/351
> Added ec2-api-tools 1.7.3.0

- cargo-nightly.json
> Update cargo-nightly urls

- fossil.json
Fossil is an all-in-one distributed version control system with built-in wiki and but tracking.
> Fossil SCM added.

- conemu.json
Been playing around with conemu lately. If you havn't tried it as a replacement to the default windows powershell/cmd console I would *highly* recommend it. It has many features which I find increase my productivity heaps! It takes a bit of customising and tinkering to figure everything out.
- Easily resize windows
- Copy-paste support
- Highlighting text
- Tabs and split panes
- Borderless, maximised windows
- Better font rendering
- Easily hide and show with a keypress
> Update and correct conemu manifest

- git-preview.json
https://github.com/git-for-windows/git/releases/tag/v2.3.5.windows.8
> Git 2.3.5 Preview

- enso.json
Enso is a launcher for Windows similar to Spotlight on OSX.
> Add enso 0.1.5

- oraclejdk.json
- oraclejdk7.json
> Update oraclejdk and oraclejdk7

- README.md
I take a time to figure out that was a command.
> Change on README.md to improve readability

- keepass.json
> Add KeePass

- dart-dev.json
Upgrade the dart dev channel from upgrade dart to 1.13.0-dev.0.0 to upgrade dart to 1.13.0-dev.7.0.
> upgrade dart to 1.13.0-dev.7.0

- rabbitmqadmin.json
RabbitMQ management CLI: https://www.rabbitmq.com/management-cli.html
> Add rabbitmqadmin

- emacs.json
I've added GNU TLS to e.g. support https access to package archives.
> Added GNU TLS support

- apache64bit.json
Update Apache 64bit 2.4.18
Fix 404 error lukesampson/scoop#660
> Apache64bit 2.4.18

- atom.json
> Fix hash for Atom

- putty.json
Messed up a bit with the previous PR by pulling your newer changes, so doing a fresh one with only this update with static links that won't change on update.
> Updated to 0.67

- rancher-compose.json
Add manifest for the `rancher-compose` tool.
> Add rancher-compose

- packer.json
- terraform.json
Updates the `packer` manifest to point to the latest version and adds a `terraform` manifest.
> Add/Update Hashicorp tools

- vscode.json
Add a manifest for installing Visual Studio Code.
> Visual Studio Code

- gitextensions.json
- ilspy.json
- orca.json
- p4merge.json
- procexp.json
Adding these to the extras bucket as discussed.
> Adding gitextensions, ilspy, orca and procexp

- ncftpclient.json
- rabbitmq.json
- rabbitmqadmin.json
https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_2
> Update RabbitMQ and RabbitMQadmin 3.6.1 --> 3.6.2

- conemu.json
Updates the ConEmu manifest to the latest stable version (v16.06.19)
> update conemu to 16.06.19

- conemu.json
> update conemu to 160710

- sourcetree.json
updated binary and sha256 checksum
> sourcetree 1.8.3

- whois.json
> Removed hash from whois.json since the zip file isn't versioned

- winmerge2011.json
I noticed Notepad++ did it but WinMerge didn't. Very useful.
> Added Programs shortcut to WinMerge 2011

- vscode.json
Hi - bumping vscode from 1.7.1 to 1.8.1.
> bumped vscode 1.8.1

- nssm.json
Dup of https://github.com/lukesampson/scoop/blob/master/bucket/nssm.json
> Delete nssm as it's in scoop

- ShareX.json
i even gave it an autoupdate line but im unable to test if it works.
the autoupdate code came from [these](https://github.com/lukesampson/scoop/blob/master/bucket/forge.json#L9-L14) forge lines.
> added a json file for sharex

- processhacker.json
this is an update to the process hacker json that adds a desktop shortcut and a possibly working version checker
> An update to the process hacker json

- ShareX.json
- atom.json
- baretail.json
- dart-dev.json
- darteditor.json
- dartium-dev.json
- dartium.json
- dartium_content_shell-dev.json
- dartium_content_shell.json
- ditto.json
- filezilla.json
- gvim.json
- keepassxc.json
- mplayer.json
- neovim-qt.json
- neovim.json
- notepad2-mod.json
- notepadplusplus.json
- php64bit.json
- processhacker.json
- telegram.json
- xmllint.json
* Updates and checkver fixes
* Neovim and Nevim-qt are now separate manifests for better version control
* Added KeePassXC
> Several updates and two additions

- whatsapp.json
I didn't add an autoupdate section because it does that automatically.
> Add WhatsApp

- cmake-rc.json
Needed this to access newer features in CMake and thought it might be useful for others as well :)
> Adds CMake RC

- brackets.json
> Add Brackets text editor.

- leet.json
> Add leet.json

- putty.json
PuTTY: Added 64bit, shortcuts and autoupdate. Updated to version 0.68.
> Added 64bit, shortcuts and autoupdate. Updated to version 0.68.

- cloudfoundry-cli.json
Maybe Cloudfoundry CLI could be included in extra?
> Cloudfoundry CLI with autoupdate and multiarch.

- protobuf.json
Not sure if manifest is as complete as it needs to be. Let me know if it's not.
> added protobuf v3.3.0

- vcxsrv.json
Moved here as suggested in scoop pull request [#1463](https://github.com/lukesampson/scoop/pull/1463)
> VcXsrv: Open Source Windows X-server based on the xorg git sources

- tortoisesvn.json
In order for the installer to run properly the UI must show at least in reduced/passive mode
> Adding tortoise-svn

- synctrayzor.json
Windows tray utility for syncthing (See https://github.com/lukesampson/scoop/pull/1571)
> Add synctrayzor 1.1.16

- eclipse-committers.json
- eclipse-cpp.json
- eclipse-dsl.json
- eclipse-java.json
- eclipse-javascript.json
- eclipse-jee.json
- eclipse-modeling.json
- eclipse-parallel.json
- eclipse-php.json
- eclipse-platform.json
- eclipse-rcp.json
- eclipse-reporting.json
- eclipse-scout.json
- eclipse-sdk.json
- eclipse-testing.json
> Eclipse Oxygen (4.7.0)

- oraclejre-server.json
- oraclejre.json
Seems that auto-pr does not work with match groups. Should I create an issue?
> Fix extract_dir for oracle-(jre|jre-server) 8u141-b15

- sfk.json
> Update sfk to 1.8.7

- vscode.json
> Add 64bit to vscode (fixes #495)

- renderdoc.json
Adds the [RenderDoc graphics debugger](https://renderdoc.org/).
> Add RenderDoc v0.91.

- hack-font.json
Adds the monospace programming ttf font "Hack"
> Add hack ttf font version 1.2.0.

- apache-ivy.json
Adds a manifest for apache-ivy that installs apache-ivy to the lib folder for ant
> Add apache-ivy version 2.4.0. Closes #101.

- kakaotalk.json
KakaoTalk is a popular Korean chat app. Something like 50 million active users.
> Added KakaoTalk

- sabnzbd.json
Added SABnzbd - a popular newsgroup binary grabber.
> Added SABnzbd

- makemkv.json
Adds MakeMKV - a popular DvD and Bluray backup tool.
> Add MakeMKV

- deluge.json
Adds the popular Deluge torrent client.
> Add Deluge

- subtitleedit.json
Adds Subtitle Edit - a powerful, popular, and opensource subtitle editing suite.
> Add Subtitle Edit

- anaconda3.json
This adds the full Anaconda 3 distribution.
> Add Anaconda 3 version 4.4.0.

- robo3t.json
> update shortcuts for robo3t

- assume-role.json
handy helper for AWS STS assume role commands.
> add https://github.com/remind101/assume-role 

- wiztree.json
WizTree lets you see what folders/files are using the most space on your system
> Add WizTree version 3.00.

- processhacker.json
Realized I should have had it there to begin with!
> Added shortcut to Process Hacker

- ccleaner.json
Added [CCleaner](https://www.piriform.com/ccleaner). References portable version, no installation.
> Add CCleaner

- storageexplorer.json
Update `checkver` to use the Azure Storage Explorer release notes. 
Update to version 0.8.16.
> Update storageexplorer to version 0.8.16

- winscp.json
Free SFTP, SCP and FTP client for Windows
http://winscp.net
> Add WinSCP

- wiztree.json
Update wiztree to version 3.10.
> Update wiztree to version 3.10

- winscp.json
Hopefully this works better. Somehow I used the master branch for the last PR...
> WinSCP: fix autoupdate hash

- sublime-text.json
It seems the contents in the Data directory should all be persisted. I was conservative.
> fix sublime persist

- gcloud.json
Hi, I created a manifest for Google Cloud SDK.
> Create gcloud.json for Google Cloud SDK

- plantuml.json
I've added [PlantUML](http://plantuml.com/), a tool to create UML diagrams, using a simple and human readable text description.
> Add PlantUML

- everything.json
Added [Everything](https://www.voidtools.com/), a really fast file search engine for Windows.
> Add Everything

- gitkraken.json
Updated gitkraken hashes to match their correct hashes.
> Updated gitkraken hashes

- natural-docs.json
Natural Docs is a documentation generator for a variety of programming languages.
> Add Natural Docs version 2.0.1.

- ppsspp.json
This pull requests adds the playstation portable emulator ppsspp :smile:
> Add ppsspp 1.4.2.

- speccy.json
Speccy is a system specs analyzer from the same group that made ccleaner :smile:
> Add speccy version 1.31.732.

- hexchat.json
Added [HexChat](https://hexchat.github.io/), an Open Source IRC client for Windows.
> Add HexChat

- sts.json
Links/checksum from: http://dist.springsource.com/release/STS/index.html
> updated to 3.9.1

- rabbitmq.json
> Update rabbitmq to version 3.6.12

- rabbitmqadmin.json
Update to 3.6.12
Bin script is still valid.
> Update rabbitmqadmin to version 3.6.12

- hwmonitor.json
> Update hwmonitor 1.33 hashes

- idea-eap.json
- idea-ultimate-eap.json
Hello, I'm using idea eap at work which is basically ultimate with additional features, free and usable for commercial uses. I personnaly think it's a great addition but I would understand if you don't think so.
Thanks for your work 👍
> Add Idea EAP

- accesschk.json
Update `homepage` to point directly to tool
Add `hash`
Update to version 6.11
> Update accesschk to version 6.11

- gitextensions.json
> Update gitextensions to version 2.50.02

- strings.json
Add `hash`
Update to version 2.53
> Update strings to version 2.53

- whois.json
> Update whois to version 1.14

- wifi-manager.json
> Update wifi-manager to version 0.2

- whatsapp.json
Whatsapp checksums are outdated.
> Update whatsapp checksums

- solidity.json
[Ethereum Blockchain backend compiler](https://github.com/ethereum/solidity)
> Added solidity (dapp compiler)

- kdiff3.json
Hello,
I have added a manifest for [KDiff3](http://kdiff3.sourceforge.net/).
> add JSON manifest for KDiff3

- notepadplusplus.json
Explain how to add explorer context menu
> Add note to notepad++

- sharpkeys.json
SharpKeys is a great open source app that I use to map capslock to control.
> add manifest for SharpKeys 3.5

- dbeaver.json
- foxit-reader.json
Hello,
I was missing these two tools and plan on adding others that I'll need.
Let me know if I'm doing it correctly.
Kr,
Eric
> Added dbeaver and foxit-reader

- enso.json
- Update enso to `0.1.8`
- Implement auto update
> Update enso to version 0.1.8

- echoargs.json
- Update to version `3.2`
- Add hash
> Update echoargs to version 3.2

- s.json
Add [s](https://github.com/zquestz/s/releases) version 0.5.11
> Add s version 0.5.11

- rabbitmqadmin.json
Update to version `3.6.14`
Implement autoupdate
> Update rabbitmqadmin to version 3.6.14

- rabbitmq.json
Update to version `3.6.14`
Implement autoupdate
> Update rabbitmq to version 3.6.14

- sqlitestudio.json
SQLiteStudio is an excellent open source SQLite database manager
> add SQLiteStudio 3.1.1

- .gitignore
- dbeaver.json
Only updated dbeaver in that branch
> dbeaver in version 4.2.5

- imgburn.json
ImgBurn is a lightweight CD / DVD / HD DVD / Blu-ray burning application.
> add ImgBurn 2.5.8

- mc.json
Midnight Commander 32-bit added
- dual window file manager
- program can be executed in cmd / powershell with command "mc"
> Midnight Commander (mc) added

- resource-hacker.json
Not sure if there was a reason why this was omitted or if it was just forgotten.
> resource-hacker: Add start menu shortcut

- eclipse-android.json
- eclipse-automotive.json
- eclipse-committers.json
- eclipse-cpp.json
- eclipse-dsl.json
- eclipse-java.json
- eclipse-javascript.json
- eclipse-jee.json
- eclipse-modeling.json
- eclipse-parallel.json
- eclipse-php.json
- eclipse-platform.json
- eclipse-rcp.json
- eclipse-reporting.json
- eclipse-scout.json
- eclipse-sdk.json
- eclipse-testing.json
> Sunset train-to-version

- eclipse-android.json
- eclipse-automotive.json
- eclipse-committers.json
- eclipse-cpp.json
- eclipse-dsl.json
- eclipse-java.json
- eclipse-javascript.json
- eclipse-jee.json
- eclipse-modeling.json
- eclipse-parallel.json
- eclipse-php.json
- eclipse-rcp.json
- eclipse-reporting.json
- eclipse-scout.json
- eclipse-testing.json
@r15ch13 Sorry, made a small mistake with the redirection (?r=1 instead of &r=1) in autoupdate, so I broke things. This will fix it.
> Eclipse: Fix redirection bug in autoupdate

- ditto.json
When I created the last pull request I did not know about `innosetup`.
> Ditto: unpack exe file instead of installing it

- libsndfile.json
Also adds library and header to pkg-config, and thus cmake.
> Add libsndfile

- faas-cli.json
> OpenFaas faas-cli

- elasticsearch.json
- tortoisesvn.json
I am not sure why ElasticSearch commits are in this pull request when we merged them before. This pull request is for TortoiseSVN
> Update TortoiseSVN to version 1.9.7

- nirlauncher.json
Depends on https://github.com/lukesampson/scoop/pull/1945
> Add nirlauncher at 1.20.25

- pwsafe.json
> added pwsafe

- bin/checkurls.ps1
- signal.json
- Add checkurls
- Fix download link
> Fix signal download link

- emacs.json
See: http://ftp.gnu.org/gnu/emacs/windows/emacs-25.3_1.readme
> Update to emacs 25.3_1 for 64bit

- jd-gui.json
Added Java decompiler (jd-gui) version 1.4.0
> Added Java decompiler (jd-gui) version 1.4.0

- apache-directory-studio.json
Added Apache Directory Studio version 2.0.0-M13
> Added Apache Directory Studio version 2.0.0-M13

- pwsafe.json
Updated pwsafe to version 3.45.0
>  Updated pwsafe to version 3.45.0

- mp3tag.json
https://www.mp3tag.de/
Think I covered everything here. Have also had a chance to test the autoupdate.
> Add Mp3tag (v2.86)

- robo3t.json
URLs were moved into a modal. Fixes checkver.
> Update robo3t checkver

- everything.json
See https://github.com/lukesampson/scoop/issues/1981
> Add pre_install to everything

- godot.json
[Godot 3.0 was released recently.](https://godotengine.org/article/godot-3-0-released)
> Update Godot to version 3.0

- snaketail.json
> Added SnakeTail v1.9.0

- gcc-arm-none-eabi.json
> Update gcc-arm-none-eabi checkver

- php-nts-xdebug.json
Updated to latest and switched autoupdate to reference vc15
> Update Xdebug for NTS

- idea.json
> Add shortcuts to idea.json

- cpu-z.json
It's a GUI, and launching it from cmd doesn't work as it requires admin permissions.
> Add shortcuts for CPU-Z

- qutebrowser.json
Added qutebrowser!
Feel free to fix any problem! 👍 
(I can be never sure "checkver" and "autoupdate" part! Please check. I will be very happy any guidance about those parts!)
> Added qutebrowser!

- vifm.json
Added vifm. (vi like file manager)
> Added vifm!

- yatqa.json
> Update yatqa to version 3.9b

- hostsman.json
> Fix hostsman checkver

- Scoop-Bucket.Tests.ps1
lukesampson/scoop#2024 moved some DLLs and I guess it will break those tests.
See also lukesampson/scoop#2034
Best regards,
Philippe Crama
> Adapt to path change of validator dlls from lukesampson/scoop#2024

- paint.net.json
Not sure if the `.` in the name is a problem. If so it could be renamed `paintdotnet`.
Also it requires .Net 4.7.1 installed to run. Don't know if that's a problem.
Thanks for the help :)
> Add Paint.NET

- pwsh.json
> Add PowerShell 6

- x64dbg.json
Added x64dbg (with x32dbg) version snapshot_2018-02-14_22-42!
Feel free to edit any mistakes!
> Add x64dbg (with x32dbg) v:snapshot_2018-02-14_22-42!

- sdl2.json
Simplify build script by using SDL2 dual arch MSVC bundle
> Simplify sdl2.json

- mitmproxy.json
- pathod.json
Added mitmproxy and pathod v3.0.3!
Feel free to correct any mistakes!
> Added mitmproxy and pathod v3.0.3!

- jd-gui.json
- mqtt-spy.json
- terminals.json
Add terminals 🌐 
Also ran the formatter...
> Add terminals version 4.0.1

- kdiff3.json
Fixing kdiff3 SourceForge Address!
> Fixing kdiff3 SourceForge Address!

- renderdoc.json
> Fixing RenderDoc Shims!

- springboot.json
Add manifest to install Spring Boot CLI (https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started-installing-spring-boot.html)
> Add springboot manifest

- sfk.json
Fixing SFK SourceForge Address! #829
> Fixing SFK SourceForge Address!

- sqlopsstudio.json
Adds latest preview version of [SQL Operations Studio](https://docs.microsoft.com/en-us/sql/sql-operations-studio/what-is) ([GitHub Repository](https://github.com/Microsoft/sqlopsstudio/)).
Is there a guide for adding new packages? I searched but couldn't find one. Any feedback would be greatly appreciated.
> Add Sql Operations Studio

- ziglang.json
Ziglang: a programming language designed for robustness, optimality, and clarity.
> Add Ziglang v0.2.0

- bleachbit.json
first app manifest, so please critique and I will make any changes necessary. thanks.
> add bleachbit

- freeclipboardviewer.json
http://www.freeclipboardviewer.com/
> Add freeclipboardviewer

- wxhexeditor.json
https://github.com/EUA/wxHexEditor
No persist files as settings are stored in registry :(
> Add wxHexEditor

- retroarch.json
RetroArch is a frontend for emulators, game engines and media players.
> Adds RetroArch Emulator Frontend

- oni.json
> Added Oni v0.3.1!

- pycharm.json
I wanted to add a PyCharm to the list of applications.
Thank you again.
> Adding IDEA's PyCharm

- jd-cmd.json
Next to https://github.com/lukesampson/scoop-extras/blob/master/jd-gui.json i added jd-cmd
> jd-cmd.json

- boot-clj.json
> add: boot-clj - http://boot-clj.com

- filezilla.json
I changed the source of the hash in autoupdate.
> filezilla.json: Changed hash source in autoupdate

- serve.json
Hi, this PR would add [serve](https://github.com/philippgille/serve) to the extras bucket.
If you have any questions or improvement suggestions please let me know so I can improve the app or the manifest.
Closes philippgille/serve#4
P.S.: Scoop is awesome!
> Add serve version 0.2.0

- shadowsocks.json
persist `gui-config.json` file.
> Create persist data for shadowsocks config

- dnSpy.json
> Adding dnSpy

- kdenlive.json
> Add Kdenlive

- sysinternals.json
For some reason, the hash has changed.
> Update sysinternals hash

- dnsjumper.json
I wrote this app manifest for myself, but I think this little and useful software belongs here (I was quite surprised it wasn't here already, actually. Is there maybe already another app that makes this one redundant?).
Also, this is one of my first attempts in writing an app manifest. I believe it's fine, but please give me a feedback if something is wrong and/or can be improved.
> Add manifest for Dns Jumper

- emacs.json
Directory structure of the GNU server seems has been changed.
> Update download urls for Emacs

- pandoc-crossref.json
https://github.com/lierdakil/pandoc-crossref
"pandoc-crossref is a pandoc filter for numbering figures, equations,
tables and cross-references to them."
> Add pandoc-crossref

- ditto.json
I made sure that settings and the previously saved clipboard texts get persisted when updating ditto.
> Persist ditto settings and clipboard database

- idea-eap.json
- idea-ultimate-eap.json
- idea-ultimate.json
- idea.json
Updated the shortcut name for IDEA Community Edition and added shortcuts for the 3 other versions
> Fix shortcuts for IntelliJ IDEA products

- foxe.json
Firstobject's free XML editor for Windows is called foxe. 
It loads big files (multi-megabyte) fast and 
lets you format XML and edit HTML and any loosely formed XML or other markup. 
more info: http://www.firstobject.com/dn_editor.htm
> Adding foxe to extras bucket

- pixie.json
oldie but goodie tiny color picker
http://www.nattyware.com/pixie.php
> Adding pixie to extras bucket

- executor.json
This is a multi purpose launcher and a more advanced and customizable version of windows run.
A hidden gem: Slickrun + Launchy
http://executor.dk/
> Adding executor to extras bucket

- posh-git.json
posh-git is a PowerShell module which provides Git/PowerShell integration.
more info:  http://dahlbyk.github.io/posh-git/
> Adding posh-git to extras bucket

- freecommander.json
windows explorer ++
https://freecommander.com/en/summary/
> Adding freecommander to extras bucket

- musescore.json
Adding [MuseScore](https://github.com/musescore/MuseScore) to the extras bucket.
> Add MuseScore version 2.3.1

- boostnote.json
A "note-taking" tool mostly for programers, free cousin of "Cacher" with less features.
Again not sure about the manifest and standards, but at least working for me.
> add boostnote version 0.11.7

- vscode-insiders-portable.json
- vscode-portable.json
- vscode.json
> Disable portable mode of VS Code

- aida64extreme.json
> AIDA64 Extreme is an industry-leading system information tool, loved by PC enthusiasts around the world, which not only provides extremely detailed information about both hardware and installed software, but also helps users diagnose issues and offers benchmarks to measure the performance of the computer.
> Add AIDA64 Extreme

- beyondcompare.json
> Beyond Compare is a multi-platform utility that combines directory compare and file compare functions in one package. Use it to manage source code, keep directories in sync, compare program output, etc.
> Add Beyond Compare

- microsip.json
> MicroSIP - open source portable SIP softphone based on PJSIP stack for Windows OS.
https://www.microsip.org/
> Add MicroSIP

- msiafterburner.json
> MSI Afterburner is the world's most recognized and widely used graphics card overclocking utility which gives you full control of your graphics cards. Works with all graphics cards vendors.
https://www.msi.com/page/afterburner
> Add MSI Afterburner with RTSS

- speedfan.json
> SpeedFan is a system monitor for Microsoft Windows that can read temperatures, voltages and fan speeds of computer components. It can change computer fan speeds depending on the temperature of various components.
http://www.almico.com/speedfan.php
> Add SpeedFan

- syncbackpro.json
> SyncBackPro, the professional's tool to backup, synchronize, and restore data files.
https://www.2brightsparks.com/syncback/sbpro.html
> Add SyncBackPro

- mpv.json
> mpv: Fix hashes

- firefox-beta.json
- firefox-developer.json
- firefox-esr.json
- firefox-nightly.json
- firefox.json
Also adds license and description.
> firefox: extract instead of running installer

- flutter.json
This change set was generated with `.\bin\formatjson.ps1` based on the changes in https://github.com/lukesampson/scoop/pull/2444. Opening as a PR for demonstration purposes.
> Normalize multi-line strings to string arrays

- speedyfox.json
[https://www.crystalidea.com/speedyfox](https://www.crystalidea.com/speedyfox)
Boost Firefox, Skype, Chrome, Thunderbird in a Single Click!
- Boost Startup in up to 3 times!
- Speed-up browsing history
- Overall quicker operation
- Smaller profile size
> Add speedyfox version 2.0.23

- cura.json
[https://ultimaker.com/en/products/ultimaker-cura-software](https://ultimaker.com/en/products/ultimaker-cura-software)
Ultimaker Cura prepares your model for 3D printing.
x64 version only
> Add cura version 3.4.1

- texteditoranywhere.json
https://www.listary.com/text-editor-anywhere
> Add Text Editor Anywhere

- xx-net.json
> Add XX-Net

- monero.json
[Monero](https://getmonero.org/) is a private, secure, untraceable, decentralised cryptocurrency.
> Add Monero

- dismplusplus.json
[DISM++](https://www.chuyu.me/en/index.html) is a gatis Windows utility similar to DISM, but with a GUI and based on CBS.
> Add DISM++

- psiphon3.json
> Add Psiphon3

- xx-net.json
Should be changed to 
<del>`$dir\\code\\$version\\launcher\\web_ui\\favicon.ico`</del>
`$dir\\code\\default\\launcher\\web_ui\\favicon.ico`.
> XX-Net: Fix shortcut icon

- lunacy.json
Per discussion here:
https://github.com/icons8/lunacy-docs/issues/17
> Updating license link to correct version

- peerblock.json
; and fix checkver ...though I don't know whether I'm sane now or not
> PeerBlock: Improve autoupdate for its freak status

- listenmoeclient.json
It's a simple portable app that allows you to listen to https://listen.moe without using your browser.
First time contributing something like this, so please tell me if there is something wrong.
> Add listen.moe Windows Client

- mediainfo-gui.json
> Add MediaInfo GUI version 18.05

- unetbootin.json
> Add UNetbootin version 661

- xmousebuttoncontrol.json
Closes #1196 
Creating XML elements as text. I don't think it's neccessary to create it using some new XML, XMLAttributs,...
Not sure how this repo cares about check for updates, but I disable them always when it's possible. 
It could be disabled by adding `<CheckVersion Days=\"5\" Enable=\"false\" Beta=\"false\" />` into settings file.
> Add X-MouseButtonControl

- thunderbird.json
Add x64 version,  en-US locale only.
> thunderbird: Add x64 version

- xmedia-recode.json
> xmedia-recode: Fix extract_dir name

- flutter.json
Corrected autoupdate URL to use version provided by checkver.
> Corrected autoupdate URL

- azure-cli.json
> Fix for issue 1263

- jdownloader.json
- mqtt-spy.json
- tomcat.json
See scoop issue [#2622](https://github.com/lukesampson/scoop/issues/2622).
> Remove/update suggests for oraclejre/-server

- eclipse-mat.json
Ref https://github.com/lukesampson/scoop-extras/commit/ee313fc7c835c9c53c668ff3e04402c75d8f4fe7#comments
> eclipse-mat: Update regex to match releasenumber better

- textadept.json
Closes https://github.com/lukesampson/scoop-extras/issues/1293
> fixed the hashcode for text adept

- lockhunter.json
Lockhunter is a file unlocker :smile:
> Add lockhunter. Closes #1301.

- terminus.json
Since the release of terminus nupkg was gone, changed to portable version
> fix terminus auto_update

- jdownloader.json
> JDownloader: Change to nightly

- jitsi-meet-electron.json
Hey guys,
What do you recommend for auto updating hash, when the publisher is not publishing one. 
Thx
> Add jitsi-meet-electron.json

- netbeans.json
> Netbeans updated to 9.0

- gpu-z.json
update to version 2.12.0
correct dot in checkver re
add bin
> gpu-z: Update to version 2.12.0

- rufus.json
- smartty.json
* updated rufus urls
* updated smartty homepage url
> rufus: update links

- lightshot.json
Lightshot is a utility tool for taking screenshots. See more at https://prnt.sc
This PR contains the Lightshot app manifest. The manifest has 2 principal configurations:
- Application autostart on install
- Application autostart on Windows startup
> Add Lightshot version 5.4.0.35

- ccleaner.json
Not download correct file with / without aria2, html page only
1 redirect http 301
2 redirect JavaScript
correct direct link
> ccleaner: Fix download link

- altools.json
Changed #dl.7z to #/dl.7z in URL for consistency
> Fix ALTools URL

- paint.net.json
- Bump version to 4.1.3
- Use architecture specific installers
> Paint.net tweaks

- azuredatastudio-insiders.json
- azuredatastudio.json
Adds [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio), previously released under the preview name SQL Operations Studio. Also, adds a insiders version as well.
This is based on the SQL operations studio configuration.
> Add Azure Data Studio

- krita.json
- Add bin
@brandon93s What was purpose of deleting 32bit version in  c55eeff5600348e5320d9e8baf4e7b2893d329d7 ??
> Krita: Add 32bit version

- zlocation.json
ZLocation is an improved version of Jump-Location:
https://github.com/vors/ZLocation
> Add ZLocation Powershell module

- astrogrep.json
- http://astrogrep.sourceforge.net/
- AstroGrep is a Microsoft Windows grep utility. Grep is a UNIX command-line program which searches within files for keywords.
> Add: Astrogrep

- ldap-admin.json
Added LDAP Admin with tested autoupdate.
> Add: LDAP Admin

- steam.json
- Remove my fingerprints / signatures
- Simplify bin
- Don't create folders in installer script, since persisted directories are created when does not exists.
> Steam: Tweaks

- grafana.json
> Grafana 5.3.2

- spytify.json
Not much to say about this one. Stores its config in `C:\Users\USER\AppData\Local\jwallet\`.
> Add Spytify

- chromium-dev.json
Per https://github.com/lukesampson/scoop/issues/2736
> chromium-dev: Update to 71.0.3576.0 (manually)

- onefetch.json
Neotfetch functionality for git projects.
Note: there's no autoupdate (yet) since there's only been one release, so i can't tell if the release archive names are consistent.
Also proof-read the `notes` please.
> Add onefetch v1.0.0

- scallion
- scallion.json
A PR a day keeps the inactivity at bay ^^
> Add Scallion v2.1

- fsviewer.json
Per https://github.com/lukesampson/scoop/issues/2736
> fsviewer: Update to 6.7 (manually)

- kdenlive.json
Per https://github.com/lukesampson/scoop/issues/2736
> kdenlive: Update to 18.08.2 (manually)

- 3rvx.json
- Fix checkver
- Persist Settinngs
> 3rvx: Tweaks

- mobaxterm.json
- Add autoupdate
- Bumped to 11.0
- Precrete non existing persist files
- Rename executable (allow updates using Excavator)
> MobaXterm: Tweaks

- sharex.json
After each update of sharex you need to import settings manually from sxb file.
In ShareX folders are located settings (history, destination configuraion) and tools (ffmpeg downloaded for GIF capture)
> sharex: Persist ShareX Folder

- wurl.json
i considered PR'ing this to the main bucket, but stumbled over "reasonably well-known and widely used". maybe later.
> Add wurl v1.0.1

- pdfsam.json
This PR adds an app manifest for pdfsam: https://github.com/torakiki/pdfsam.
> Add pdfsam manifest

- kitty.json
> kitty: Update to 0.70.0.6 (and move off of fosshub)

- terminus.json
> terminus: fix auto-update

- geany.json
> add geany 1.33

- terminus.json
> terminus: fix add extract_dir and remove pre post install

- kitty.json
Until @rasa fixes autoupdate 🙂 
#1476 
#1471
> kitty: manual update to 0.70.0.7

- task.json
https://github.com/go-task/task
Thanks for your great software. I've added a simple task runner written in Go, called [Task](https://taskfile.org), so could you review it?
Anyone who need it ASAP, use https://gist.github.com/lambdalisue/f6c02275d2be63b82abe7921a5a6b71e
> Add go-task/task

- cacher.json
- Remove junk folder after installation
> cacher: Fix hash extraction

- blink1control2.json
> [blink1control2] Bumped 2.2.1

- inboxer.json
> [inboxer]: Use hash from vendor

- fritzing.json
A popular tool for hardware tinkerers to layout their sketches and PCBs
> Add fritzing

- zotero.json
> Add Zotero

- patchcleaner.json
Which name should the json file have? "patchcleaner" or better "win-patchcleaner"?
> Added PatchCleaner

- CommandBox.json
Added commandbox coldfusion development tool:
"CommandBox is a standalone, native tool for Windows, Mac, and Linux that will provide you with a Command Line Interface (CLI) for developer productivity, tool interaction, package management, embedded CFML server, application scaffolding, and some sweet ASCII art."
> Add command box .json

- alacritty.json
- winpty.json
Alacritty from https://github.com/jwilm/alacritty
> Add Alacritty terminal emulator

- gitextensions.json
Resolves #1516 
Note, I did not attempt to update checkver or autoupdate. I only updated version, url and hash
> updated git extensions to v3.00.00

- riot.json
Is an electron app and persistence problem is solved the scoop way.
> Add riot chat app, a matrix.org client

- awareness.json
Awareness is an application that sits in your taskbar and makes a Tibetan singing bowl sound every hour of continuous computer use, and then the sound stops when you take a 5 minute break.
Awareness is a pretty old application so there are no updates and it has no version listed, but it's been useful lately at work
> Add awareness.

- flutter.json
Flutter is now updating to stable version.Please update its manifest.
> update flutter manifest to stable version

- ueli.json
Add ueli, a keystroke launcher.
> Add ueli v7.1.0

- storageexplorer.json
> Fixes storageexplorer v1.6.1 hash check

- stunnel.json
Added a note about the change from being a 32 bit application to a 64 bit.
Closes #1535
> Stunnel: Update to version 5.50, change to 64 bit.

- gcc-arm-none-eabi.json
> gcc-arm-none-eabi: Update to version 8-2018-q4-major

- portable-virtualbox.json
Due to this launcher's disability to download integrated installer, I added them into the manifest both.
> Add Portable-VirtualBox

- ldplayer.json
An Android emulator optimized for mobile gaming with lower resource consumption
> Add LDPlayer

- ConEmu-Color-Themes.json
- Install-ConEmuTheme.json
A collection of conemu themes with a powershell script to help user adding them into conemu.xml
> Add ConEmu-Color-Themes

- mcomix.json
> Add MComix

- greenshot.json
- Add license
- Persist all configurations
> GreenShot tweaks

- anaconda3.json
Change file hash and autoupdate to sha256
> Anaconda3: Fix autoupdate.hash to sha256

- musescore.json
> Fix musescore URL

- istio.json
> istio: Initial commit for istio-1.0.5

- tcpipmanager.json
- Add:
- license
- description
- checkver
- autoupdate
- Persist bin folder
- Use direct sourceforge url
- For automatic hash extracion
> Tweak tcpipmanager

- texteditoranywhere.json
- Persist config
- Simplify checkver
> Texteditoranywhere: Tweaks

- sumatrapdf.json
- persist and pre-create Settings file
- https://www.sumatrapdfreader.org/settings.html
- > The file is stored in %APPDATA%\SumatraPDF directory for the installed version or in the same directory as SumatraPDF.exe executable for the portable version.
- Disable check for update on default
- Check version from changelog instead of some javascript file.
> Tweak SumatraPDF

- anaconda3.json
Fix anaconda3.json:
- Add `bin` as miniconda3.json and python.json
- Simplify `url`, `autoupdate.url` and `installer.file`
- Correct `uninstaller.file`
- Persist `envs` as miniconda3.json
> Anaconda3: Fix manifest

- puttytel.json
Previous one was for matching download page, not homepage
> puttytel: fix checkver

- bucket/irfanview.json
Yes, mea culpa, mea maxima culpa (#1632). In my defense, you didn't notice it, either ;)
> Fix IrfanView Hashes

- bucket/qtox.json
- Closes lukesampson/scoop#2959
> Add qTox 1.16.3

- bucket/slack.json
> fix(hash): Update Slack's 64bit hash

- bucket/squalr.json
- Closes lukesampson/scoop#3002
> Add Squalr 2.3.13

- bucket/trilium.json
Add trilium, a personal knowledge base builder
> trilium: Add version 0.28.3

- bucket/universal-ctags.json
Originally opened https://github.com/scoopinstaller/nightlies/pull/3 but as discussed that repo is dead and here is a better choice.
> Add universal-ctags

- bucket/subtitleedit.json
Their update process is consistent, so you could assume, that there will be portable version and next will be Finnish version.
> SubtitleEdit: Add hash extraction

- bucket/altdrag.json
This was requested by @stuaxo in https://github.com/lukesampson/scoop/issues/3054.
This looks pretty interesting (and it works without administrator privileges), so I might use it too :slightly_smiling_face:
> Add AltDrag version 1.1

- bucket/audioswitcher.json
> Add audioswitcher manifest

- bucket/bulk-crap-uninstaller.json
- bucket/deluge.json
- bucket/franz.json
- bucket/jpegview.json
- bucket/ldplayer.json
- bucket/nimbleset.json
- bucket/nimbletext.json
- bucket/openhardwaremonitor.json
- bucket/rambox.json
- bucket/screentogif.json
- bucket/taiga.json
- bucket/todolist.json
- Totolist
- Use https for downloading
- Simplify pre_install code
- Add missing descriptions
> [Multiple manifests] Convert homepages to https when possible

- bucket/pass-winmenu-nogpg.json
This version of pass-winmenu is for people that already have gpg installed.
> Add manifest for pass-winmenu-nogpg

- bucket/blender.json
No need to use `$match` variables, when you can use internal Head variable of autoupdate
> Blender: Optimize checkver and autoupdate

- bucket/enpass.json
> Enpass: Fix installation

- bucket/ccleaner.json
> CCleaner: Fix installation

- bucket/yubioath.json
> Add yubioath 4.3.5

- bucket/shutup10.json
For issue #1658 
This is my first manifest, so hopefully I haven't missed anything.
> Add O&O ShutUp10 1.6.1401

- bucket/cheat-engine.json
> cheat-engine: Fix hash

- bucket/arduino-portable.json
> Add arduino portable

- bucket/doublecmd.json
Change checkver url to wiki
- Closes #1742
> Doublecmd: Bumped to 0.9.1

- bucket/tinymediamanager.json
https://www.tinymediamanager.org/
http://release.tinymediamanager.org/
> Add tinyMediaManager version 2.9.16_42413ce

- bucket/ibmcloud-cli.json
See https://github.com/IBM-Cloud/ibm-cloud-cli-release/issues/73
> ibmcloud-cli: Fixed hash

- bucket/nsudo.json
- Closes lukesampson/scoop#3144
> Add NSudo 6.2.1812.31

- bucket/p4merge.json
> Add vcredist2013 to p4merge dependencies

- bucket/shadowsocks.json
When I installed shadowsocks, I couldn't start it because it was created as a folder type.
> Fix shadowsocks.json

- bucket/keepass-plugin-keetraytotp.json
https://github.com/victor-rds/KeeTrayTOTP
> Add KeeTrayTOTP version 0.97-Beta (plugin for KeePass 2.x)

- bucket/logstalgia.json
https://logstalgia.io/
Add logstalgia version 1.0.9
Current release is 1.1.2, but for windows is 1.0.9
> Add logstalgia version 1.0.9

- bucket/jmeter-pm.json
- bucket/jmeter.json
Tested and used for a while from a private repo.
> Add jmeter and jmeter plugin manager

- bucket/x64dbg.json
close #1775 . (ping https://github.com/lukesampson/scoop/pull/2897#issuecomment-447636572)
> x64dbg: ensure files persist

- bucket/meow.json
- bucket/shim.json
- Change `checkver` (same as https://github.com/lukesampson/scoop/pull/3171)
> shim, meow: Modify checkver

- bucket/kombucha.json
Add [Kombucha](https://github.com/lptstr/kombucha), a simple package manager for PowerShell.
Oh, and I didn't use any datetime hack 😜
> Add Kombucha v0.1.0

- bucket/php-nts-xdebug.json
- bucket/php-xdebug.json
php73-xdebug in versions will be created soon.
> php-xdebug: Update to php 7.3

- bucket/apache-directory-studio.json
- bucket/axis.json
- bucket/netbeans.json
- bucket/spark.json
- bucket/tomcat.json
- bucket/zeppelin.json
> Use non mirror apache url

- bucket/appbuster.json
- bucket/regeditor.json
- bucket/shutup10.json
- Add [AppBuster](https://www.oo-software.com/en/ooappbuster), [RegEditor](https://www.oo-software.com/en/ooregeditor) by O&O Software
- Fix ShutUp10's persist file creating.
> AppBuster, RegEditor: Add some O&O Freetools

- bucket/jaspersoft-studio.json
https://community.jaspersoft.com/project/jaspersoft-studio
The Eclipse-based report development tool for JasperReports and JasperReports Server
> Add jaspersoft-studio version 6.6.0

- bucket/inbucket.json
https://www.inbucket.org/
Inbucket is an email testing application; it will accept messages for any email address and make them available to view via a web interface.
> Add inbucket version 2.1.0

- bucket/msiafterburner.json
Newest version do not have installer in a separate folder anymore
Closes https://github.com/lukesampson/scoop-extras/issues/1821
> Fix for MSI Afterburner failing to extract

- bucket/7tt.json
- bucket/workspaceutilities.json
Workspace Utilities provides hotkey access to custom window sizes and layouts.
The utility is on SourceForge with source, but no license is specified anywhere.
Also, I wasn't able to find the version number anywhere, so no autoupdate :-(
> Add Workspace Utilities version 1.0.0.6

- bucket/flutter.json
Basically the flutter manifest was outdated. Website changed in the meantime...
Also added `dart` as a dependency.
> Updated flutter manifest to work with latest flutter website.

- bucket/standardnotes.json
Hey, I have added Standard Notes in version _3.0.6_. The application wasn't in this bucket before.
> standardnotes: Add version 3.0.6

- bucket/ktlint.json
Could be moved to main bucket since, it's only command line.
> ktlint: Simplify manifest

- bucket/winaero-tweaker.json
> Add Winaero Tweaker 0.14

- bucket/lepton.json
- [https://hackjutsu.com/Lepton/](https://hackjutsu.com/Lepton/)
- A lean code snippet manager based on GitHub Gist
> Add Lepton

- bucket/paint.net.json
paint.net did not create any shim. Added bin entry.
> added bin entry for paintdotnet.exe shim

- bucket/plex-player.json
> plex-player: Change depends

- bucket/simplenote.json
> Add SimpleNote version 1.5.0 (#1879)

- bucket/sysinternals.json
Downloaded file from sysinternals.com and calculated sha256 hash.
> Fix hash, fixes #1888

- bucket/flutter.json
To query using JSONPath needs multi-conditions, which I don't know how to do, so just use simple regex.
> flutter: Fix checkver and autoupdate

- bucket/posh-git.json
Also added the proper checkver
> posh-git: Update to version 0.7.3.1

- bucket/lantern-client.json
> lantern-client: fix hash

- bucket/keepass.json
> KeePass: Fix persist

- bucket/ipfilter-updater.json
> ipfilter-updater: fix url

- bucket/kicad.json
> KiCad: Fix url and hash

- bucket/lamexp.json
Please merge after https://github.com/lukesampson/scoop/pull/3263, close #1907
> lamexp: Add version 4.17.2188

- bucket/flat-assembler.json
> Add flat assembler 1.73.09

- bucket/album-art-downloader.json
> Album Art Downloader: Add version 1.03

- bucket/lazarus.json
> Lazarus: Add version 2.0.0

- bucket/fsviewer.json
> fsview: Fix persistence

- bucket/vibrance-gui.json
> Add vibranceGUI 2.3

- bucket/zmc.json
Close https://github.com/lukesampson/scoop/issues/3264
PS. I don't know why the request issue is in scoop-main...
> zmc: Add version 7.0.0

- bucket/cpu-z.json
> cpu-z: Fix hash and add persist

- bucket/chrome.json
- Closes #1805 (since it is stale)
#400
> Add Chrome 73.0.3683.86

- bucket/skype.json
> Add Skype 8.42.0.60

- bucket/sysinternals.json
> sysinternals: Fix hash

- bucket/hexchat.json
[innounp.log](https://github.com/lukesampson/scoop-extras/files/3026074/innounp.log)
Unpacking works and portability too.
> hexchat: getting rid of UAC prompt

- bucket/kitty.json
> Update kitty to 0.70.0.10

- bucket/totalcommander.json
> Totalcommander 9.22a: fix hash

- bucket/appium.json
Close #1801 (JMeter is in extras)
> Appium: Add version 1.12.0

- bucket/winfetch.json
added manifest for [WinFetch](https://github.com/lptstr/winfetch) v1.0.0. Basically Neofetch for Windows.
> Add Winfetch v1.0.0

- bucket/scribus.json
>  Scribus: Add version 1.4.8 

- bucket/tribler.json
Privacy enhanced BitTorrent client with P2P content discovery
> add tribler

- bucket/safebrowser.json
> add safebrowser

- bucket/accesser.json
A tool which can help you bypass SNI RST
> add Accesser

- bucket/playnite.json
Created an App Manifest for [Playnite](https://github.com/JosefNemec/Playnite).
> playnite: Added Playnite version 4.74

- bucket/dbeaver.json
Remove 32bit support per [6.0.1 release](https://dbeaver.io/2019/03/25/dbeaver-6-0-1/)
> Update dbeaver to 6.0.2

- bucket/regeditor.json
Otherwise the user is prompted to specify the type.
> regeditor: Add ItemType to preinstall entry

- bucket/pocketsphinx.json
- bucket/sphinxbase.json
- bucket/sphinxtrain.json
> Add installation manifest for pocketsphinx, sphinxbase and phinxtrain

- bucket/nuget-package-explorer.json
Add hash from Chocolatey.
Please also consider https://github.com/lukesampson/scoop/pull/3249
> nuget-package-explorer: Change url to Chocolatey

- bucket/deepgit.json
- bucket/smartgit.json
- bucket/smartsvn.json
- bucket/smartsynchronize.json
- Homepage: https://www.syntevo.com
- DeepGit: Git Archaeology Tool. [Homepage](https://www.syntevo.com/deepgit/)
- SmartGit: A graphical Git client with support for SVN and Pull Requests for GitHub and Bitbucket. [Homepage](https://www.syntevo.com/smartgit/)
- SmartSVN: A popular Subversion client. [Homepage](https://www.smartsvn.com/)
- SmartSynchronize: An advanced file and directory compare tool. [Homepage](https://www.syntevo.com/smartsynchronize/)
> Add syntevo tools: DeepGit, SmartGit, SmartSVN, SmartSynchronize

- bucket/transgui.json
A portable and lightweight transmission client.
w/ autoupdate entry
> Add Transmission Remote GUI

- bucket/vscodium-portable.json
- bucket/vscodium.json
Free/Libre Open Source Software Binaries of VSCode
> VSCodium: Add version 1.33.0

- bucket/papercut.json
Simple SMTP Desktop Email Receiver
> Papercut: Add version 5.5.1

- bucket/mpc-be.json
- bucket/mpv-git.json
- bucket/patchcleaner.json
- bucket/win32-disk-imager.json
- Closes lukesampson/scoop#2199
> Convert sourceforge urls to use downloads mirror

- bucket/windowsspyblocker.json
Block spying and tracking on Windows
> add windowsspyblocker

- bucket/celestia.json
kinda refs lukesampson/scoop#3339
> Add Celestia v1.6.1

- bucket/slack.json
1d699d9d1f3b06d621533807fbb1598b4629e913 -> 9b8fe53f4a86d84734a6dfa4c87044774dbe5e26
fixes https://github.com/lukesampson/scoop-extras/issues/2047
> slack: Hash fix

- bucket/inno-setup.json
Wait until https://github.com/lukesampson/scoop/issues/3407 is fixed.
> Inno-Setup: Fix url

- bucket/inno-setup.json
Reverts lukesampson/scoop-extras#2067
> Revert "Inno-Setup: Fix url"

- bucket/foxit-reader.json
> Foxit Reader: Fix hash

- bucket/elasticsearch.json
- Closes #2061
- Closes #2051
- Bump to 7.0.0
- Simplify bins
- Remove suggest to JDKs (JDK is bundled)
- Lint `post_install`
- Add license
There are lots of binaries. What needs to be added? /cc @carsonhynes
> elasticsearch: Fix manifest

- bucket/listary.json
> Listary: Add version 5.00.2843

- bucket/totalcommander.json
From today total commander download page added more whitespaces
> totalcommander: Fix checkver

- bucket/libreoffice-fresh.json
- Closes #2042 
- Change hash mode to metalink
- Use https download urls
- Added description
> LibreOffice-fresh: suggest vcredist2015

- bucket/boot-clj.json
- bucket/flutter.json
- bucket/ipscan.json
- bucket/jdownloader.json
- bucket/mqtt-spy.json
- bucket/ripme.json
- bucket/yed.json
> Update depends and suggests for Oracle Java

- bucket/caprine.json
> Add Caprine 2.30.2

- bucket/freecad.json
a common CAD tool for education
> Add FreeCAD version 0.18.16110

- bucket/pandownload.json
PanDownload is a third-party Baidu disk download tool.
> Add PanDownload version 2.1.0

- bucket/pandownload.json
Fix a bug in PanDownload: directory error.
> PanDownload: fix extract_dir

- bucket/traymond.json
A simple Windows app for minimizing windows to tray icons
> Add traymond version 1.0.2

- bucket/streamlink-portable.json
Sorry messed up last pr, this one should work.
> streamlink-portable: Added plugins to persist

- bucket/msbuild-structured-log-viewer.json
https://github.com/KirillOsenkov/MSBuildStructuredLog
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/246
> msbuild structured log viewer

- bucket/listen1desktop.json
One for all free music in China
- Closes #2099
> Add a new app: Listen1 desktop.

- bucket/sql-workbench-dev.json
- bucket/sql-workbench.json
> Added persist for sql-workbench

- bucket/freedownloadmanager.json
> Add freedownloadmanager version 5.1.38

- bucket/capframex.json
- bucket/ocat.json
- bucket/plex-player.json
This should be merged immediately after https://github.com/lukesampson/scoop/pull/3432.
> Fix 'Expand-DarkArchive'

- bucket/librecad.json
> Add librecad version 2.1.3

- bucket/koffee.json
Adding Koffee, which is my gui-based, keyboard-driven file explorer.
> Add koffee version 0.4.1

- bucket/languagetool.json
I added LanguageTool, a style and grammar checker.
languagetool.jar is a GUI application. languagetool-commandline.jar and languagetool-server.jar are command line tools.
> Add LanguageTool version 4.5

- bucket/noty.json
https://github.com/fabiospampinato/noty
> noty: Add version 2.2.0

- bucket/prime95.json
> prime95: fix hashes

- bucket/roughgrep.json
I am the maintainer of RoughGrep and willing to maintain this manifest in scoop extras
> Add RoughGrep https://github.com/vivainio/RoughGrep

- bucket/trafficmonitor.json
TrafficMonitor is a network monitoring suspension window software in Windows platform. It can display the current network speed, CPU and memory usage. It also support the functions of display in the taskbar, change skin and historical traffic statistics.
> Add TrafficMonitor

- bucket/kdenlive.json
> Adapt to refactored versions of kdenlive

- bucket/rapidee.json
> rapidee: Enable portable mode and better version extraction

- bucket/ssh-agent-wsl.json
Hello, I am new to scoop, so I would appreciate if someone could check this manifest.
- Is the auto-update part correct?
- Is there a way to make the notes more user-friendly, eg. by a script echoing the correct path instead of the hardcoded ones?
> Add ssh-agent-wsl version 2.2

- bucket/keepass-plugin-keeanywhere.json
Added support for KeeAnywhere Keepass plugin.
> Add KeeAnywhere (keepass-plugin-keeanywhere) version 1.5.1

- bucket/tinode-mysql.json
Should I also add tinode-rethinkdb?
> Add tinode-mysql 0.15.14

- bucket/accesser.json
Accesser release a hot fix but doesn't change the version.
> Accesser: Update hash

- bucket/cryptomator.json
as suggested by @porti on 938df7a
> cryptomator: add settings and logs to persist

- bucket/brackets.json
Add a short description for the software bracket. The short description is from its official web site.
> Add description for bracket.

- bucket/marktext.json
> marktext: Fix installer.script

- bucket/freedownloadmanager.json
> freedownloadmanager: Attach dependency

- bucket/tor-browser.json
Added 64-bit version, but installer for it doesn't allow 7zip extraction hence installer script. Autoupdate fixed too.
> Fix for #2186 and update to tor-browser

- bucket/mpv.net.json
> Add mpv.net version 4.1

- bucket/bugn.json
The only available window manager, hotkey daemon for Windows. Free, open source.
> Add bug.n: dynamic tiling window manager

- bucket/sysinternals.json
They updated it again apparently :)
> sysinternals: update archive hash

- bucket/autoit-script-editor.json
Shortcut is in `main/autoit` (https://github.com/ScoopInstaller/Main/pull/135)
> autoit-script-editor: Add version 19.102.1901.0

- bucket/rambox-pro.json
> rambox-pro: Fix manifest

- bucket/lunacy.json
Tested and working. .exe is 32-bit.
> lunacy: Update to 4.0.1 (manually)

- bucket/altair.json
- bucket/colon.json
- bucket/dn-tool-container.json
- bucket/hexo-blog-client.json
- bucket/hexo-client.json
- bucket/httptoolkit.json
- bucket/jasper.json
- bucket/local-browser.json
- bucket/metrogit.json
- bucket/open-log-viewer.json
- bucket/timeseriesadmin.json
- bucket/tweakstyle.json
- bucket/wordmark.json
- bucket/zettlr.json
- Altair: Beautiful feature-rich GraphQL Client.
- Colon: Flexible text editor.
- DN-Tool-Container: Convenience APP can install many small tools.
- Hexo Blog Client: Cross-platform hexo blog management client.
- Hexo Client: Cross-platform hexo client.
- HTTPToolkit: HTTP(S) debugging proxy, analyzer and client.
- Jasper: Flexible and powerful issue reader for GitHub.
- Local Browser: Share your localhost in a new way (peer to peer browser).
- MetroGit: Git visualization tool that's more than just git.
- Open Log Viewer: Multi-platform log viewer built with Electron and styled with Material Design.
- Time Series Admin: Administration panel and querying interface for InfluxDB databases.
- TweakStyle: Integrated Development Environment for Web Development.
- WordMark: Real time Markdown …
> Add some electron-based apps

- bucket/orca.json
Close https://github.com/lukesampson/scoop-extras/issues/2278
Orca 3 has been moved to `versions`.
> orca: Update to 5.0.18362.1

- bucket/mpv-git.json
- bucket/mpv.json
Should merge after https://github.com/lukesampson/scoop/pull/3366 is merged into 'master'.
> mpv: Change bin

- bucket/freedownloadmanager.json
Ref: https://github.com/lukesampson/scoop/pull/3487
Merge after above PR be merged.
> freedownloadmanager: Modify installer.script

- bucket/android-messages.json
- bucket/beaker.json
- bucket/caprine.json
- bucket/franz.json
- bucket/listen1desktop.json
- bucket/mockoon.json
- bucket/mqtt-explorer.json
- bucket/simplenote.json
- bucket/standardnotes.json
- Closes #2355 
- Closes lukesampson/scoop#3532
> fix(decompress): Regression from latest changes

- bucket/zeronet.json
Fix #2365
It's version is 0.7.0, indeed.
> zeronet: Fix hash and add 64bit

- bucket/musicbee.json
> musicbee: Add autoupdate

- bucket/chefdk.json
> chefdk: Fix checkver

- bucket/hain.json
> hain: Fix checkver

- bucket/inbucket.json
> inbucket: Fix checkver

- bucket/jaspersoft-studio.json
> Jaspersoft Studio: Remove 32bit

- bucket/monero.json
For 32bit, see https://github.com/ScoopInstaller/Main/pull/210
> monero: Remove 32bit and update to 0.14.1.0

- bucket/freecad.json
FreeCAD has official hash files, but with white spaces...
> freecad: Fix manifest and update to 0.18.2

- bucket/lightshot.json
Close https://github.com/lukesampson/scoop-extras/issues/2176
Close https://github.com/lukesampson/scoop-extras/issues/2418
> Lightshot: Remove extract_dir

- bucket/sc1.json
- bucket/scite.json
https://www.scintilla.org/SciTE.html
> SciTE: Add version 4.1.7 and Sc1

- bucket/foxit-reader.json
> Foxit-reader: Fix au

- bucket/sagemath-installer.json
Close https://github.com/lukesampson/scoop-extras/issues/1995 , by the way
> Sagemath: Update checkver

- bin/auto-pr.ps1
- bin/checkurls.ps1
- bin/checkver.ps1
- bin/formatjson.ps1
- bin/missing-checkver.ps1
> Fixed problem with spaces in paths in checkver script and others

- bucket/mp3tag.json
Seems like the devs uploaded a new file without changing the version.
> mp3tag: fix hash

- bucket/reaper.json
> reaper: Fix hash

- bucket/diskgenius.json
To close https://github.com/lukesampson/scoop-extras/issues/2440
> Add DiskGenius

- bucket/foobar2000.json
How does this happen though? :/
It looks legit...
> foobar2000: fix hash again

- bucket/kitty.json
Closes #2390.
Generated via https://github.com/lukesampson/scoop/pull/3518
> kitty: Update to 0.71.0.6 (manually)

- bucket/mupdf.json
> mupdf: Fix au.extract_dir and add au.hash

- bucket/ghostwriter.json
https://github.com/wereturtle/ghostwriter/issues/367
> Windows Download
A volunteer has kindly stepped up to provide a Windows installer here:
https://github.com/michelolvera/vs-ghostwriter
> ghostwriter: switch to latest forked version & add autoupdate

- bucket/vcredist.json
- bucket/vcredist2008.json
- bucket/vcredist2010.json
- bucket/vcredist2012.json
- bucket/vcredist2013.json
- bucket/vcredist2015.json
- bucket/vcredist2017.json
- bucket/vcredist2019.json
MERGE AFTER https://github.com/lukesampson/scoop/pull/3547
- Fix https://github.com/ScoopInstaller/Main/issues/200
- Fix https://github.com/lukesampson/scoop/issues/3554
> vcredist: Fix error when not run as administrator

- bucket/dosbox-x.json
Ref: https://github.com/ScoopInstaller/Main/pull/203#discussion_r299972925
> dosbox-x: Add version 0.82.19

- bucket/gimagex.json
**GImageX** ([Homepage](https://www.autoitconsulting.com/site/software/gimagex/)) is a free GUI tool for working with WIM files.
> GImageX: Add version 2.2.0

- bucket/euler.json
Its External Editor needs Java
> euler: Add version 2019-06-27

- bucket/maxima.json
home: http://maxima.sourceforge.net/
> maxima: Add version 5.43.0

- bucket/pov-ray.json
homepage: https://www.povray.org/
Latest stable edition is released 2013, and activately developed in https://github.com/POV-Ray/povray, but still in development release.
> pov-ray: Add version 3.7.0

- bucket/aria-ng-gui.json
https://github.com/Xmader/aria-ng-gui#ariang-gui-1
> Add AriaNgGUI

- bucket/tabula.json
Close https://github.com/lukesampson/scoop-extras/issues/2012
> Add tabula 1.2.1

- bucket/blender.json
> blender: fix blenderplayer.exe that doesn't exist.

- bucket/pscolor.json
I didn't write `checkver` and `autoupdate` because the project seems unmaintained and lacks fixed releases.
> PSColor: add version 1.0.0.0

- bucket/pcem.json
> pcem: Fix hash

- bucket/eclipse-committers.json
- bucket/eclipse-cpp.json
- bucket/eclipse-dsl.json
- bucket/eclipse-java.json
- bucket/eclipse-javascript.json
- bucket/eclipse-jee.json
- bucket/eclipse-mat.json
- bucket/eclipse-modeling.json
- bucket/eclipse-parallel.json
- bucket/eclipse-php.json
- bucket/eclipse-platform.json
- bucket/eclipse-rcp.json
- bucket/eclipse-reporting.json
- bucket/eclipse-rust.json
- bucket/eclipse-scout.json
- bucket/eclipse-sdk.json
- bucket/eclipse-testing.json
Change url to http. Or change to a https mirror.
> eclipse: Update checkver, au.hash

- bucket/zeronet.json
> Zeronet: Fix hash

- bucket/kitty.json
Mentioned in #2308. (Outstanding Excavator issues)
> Kitty: Update to version 0.71.0.7 (manually)

- bucket/gpu-z.json
> gpu-z: Fix au.hash

- bucket/fork.json
> Add Fork 1.37.2

- bucket/babelmap.json
A free character map application that allows you to browse through the entire Unicode character repertoire.
> Add BabelMap 12.1.0.1

- bucket/spacescape.json
http://alexcpeterson.com/spacescape/
**Application Source:** https://github.com/petrocket/spacescape
Spacescape is a free GUI tool to create space skyboxes.
The current manifest *seems to work*, at least on my computer (both locally and with the remote repo) - opening for review and eventual enhancement.
> Add spacescape (v0.5.1)

- bucket/meshlab.json
MeshLab is an open source tool for processing and editing 3D triangular meshes.
Homepage: http://www.meshlab.net
> MeshLab: Add version 2016.12

- bucket/makehuman.json
**MakeHuman** is an open source tool for making 3D characters.
Official homepage of MakeHuman: http://www.makehumancommunity.org/
note: MakeHuman has an official Github repo, but the "release files" in the official Github repo does not contain *binary releases* (.exe) 
> MakeHuman: Add version 1.1.1

- bucket/audacious.json
- bucket/exaile.json
- bucket/museeks.json
- bucket/musique.json
- bucket/quodlibet.json
- bucket/strawberry.json
- bucket/winyl.json
Update Winyl: Add 64bit architecture,
Add Exaile 4.0.0,
Add Quod Libet 4.2.1,
Add Museeks 0.11.0,
Add Musique 1.6,
Add Audacious 3.10.1,
Add Strawberry Music Player 0.5.5
> Add some open source music players

- bucket/megasync.json
> megasync: Fix hash

- bucket/dnsjumper.json
> dnsjumper: Fix hash

- bucket/foxit-reader.json
> foxit-reader: Fix installer script

- bucket/vieas.json
[Vieas](http://www.vieas.com/en/software/vieas.html) is an image viewer and converter with combination of two window forms.
> vieas: Add version 5.4.6.0

- bucket/testmace.json
See https://testmace.com/blog/2019/07/01/powerful-ide-to-work-with-api/ for `Freeware` license.
> testmace: Add version 0.0.1-beta.16

- bucket/dbeaver.json
> dbeaver: Fix hash

- bucket/subtitleedit.json
> subtitleedit: Fix hash

- bucket/anki.json
> anki: add 32bit version

- bucket/dualmonitortaskbar.json
https://sourceforge.net/projects/dualmonitortb/
A taskbar for the second monitor. 
- Taskbar on the every monitor
- Pinned programs
- Aero support
- Window manager
- Mirror mode
- Auto-Hide
- Notification area
- Start Button (BETA)
> Add DualMonitorTaskbar 1.22.021813

- bucket/kubebox.json
Add kubebox from https://github.com/astefanutti/kubebox
> Add kubebox version 0.6.0

- bucket/bgpkiller.json
- bucket/kitty.json
- bucket/megasync.json
- bucket/translucenttb.json
https://github.com/lukesampson/scoop-extras/search?q=taskkill&unscoped_q=taskkill
Remove potential dangerous forced task kills, which could lead to forced application exits while it is syncing (for example in with mega) or flushing data to file / db
Merge after lukesampson/scoop#3608 is in master
> Multi manifest: Remove taskkill uninstaller scripts

- bucket/firefox-beta.json
- bucket/firefox-developer.json
- bucket/firefox-esr.json
- bucket/firefox-nightly.json
- bucket/firefox.json
Ref: 
https://github.com/lukesampson/scoop-extras/pull/2124#issuecomment-496871239
https://github.com/lukesampson/scoop-extras/issues/2340#issuecomment-521883530
> Firefox: checkver

- bucket/bgpkiller.json
- bucket/kitty.json
- bucket/megasync.json
- bucket/translucenttb.json
Reverts lukesampson/scoop-extras#2727
> Revert "Multi manifest: Remove taskkill uninstaller scripts"

- bucket/retroarch.json
> RetroArch: fix hash

- bucket/cheat-engine.json
close https://github.com/lukesampson/scoop-extras/issues/2777
> CheatEngine: Fix checkver

- bucket/retroarch.json
close https://github.com/lukesampson/scoop-extras/issues/2781
> retroarch: fix checkver

- bucket/msiafterburner.json
> MSIAfterBurner: fix hash

- bucket/caprine.json
> Caprine: fix url

- bucket/nextcloud.json
Maybe we need something like `-gui` option, so we can always run gui from cmd.
> Nextcloud: add version 2.5.3

- bucket/quickviewer.json
Close https://github.com/lukesampson/scoop-extras/issues/2755
Persist doesn't works, so copy files manully.
> QuickViewer: Add version 1.1.6

- bucket/gpg4win-portable.json
gpgol and gpgex can't be portable. gpgex need to be add into context menu.
> gpg4win: portable

- bucket/filebot.json
* moved to `extras` from https://github.com/ScoopInstaller/Main/pull/370
> [ADD] FileBot 4.8.5

- bucket/franz.json
> Franz: fix checkver

- bucket/universal-ctags.json
> universal ctags: fix checkver

- bucket/soulseekqt.json
> soulseekqt: fix checkver

- bucket/powertoys.json
[PowerToys](https://github.com/microsoft/PowerToys) is a set of utilities for power users to tune and streamline their Windows experience for greater productivity.
This tools is made by Microsoft.
> powertoys: Add version 0.11.0

- bucket/bulk-rename-utility.json
> bulk-rename-utility: Add version 3.1.0.0

- bucket/fork.json
Close #1094
Version 1.39 of Fork s[upports Git directory through %forkgitinstance% environment variable](https://git-fork.com/releasenoteswin).
> fork: change git detection

- bucket/marktext.json
Fix #2825 
```
Usage: marktext [commands] [path ...]
Available commands:
--debug                   Enable debug mode
--safe                    Disable plugins and other user configuration
--dump-keyboard-layout    Dump keyboard information
-n, --new-window              Open a new window on second-instance
--user-data-dir           Change the user data directory
--disable-gpu             Disable GPU hardware acceleration
-v, --verbose                 Be verbose
--version                 Print version information
-h, --help                    Print this help message
```
> marktext: Add bin

- bucket/rtss.json
- Add standalone version of RivaTuner Statistics Server
- Migrates profiles from old MSI Afterburner persist structure
> rtss: Add version 7.2.3

- bucket/msiafterburner.json
> msiafterburner: Fix manifest

- bucket/retroarch.json
Fix https://github.com/lukesampson/scoop-extras/issues/2854 
Fix https://github.com/lukesampson/scoop-extras/issues/2858
> retroarch: fix hash for version 1.7.8v4

- bucket/storageexplorer.json
- Closes #2873 
- Closes #2874
> storageexplorer@1.10.0: Hash fix

- bucket/teamviewer.json
> Fix wrong teamviewer hash for new version

- bucket/debugviewpp.json
> DebugViewPP: Fix checkver

- bucket/webtorrent.json
See https://github.com/webtorrent/webtorrent-desktop/pull/1642
> Webtorrent: Remove 32bit

- bucket/euler.json
> Euler: fix ckeckver

- bucket/safebrowser.json
> Safebrowser: Fix autoupdate and installer

- bucket/yacreader.json
> Yacreader: Fix checkver

- bucket/waifu2x-caffe.json
Restore of #2846. Original pull closed due to branch conflict in the clone repo.
> waifu2x-caffe: Add version 1.2.0.2

- bucket/bleachbit.json
> bleachbit: fix checkver

- bucket/mpc-be.json
mpc-be: Fixing an entry in the pre-install section
> mpc-be: Fixing an entry in the pre-install section

- bucket/insomnia.json
> Insomnia: fix checkver

- bucket/gog-galaxy-plugin-downloader.json
Proposed to move here from https://github.com/Calinou/scoop-games/pull/61
> gog-galaxy-plugin-downloader: Add version 0.0.3

- bucket/rainmeter-portable.json
- bucket/rainmeter.json
> rainmeter: fix checkver

- bucket/vscode-insiders-portable.json
- bucket/vscode-insiders.json
- bucket/vscode-portable.json
- bucket/vscode.json
- bucket/vscodium-portable.json
- bucket/vscodium.json
close https://github.com/lukesampson/scoop-extras/issues/2990
> vscode: fix post_install scripts

- bucket/axiom.json
Axiom is an FFmpeg GUI for Windows.
> axiom: Add version 1.7.6.0-alpha

- bucket/dual-monitor-tools.json
Dual Monitor Tools is a utility for users with dual or multiple monitor setups.
> Dual-Monitor-Tools: Add version 2.7

- bucket/treesize-free.json
Add TreeSize Free:
https://www.jam-software.de/treesize_free/
> TreeSize-Free: Add version 4.3.1

- bucket/archi.json
> Archi: fix checkver

- bucket/mattermost.json
> mattermost: fix autoupdate

- bucket/wumgr.json
Fix #3015. Also modified **description** to make it more brief.
> WuMgr: fix hash

- bucket/dumo.json
> DuMo: fix hash

- bucket/lunacy.json
> Lunacy: fix checkver

- bucket/linqpad.json
> linqpad: fix checkver

- bucket/ghostwriter.json
Fix #2997 
Modify **description** to make it more brief.
> GhostWriter: fix hash

- bucket/rawtherapee.json
- bucket/windowsspyblocker.json
create `rawtherapee.json`
RawTherapee is  a raw image processing program
ver 5.7
> Add RawTherapee (a raw image processing program)

- bucket/streamdeck.json
Add streamdeck:
https://www.elgato.com/en/gaming/downloads#sd-win
> streamdeck: Add version 4.3.3.11845

- bucket/wireshark.json
- close #2927
Should be merged after https://github.com/ScoopInstaller/Main/pull/466
> wireshark: Add notes about Npcap/WinPcap

- bucket/diffinity.json
[Diffinity](http://www.truehumandesign.se/s_diffinity.php) is a free diff and merging tool for Windows with focus on accurate and easy to read source code diffs.
> diffinity: Add version 0.9

- bucket/kcc.json
Adding [Kindle Comic Converter](https://github.com/ciromattia/kcc) (not the Amazon Kindle Comic Creator).
> kcc: Add version 5.5.1

- bucket/mattermost.json
close https://github.com/lukesampson/scoop-extras/issues/3042
> mattermost@4.3.1: hash fix

- bucket/rawtherapee.json
> rawtherapee: Fix installation for powershell5

- bucket/postman.json
> postman: Update to 7.10.0 (manually)

- bucket/googlechrome-beta.json
- bucket/googlechrome-canary.json
- bucket/googlechrome-dev.json
- bucket/googlechrome.json
This PR fixes #3070 
Close #3070
> googlechrome*: new API endpoint for checkver

- bucket/openface.json
OpenFace – a state-of-the art tool intended for facial landmark detection, head pose estimation, facial action unit recognition, and eye-gaze estimation.
> openface: Add version 2.2.0

- bucket/thonny.json
Thonny - a Python IDE for beginners
> thonny: Add version 3.2.1

- bucket/tusk.json
Tusk is an elegant Evernote desktop app. I wasn't sure if I should wrap the installer script in `architecture`.
> tusk: Add version 0.23.0

- bucket/dadroit.json
- bucket/dadroitjsonviewer.json
[Dadroit](https://viewer.dadroit.com/) is a JSON viewer that gives a new approach to process JSON Data files.
License: Free for non-commercial use
> dadroitjsonviewer: Add version 1.1.1407

- bucket/neatdownloadmanager.json
[Neat Download Manager](http://neatdownloadmanager.com/index.php) is a simple and lightweight GUI wrapped around a powerful and optimized Download-Engine.
> neatdownloadmanager: Add version 1.1

- bucket/vcredist2012-portable.json
- bucket/vcredist2013-portable.json
- bucket/vcredist2015-portable.json
- bucket/vcredist2017-portable.json
- bucket/vcredist2019-portable.json
Related: https://github.com/lukesampson/scoop/issues/3688
> vcredist2012/2013/2015/2017/2019: Add portable version

- bucket/caffeine.json
Caffeine is a small program that keeps a computer awake by simulating a keypress every 59 seconds by default.
- Closes #3086
> caffeine: Add version 1.64

- bucket/dont-sleep.json
> dont-sleep: Fix hash

- bucket/fritzing.json
[Fritzing](http://fritzing.org/download/) changed the layout of their website.
> fritzing: fix checkver

- bucket/liteide.json
> liteide: fix download url

- bucket/tinytask.json
#2308. (Outstanding Excavator issues)
[TinyTask](https://www.tinytask.net/) has changed the layout of their website.
I also modified `description` to make it more brief.
> tinytask: fix checkver

- bucket/sumatrapdf.json
Its frustrating to lose thumbnail cache with each update.
> sumatrapdf: Persist sumatrapdfcache folder

- bucket/mkvtoolnix.json
Close https://github.com/lukesampson/scoop-extras/issues/3140
Change to fosshub for better download speed.
> mkvtoolnix: fix persist

- bucket/mpv-git.json
- bucket/mpv.json
close https://github.com/lukesampson/scoop-extras/issues/3120
> mpv: change to shinchiro's build

- bucket/flux.json
fix https://github.com/lukesampson/scoop-extras/issues/1928 ? If we don't run the uninstaller, we won't lose anything.
> flux: extract instead install

- bucket/fun.json
https://github.com/alibaba/funcraft/blob/master/README-en.md
> fun: Add version 3.0.8

- bucket/vidcoder.json
Open-source DVD/Blu-ray ripping and video transcoding tool that uses HandBrake as its encoding engine.
> vidcoder: Add version 4.36

- bucket/qtranslate.json
close #3115
**QTranslate** ([homepage](https://quest-app.appspot.com/download)) is a free translator utility.
* QTranslate stores its user configurations under `Data` folder. This folder will be created by QTranslate if it doesn't exist.
> QTranslate: add version 6.7.3

- bucket/qimgv.json
> qimgv: Update to version 0.8.8

- bucket/keepassxc.json
Persist doesn't seem to work properly (see lukesampson/scoop#3212) for now, so doing it manually
- Closes #2018
> keepassxc: Persist configuration file

- bucket/ida-free.json
> ida-free@7.0: Fix hash

- bucket/monero.json
> monero: Fix checkver

- bucket/linqpad.json
> linqpad@6.3: Fix Hash

- bucket/notepadplusplus.json
> Notepad++: fix au

- bucket/openvpn.json
I hope I602 is not going to change
> openvpn: Add requirement checks

- bucket/aurora.json
Unified lighting effects for keyboards across multiple brands and various games
> aurora: Add version 0.7.1

- bucket/gpu-z.json
- Closes #3211
- Closes #3210
- Closes #3209
- Closes #3205
> gpu-z@2.27.0: Fix hash

- bucket/lantern-client.json
> lantern: fix checkver

- bucket/celestia.json
The website is behind CloudFlare.
> celestia: fix checkver

- bucket/free-manga-downloader.json
Close https://github.com/lukesampson/scoop-extras/issues/3197
I didn't disable AutoCheckLatestVersion because it will also check modular update.
> free-manga-downloader: Add version 0.9.158.0

- bucket/blender.json
close https://github.com/lukesampson/scoop-extras/issues/3234
See https://www.blender.org/download/requirements/
> blender: Remove 32bit architecture

- bucket/draw.io.json
close https://github.com/lukesampson/scoop-extras/issues/3223
> draw.io: Add version 12.2.2

- bucket/sourcetrail.json
Close https://github.com/lukesampson/scoop/issues/3761
> sourcetrail: Add version 2019.4.61

- bucket/furmark.json
> furmark: Fix download URL

- bucket/sdl2.json
Update sdl2 from 2.0.7 to 2.0.10
> sdl2 update to 2.0.10

- bucket/firefox-beta.json
- bucket/firefox-developer.json
- bucket/firefox-esr.json
- bucket/firefox.json
- bucket/thunderbird-portable.json
- bucket/thunderbird.json
- bucket/uget-portable.json
- bucket/uget.json
reflect https://github.com/lukesampson/scoop/pull/3615
> polish hash extract

- bucket/virtualdub.json
Any idea how the build number can be managed in the autoupdate section ?
> virtualdub: Add version 1.10.4

- bucket/wifi-manager.json
> wifi-manager@0.2: Fix hash

- bucket/aida64extreme.json
> aida64extreme@6.20: Fix hash

- bucket/arduino-portable.json
> arduino-portable: fix persistence

- bucket/ccleaner.json
> ccleaner: Persist exported configurations

- bucket/ridnacs.json
Closes #3247 
This is very barebones and I could not find much info. Can't tell if this is 64 or 32 bit, and don't think an autoupdate is needed (or possible) considering the latest release is from ~2014.
> ridnacs: Add version 2.0.3

- bucket/calibre-normal.json
- bucket/calibre.json
> calibre: Add more bins and shorcuts

- bucket/crow-translate.json
- Closes #3299
Binaries were regenerated due to bug
https://github.com/crow-translate/crow-translate/issues/74#issuecomment-549958479
> crow-translate@2.2.3: Fix hash

- bucket/shutup10.json
- Closes #3301
Delay between release and page change was pretty high
> shutup10@1.7.1404: Fix hash

- bucket/blush.json
**[blush](https://github.com/arsham/blush)**
Description: Grep with colours
License: MIT
Preview:
> blush: Add version 0.5.3

- bucket/infoqube.json
[InfoQube](http://www.infoqube.biz/) is an powerfull Information Management System.
> infoqube: Add version 0.9.113f

- bucket/powertoys.json
Add version number to file name
> powertoys: Fix url

- bucket/todolist.json
> todolist: Fix homepage url

- bucket/gridea.json
[Gridea](https://gridea.dev/en/): A static blog writing client.
License: MIT
> gridea: Add version 0.8.3

- bucket/falconx.json
[FalconX](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar): Center Windows taskbar icons with a variety of animations and options.
License: MIT
Version: 1.3.3.0
Preview:
> falconx: Add version 1.3.3.0

- bucket/pomotodo.json
[Pomotodo](https://pomotodo.com/): A time management app designed for the creators. It is based on Pomodoro Technique and GTD theory.
License: Proprietary (Free version is enough)
> pomotodo: Add version 3.2.3

- bucket/rdcman.json
> rdcman: Add version 2.7.1406.0

- bucket/hexchat.json
Adds text only hexchat option.
> hexchat: Add hexchat-text shim

- bucket/lockhunter.json
> lockhunter@3.3.4: Fix url

- bucket/hourglass.json
[hourglass](https://chris.dziemborowicz.com/apps/hourglass): The simple countdown timer for Windows.
Github: https://github.com/dziemborowicz/hourglass
License: MIT
I just found out today that I accidentally closed the pull #3326 and re-pull request it now.
> hourglass: Add version 1.10.0

- bucket/tftputil-gui.json
**TFTPUtil GUI** ([homepage](https://sourceforge.net/projects/tftputil/)) is a TFTP server and client suite written in .NET framework.
Notes:
* The `0BSD` license ([BSD Zero-Clause license](https://spdx.org/licenses/0BSD.html)) is contained in the archive.
* TFTPUtil has not been updated since 2014. Therefore *checkver* and *autoupdate* is not needed.
> tftputil-gui: Add version 1.4.5

- bucket/qbittorrent-portable.json
Close https://github.com/lukesampson/scoop-extras/issues/3363 
I don't know why not download from fosshub.
> qbittorrent-portable: remove --portable option

- bucket/rstudio.json
> rstudio: Fix au.hash

- bucket/winaero-tweaker.json
> winaero-tweaker@0.16: Fix hash

- bucket/mitmproxy.json
> mitmproxy@5.0.0: Fix hash

- bucket/azuredatastudio-insiders.json
- bucket/azuredatastudio.json
> azuredatastudio,azuredatastudio-insiders: Remove extract_dir

- bucket/caffeine.json
> caffeine@1.64: Fix hash

- bucket/linqpadless.json
> linqpadless@1.1.0: Fix hash

- bucket/vcredist.json
- bucket/vcredist2019-portable.json
- bucket/vcredist2019.json
> vcredist: Update to 14.24.28127.4

- bucket/chrlauncher.json
For it to be available in `PATH`.
> chrlauncher: Add chrlauncher.exe shim

- bucket/rednotebook.json
A handy journal-style notebook
> rednotebook: Add version 2.15

- bucket/quicktextpaste.json
Another really useful freeware from SoftwareOK (also the creator of dont-sleep, which is already in this bucket). I used this json file as my starting point: https://github.com/lukesampson/scoop-extras/blob/master/bucket/dont-sleep.json
> quicktextpaste: Add version 5.41

- bucket/pip-tool.json
[PiP-Tool](https://github.com/LionelJouin/PiP-Tool): is a software to use the Picture in Picture mode on Windows.
> pip-tool: Add version 1.1.2

- bucket/winscan2pdf.json
Another great freeware utility from SoftwareOK. I use this one to scan documents easily & quickly.
> winscan2pdf: Add version 5.15

- bucket/q-dir.json
Another freeware utility from softwareok - this one is a quad window file manager
> q-dir: Add version 7.99

- bucket/aimp.json
> aimp: Add version 4.60.2167

- bucket/openoffice.json
> openoffice: Add version 4.1.7

- bucket/everything.json
File **Bookmarks.csv** saves a list of bookmarks (Also known as: search filter).
> everything: Persist Bookmarks.csv

- bucket/encryptpad.json
- Closes ScoopInstaller/Main#698
> encryptpad: Add version 0.4.0.4

- bucket/foxit-reader.json
> foxit-reader@9.7.1.29511: Fix URL

- bucket/gitextensions.json
- bucket/tern-subtitle-file-translator.json
[Tern-Subtitle Fille Translator](https://tern.1c7.me/) is a .srt .ass .vtt file translator.
> tern-subtitle-file-translator: Add version 1.1.1

- bucket/pdftk-builder.json
[PDFTK Builder](http://www.angusj.com/pdftkb/) is a free graphical interface to PDFTK.
> pdftk-builder: Add version 3.10.0

- bucket/bencode-editor.json
BEncode Editor
https://sites.google.com/site/ultimasites/bencode-editor
> bencode-editor: Add version 0.7.1.0

- bucket/tak.json
Tom's lossless Audio Kompressor
http://thbeck.de/Tak/Tak.html
https://wiki.hydrogenaud.io/index.php?title=TAK
> tak: Add version 2.3.0

- bucket/honeyview.json
> honeyview@5.32: Fix hash

- bucket/pixelorama.json
[Pixelorama](https://www.orama-interactive.com/pixelorama) is an open source 2D sprite editor designed for pixel art.
> pixelorama: Add version 0.6.1

- bucket/stretchly.json
This app was also in the initial #3526 but has been split out in this separate branch
> stretchly: Add version 0.21.1

- bucket/wpsoffice.json
https://github.com/lukesampson/scoop-extras/issues/3576
> wpsoffice: Update to version 11.2.0.9148

- bucket/pritunl-client.json
close #3458
close #3575
* Fix the extraction error mentioned in #3575.
* Add check for admin privileges. Remove dependency on `sudo`.
* Modify *description*.
> pritunl-client@1.0.2317.40: Fix extraction

- bucket/olive-editor.json
> olive-editor: Add version 0.1.0

- bucket/throttlestop.json
close #3532 
**ThrottleStop** ([homepage](https://www.techpowerup.com/download/techpowerup-throttlestop/)) is an application for monitoring and adjusting CPU throttling on laptop computers.
Notes:
* The `BSD-2-Clause` license can be found in the archive. (ThrottleStop_8.70.6.zip)
> throttlestop: Add version 8.70.6

- bucket/stoplight-studio.json
> stoplight-studio: Add version 1.9.0

- bucket/wavebox10-pro.json
see https://github.com/lukesampson/scoop-extras/pull/3604
> wavebox10-pro: Add version 10.0.69.2

- bucket/yakyak.json
**YakYak** ([homepage/Github repo](https://github.com/yakyak/yakyak)) is an open-source desktop chat client for Google Hangouts.
also mentioned in #3227.
Notes:
* *persist* is not needed because *yakyak* stores its user settings at `$Env:APPDATA\yakyak`.
> yakyak: Add version 1.5.4

- bucket/instant-eyedropper.json
Instant Eyedropper is a free color detection & picker tool.
> instant-eyedropper: Add version 1.9.3

- bucket/picpick.json
[PicPick](https://picpick.app/) is a full-featured screen capture tool, Intuitive image editor, color picker, color palette, pixel-ruler, protractor, crosshair, whiteboard and more.
> picpick: Add version 5.0.7

- bucket/powertoys.json
#2308 
0.15.0 release notes:
https://github.com/microsoft/PowerToys/releases/tag/v0.15.0
0.15.1 release notes:
https://github.com/microsoft/PowerToys/releases/tag/v0.15.1
> powertoys: Update to version 0.15.1

- bucket/shadered.json
[SHADERed](https://shadered.org/) is a lightweight, cross-platform & full-featured desktop IDE for HLSL and GLSL shaders.
> shadered: Add version 1.3

- bucket/archi.json
> archi@4.6.0: Fix URL

- bucket/sumatrapdf.json
> sumatrapdf: Update to version 3.2

- bucket/fsresizer.json
[FastStone Photo Resizer](https://www.faststone.org/FSResizerDetail.htm): An image converter and renaming tool that intends to enable users to convert, rename, resize, crop, rotate, change color depth, add text and watermarks to images in a quick and easy batch mode.
> fsresizer: Add version 4.3

- bucket/xnresize.json
[XnResize](https://www.xnview.com/en/xnresize/): A fast, powerful and free cross-platform image resizer.
> xnresize: Add version 1.00

- bucket/speedyfox.json
> speedyfox@2.0.28: Change URL

- bucket/sysguage.json
[SysGauge](https://www.sysgauge.com) is a system and performance monitoring utility.
> sysguage: Add version 6.7.14

- bucket/qv2ray.json
Yet another v2ray client. Qv2ray is a Qt based cross-platform GUI client using v2ray core.
More detail: https://github.com/Qv2ray/Qv2ray
> qv2ray: Add version 2.1.2

- bucket/tern-subtitle-file-translator.json
- Closes #3772 
Extract dir changed.
> tern-subtitle-file-translator@1.4.1: Fix installation

- bucket/qview.json
qView is a free and open source minimal image viewer based on Qt5.
> qview: Add version 3.0

- bucket/kdenlive.json
> kdenlive: Update to version 19.12.3

- bucket/kitty.json
- Closes #3734
Add more persist folders - SshHostKeys, Jumplist
> kitty: Persist SshHostKeys, Jumplist

- bucket/xournalpp.json
The latest version of xournalpp 1.0.17 has fixed the issue. Now xournalpp package is OK to be updated.
- #3492
- xournalpp/xournalpp#1600
> xournalpp: Update to version 1.0.18

- bucket/bleachbit.json
Directory is used for custom cleaner definitions
> bleachbit: Persist "cleaners" directory

- bucket/rabbitmq.json
Also ordered the list so its easier to check if something is missing
> rabbitmq: Add additional bins

- bucket/madvr.json
Application configuration file
> madvr: Persist "settings.bin"

- bucket/fscapture.json
- bucket/fsviewer.json
close https://github.com/lukesampson/scoop-extras/issues/3941
> fs(capture,viewer): Rename the shortcuts

- bucket/cryptomator.json
Fixes data storage path. For more details see linked issue below
Fixes #3957
> cryptomator: Fix data storage path

- bucket/meshlab.json
Update the zip folder structure.
> meshlab@2020.05: Fix installation

- bucket/chromium-dev-nosync.json
- bucket/chromium-dev.json
- bucket/chromium-nosync.json
The regular version of Chromium already has the correct name
> chromium: Add chromimum shims

- bucket/mednafen.json
Mednafen is a libre emulator for a few systems.
> mednafen: Add version 1.24.1

- bucket/openboard.json
Please add [OpenBoard](http://www.openboard.ch)
> openboard: Add version 1.5.4

- bucket/fbflipper.json
> fbflipper: Add version 0.40.0

- bucket/qgroundcontrol.json
Adds [QGroundControl ](http://qgroundcontrol.com/) version 4.0.6
> qgroundcontrol: Add version 4.0.6

- bucket/wezterm.json
A GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust
> wezterm: Add version 20200505-090057-31c6155f

- bucket/eartrumpet.json
Let me know if this isn't the correct way to handle packages downloaded from Chocolatey. :)
> eartrumpet: Add version 2.1.7.0

- bucket/mindforger.json
Thinking notebook and Markdown editor
> mindforger: Add version 1.52.0

- bucket/banana-cake-pop.json
Banana Cake Pop is a GraphQL IDE which works well with Hot Chocolate and any other GraphQL server.
> banana-cake-pop: Add version 1.0.0-preview.3

- bucket/sharpapp.json
> sharpapp: Add version 0.41.0

- bucket/ppsspp.json
- Closes #4119
All user data are stored in dir `memstick`
> ppsspp: Persist "memstick" directory

- bucket/calibre-normal.json
- bucket/calibre.json
> calibre(-normal)@4.17.0: Fix URL

- bucket/transmission.json
> transmission: Suggest vcredist2019

- bucket/gcc-arm-none-eabi.json
> gcc-arm-none-eabi@9-2020-q2-update: Fix URL

- bucket/simplewall.json
> simplewall: Persist profile.xml

- bucket/nirlauncher.json
- Closes #4205
- Rename 'MozillaCacheView.exe' to 'MZCacheView.exe'
> nirlauncher: Update binary list

- bucket/snoop.json
Latest Snoop version. (marked as alpha but very stable).
> snoop: Add version 3.0.0-alpha0116

- bucket/responsively.json
> responsively: Add version 0.1.5

- bucket/homebank.json
- Closes #4093
HomeBank
http://homebank.free.fr/
> homebank: Add version 5.4.2

- bucket/freedownloadmanager.json
> freedownloadmanager: Update to version 6.10.0

- bucket/maxima.json
wxmaxima.exe changed path to bin directory in this version
> maxima: Fix shortcut

- bucket/juce.json
> juce: Add version 5.4.7

- bucket/telegram.json
Issue with formatting on save in VSCode fixed upstream
> Updated setting.json in .vscode folder

- bucket/azuredatastudio.json
- Closes #4302 
Update the app version.
Update the checkver for auto-update using the new URL format.
> azuredatastudio: Update to version 1.19.0

- bucket/vcredist2010.json
10.0.40219.325 (2011-06-28ish) to 10.0.40219.473 (2016-10-25ish)
> vcredist2010: Update to version 10.0.40219.473

- bucket/ripcord.json
Lightweight Discord/Slack client.
https://cancel.fm/ripcord/
> ripcord: Add version 0.4.26

- bucket/hokus.json
https://www.hokuscms.com
https://github.com/julianoappelklein/hokus
> hokus: Add version 0.6.1

- bucket/cloudfoundry-cli.json
- Closes lukesampson/scoop#4047
Fix bin entry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lukesampson/scoop-extras/4353)
> cloudfoundry-cli: Fix shims

- bucket/so.json
so - is a terminal interface for StackOverflow written in Rust by Say Tay
repo: https://github.com/samtay/so
> so: Add version 0.3.6

- bucket/element.json
- bucket/riot.json
- Closes #4437
[App name changed from Riot to Element.](https://element.io/blog/welcome-to-element/)
> element: Add version 1.7.1

- bucket/android-sdk.json
AVD images persists while upgrading.
> android-sdk: Persist system-images

- bucket/mini-sftp-server.json
- Closes https://github.com/lukesampson/scoop-extras/issues/4375
> mini-sftp-server: Add version 2.25

- bucket/fluent-reader.json
https://github.com/yang991178/fluent-reader
> fluent-reader: Add version 0.6.2-beta

- bucket/dottorrent-gui.json
https://github.com/kz26/dottorrent-gui
> dottorrent-gui: Add version 1.3.11

- bucket/abricotine.json
https://github.com/brrd/abricotine
> abricotine: Add version 1.0.0

- bucket/element.json
https://github.com/vector-im/riot-desktop/commit/94086f247a8c89630ddf3c134e4af50c18d1af3b
> element@1.7.2: Fix bin and shortcuts

- bucket/crystaldiskinfo.json
- Closes #4502 
Fix the problem that installer scripts creat trash files in app directory
> crystaldiskinfo: Improve pre persit file creation

- bucket/everything.json
> everything: Fix persisting

- bucket/coppeliasim.json
> coppeliasim: Update to version 4.1.0

- bucket/electrum.json
https://github.com/spesmilo/electrum
> electrum: Add version 4.0.2

- bucket/rssguard.json
- Closes #4514
Moved from https://github.com/hoilc/scoop-lemon/blob/master/bucket/rssguard.json
> rssguard: Add version 3.7.0
