ScoopInstaller/Extras

bucket/teamviewer.json
The version string was updated. The hash was right.
If the version string is old and you are already on that version, the update will not be triggered.
Closes #8097
=> teamviewer@15.25.8: update version string

bucket/waifu2x-snowshell.json
Added waifu2x-snowshell version 2.3. 
A simple gui for [extras/waifu2x-caffe](https://github.com/ScoopInstaller/Extras/blob/master/bucket/waifu2x-caffe.json), [waifu2x-converter-cpp](https://github.com/ScoopInstaller/Main/blob/master/bucket/waifu2x-converter-cpp.json) and [waifu2x-ncnn-vulkan](https://github.com/ScoopInstaller/Main/blob/master/bucket/waifu2x-ncnn-vulkan.json)
By default it already comtains `waifu2x-converter-cpp` and `waifu2x-ncnn-vulkan` but they are outdated. User can point towards standalone/up to date version of `waifu2x-converter-cpp` and `waifu2x-ncnn-vulkan` in its config.
=> waifu2x-snowshell: Add version 2.3

bucket/android-studio.json
Plugins folder should be persisted so any plugin data will not just sit in old version folder of android-studio after update and not carry over to the new version
Closes #8116
=> fix: persist plugins folder of android-studio

bucket/dbeaver.json
With the release of version 22.0 on the 7th, the version check was failing. While the download page lists it as "22.0", the actual version used in file and checksum names was "22.0.0". Switching to use their Github releases page instead gets us the correct result.
=> Fix DBeaver version check.

bucket/jmeter.json
The `bin` array is missing one: `jmeterw.bat`
See: https://jmeter.apache.org/usermanual/get-started.html#running
> **jmeterw.cmd**
> &nbsp;&nbsp;&nbsp;&nbsp;run JMeter without the windows shell console (in GUI mode by default)
=> jmeter: Add jmeterw.cmd bin

bucket/anaconda3.json, bucket/micmute.json, bucket/tinymediamanager.json
Since https://github.com/ScoopInstaller/Scoop/pull/4619 is now in `master`, we can simplify these manifests.
=> update au.hash in response to Scoop#4619

bucket/sdl2.json
This fixes the compilation errors (file not found) by replacing `@PKG_CONFIG_LIBS_PRIV@` with ` ` (nothing).
Fixes #8126
=> sdl2: Fix installation script not replacing `@PKG_CONFIG_LIBS_PRIV@`

bucket/imageglass.json
Currently, when opening ImageGlass for the first time, users get the following warning message box:
```
---------------------------
ImageGlass
---------------------------
Some settings are not compatible with your ImageGlass 8.5.1.22. It's recommended to update them before continuing.
- Click Yes to learn about the changes.
- Click No to launch ImageGlass with default settings.
---------------------------
Yes   No   
---------------------------
```
It seems in version 7.5 (released January 2020!!) there was a change to the base structure of its XML config file `igconfig.xml`. For more info see this page: https://imageglass.org/docs/app-configs. With this fix, there is no warning and the first-time setup appears straight away, as normal.
While fixing this, I also noticed & fixed a failing …
=> imageglass: fix warning on start, fix hash extraction, add 32bit

bucket/ds4windows.json
DS4Windows does not have a command-line interface. Thus, it should not be added to `bin`.
=> ds4windows: Remove bin

bucket/shaderglass.json
Creates an overlay for running GPU shaders on top of the Windows desktop.
=> shaderglass: Add version 0.7

bucket/losslesscut.json
Losslesscut releases have slightly different names than the last release so github actions auto-update didn't pick it up.
This PR addresses the filename change.
=>  losslesscut: Update to version 3.44.0

bucket/notepadplusplus.json
- Using `$dir` variable in `pre_install` script makes it refer to the `$original_dir` instead of "current" version link, so I've moved "install-context.reg" and "uninstall-context.reg" file creation to `post_install` script section.
- Explicitly use `File` item type for config file creation.
=> notepadplusplus: Use "current" version path in the registry modification

bucket/digital.json
I'm not using the exe wrapper because of https://github.com/hneemann/Digital/issues/670.
=> digital: Add version 0.29

bucket/librewolf.json
Devs decided to change the name of the portable zip, fun
=> LibreWolf: Update to 98.0 and fix autoupdate

bucket/ollydbg.json
[OllyDbg](https://www.ollydbg.de/) is an assembler-level analysing debugger for Windows binaries.
**NOTES**:
* *pre_install*: `PSAPI.DLL` and `DBGHELP.DLL` are DLLs for Windows APIs. They are not needed as newer versions can be found in `$env:PATH` under Windows 10.
* *checkver* is not needed because the last update was in 2013.
=> ollydbg: Add version 1.10

bucket/tartube.json
closes #4684
supersedes #4699
[TarTube](https://github.com/axcore/tartube) is a GUI front-end for youtube-dl, partly based on youtube-dl-gui.
**NOTES**:
* **TarTube** has changed their setup method. (different from what we see in #4699. Therefore I think *suggest* is not required in this case.
* Upon first run, will prompt the user the choose **data folder location** (this is stored at `$dir\home\user\tartube\settings.json`). Then, download required softwares (such as `youtube-dl` or `ffmpeg`) and store them in `$dir\mingw64\bin`.
=> tartube: Add version 2.3.367

bucket/lapce.json
A lightning-fast and Powerful Code Editor written in Rust
The data of lapce is stored in `%appdata%/lapce` by default, and data persistence is not supported at present.
=> lapce: Add version 0.0.11

bucket/ghostwriter.json
- The repo is updated: [wereturtle](https://github.com/wereturtle/ghostwriter/releases) has started to provide its own Windows builds again so the current repo will be deprecated.
- Additionally the version is updated to 2.1.2.
=> ghostwriter: Update to version 2.1.2

bucket/uiforetw.json
The version format of tags has been changed
=> uiforetw: Fix URLs

bucket/keepassxc.json
Relates to [Versions#461](https://github.com/ScoopInstaller/Versions/pull/461) and [keepassxc official download page](https://keepassxc.org/download/#windows) 
Keepassxc 32-bit Windows is no longer supported after v2.6.6, please download `keepassxc-legacy` from Version bucket.
=> keepassxc: Update to 2.7.0 and remove 32bit support

bucket/libreoffice.json
The "url" in "autoupdate" was wrong. I had repaired it.
**Package Name:** [libreoffice](https://github.com/ScoopInstaller/Extras/blob/4d38cbf2f8d45aaf3e6d21d76b82d11f44288ff9/bucket/libreoffice.json)
Did not update the latest version.
The libreoffice had updated to [7.2.6 or 7.3.1](https://www.libreoffice.org/download/download/?lang=zh-CN&version=7.2.6&pk_campaign=update), but the manifest still stayed in 7.2.5.
=> libreoffice: Fix autoupdate

bucket/shutter-encoder.json
closes #7102
[Shutter Encoder](https://www.shutterencoder.com/) is a multimedia file converter.
**NOTES**:
* Only 64-bit binary is available for this app.
=> shutter-encoder: Add version 15.9

bucket/typora.json
This PR changes the typora config to use versioned download URLs and also update the hashes automatically via the "download" method (sadly, there are no hashes anywhere).
=> typora: Fix URLs and hashes

bucket/onionshare.json
* closes #6198
* *persist* is not needed because config is at `$AppData\OnionShare`.
=> onionshare: Update to version 2.5, Add autoupdate

bucket/grepwin.json
* If we generate **.reg** files in `installer.script` or `pre_install`, the path in .reg will be `(scoop_dir)\apps\grepwin\2.0.10`. This will cause context menu to break when the app updates. Using **post_install** can avoid the issue.
* Copy .reg files from `$bucketsdir\extras` instead of downloading it.
=> grepwin: generate .reg files in post_install

bucket/meshlab.json
Fix the download link: Meshlab -> MeshLab
=> meshlab@2022.02: fix the download link

bucket/wezterm.json
This is necessary in order to supply additional configuration options for debugging wezterm on Windows. See https://github.com/wez/wezterm/issues/1576
=> wezterm: also register wezterm-gui.exe

bucket/freac.json
Relates to Excavator out of date: https://github.com/ScoopInstaller/Extras/runs/5777899107?check_suite_focus=true#step:3:246
=> freac: Update to version 1.1.6, fix autoupdate

bucket/bitwarden.json
closes #4843
supersedes #4844
* **bitwarden** resets config when a new version is installed. Using **portable** version instead will keep config files intact when user update the app via *Scoop*. (Also see comment in #4844)
> In my experience, it already loses user configuration between each update anyways with the current setup, I'm not sure why, but every time I update, my theme and settings return to default. This, if anything, should fix that going forward.
> it "installs" (gets a full "Add or remove programs" entry) whenever there's a new Bitwarden update. There is no way to prevent this behavior on Bitwarden's end without using the portable executable they provide.
* The portable `Bitwarden.exe` contains both 32 and 64-bit apps. If we open `Bitwarden.exe` using 7-zip, we can see …
=> bitwarden: Use portable version

bucket/windows-terminal.json
This update to Windows Terminal has a fix for the issue "Element not found" affecting a number of scoop users:
https://github.com/microsoft/terminal/issues/12305
The download URL scheme has changed.
Note that the release notes specify that the Win10 flavor of the URL will work just as well for Win11:
https://github.com/microsoft/terminal/releases/tag/v1.12.10732.0:
> If you install the Windows 10 verison on Windows 11, it will probably automatically upgrade itself to the Windows 11
version. It turns out that it is impossible to have two bundles with the same version number, so it has to be this
way.
=> Update Windows Terminal to v1.12.10732

bucket/harmonoid.json
Relates to Excavator unable to download latest version due to '-hotfix' in version name: https://github.com/ScoopInstaller/Extras/runs/5777899107?check_suite_focus=true#step:3:265
=> harmonoid: Update to 0.2.1-hotfix2, support hotfixes

bucket/gephi.json
Relates to Excavator unable to autoupdate: https://github.com/ScoopInstaller/Extras/runs/5864968342?check_suite_focus=true#step:3:220
=> gephi: Update to version 0.9.3, fix autoupdate

bucket/inkscape.json
- Improved checkver to pickup versions where the main number (1.1.2) doesn't change but the build date does
- Changed 32bit version to use compressed zip rather than PortableApp release
- Added hash extraction
=> inkscape: Update to 1.1.2_2022-02-05, improve checkver

bucket/mupdf.json
Relates to Excavator checkver failure due to change in releases url: https://github.com/ScoopInstaller/Extras/runs/5954605801?check_suite_focus=true#step:3:264
=> mupdf: Update checkver url

bucket/gammy.json
- Relates to Excavator checkver not working due to website being down - the project has been archived on GitHub and 0.9.64 is the final release: https://github.com/ScoopInstaller/Extras/runs/5954605801?check_suite_focus=true#step:3:245
- Fixes pre_install not working due to unescaped apostrophe
- Update URL to archived GitHub repo rather than dead website
=> gammy: Remove autoupdate, fix pre_install, url

bucket/chef-workstation.json
- Relates to Excavator checkver failing for `chefdk` package: https://github.com/ScoopInstaller/Extras/runs/5954605801?check_suite_focus=true#step:3:210
- This is due to ChefDK reaching End of Life - see https://www.chef.io/downloads/tools/chefdk
- That page says to upgrade to Chef Workstation, which this PR adds. I will make a PR to add a note to `chefdk` afterwards.
- Very similar manifest to `chefdk`, adds `bin` directory to path as that is where the cli programs are stored - plus a shortcut to the gui Chef Desktop
=> chef-workstation: Add version 22.4.861

bucket/neovide.json
Update neovide to beta 0.7.0 (WSL no longer works in version 0.5.0, 0.7.0 does work)
- [✔️] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> Neovide@0.7.0: current version is outdated. wsl mode does not work in 0.5.0

bucket/gcloud.json
This fixes the extraction error mentioned in https://github.com/ScoopInstaller/Scoop/issues/4647 by using **7-Zip 19.00 helper package** to extract files.
Related Issues:
* https://github.com/ScoopInstaller/Extras/issues/8298
* https://github.com/ScoopInstaller/Scoop/issues/4647
Notes:
* I changed the name(`bin`) of the helper to `7z1900-helper`, because the dot (`.`) in the file name will cause Start-Process to fail.
=> gcloud: Use 7zip 19.00 helper for extraction

bucket/qtemu.json
Relates to Excavator error `Property 'tag_name' not valid on JArray.`: https://github.com/ScoopInstaller/Extras/runs/6003978022?check_suite_focus=true#step:3:245
=> qtemu: Fix JSONpath error in checkver

bucket/discord.json, scripts/discord/disable-auto-update.ps1
Closes #8051
Switch Discord over to the portable version maintained by portapps. This version deals with the complexities of keeping Discord from auto updating itself and also redirects its data nicely. This also brings us up-to-date as our manifest version is quite old.
=> discord@1.0.9004-11: version update and switch to portable version

bucket/pixelorama.json
Pixelorama seemingly changed their release format in version 0.10
This commit fixes the `extract_dir`
=> pixelorama: Fix 0.10 extract_dir

bucket/camo-studio.json
Closes #8325 
Adds Camo Studio app used as a bridge to allow phones to become Windows recognized webcams.
=> camo-studio: Add version 1.1.6.7135

bucket/winsetupfromusb.json
[WinSetupFromUsb](http://www.winsetupfromusb.com/) is a tool that can create multi-boot USB for Windows/Linux installations.
**NOTES**:
* The site does not support HTTPS.
* license info can be found on the [FAQ page](http://www.winsetupfromusb.com/faq/)
```
12. Is the program free and may it be freely redistributed?
Program is free for personal and commercial use and can be freely redistributed as long as the licenses of the tools included are not violated and there is clear link to [this](http://www.winsetupfromusb.com/) page or the home [page @ msfn forum](https://www.msfn.org/board/topic/120444-how-to-install-windows-from-usb-winsetupfromusb-with-gui/) if it is hosted elsewhere.
The program may not be sold or included in commercial products without written consent from its author.
```
=> winsetupfromusb: Add version 1.10

bucket/fluent-search.json
closes #8320
[Fluent Search](https://fluentsearch.net/) is a search tool for running apps, browser tabs, in-app content, files and more.
**NOTES**:
* I couldn't find the exact document about *license* or *terms of use*. However it is marked as **Freeware** on other sites such as *Microsoft Store* or *Softpedia*.
=> fluent-search: Add version 0.9.66.0

bucket/pycharm-professional.json, bucket/pycharm.json
=> pycharm: fix creation of virtualenv

bucket/brave.json
Use [official GitHub release](https://github.com/brave/brave-browser/releases) and update to [version 1.37.116](https://github.com/brave/brave-browser/releases/tag/v1.37.116)
Relates to #7318
Relates to #7573
=> brave: Use official release and update to version 1.37.116

bucket/gcc-arm-none-eabi.json
=> gcc-arm-none-eabi: suggest 32bit python27 (fixes #8361)

bucket/flat-assembler.json
Relates to Excavator issue 'URL is not valid', checkver works okay locally... https://github.com/ScoopInstaller/Extras/runs/5777899107?check_suite_focus=true#step:3:230
=> flat-assembler: Update to version 1.73.30, add license URL

bucket/mathpix.json
closes #8367
[Mathpix](https://mathpix.com/) is a tool for an easy and fast way to create math equations using LaTex.
**NOTES**:
* The app (and its dependencies) is built in 32-bit.
* *persist* is not needed because config is at `$Env:LocalAppData\Mathpix\Mathpix Snipping Tool`.
=> mathpix: Add version 03.00.0074

bucket/autojump.json
supersedes https://github.com/ScoopInstaller/Main/pull/3525
closes https://github.com/ScoopInstaller/Main/issues/3520
[AutoJump](https://github.com/xen0n/autojump-rs) is a tool that helps navigate your filesystem in the command line, by recording the directories you use the most.
**NOTES**:
* about package name:
> As autojump(the python version) requires python, I hope we can just name it as autojump instead of autojump-rs? (#3520)
* *persist* is not needed because config is at `$Env:AppData\autojump`.
=> autojump: Add version 0.4.0

bucket/win-gpg-agent.json
From https://github.com/rupor-github/win-gpg-agent/releases/tag/v1.6.2:
> Make sure all config files are persisted and not only `agent-gui.conf`.
@rupor-github It would be helpful if you contributed the change here upstream as well.
=> win-gpg-agent: Add additional persist files

bucket/xkill.json
closes https://github.com/ScoopInstaller/Main/issues/1549
also requested in https://github.com/ScoopInstaller/Main/issues/2399 and https://github.com/ScoopInstaller/Extras/issues/7167
[XKill](https://bitbucket.org/sta-ger/win-xkill) is a tool that works the same as XWindow's *XKill*, which displays a special cursor as a prompt for the user to select a window to be killed.
**NOTES**:
* *autoupdate* is not needed because last update was in 2014.
* *license* and *version* info can be found in `win-xkill.nuspec` in the source code.
=> xkill: Add version 1.0.0.20141024

bucket/praat.json
Relates to Excavator unable to update: https://github.com/ScoopInstaller/Extras/runs/6084782217?check_suite_focus=true#step:3:265
=> praat: Update to version 6.2.12, fix autoupdate

bucket/windterm.json
Relates to Excavator stuck at version 2.4.0 due to using the same GitHub release tag for multiple releases: https://github.com/ScoopInstaller/Extras/runs/6172077668?check_suite_focus=true#step:3:252
=> windterm: Update to version 2.4.1, fix autoupdate

bucket/dadroitjsonviewer.json
Revert to previous version because checkver was picking up macOS only versions from Release Notes page. The issues linked below were because it had autoupdated the link to a 404 HTML page which was a hash mismatch to the exe.
Relates to #8388 #8371 #8347 #8344 #8338 #8336
=> dadroitjsonviewer: Revert to v1.5.2153, fix checkver

bucket/insomnia.json
Scoop is not recognising that there is an update to Insomnia so I am stuck on 2021.7.2. This allows scoop to check for the latest version.
=> insomnia@2022.2.1: Update checkver regex to find latest version

bucket/kdoc-formatter.json
Add version 1.4.1 of [kdoc-formatter](https://github.com/tnorbye/kdoc-formatter) - Kotlin KDoc auto-format tool
=> kdoc-formatter: Add version 1.4.1

bucket/mpc-hc-fork.json
- Relates to Excavator unable to update due to reusing the releases tag for multiple further releases: https://github.com/ScoopInstaller/Extras/runs/6224966985?check_suite_focus=true#step:3:231
- Similar method for checkver as https://github.com/ScoopInstaller/Extras/pull/8392
=> mpc-hc-fork: Update to 1.9.21.2, fix checkver

bucket/dangerzone.json
closes #8319
[DangerZone](https://dangerzone.rocks/) is an app that take potentially dangerous PDFs, office documents, or images and convert them to a safe PDF.
**NOTES**:
* *DangerZone* requires **Docker desktop** to run (will prompt user on startup). **Docker desktop** is currently not avaiable on Scoop because it needs to install services. I will work on that later.
* The app (and its dependencies) is built in 32-bit.
* *persist* is not needed because config is at `$Env:LocalAppData\DangerZone`.
=> dangerzone: Add version 0.3.1

bucket/librehardwaremonitor.json
Relates to Excavator unable to update, file name includes .NET version which has changed: https://github.com/ScoopInstaller/Extras/runs/6254370286?check_suite_focus=true#step:3:222
=> librehardwaremonitor: Update to 0.9.0, fix checkver

bucket/kdenlive.json
Relates to Excavator unable to update due to hyphen in version: https://github.com/ScoopInstaller/Extras/runs/6263781836?check_suite_focus=true#step:3:224
=> kdenlive: Update to version 22.04.0-1, fix checkver

bucket/manifold-viewer.json, bucket/manifold.json
- Relates to Excavator unable to update due to `-r2` in version: https://github.com/ScoopInstaller/Extras/runs/6254370286?check_suite_focus=true#step:3:225
- Update extract_dir to use version number without `-r2`
=> manifold|-viewer: Update to 9.0.176.3-r2, fix checkver

bucket/windterm.json
Only one persisted folder named '.wind' is defined, notes with suggestion how to configure the app to use profile stored along the application files added.
Closes #8409
=> windterm@2.4.1: Fix for changed way of storing profiles by the app

bucket/uivonim.json
[Uivonim](https://github.com/smolck/uivonim) is a maintained fork of **Veonim** (`extras/veonim`, deprecated), a GUI frontend for Neovim.
**NOTES**:
* *persist* is not needed because config is at `$Env:AppData\uivonim`.
=> uivonim: Add version 0.29.0

bucket/nextcloud.json
Relates to Excavator unable to update due to picking pre-release version from website: https://github.com/ScoopInstaller/Extras/runs/6286416461?check_suite_focus=true#step:3:236
=> nextcloud: Update to version 3.5.0, fix checkver

bucket/brackets.json
closes #8433
**NOTES**:
* Although the repo is called *brackets-cont*, it is the official one. See [homepage](http://brackets.io/) for more info.
* *persist* is not needed because config/extensions is at `$Env:AppData\Brackets`.
* The "ml" in Brackets.2.0.1**ml**.exe stands for multi language.
* The installer is created using *Advanced Installer*, more info can be found in [exeinfo](https://github.com/ScoopInstaller/Extras/files/8645474/exeinfo.txt) generated by *uniextract*.
=> brackets: Update to version 2.0.1

pdd.json
closes #8419
[pdd](https://github.com/jarun/pdd) is a date/time difference calculator and countdown timer. The name 'pdd' stands for Python Date Diff.
**NOTES**:
*~I packed the app into a **standalone exe** so that the app has less depedency and less likely to cause problems. This has to be updated manually, but I think it is fine because the app does not update very often (last update was in October 2020).~
Install .py script instead.
=> pdd: Add version 1.5

bucket/cdex.json
closes #5481
[CDex](https://cdex.mu/) is an open-source digital audio CD extractor.
**NOTES**:
* *persist* is not needed because config is at `$Env:AppData\CDex`
=> cdex: Add version 2.24

bucket/jetaudio-basic.json
closes #7127
[jetAudio](http://www.jetaudio.com/) is a music and video organizer.
**NOTES**:
* This is the free version of *jetAudio*. The non-free version is called *jetAudio Plus*.
* I use `ScoopInstaller/Binary` for download URL because:
(1) The offcial url for the file (`http://www.jetaudio.com/download/5fc01426-741d-41b8-a120-d890330ec672/jetAudio/JAD8108_BASIC.exe`) requires referer to work properly.
(2) The installer is made with InstallShield. However the format is not extractable by either *ISX* or *Uniextract*.
(3) Last update was on December 12, 2015.
=> jetaudio-basic: Add version 8.1.8

bucket/yumi-exfat.json, bucket/yumi-uefi.json, bucket/yumi.json
closes #7146
closes #7147
[YUMI](https://www.pendrivelinux.com/yumi-multiboot-usb-creator/) is a Multiboot USB Boot Creator.
**NOTES**:
* The apps are all built in 32-bit.
* *license* info can be found in the dialogs of the app.
* The 3 variants of the app are: (https://www.pendrivelinux.com/yumi-multiboot-usb-creator/)
```
NOTE: I know you are probably asking, How can you boot from exFAT USB? A YUMI exFAT USB Boot variant is now available and recommended. It can be used to automatically create an exFAT boot USB. Here are the key differences between the variants:
YUMI exFAT supports exFAT format & 4GB+ files. BIOS and UEFI USB boot.
YUMI Legacy supports either NTFS or Fat32 format. BIOS USB boot only.
YUMI UEFI https://www.pendrivelinux.com/yumi-multiboot-usb-creator/#YUMI-UEFI) supports …
```
=> Add yumi packages

bucket/7ztm.json
[7zTM](http://www.7ztm.de/) is a theme manager for 7-Zip.
=> 7ztm: Add version 2.1.1

bucket/react-native-debugger.json
closes #8454
[React Native Debugger](https://github.com/jhen0409/react-native-debugger) is a standalone app based on official debugger of React Native, and includes React Inspector / Redux DevTools.
**NOTES**:
* [The documentation](https://github.com/jhen0409/react-native-debugger/tree/master/docs) has no content about command-line args.
* *persist* is not needed because config is at `$Env:UserProfile\.rndebuggerrc`.
=> react-native-debugger: Add version 0.12.1

bucket/lapce.json
Release Notes: https://github.com/lapce/lapce/releases/tag/v0.1.0
- switched from WGPU to OpenGL for better compatibility
- subpixel text rendering 
- WSL remote development support
- syntax highlighting for new languages
=> lapce: Update to version 0.1.0, switched from wgpu to opengl

bucket/3d-fix-manager.json
[3D Fix Manager](http://helixmod.blogspot.com/2017/05/3d-fix-manager.html) is a tool for Installing **Nvidia 3D Vision** Fixes and changing 3D related settings such as 3D depth and convergence while gaming.
**NOTES**:
* Nvidia [removed 3D Vision support](https://www.nvidia.com/en-us/geforce/forums/3d-vision/41/298376) in their driver since version 426.x. This tool can be useful for those who want to use 3D Vision features on newer drivers.
* command-line args is avaiable, see [change notes](http://helixmod.blogspot.com/2017/05/3d-fix-manager.html) for example
> Change Notes Version 1.83 (March 09, 2021):
> ...
> Changed: Added "-window-mode exclusive" launch argument when selecting Unity universal fix in "Fix Profile" tab. Makes sure 3D kicks in on 3D Vision monitors.
* There is a pop-up …
=> 3d-fix-manager: Add version 1.85

bucket/umbrello.json
closes #8467
[Umbrello](https://umbrello.kde.org/) is a UML (Unified Modelling Language) diagram program based on KDE Technology
**NOTES**:
* The app supports **command-line args**. See [ChangeLog](https://github.com/KDE/umbrello/blob/master/ChangeLog) for examples.
> Version 1.5.4
> ...
> * Command line switches: graphics export to directory does not work with relative paths (130600)
> 
> Version 1.5
> ...
> * Image export via command line
* *persist* is not needed because config is at `$Env:AppData\.kde4\share\config\umbrellorc`.
* I tried to put `autoupdate.hash` outside of `architecture` block, but it doesn't seem to work. This is probably an upstream problem of *Scoop*, will investigate later.
* This package requires a **checkver script** because 64-bit and 32-bit binaries have …
=> umbrello: Add version 2.32.0

bucket/interlink.json
Relates to Excavator unable to update: https://github.com/ScoopInstaller/Extras/runs/6448579156?check_suite_focus=true#step:3:229
=> interlink: Update to version 52.9.8165, fix checkver

bucket/opentrack.json
Relates to Excavator unable to update: https://github.com/ScoopInstaller/Extras/runs/6448579156?check_suite_focus=true#step:3:248
=> opentrack: Update to version 2022.2.0, fix autoupdate

bucket/inkscape.json
Closes #8488 
Reran `checkver.ps1` and it works now. The file name changed and the old file doesn't return 404 and downloads HTML instead.
Closes #XXXX
=> inkscape@1.2_2022-05-15: Fix checkver script

bucket/wingetui.json
[wingetui](https://github.com/martinet101/WingetUI) is a GUI to manage Winget and Scoop packages
Closes https://github.com/ScoopInstaller/Scoop/discussions/4660#discussioncomment-1971483
=> wingetui: Add version 1.0

bucket/cura.json
Relates to Excavator unable to update: https://github.com/ScoopInstaller/Extras/runs/6485627258?check_suite_focus=true#step:3:214
- Updated URL, CLI location, and shortcut location
- Fixed autoupdate
=> cura: Update to version 5.0.0, fix autoupdate, url, bin

bucket/w10privacy.json
This is my attempt to fix:
- The version, which was stuck at 3.8.0.0
- The corresponding hash for the new version; 3.8.0.2
- The Autoupdate section
=> w10privacy: Update to version 3.8.0.2, Fix autoupdate

bucket/bulk-crap-uninstaller.json
The URL has changed slightly, as well as using ZIP format instead of 7z.
Updates URL and Autoupdate, as well as making the Bin section alphabetical.
=> bulk-crap-uninstaller: Update to version 5.3, Fix autoupdate

bucket/eget.json
> Eget is the best way to easily get pre-built binaries for your favorite tools. It downloads and extracts pre-built binaries from releases on GitHub.
This is what it does. More information can be found on https://github.com/zyedidia/eget
It is licensed under MIT License.
Its FAQ page is https://github.com/zyedidia/eget#faq
Closes #8521
=> Eget: Add version 1.0.1

bucket/sioyek.json
Closes #8526
In version 1.3.0 the word "release" was removed from the file names of soiyek.
Updated and tested the app manifest. Works for me.
=> sioyek@1.3: updated download url to new naming scheme

bucket/notepad2-zifuliu.json
closes #8524
[Notepad2-zifuliu](https://github.com/zufuliu/notepad2) is a **maintained fork** of Notepad2, a light-weight Scintilla-based text editor. Featuring syntax highlighting, code folding, auto-completion and API list for about 80 programming languages/documents.
**NOTES**:
* `notepad2.exe` supports **command-line args**. See [documentation: Command-Line Switches](https://github.com/zufuliu/notepad2/wiki/Command-Line-Switches) for examples.
=> notepad2-zifuliu: Add version 4.22.05r4220

bucket/glary-utilities.json
closes #8530
[Glary Utilities](https://www.glarysoft.com/) is an all-in-one utility for cleaning your PC.
**NOTES**:
* There is [an existing manifest](https://github.com/gregwen/grewen-scoop/blob/master/bucket/glary-utilities.json) in a custom bucket for us to refer to.
* **bin**: The app does not seem to have command-line args. See [Feedback: I suggest a command line interface](http://feedback.glarysoft.com/forums/203980-general-feedback/suggestions/38308534-i-suggest-a-command-line-interface) for example.
* **license**: I put `Freeware` instead of `Freeware|Proprietary` because the **free** and **pro** version are different apps, see [download page](https://www.glarysoft.com/glary-utilities/download/) for details.
=> glary-utilities: Add version 5.188

bucket/universal-mediacreationtool.json
closes #8532
[Universal MediaCreationTool](https://github.com/AveYo/MediaCreationTool.bat) is a wrapper for all Windows 10/11 versions from 1507 to 21H1 with business (Enterprise) edition support. Named after **MediaCreationTool** ([extras/mediacreationtool](https://github.com/ScoopInstaller/Extras/blob/master/bucket/mediacreationtool.json)).
**NOTES**:
* There is an [existing manifest](https://github.com/ACooper81/scoop-apps/blob/master/bucket/UniversalMediaCreationTool-Portable.json) in a custom bucket.
* This manifest downloads the whole repo (instead of just `MediaCreationTool.bat`) so that [bypass11](https://github.com/AveYo/MediaCreationTool.bat/tree/main/bypass11) can also be included. *Universal MediaCreationTool* does not depend on *bypass11* to work, but it can be useful in some …
=> universal-mediacreationtool: Add version 2022.03.20

bucket/telegram.json
Changed download links and autoupdate links from tdesktop.com to github. This is to resolve issue #7002.
> Telegram has anti-DDoS measurement, even if Telegram itself isn't blocked by your country or region. It might halt your telegram install or updates.
To fix this is simply access the web site: https://desktop.telegram.org/
Click the link to "Portable version" download: https://desktop.telegram.org/
Then lets your IP indexed on their whitelist database. It will downloads the portable version on your web browser, you can cancel it, then rerun the telegram update (or install),
Hence this measure. Not a major change, but github is always better.
Closes #7002
=> Telegram@v3.7.3: Changed links to github

bucket/spotify.json
Fixes https://github.com/ScoopInstaller/Extras/discussions/8534
=> spotify: Run uninstaller only on uninstall

bucket/speedtest.json
Added Speedtest GUI.
Homepage is https://speedtest.net/
This can be done online only but some people prefer the app.
I have not added the autoupdate part as the url remains same even after new version is released.
The checkver contains html elements as the regex part was not detecting things properly.
Closes #7136
=> Speedtest GUI: Add version 1.10.163

bucket/dnspy.json, bucket/dnspyex.json
closes #8544
[dnSpyEx](https://github.com/dnSpyEx/dnSpy) is a continuation of the dnSpy project, a .NET debugger and assembly editor.
**NOTES**:
* *persist* is not needed because config is at `$Env:AppData\dnspy`.
=> dnspyex: Add version 6.1.9

bucket/icecast.json
closes https://github.com/ScoopInstaller/Extras/issues/8538
[IceCast](https://icecast.org/) is a streaming media (audio/video) server which supports Ogg (Vorbis and Theora), Opus, WebM and MP3 streams.
**NOTES**:
* This package is in *Extras* (rather than *Main*) because of non-standard install methods.
* *IceCast* used to have Windows GUI and Windows service installation, but was removed in 2.3.3.
> https://icecast.org/faq/
What happened to the Windows GUI? I only see a black window with some text.
Icecast used to have a graphical user interface on Windows, but that was deprecated in 2.3.3 as it wasn’t frequently used and hard to maintain. Considering that most of the things the GUI could do now are possible using the Icecast web interface, it’s not needed anymore.
The black window with …
=> icecast: Add version 2.4.3

bucket/listary.json
fixes #8557
* [Listary](https://www.listary.com/download) doesn't seem to provide portable ZIP version anymore, which is causing installation to fail.
* The config data of the **installer** version is at `$Env:AppData\Listary\UserProfile`. However I cannot find the portable version to compare the difference. Therefore, I cannot be sure if copying the data from `$persist_dir\UserData` to `$Env:AppData` is safe. The config data of the two versions may be incompatible.
=> listary@6.0.9.25: Use installer instead of portable zip

bucket/uget.json
uget is currently 2.2.3 https://sourceforge.net/projects/urlget/files/uget%20%28stable%29/
=> uget@2.2.3: Fix checkver, autoupdate

bucket/openclosedriveeject.json
Previous v2 version's 64bit exe was "OpenCloseDriveEject_x64_p.exe" and new one is "OpenCloseDriveEject_x64.exe".
When updating, I was getting this error: Can't shim 'OpenCloseDriveEject_x64_p.exe': File doesn't exist.
Closes #XXXX
=> openclosedriveeject: new v3 changed executable name

bucket/sumatrapdf.json
Relates to Excavator unable to update due to change in download urls: https://github.com/ScoopInstaller/Extras/runs/6635716977?check_suite_focus=true#step:3:302
=> sumatrapdf: Update to version 3.4.2, fix autoupdate

bucket/twitchtest.json
[TwitchTest](https://r1ch.net/projects/twitchtest) is a lightweight program that performs a bandwidth test for Twitch.
**NOTES**:
* **suggest**: This app requires **VCRedist 2015**. Also, VCRedist 2022 now covers all functions from VC2015-2022.
> https://r1ch.net/projects/twitchtest
TwitchTest will work on all modern versions of Windows. The [Visual Studio 2015 Runtime (vc_redist.x86.exe)](https://www.microsoft.com/en-us/download/details.aspx?id=52685) is required (you'll get a missing VCRUNTIME140.DLL error otherwise). The program will prompt to launch as an administrator since connection quality statistics can only be measured under admin mode.
=> twitchtest: Add version 1.52

bucket/office-tool-plus.json
[office-tool-plus](https://github.com/YerongAI/Office-Tool) is a powerful and useful tool for Office deployments.
According to Sandboxie, it store its configuration in registry.
=> office-tool-plus: Add version 8.3.10.7

bucket/vesta.json
> VESTA is a 3D visualization program for structural models, volumetric data such as electron/nuclear densities, and crystal morphologies created and maintained by jp-minerals.org
VESTA is a successor to two 3D visualization programs, VICS and VEND, in the [VENUS (Visualization of Electron/NUclear and Structures) software package](http://fujioizumi.verse.jp/visualization/VENUS.html).
VESTA runs on Windows, Mac OS X, and Linux. It is contributed free of charge for non-commercial users.
More about it can be read [here](https://jp-minerals.org/vesta/en/)
=> vesta: Add version 3.5.7

bucket/freerapid.json
* closes https://github.com/ScoopInstaller/Versions/issues/532
* related: #8490
[FreeRapid](http://wordrider.net/freerapid/) is a Java downloader that supports downloading from Rapidshare, Youtube, Facebook, Picasa and other file-sharing services.
**NOTES**:
* **file source**: *FreeRapid* now puts their download behind a **pay-wall**.
In https://github.com/ScoopInstaller/Versions/issues/532, @NatoBoram states that there is a way to fetch files directly from their SVN.
However I don't think we should download from SVN because (1) they may close the access of SVN because of unusual number of connections, etc.  (2) This is some sort of "hacking", which should not be encouraged, especially in an open-source software.
Instead, we can just use the file fetched by `archive.org` before they put …
=> freerapid: Add version 0.9u4

bucket/extraterm.json
- Relates to Excavator unable to check for latest version: https://github.com/ScoopInstaller/Extras/runs/6645678794?check_suite_focus=true#step:3:224
- Now built with Qt so `qt` added to file name
=> extraterm: Update to version 0.62.0, fix checkver

bucket/uget-integrator.json
I found that uget-integrator will not work if user run the install command in Windows PowerShell instead of PowerShell Core.
On Windows PowerShell, the default encoding is utf-16le which makes post_install script break the app.
=> uget-integrator@1.0.0: Fix Out-File encoding

bucket/fclones.json
Relates to Excavator unable to update (`win` --> `windows`): https://github.com/ScoopInstaller/Extras/runs/6722644998?check_suite_focus=true#step:3:232
=> fclones: Update to v0.25.0, fix autoupdate

bucket/upx-easy-gui.json
* closes #5207
**[UPX Easy GUI](https://www.novirusthanks.org/products/upx-easy-gui/)** is a graphical user interface (GUI) for UPX EXE Compressor (`main/upx`).
**NOTES**:
* Not suggesting `upx` here because this upx-easy-gui contains bundled UPX.
* *license* info can be found in [EULA.txt](https://github.com/ScoopInstaller/Extras/files/8831243/EULA.txt) in the archive.
=> upx-easy-gui: Add version 2.1

bucket/rxrepl.json
Files for Google Sites are now hosted on Google Drive. So, "https://drive.google.com/uc?id=1reCUlV4He6ZDqX8GgJtuFsegc557PgDi&export=download" instead of "https://sites.google.com/site/regexreplace/home/rxrepl.zip?attredirects=0". Everything else seems the same.
Closes #XXXX
=> rxrepl@1.5: Fix URL

bucket/notepadplusplus.json
Notepad++ uses GPL-3.0-or-later
https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/master/LICENSE
Closes #XXXX
=> notepadplusplus: Correct license

bucket/imageglass.json
replaced the wrong URLs SHA1s and regex strings with correct ones
Closes #8611
Relates to #8611
=> ImageGlass: fix URL and SHA1 and regex

bucket/litebrowser.json
**[LiteBrowser](https://github.com/litehtml/litebrowser)** is a simple web browser designed to test the [litehtml HTML rendering engine](https://github.com/litehtml/litehtml).
**NOTES**:
* The version number `7ee5c11` comes from [the download page](http://www.litehtml.com/download.html).
> Download litebrowser
Built from 7ee5c11 commit (October 23 2015)
* **Command-line** usage can be found in [ReadMe](https://github.com/litehtml/litebrowser#readme).
> Run litebrowser with command line parameter:
litebrowser.exe http://www.litehtml.com
If you run litebrowser without parameter, the dmoz.org will be opened.
* Not suggesting `litehtml` here because (1) There is no `litehtml` in Scoop's official buckets. (2) I couldn't find a reliable distribution of …
=> litebrowser: Add version 7ee5c11

bucket/fluent-search.json
According to [Fluent Search blog post](https://fluentsearch.net/posts/fluent-search-version-09900), by the time PR #8362 created it is version 0.9.90.0.
Relates to #8362
=> Update fluent search version to 0.9.90.0

bucket/pterm.json
PuTTY 0.77 added the pterm application which is a wrapper around the Windows Command Prompt or other Windows Console applications. It is not included in the main PuTTY installation package.
Closes #8628 
=> pterm: Add version 0.77

bucket/siyuan-note.json
Siyuan-Note opened its source code with AGPL since v2.0.14.
https://github.com/siyuan-note/siyuan/blob/master/LICENSE
=> Siyuan-Note@2.0.17: license & homepage changed

bucket/peid.json
**PEiD** ([archived homepage](https://web.archive.org/web/20110226030434/http://peid.info/)) is a tool that detects most common packers, cryptors and compilers for PE files. It supports more than 470 different signatures in PE files.
**NOTES**:
* See [this page on Aldeid](https://www.aldeid.com/wiki/PEiD) for more info/usage.
* Using `ScoopInstaller/Binary` because the site http://peid.info is no longer valid.
* The app supports command-line args, for example:
> Information
PEiD detects most common packers, cryptors and compilers for PE files. It can currently detect more than 600 different signatures in PE files.
...
.4. Shell integration, Command line support, Always on top and Drag'n'Drop capabilities.
> PEiD News
...
New: Added a '-e' option to …
=> peid: Add version 0.95

bucket/simple-assembly-explorer.json
**[Simple Assembly Explorer](https://code.google.com/archive/p/simple-assembly-exploror/)** is an open-source .NET assembly tool that can browse assembly classes, edit method instructions, and manipulate resources.
**NOTES**:
* **autoupdate** is not needed because last update was in 2015.
* The app requires .NET Framework 4.0, but I don't think we need to **suggest** it because Win10/11 already have .NET4.0 built-in.
=> simple-assembly-explorer: Add version 1.14.4

bucket/dotnet-generic-unpacker.json
**[.NET Generic Unpacker](https://ntcore.com/?page_id=353)** is a program to dump .NET packed applications.
**NOTES**:
* Only **32-bit version** of .NET Generic Unpacker can dump **32-bit executables**. The same rule applies to 64-bit version.
> Download the x64 version of the .NET Generic Unpacker only if the process is not an x86 process. In all other cases download the x86 version.
* *autoupdate* is not needed because last update was in 2008.
=> dotnet-generic-unpacker: Add version 1.0.0.1

bucket/tak.json
The current manifest has a failing hash check because the developer's site seems to redirect links from old versions to the latest version. So this updates to the latest version available and adds autoupdate to handle that.
=> tak@2.3.2: Update manifest, add autoupdate

bucket/sidebar-diagnostics.json
Added Sidebar Diagnostics. A simple sidebar that displays hardware diagnostic information.
64bit
Stores settings at `%localappdata%\SidebarDiagnostics`
Closes https://github.com/ScoopInstaller/Extras/issues/8641
=> sidebar-diagnostics: Add version 3.6.2

bucket/lenovolegiontoolkit.json
Relates to Excavator unable to update due to change in download filename: https://github.com/ScoopInstaller/Extras/runs/6827520470?check_suite_focus=true#step:3:376
Added innosetup as it is no longer a standalone exe but an installer to be unpacked. Shortcut changed too.
=> lenovolegiontoolkit: Update to v2.0.0, fix autoupdate

bucket/draw.io.json
Relates to Excavator unable to update due to change in download filenames: https://github.com/ScoopInstaller/Extras/runs/6827520470?check_suite_focus=true#step:3:229
=> draw.io: Update to version 19.0.3, fix autoupdate

bucket/liteide.json
Relates to Excavator stuck at version 37.4 because different Qt versions in 32 and 64bit filenames: https://github.com/ScoopInstaller/Extras/runs/6827520470?check_suite_focus=true#step:3:391
=> liteide: Update to version 38.0, fix checkver

bucket/exeinfo-pe.json, bucket/peid.json
**[ExeInfo PE](http://exeinfo.booomhost.com/?i=1)** is an EXE analyzer inspired by **PEiD** (#8639). It is designed to detect exe signatures, compressor format and dump internal information.
**NOTES**:
* `exeinfope.exe` supports command-line args. 
For example, you can open an exe/dll by running `exeinfo (file path)`.
* Add **notes** to `extras/peid` that refers to this app.
**SCREENSHOTS**:
=> exeinfo-pe: Add version 0.0.6.9

bucket/everything.json
* This `pre_uninstall` script detects and stops **Everything service** before updating/uninstalling the app.
* Migrate existing actions from `uninstaller.scripts`.
* **Everything** requires admin rights to index NTFS volumes. This can either achieved by:
(1) Always run *Everything* under admin
(2) Install Everything service via Everything GUI, which is the more common way.
* However in the case of (2), users will have to either "stop everything service" or "terminate everything.exe" before updating the app via *Scoop*. Otherwise there will be a "file in use" error. This `pre_install` solves the problem.
* Using `Stop-Process` before stopping service because *Everything* **stays in tray** even after user closes the window. I think it is safe to kill the process because it does not break …
=> everything@1.4.1.1017: Add pre_uninstall script

bucket/strawberry.json
Relates to Excavator unable to find 32bit version in autoupdate: https://github.com/ScoopInstaller/Extras/runs/6842092174?check_suite_focus=true#step:3:428
32bit version is no longer in the file list and is no longer mentioned on the homepage: https://www.strawberrymusicplayer.org/
=> strawberry: Update to version 1.0.5, remove 32bit

bucket/ilmerge.json
**[ILMerge](https://github.com/dotnet/ILMerge)** is a static linker for .NET Assemblies developed by Microsoft .NET team.
**NOTES**:
* This is a command-line tool. I put this in `Extras` due to **popularity issues**. *ILMerge* is developed by Microsoft and has 1K starts, but this project has been **archived** and somewhat outdated. Some projects are still using it though.
=> ilmerge: Add version 3.0.41

bucket/qbittorrent-enhanced.json
Since v4.4.3.12, the released file of qbittorrent-enhanced had changed its name from `qbittorrent_enhanced_4.4.2.10_Qt6_x64_setup.exe` to `qbittorrent_enhanced_4.4.3.12_Qt6_setup.exe`
=> qbittorrent-enhanced: Update to version 4.4.3.12

bucket/rustdesk.json
- Looks like they silently changed their license in (https://github.com/rustdesk/rustdesk/commit/bf736c80e99d411b58eff8f206e871e445854ce9, https://github.com/rustdesk/rustdesk/commit/66070320b5c88836a6fa80f5c916276f583aed27)
- Remove `bin` as it has no CLI
- Capitalize `RustDesk.exe`
=> rustdesk: Change license to AGPL-3.0-only, Remove `bin`

bucket/klogg.json
The binaries in the release have been updated to addres an issue with bug reporting link. This PR updates links and hashes in package.
Closes #8691
=> Bump klogg to 22.06.0.1289

bucket/dnspyex.json
As of https://github.com/dnSpyEx/dnSpy/releases/tag/v6.2.0, dnSpyEx is no longer double zipped.
=> dnspyex: Remove pre_install

bucket/sunshine.json, scripts/sunshine/install-service.bat, scripts/sunshine/uninstall-service.bat
- Add `extract_dir`
- Copy `install-service.bat` and `uninstall-service.bat` to scripts for now because they were removed (https://github.com/SunshineStream/Sunshine/issues/197)
- Add a shortcut to match [installer](https://github.com/SunshineStream/Sunshine/releases/download/v0.14.0/sunshine-windows.exe) behavior.
- Fix `persist`
=> sunshine: Fix installation

bucket/protonmail-bridge.json
* Closes #7139
* **[ProtonMail Bridge](https://proton.me/mail/bridge)** is a bridge app that allows to keep using a desktop client while benefiting from Proton Mail’s end-to-end encryption.
**NOTES**:
* config location: `$Env:AppData\protonmail`.
* Using `pre_uninstall` because the app stays in tray after closing the window.
=> protonmail-bridge: Add version 2.1.3

bucket/folder-marker.json
* closes https://github.com/ScoopInstaller/Nonportable/issues/3
* **[Folder Marker](https://foldermarker.com/en/)** is a tool to label folders with color-coded / image-coded icon.
**NOTES**:
* This app requires **admin rights** to install because it requires registering DLLs. See [extracted InnoSetup script](https://github.com/ScoopInstaller/Extras/files/8930918/install_script.iss.txt) for more details.
* However, I think it is **accpetable** for `Extras` because we are simply extracting files and set up envs for it to work. (rather than running the installer).
* *license* info can be found in `License.rtf` under installation directory.
* config location: `HCKU:\Software\ArcticLine\FolderMarker`.
=> folder-marker: Add version 4.6

bucket/uniextract2.json
This solves the issue mentioned in https://github.com/ScoopInstaller/Extras/pull/8681#pullrequestreview-1005860044.
=> uniextract2: Prevent setup window from showing up upon first run

bucket/imo-messenger.json
* Closes #8677
* **[IMO Messenger](https://imo.im/)** is a free video calls and chat software.
**NOTES**:
* **package naming**: I named the package `imo-meessenger` (instead of `imo`) because both the shortcut *(created by the installer)* and window title says `imo Messenger`.
* `pre_uninstall` is used here because imo Messenger **stays in tray** after closing the window.
* **checkver**: using **third-party site** for *checkver* because imo's homepage **requires JS to load**.
I think it won't hurt because *imo* keeps their old releases on thier site. (which means it will not cause the installation failures even if the third-party site need a bit of time to catch up with the update). If there is a better source for *checkver*, please tell me. Thanks!
=> imo-messenger: Add version 1.4.1.6

bucket/vial.json
Vial is a graphical keyboard configuration tool for QMK powered keyboards.
=> vial: Add version 0.6

bucket/linphone.json
Linphone seems to update their install file on the same version (as you can see in the issue history well). 
Closes #8710
=> linphone@4.4.6: Fix hash

bucket/viddy.json
Add a manifest for viddy - A modern watch command. Time machine and pager etc.
https://github.com/sachaos/viddy
=> viddy: Add version 0.3.4

bucket/smplayer.json
* closes #8701
* **[SMPlayer](https://www.smplayer.info/)** is a video player forked from MPV. It can also play Youtube videos, search and download subtitles, and includes other features like a thumbnail generator and audio and video filters.
**NOTES**:
* not using `#/dl.7z` here because it will be treated as part of the input `www.fosshub.com/SMPlayer.html?dwl=...`, causing URL error.
* *persist*: **.m3u8** are playlists encoded in UTF-8. ([Wikipedia](https://en.wikipedia.org/wiki/M3U))
=> smplayer: Add version 22.2.0.0

bucket/camstudio.json
**[CamStudio](https://camstudio.org/)** is a free desktop recorder and video streaming software.
**NOTES**:
* Aside from `controller.ini`, most of the config is stored at registry: `HKCU:\SOFTWARE\CamStudioOpenSource for Nick`.
* *autoupdate* is not needed because last update was in 2015.
=> camstudio: Add version 2.7.4-r354

bucket/aimp.json
fix version checkver regex..
aimp have version format 5.03.xxxx. with current regex only returning 5.03.
=> aimp: Fix checkver

bucket/nvidia-profile-inspector-foulplay.json
This is FoulPlay's fork of the NVIDIA Profile Inspector. The original project by [Orbmu2k](https://github.com/Orbmu2k) has been inactive for a very long time (the latest stable version used in the original manifest is from Jan 13, 2020).
FoulPlay's fork is what's mentioned on the [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector).
The tool is used to modify game profiles inside the internal driver database of the NVIDIA driver. All game profiles are provided by the NVIDIA driver, but you can add your own profiles for games missing in the driver database. You also have access to hidden and undocumented settings, which are not provided by the driver's control panel.
=> nvidia-profile-inspector-foulplay: Add version 2.4.6.2

bucket/zlib.json, scripts/zlib/register.reg, scripts/zlib/unregister.reg
**[zlib](http://www.zlib.net/)** is a massively spiffy yet delicately unobtrusive compression library. Unencumbered by patents. It is being used in many well-known apps including *FFMpeg*, *MiKTex*, *caffe*, *PyTorch*, etc.
* This package is mainly for users who are building **projects that depends on zlib**.
* [The zlib license](https://spdx.org/licenses/Zlib.html) is an SPDX license.
* I did not add `$dir\bin` (which contains `zlib.dll`) to PATH because the file should be **bundled** with the app that is using it. Having `zlib.dll` in PATH may lead to some confusing situations.
* This package has to be **manually updated**, but I think it's fine because *zlib* does not receive updates very often. They have a recent bug fix in **2022.3**. The update …
=> zlib: Add version 1.2.12

bucket/handbrake.json
handbrake depends on .Net 5.0 which is [windowsdesktop-runtime](https://github.com/ScoopInstaller/Extras/blob/master/bucket/windowsdesktop-runtime.json) in scoop
Closes #XXXX
=> handbrake: Update depends

bucket/standardnotes.json
Bump Standard Notes version from v3.22.11 to v3.23.21. Additionally, Standard Notes made their [desktop repository](https://github.com/standardnotes/desktop) archive status and migrated their desktop application to their [standardnotes/app repository](https://github.com/standardnotes/app).
=> standardnotes: Bump version, update repository information

bucket/imhex.json
fix autoupdate url and bump to 1.19.0
=> imhex@1.19.1: Fix autoupdate url

bucket/manifold-viewer.json, bucket/manifold.json
Version numbers of Manifold|-Viewer are:
9.0.xxx or 9.0.xxx.yy and occasionally 9.0.xxx.yy-rN 
Change in #8417 broke "extract_dir" autoupdate for  9.0.xxx
This is manual quick-fix while preparing permanent fix.
Relates to #8417
=> manifold|-viewer: quick-fix for extract_dir and checkver

bucket/fvm.json
- Closes #8819
- Settings stored in `$dir\.settings` and is persisted
- Installed versions of Flutter go in `$dir\versions` and are persisted
- Environment variaable `FVM_HOME` set so that it can find the installed versions
Tested with 32bit and 64bit. Tested by running `fvm install stable` and then `fvm spawn stable --version` which outputs:
```
Spawning version "stable"...
Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (8 days ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2
```
=> fvm: Add version 2.4.1

bucket/runcat.json
I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> runcat: Update to version 2.0, Fix autoupdate

bucket/multibootusb.json
* closes #7143
* [MultiBootUSB](https://github.com/mbusb/multibootusb) is a tool that creates multiboot live Linux on a USB disk.
**NOTES**:
* Aside from the log, other config data is stored at `$Env:LocalAppData\Temp\multibootusb`.
=> multibootusb: Add version 9.2.0

bucket/calibre-normal.json
Calibre drops support for 32-bit CPUs after v6.0.0, if you are running a 32-bit system, please download `calibre-normal5` from Scoop Version bucket. 
> Source: https://calibre-ebook.com/new-in/fifteen
Also, add two new bins, `calibre-parallel.exe` and `calibre-complete.exe`
=> calibre-normal: Update to 6.0.0

bucket/chromium.json
Chromium can't be updated to a previous version because the hash check fails. The hash check fails because it's always comparing against the `latest` version instead of the version being installed.
```
$ scoop install chromium@102.0.5005.115-r1142
WARN  Given version (102.0.5005.115-r1142) does not match manifest (103.0.5060.66-r1002911)
WARN  Attempting to generate manifest for 'chromium' (102.0.5005.115-r1142)
Autoupdating chromium
Searching hash for chrome.sync.7z in https://github.com/Hibbiki/chromium-win32/releases/latest
Found: sha1:41be8f368a2e7d125b970969d82cce9481b7942b using Extract Mode
Searching hash for chrome.sync.7z in https://github.com/Hibbiki/chromium-win64/releases/latest
Found: sha1:a133ccb2a19de065632ee575c5a88979a3ec92a8 using Extract Mode
Writing updated chromium …
```
=> chromium: Fix autoupdate.hash for old versions

bucket/raindrop.io.json
Relates to #8849
The issue mentions that the license is MIT, but I can't find the source information, so I'm using Unknown for now.
=> raindrop.io: Add version 5.5.5

bucket/pixitracker-1bit.json, bucket/pixitracker.json
**[PixiTracker](https://warmplace.ru/soft/pixitracker/)** is a simple tool to quickly create **musical sketches**, chiptunes and sound experiments, without requiring a lot of musical knowledge.
The app comes with 2 variants: regular **16Bit** (high quality) and retro-style **1Bit**.
**NOTES**:
* license info is written in `$dir\docs\license`.
**SCREENSHOTS**:
=> pixitracker(-1bit): Add version 1.6.5

bucket/calibre-normal.json, bucket/calibre.json
calibre release assets is removed after a new version is relased. old version files are served at download.calibre-ebook.com
=> Calibre: fix url

bucket/quarto.json
~This PR update Quarto to  last stable v1 version which is v1.0.35. ~ Update has been done in the meantime in the repo. 
It also change the bundle to use the zip file instead of the MSI file as the zip bundle provided by quarto team is the portable one. No need to download a msi file to unzip.
=> quarto: use zip bundle instead of msi file

bucket/appflowy.json
appflowy tops 1st in [GitHub Trending](https://github.com/trending) today
AppFlowy is an open-source alternative to Notion. You are in charge of your data and customizations. Built with Flutter and Rust.
24k stars
https://github.com/ScoopInstaller/Main/pull/3770
=> appflowy: Add Version 0.0.4

bucket/appflowy.json
Fix `Creating shortcut for AppFlowy (app_flowy.exe) failed: Couldn't find D:\Scoop\apps\appflowy\current\app_flowy.exe`
=> AppFlowy: Fix extract_dir

bucket/chromium.json
fixed the checkver by querying the github api for the lastest tag (as upstream sometimes only makes a tag and not a release while still uploading binaries)
=> chromium@103.0.5060.134-r1002911: fix checkver and update

bucket/keepass-plugin-keeagent.json
Fix the autoupdate url and update version to 0.13.1.
=> keepass-plugin-keeagent@0.13.1: Fix autoupdate and update

bucket/pinta.json
- Relates to #8919
- Settings stored in `AppData\Roaming\Pinta`
- Downloaded file is renamed to `Pinta-dl.exe` so it doesn't conflict when the main program is unpacked as `Pinta.exe`
- 64-bit only, checked with `sigcheck`
=> pinta: Add version 2.0.2

bucket/kubeconform.json
Just for confirmation:
```
C:\App\Scoop
❯❯ .\apps\scoop\current\bin\checkver.ps1 -App .\buckets\extras\bucket\kubeconform.json
kubeconform: 0.4.14
C:\App\Scoop took 1s282ms
❯❯ scoop install kubeconform
Installing 'kubeconform' (0.4.14) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 789c9d|OK  |   2.1MiB/s|C:/App/Scoop/cache/kubeconform#0.4.14#https_github.com_yannh_kubeconform_releases_download_v0.4.14_kubeconform-windows-amd64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of kubeconform-windows-amd64.zip ... ok.
Extracting kubeconform-windows-amd64.zip ... done.
Linking …
```
=> kubeconform: Add version 0.4.14

bucket/godot-mono.json, bucket/godot.json
Download URLs are from GitHub Releases, so it makes more sense to use checkver from GitHub.
This also fixes checkver as it recently broke due to design changes on the Download page.
I ran checkver.ps1 locally to update the manifest and make sure it works as expected.
=> godot|-mono: Update checkver to rely on GitHub Releases

bucket/sysinternals.json
Using version number from Sysinternals doc's source file (which is in GitHub).
- Closes #8962
=> sysinternals: Use digital version number

bucket/keepass-plugin-keeagent.json
Updated URL and autoupdate URL to match current repository release URL structure.
Closes #8982
=> keepass-plugin-keeagent@0.13.1: Fix download URL

bucket/divoom-cli.json, bucket/divoom-gateway.json
2 command line tools for controlling the [divoom device](https://www.divoom.com/products/pixoo-64).
Repo and more README could be found here: https://github.com/r12f/divoom.
- divoom-cli: https://github.com/r12f/divoom/tree/main/divoom_cli
- divoom-gateway: https://github.com/r12f/divoom/tree/main/divoom_gateway
=> divoom-cli, divoom-gateway: Add version 0.1.25

bucket/pet.json
- Name: Pet
- Description: Simple command-line snippet manager, written in Go.
- Homepage: https://github.com/knqyf263/pet
- Download link(s): https://github.com/knqyf263/pet/releases
- Popularity: Star 3.5k, Fork 176
- Config and snippets are stored in `AppData\Roaming\pet`
---
=> pet: Add version 0.4.0

bucket/paraview.json
There once had been a bucket for Paraview, but it got removed: e6b9494eba9a88674569601fba3973557e0f5ecc. However, I cannot figure out the reason for this deletion.
This new PR installs correctly. But there are two caveats:
- How can we incorporate the [ParaView Settings Files](https://www.paraview.org/Wiki/ParaView_Settings_Files) into the `persist` directory? There seem to be two files under `%APPDATA%\ParaView`, namely `ParaView-UserSettings.json` and `ParaViewX.Y.ini`. In this filename, `X.Y` are kind of dynamically named. Maybe we could somehow use`$majorVersion.$minorVersion`?
- How can we add `checkver` and `autoupdate`? A machine-readable list of all versions can be found at https://www.paraview.org/files/listing.txt. But I cannot figure out how use this list in `checkver`.
=> paraview: Add version 5.10.1

bucket/runcat.json
Relates to #8837
Users may already have installed _.NET 6.0 Desktop Runtime_, or they don't want to use scoop to install the runtime.
=> runcat: move windowsdesktop-runtime to suggest

bucket/vcredist2008.json, bucket/vcredist2012.json, bucket/vcredist2013.json, bucket/vcredist2015.json, bucket/vcredist2017.json
Hi guys, this is my first MR in this repo, please advice me on anything I am doing wrong.
I had the issue today, that the ArgumentList that was passed to the vcredist2013 package was ignored (/quiet),
so scoop was always opening the prompt to accept the license informations to install.
That halts my automation script and I realized this behaviour is not expected, it's a small bug in the post_install script.
So.. there is the fix!
=> vcredist*: Fixed ArgumentList in post_install scripts.

bucket/android-messages.json
and switch to maintained fork. 
The current version 3.0.1 points to 1.0.1.
Source: https://github.com/rasa/scoops/blob/master/bucket/android-messages.json
=> android-messages: Update to 5.3.4

bucket/komorebi.json
Updates the hash of release `v0.1.11` of `komorebi`
https://github.com/LGUG2Z/komorebi/releases/tag/v0.1.11
=> komorebi: fix hash for v0.1.11

bucket/vscodium.json
version was written as static.
when auto updating this causes 404 errors.
Relates to #9014
This PR added 32bit version but failed to get upstream version.
=> vscodium: fix autoupdate for 32bit

bucket/asar7z.json
* closes #3797
* relates to https://github.com/ScoopInstaller/Main/issues/849
**[Asar7z](https://www.tc4shell.com/en/7zip/asar/)** is a 7-zip plugin that allows 7-zip to open, modify, or create **Electron .asar archives**.
**NOTES:**
* Using **path checks** for 7z (instead of `"depends": "7zip"`) so that the package is compatible with **other variants of 7-zip**, such as `versions/7zip-zstd`.
* I tested the plugin with this file: [betterdiscord.asar](https://github.com/BetterDiscord/BetterDiscord/releases/download/v1.6.2/betterdiscord.asar)
* Last update of the plugin was on `09 Jul 2022`.
=> asar7z: Add version 1.3

bucket/stretchly.json
https://github.com/hovancik/stretchly/releases/tag/v1.11.0
> ## Changed
>
> - no Linux 32 builds, as Electron does not support them anymore
=> stretchly: Update to version 1.11.0, Remove 32bit

bucket/gtk-sharp.json
* closes #8972
**[GTK#](https://www.mono-project.com/docs/gui/gtksharp/)** is a runtime library for Gtk-based applications on Microsoft .NET.
**NOTES**:
* Using `Start-Process` (instead of `Invoke-ExternalCommand`) as a workaround to avoid error when `$dir` **contains spaces**.
=> gtk-sharp: Add version 2.12.45

bucket/propertree.json
propertree has a GUI so it need shortcut
=> propertree: add persist and shortcut

bucket/vnote.json
Vnote upload a new release to fix some building problem, so change the download url for current version only.
=> vnote@3.14.0: Use file url for special patch

bucket/altsnap.json
AltSnap is receiving a feature where it can be invoked from a shell to perform actions with args, so it only makes sense to add a bin shim.
https://github.com/RamonUnch/AltSnap/issues/285
=> AltSnap: Add bin

bucket/scoop-completion.json, scripts/ModifyPSProfile.psm1, scripts/scoop-completion/append-to-profile.ps1, scripts/scoop-completion/remove-from-profile.ps1
This PR is related to #8948 , which added a PowerShell module. 
The module is aimed to provide a tool for each psmodule-like app to edit PowerShell profile, but all of them needs templet files created in advance, so I added a function to generate files without template.
=> Generate PowerShell profile modifier without templete files

bucket/vnote.json
in previous PR https://github.com/ScoopInstaller/Extras/pull/9080 I update the file url for 3.14.0 only, but didn't find that the file hash also changed.
🤔 if i recall correctly there is a CI to check file hash?
=> vnote: Update to version 3.15.0

bucket/vnote.json
... Why they change release url again?
=> vnote 3.15.0: fix 64bit url and hash

bucket/pia-desktop.json
Closes #9112
config location: $env:LocalAppData/Private Internet Access
=> pia-desktop: Add version 3.3-06906

bucket/cfssl.json
Relates to Excavator found update but no autoupdate in manifest: https://github.com/ScoopInstaller/Extras/runs/8109300378?check_suite_focus=true#step:3:214
`cfssl: 1.6.2 (scoop version is 1.6.1)`
Opening a PR because I wasn't sure if autoupdate was omitted for a specific reason, seems to work okay for me. I suspect maybe autoupdate hash extraction didn't work before for one checksum and multiple files?
=> cfssl: Update to version 1.6.2, add autoupdate

bucket/manictime.json
This pull request will include the following updates:
- Support for new portable version release URL (so changed autoupdate url)
- The file name has been changed from `ManicTimeUsb.zip` to `manictime-portable-$version-win-x64.zip` including the version name.
- Supports 64bit application added since ManicTime v5.1
- See [ManicTime releases](https://www.manictime.com/Releases/)
- Update to version ManicTime v5.1.4.1 (Previously it was v5.0.2.0)
---
=> manictime: Update to version 5.1.4.1

bucket/quarto.json
This PR modies the `bin` property to use the new `quarto.exe` binary now included in the bundle. This new exe file solves some issues in some system and is the recommended way to call quarto now.
=> quarto@v1.1.189: Use new `quarto.exe` binary

bucket/jpass.json
Add JPass version 0.1.28 - Password manager application with strong encryption (AES-256)
=> jpass: Add version 0.1.28

bucket/010editor.json
=> 010editor: Update to version 13.0, Fix autoupdate

bucket/clash-mini.json
[Clash.Mini](https://github.com/MetaCubeX/Clash.Mini) a simple GUI for [Clash](https://github.com/Dreamacro/clash).
Which first publish at #7921, and deprecated at [commit #054309](https://github.com/ScoopInstaller/Extras/commit/054309aea37ffaef4771f4c16d295bf43399abaf)
=> clash-mini: Add version 0.2.0

bucket/caesium-image-compressor.json
=> caesium-image-compressor: fix auto update for extract_dir

bucket/windowsdesktop-runtime-lts.json
Corrected some descriptions according to https://dotnet.microsoft.com/en-us/download/dotnet/6.0
ASP.NET Core Runtime 6.0.9
The ASP.NET Core Runtime enables you to run existing web/server applications. On Windows, we recommend installing the Hosting Bundle, which includes the .NET Runtime and IIS support.
.NET Desktop Runtime 6.0.9
The .NET Desktop Runtime enables you to run existing Windows desktop applications. This release includes the .NET Runtime; you don't need to install it separately.
.NET Runtime 6.0.9
The .NET Runtime contains just the components needed to run a console app. Typically, you'd also install either the ASP.NET Core Runtime or .NET Desktop Runtime.
In fact this manifest is `.NET Desktop Runtime` 6.0.9
=> windowsdesktop-runtime-lts: Update info

bucket/wsl-distrod.json
Distrod is a meta-distro for WSL 2 which installs Ubuntu, Arch, Debian, Gentoo, etc. with systemd in a minute for you. Distrod also has built-in auto-start feature on Windows startup and port forwarding ability.
=> WSL-distrod: Add version 0.1.7

bucket/vscode.json, bucket/vscodium.json
Users cannot import reg using previous commands in `"notes"`
=> vscode, vscodium: fix reg import cmds in notes

bucket/x64dbg.json
x64dbg can download debug symbols from Microsoft public symbol server. This PR add persist for downloaded symbols.
=> x64dbg: Persist symbols folder

bucket/kate.json
Closes #9289
Although the official website indicates that version 22.08.1 is available, the corresponding installer with language and translation is not yet available. Therefore, only the update to version 22.08.0 is available for now.
Since checkver and autoupdate have been fixed, if the 22.08.1 installer is released on the official website, it should be updated properly.
btw, the installation package without translations for the new version is available at https://binary-factory.kde.org/job/Kate_Release_win64/. Personally, I think it is better to use the installation package released on the official website rather than the one in https://binary-factory.kde.org/job/Kate_Release_win64/
=> kate: Update to 22.08.0

bucket/kdeconnect.json
Relates to [#9298](https://github.com/ScoopInstaller/Extras/pull/9298#issuecomment-1256052250)
And also add kdeconnect-nightly version manifest to Version bucket.
=> kdeconnect: Update to 22.08.0

bucket/filelight.json
Relates to [#9298](https://github.com/ScoopInstaller/Extras/pull/9298#issuecomment-1256052250)
And also add filelight-nightly version manifest to Version bucket.
=> filelight: fix version to 22.08.0

bucket/wireshark.json
Closes #9468
The version 4 no longer supports 32-bit OS.
Version 3.6.8: https://github.com/ScoopInstaller/Versions/pull/706
=> wireshark: Update to version 4.0.0

bucket/linphone.json
Change the hash to correct the correct hash of 6bdc54dcdb53fdd4b485b04d1c5db574b441b53953d11c7e98a1b3fa8017ac08
=> linphone@4.4.10: Fix hash

bucket/musikcube.json
It was opening outside of the term, because the wrong bin was shimmed.
Now that I checked issues, I'll also change the `32bit` version to  use milkdrop
Closes #8658
=> musikcube: Fix bin

bucket/elasticsearch.json
if you try to install a older version like '7.1.1' with scoop install <app>@<version> the shim fails to be created due to changes in the app structure,
actually the scoop installer itself should ignore missing shims in the cases were you are downgrading to a given version, I think that would be more appropriate.
in the meanwhile we can fix this by just putting the entire Elasticsearch 'bin' folder into PATH
=> elasticsearch: Use `bin` path to avoid missing shims for older versions

bucket/openrgb.json
Apparently, the download URLs changed.
=> openrgb: Fix download and autoupdate URLs

bucket/musicplayer2.json
Add a default configuration to enable the profile to be portable and persistent
=> musicplayer2@2.75: Set portable mode to default configuration

bucket/manifold-viewer.json, bucket/manifold.json
Close #9430
* Manifold no longer have 32bit mode executables. 
* URLs are changed
* extract_dir does not have -x64
* autoupdate changed
=> manifold(-viewer): Fix url, shortcuts and autoupdate

bucket/hashcheck.json
This should solve the problem of the **hashcheck** Windows shell extension not being removed by the uninstaller script.
=> hashcheck: Enhance the `installer` and `uninstaller` scripts.

bucket/librewolf.json
The wrong URL is using the id of the signature file. 
```json
{
"links": [
"@{id=1034241; name=sha256sums.txt; url=https://gitlab.com/librewolf-community/browser/windows/uploads/86ff8c2bf9be973be4b1046b3a021c80/sha256sums.txt; direct_asset_url=https://gitlab.com/librewolf-community/browser/windows/uploads/86ff8c2bf9be973be4b1046b3a021c80/sha256sums.txt; external=False; link_type=other}",
"@{id=1034240; name=librewolf-106.0.1-1.en-US.win64-portable.zip.sig; url=https://gitlab.com/librewolf-community/browser/windows/uploads/57e8cb791892a99e5d426105d28f330a/librewolf-106.0.1-1.en-US.win64-portable.zip.sig; direct_asset_url=https://gitlab.com/librewolf-community/browser/windows/uploads/57e8cb791892a99e5d426105d28f330a/librewolf-106.0.1-1.en-US.win64-portable.zip.sig; external=False; …
```
=> librewolf: Fix checkver script

bucket/jira-cli.json
Jira-CLI tool that actually works
Does support only ~/.config folder for config so no persist support can be done sadly
=> jira-cli: Add version 1.1.0

bucket/ida-free.json
=> ida-free@8.1: Fix (un)install scripts

bucket/discord-rpc-extension.json
Server for the [Discord RPC Extension](https://github.com/lolamtisch/Discord-RPC-Extension), which is used by [PreWrap](https://github.com/lolamtisch/PreWrap) and [MALSync](https://github.com/MALSync/MALSync).
=> discord-rpc-extension: Add version 0.1.2

bucket/siyuan-note.json
REF: [32-bit installations are no longer built on Windows · Issue #6386 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/6386)
=> siyuan-note: Update to version 2.4.11, Remove 32bit

bucket/fix-print-spooler.json
fix autoupdate and extract_dir
Closes https://github.com/ScoopInstaller/Extras/issues/9660
Relates to https://github.com/ScoopInstaller/Extras/pull/9701
=> fix-print-spooler: Fix extract_dir and autoupdate

bucket/viddy.json
=> viddy: Add arm64 architecture

bucket/easy-context-menu.json
Fixes this error I had with this app,
=> easy-context-menu: Fix `hash`

bucket/vt-uploader.json, scripts/vt-uploader/install-context.reg
- Use `REG` command instead of registry file
- Move `pre_uninstall` to `post_uninstall`
Closes #XXXX
=> vt-uploader: Update manifest

bucket/kryptor.json
The file names in the release changed (added -x64), therefore the auto update failed.
Also, newer versions use `.digest` (instead of `.DIGEST`) for the hash (although GitHub seems to be case insensitive here).
=> kryptor@4.0.0: Update url, hash, and autoupdate

bucket/librehardwaremonitor.json
Assets listed under GitHub releases are not parseable from HTML anymore. Values are populated from API through JavaScript.
For example, the `0.9.1` assets listed on https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases are populated from the API https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/expanded_assets/v0.9.1.
This PR reverts the `checkver` changes from #8416, and uses `github` again. This also updates librehardwaremonitor to version `0.9.1`.
Relates to #8416 and ScoopInstaller/Scoop#5190.
=> librehardwaremonitor@0.9.1: use github checkver

bucket/registry-finder.json
This PR implements a better backup method and eliminates the purpose for creating an alias shim.
Closes #9809, #9769
=> registry-finder: preserve all config files

bucket/vt-uploader.json
Fixes this issue I had with the app. The issue was when you used the context menu option, it would pull up the **Open With…** menu instead of the **VirusTotalUploader** app.
=> vt-uploader: Fix `post_install` script

bucket/megasync.json
Recently the hash of the installer was change (Issue #9877) but the program version was not changed. This pull request just bumps it to the correct version.
Relates to #9877
- I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> megasync: Update to version 4.8.1.0

bucket/mpv-git.json, bucket/mpv.json
[mpv.net](https://github.com/mpvnet-player/mpv.net) fails to terminate MPV subprocesses when using the shim. This was causing problems such as [thumbfast](https://github.com/po5/thumbfast) not displaying the thumbnails properly. Adding mpv directly to the path fixes the problem.
=> mpv(-git): Add to path instead of shimming

bucket/mpv.json
`mpv` does not have an `updater.bat`, my bad.
Related to #9662
=> mpv: Remove `pre_install`

bucket/skaffold.json
The skaffold team republished the `v2.0.2` windows binary due to an issue with signing the binary which was later resolved.  The sha256 value that the github action picked up is no longer correct as a result of this.  This PR contains the correct hash.
Skaffold `v2.0.2` windows binary from our release page has the value in this PR:
https://github.com/GoogleContainerTools/skaffold/releases/download/v2.0.2/skaffold-windows-amd64.exe
https://github.com/GoogleContainerTools/skaffold/releases/download/v2.0.2/skaffold-windows-amd64.exe.sha256
```
aprindle@aprindle-ssd ~/Downloads $ sha256sum skaffold-windows-amd64.exe
7a1202a0674c7600d16b9f05c96185aaec01b6a1108b56891d0344dbf2dbd3a0  skaffold-windows-amd64.exe
aprindle@aprindle-ssd ~/Downloads $ cat skaffold-windows-amd64.exe.sha256 …
```
=> skaffold@2.0.2: Fix hash

bucket/psiphon3.json
Relates to #9661 
hash of psiphon3 changed again
=> psiphon3: fix hash

bucket/qbittorrent-enhanced.json
- Use standard version instead of qt6
- 32bit
- Update `autoupdate`
Closes #9930 #9931 #9914
=> qbittorrent-enhanced@4.5.0.10: Update manifest

bucket/mp3tag.json
This allows for mp3tag to be added as a shell extension when the user installs this app.
=> mp3tag: Enhance `pre_install` script, add `pre_uninstall` script, and change `persist`

bucket/octant.json
Some updates for octant:
- add arm64 architecture;
- update `homepage`.
=> octant: Add arm64 architecture

bucket/onefetch.json
Since 2.14.0 the "v" in naming convention is dropped, so:
- `autoupdate` URL fixed accordingly;
- manifest updated to the actual version.
Relates to o2sh/onefetch#868.
=> onefetch: Fix autoupdate

bucket/tor-browser.json
Tor browser installer's file name has changed from using suffix en-US to ALL. As a result auto-update has been failing (version check still works fine).
=> tor-browser: Update to 12.0, fix AU URLs

bucket/vieb.json
This PR provides updates manifest of Vieb and adds support for ARM64 binaries.
Contains url to artifact and hash.
=> vieb: Add version 9.4.0 for arm64

bucket/min.json
Some updates for min:
- add 32bit (ia32) architecture;
- move `extract_dir` to higher level (since it equals for both 64bit/32bit versions);
- update homepage.
=> min: Add 32bit version

bucket/oculante.json
Tested via both installing the previous version and autoupdating manifest to the current version with the checkver (the udpated manifest is in this PR)
Closes #10003
=> Add oculante

bucket/jenv.json
Adds https://github.com/FelixSelter/JEnv-for-Windows for managing Java versions.
It was recommended to move this to Extras [here](https://github.com/ScoopInstaller/Java/pull/378).
=> jenv: Add version 2.1.0

bucket/restish.json
Some updates for restish:
- add arm64 architecture;
- add autoupdate hash extraction.
=> restish: Add arm64 architecture

bucket/mp3tag.json
**mp3tag** has a problem where the program will not uninstall if the context menu is installed. This edit should fix that issue.
=> mp3tag: Fix `pre_(un)install` script

bucket/xmedia-recode.json
Updates **xmedia-recode** to the latest version. The manifest is using the setup files instead of the portable files. The reason for this is due to the developer discounting development for the portable 32bit version.
=> xmedia-recode: Update to version 3.5.6.7

bucket/lite-xl.json
Update the lite-xl manifest to lite-xl v2.1.0
=> lite-xl: Update to version 2.1.0

bucket/imhex.json
**imhex** settings files have been moved to the `config` folder by the dev. This manifest has been fixed to deal with that issue.
=> imhex: Removed `pre_install`. Added `pre_uninstall` & fixed `persist`

bucket/vscode.json, bucket/vscodium.json
It seems that starting from version 1.74, vscode replaces paths in `extensions.json` with the actual path where before it was happy with `current`.  In consequence, after an update and a cleanup, paths in `extensions.json` point to the directory of the older version. For example, if we update from `1.74.0` to `1.74.1`, a path would be left to:
```text
c:\\Users\\xxx\\scoop\\apps\\vscode\\1.74.0\\data\\extensions\\ms-vscode-remote.vscode-remote-extensionpack-0.23.0
```
This makes all extensions disappear from vscode.
This PR modifies the post-install script in order to replace whatever version is in the `extensions.json` file with the current version. We don't replace with `current` because as all new extensions would be installed with the current version number, it would make the …
=> vscod(e|ium): Adjust extensions paths after update

bucket/microsip.json
Current microsip manifest uses the lite package instead of the full one.
They are both equally portable, and the difference in size is about 7MB which is minor, for gaining video support.
=> microsip: Change lite to full version

bucket/winmtr-live.json
fork of a fork, even has a cli bin
=> winmtr-live: Add version 1.1

bucket/xampp.json
File `xampp-control.ini` is not in archive by default, so we create it.
Scoop links it as directory, not a file, if it does not exist, which leads to incorrect start of application.
Also add automatic PHP setup (does not change system files).
=> xampp@8.1.12-0: Fix config and Add setup

bucket/vscodium.json
I made a mistake in the PR #10074 when copy pasting my fix for vscode. I didn't take into account the fact that the paths are not the same. Sorry about that.
Closes #10088
=> 🐛 #10088: Bad extensions path when replacing versions

bucket/gitextensions.json
GitExtensions v4.0.0 has a blocking issue which prevents it from being able to [pull with git 2.39](https://github.com/gitextensions/gitextensions/pull/10521).
This PR updates gitextensions to v4.0.1 and revert the autoupdate to the previous versions because it is [working for v4.0.1](https://github.com/val1984/scoop-main-alternative-location/commit/e9af58d13067a14579d8579f99a5eb147170ae8c) as well and https://github.com/gitextensions/gitextensions/releases/expanded_assets/v4 is always showing v4.0.0 which is why v4.0.1 isn't offered.
I found a similar PR but this autoupdate fix is far simpler and I was able to test that it works with Excavator on my small private bucket.
=> gitextensions: Update to version 4.0.1 & fix autoupdate

bucket/freeplane.json
Freeplane [requires Java 11 to 17 to be installed](https://docs.freeplane.org/getting-started/Distributions.html), while openjdk/oraclejdk is 19.
=> (fix) freeplane@1.10.6  java version

bucket/mpc-qt.json
It works only on 64-bit Windows.
=> MPC-QT: Restrict to 64-bit

bucket/mcomix.json
It works only on 64-bit Windows.
=> MComix: Restrict to 64-bit

bucket/ghidra.json
Changed java version to 17 in suggest and notes fields, for last version of ghidra
Closes #XXXX
EDIT:
https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/stable/GhidraDocs/InstallationGuide.html#Requirements
=> ghidra@10.2.2-20221115: Update `notes` and `suggest`

bucket/ventoy.json
Ventoy supports Windows command line mode since 1.0.86. https://www.ventoy.net/en/doc_windows_cli.html
Closes #XXXX
=> ventoy: Add bin for CLI mode

bucket/powertoys.json
PowerToys adopted a strategy of creating links in the file system to share dependencies between utilities. The fact that the PowerToys Scoop package doesn't run the installer means that these dependencies don't get created except by doing extra steps.
This means that auto-updating the PowerToys manifest leads to installations that do not work properly at runtime. This has happened with 0.63 and 0.64. ( #9419 and #9643 , respectively).
This is bound to happen again in 0.66, set to release this week, since the inclusion of self-contained .NET binaries: https://github.com/microsoft/PowerToys/commit/6ac508fb933d0a30e1176baae34981f91e0984cf
This commit removes the auto-update feature, as the scoop manifest needs extra additions to have a working 0.66 installation.
Relates to #9419 and #9643
=> PowerToys@0.66+: Remove auto-update

bucket/gcc-arm-none-eabi.json
Release Note for Downloads 12.2.Rel1:
> Known Limitations and Issues
> 
> In the Linux hosted toolchains, GDB is provided with Python support. In the Windows and macOS hosted toolchains, GDB is provided without Python support.
>
=> gcc-arm-none-eabi: Update notes and regex of checkver

bucket/brave.json
Brave's checkver keeps picking up versions that are very old and I can't work out why. It has picked up the following releases: [1.5.9](https://github.com/ScoopInstaller/Extras/commit/3e1999f1e2d6ad7ca97d4594b22997d3a8415e11), [1.9.2](https://github.com/ScoopInstaller/Extras/commit/a406a4dfbe0774e94e808df4260bdb5a4c689a64), [1.1.1](https://github.com/ScoopInstaller/Extras/commit/6866d4d74126eeb72e4dcc7cd0bcb556a45f0c16). I think this could be caused by the lack of any stable releases in the list that the GitHub API returns or maybe an occasional API error. Instead I suggest we use [Brave's release notes page](https://brave.com/latest/). I suggest we keep the checkver for the beta and nightly versions as that seems to be working fine.
=> brave: Fix checkver

bucket/pterm.json, bucket/putty.json, bucket/puttytel.json
Add arm64 version for:
- putty;
- puttytel;
- pterm.
=> pterm|putty|puttytel: Add arm64

bucket/darktable.json
=> darktable@4.2.0: Extract via 7zip instead of run installer

scripts/everything/install-context.reg
Changes the context menu from 'search with Everything' to 'Search with Everything'. This issue also affects `everything-alpha` in the version bucket. PR for that: https://github.com/ScoopInstaller/Versions/pull/938
=> everything: Fix typo in context menu item

bucket/tailscale.json
Tailscale a WireGuard based mesh VPN, used
to connect your computers and other devices
together securely without proxies.
=> tailscale: Add version 1.34.2

bucket/universal-ctags.json
Previously this was on build 2020-10-11, I've updated it to use the `"github"` autoupdate and to v6.0.0.
=> universal-ctags: Update to version 6.0.0 and Add checkver

bucket/freecad.json
This PR fixes broken a shim/shortcut caused by a change in the extracted folder structure since version 20.1.
Previously, the program executables resided in `\\bin`, but now they are in `\\FreeCAD-portable\bin`. I don't know if this change was intentional by the developers but until/unless they change it back, this fix is required for the scoop manifest...
=> FreeCAD@0.20.2-2: Fix shim/shortcut

bucket/twine.json
Since the binary releases URLs changed on 2.4.x, the `autoupdate` `url` field was properly fixed. After running `.\bin\checkver.ps1` the version and its hash were automatically updated as well.
=> twine@2.6.0: Update to 2.6.0 and fix autoupdate url

bucket/trafficmonitor-lite.json, bucket/trafficmonitor.json
This package depends on `vcredist2019`, but this dependency was missing in the manifest file. Therefore, this commit adds it accordingly. It also changes the wording in description.
=> trafficmonitor, trafficmonitor-lite: fix missing dependency and typo

bucket/qview.json
This allows people to add `imageformats` plugins if they so choose
These are common ones, I'm open to adding more on request, but it's better to at least support these as it's a pretty large amount of functionality.
Relates to https://github.com/ScoopInstaller/Versions/pull/899
=> qview: Add possible plugin persists

bucket/hwinfo.json
Since `persist` does not have conditional functionality, 32-bit profiles will generate invalid links when only 64bit scripts are executed.
=> hwinfo: Fix persistence

bucket/freecad.json
My PR #10257 had exactly the right description but my code had the subfolders reversed and of course I broke rule 4... didn't test it first. So the manifest remains broken.
This PR fixes the typo and HAS BEEN TESTED on my local machine. Maintainers, feel free to double-check my sanity.
=> freecad@0.20.2-2: Fix subfolder reversal typo in recent change

bucket/android-sdk.json
The current version of 'emulator.exe' is installed into the folder 'emulator' and not 'tools'.
The executable in 'tools' either complains about using an old version or refuses to start with an error like this:
PANIC: Missing emulator engine program for 'x86' CPU.
Apparently this change of paths was made sometime in 2017:
https://developer.android.com/studio/releases/emulator#25-3
The date of 'tools/emulator.exe' is 2017-09-13, while emulator/emulator.exe is '2023-01-21'.
References:
https://stackoverflow.com/questions/51606128/windows-emulator-exe-panic-missing-emulator-engine-program-for-x86-cpu/51627009#51627009
https://developer.android.com/studio/run/emulator-commandline
=> android-sdk@4333796: Fix shim path for emulator

bucket/kscript.json
Added kscript.json to the bucket
=> kscript: Add version 4.1.1

bucket/git-credential-manager.json
Microsoft renamed the exe. The old one still works, but outputs a nag message:
> git-credential-manager-core --version
warning: git-credential-manager-core was renamed to git-credential-manager warning: see https://aka.ms/gcm/rename for more information 2.0.886+ea93cb5158
The [rename explainer page][1] says they'll keep the symlinks for two major Git versions, so maybe scoop should do the same? I kept the core.exe. I don't see any reason to link to the old exe for the start menu shortcut, so that's just pointing to the new one.
[1]: https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/rename.md
Closes #10382
=> Add git-credential-manager.exe shim

bucket/hwmonitor.json
Use HTTPS to download hwmonitor, like its cousin cpu-z.
=> hwmonitor: use https to download

bucket/localsend.json
An open source cross-platform alternative to AirDrop similar to Sharik.
Settings are stored under `$env:APPDATA\org.localsend\localsend_app\shared_preferences.json`
Closes #10368
=> localsend: Add version 1.6.2

bucket/ditto.json
Sourceforge downloads are slow and the project development moved to github. Even the sourceforge homepage links to github releases as the download links.
=> ditto: use github releases

bucket/kdeconnect.json
- Update to version 21.12.3-903
- `autoupdate.hash` not removed, even invalid now
Closes #XXXX
=> kdeconnect: Fix checkver

bucket/win10_brightnessslider.json
This is a simple GUI utility. I've been running this package for a bit in my personal bucket and it works https://github.com/scowalt/scoop-apps/blob/main/bucket/win10_brightnessslider.json
=> Win10_BrightnessSlider: add version 1.7.15

bucket/okular.json
- Fixed Okular's `checkver.regex` (wasn't working).
- Ran `checkver.ps1 -app "okular.json" -update`.
- Small adjustment to `autoupdate`'s `regex`.
=> okular: Fix `regex` and update to version 22.12.1

bucket/android-sdk.json
commit for fixing an installation failure bug of next package: Extras/android-sdk
Closes #10335
=> fix emulator.exe shim dir of android-sdk.json

bucket/rabbitmq.json
has been since July 2020 [1].
1. https://github.com/rabbitmq/rabbitmq-server/blob/main/LICENSE
=> RabbitMQ is licensed under the MPL2

bucket/activate-linux.json
The "Activate Windows" watermark ported to Linux, backported to Windows.
Closes https://github.com/ScoopInstaller/Extras/issues/10389
=> activate-linux: Add version 1.1.0

bucket/musikcube.json
Closes #10501
Relates to #10501
I believe everything is good.
used `Get-Filehash -path "E:\musikcube_win64_0.99.5.zip" -algorithm SHA256 | fl` and `Get-Filehash -path "E:\musikcube_win32_0.99.5.zip" -algorithm SHA256 | fl` to get hash and fixed 32 bit download url to new one.
=> musikcube: Update to version 0.99.5

bucket/dosbox-x.json
=> dosbox-x: Update to version 2022.12.26, fix autoupdate, add `arm64` arch

bucket/ventoy.json
https://www.ventoy.net/en/doc_start.html
> `Ventoy2Disk.exe` is a x86_32 application and supports both 32-bit and 64-bit Windows PC with intel/amd processor.
> Since 1.0.58, Ventoy also provides `Ventoy2Disk_X64.exe/Ventoy2Disk_ARM.exe/Ventoy2Disk_ARM64.exe` you can use them if needed.
> These exe files are in `altexe` directory of the installation package.
> You must copy them to the upper directory to use them. (The same location with `Ventoy2Disk.exe`)
Closes #10452
=> ventoy: Copy altexes to root folder, Fix bin and shortcut, Update hash url

bucket/manifold-viewer.json, bucket/manifold.json
Fixes error:
Can't shim 'bin64\manifold.exe': File doesn't exist.
=> manifold|-viewer: no more bin64 subdirectory

bucket/nicotine-plus.json
The current homepage for Nicotine+ is https://nicotine-plus.org.
=> nicotine-plus: Update homepage

bucket/prusaslicer.json
Correct the extract_dir value with "PrusaSlicer-2.6.0-alpha3+win64-202302031521_signed" with a "_signed" suffix.
Without this suffix there is the following problem:
````
Installing 'prusaslicer' (2.6.0-alpha3) [64bit] from extras bucket
Loading PrusaSlicer-2.6.0-alpha3+win64-202302031521_signed.zip from cache.
Checking hash of PrusaSlicer-2.6.0-alpha3+win64-202302031521_signed.zip ... ok.
Extracting PrusaSlicer-2.6.0-alpha3+win64-202302031521_signed.zip ... Could not find 'PrusaSlicer-2.6.0-alpha3+win64-202302031521'! (error 16)
Au caractère D:\Applications\Scoop\apps\scoop\current\lib\core.ps1:638 : 9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : …
```
=> Correct extract_dir value for prusaslicer 2.6.0-alpha3 win64 version

bucket/sophiapp.json
Reason: This file is already included inside the zip file, and only exists to help the **SophiApp.exe** file. There is no need to persist it.
=> sophiapp: Remove "SophiApp.exe.config" from `persist`

bucket/glazewm.json
A tiling window manager for Windows inspired by i3 and Polybar.
Closes #10523
Closes https://github.com/lars-berger/GlazeWM/issues/141
=> glazewm: Add version 1.11.1

bucket/zoom.json
Close #10427
By emulating the way the official installer unpacks the runtime library, it makes Zoom ready to run out of the box without the need to install the runtime library.
=> zoom: Fix missing DLLs

bucket/obs-studio.json
Closes #10441
OBS's functionality can be extended using plugins located in `$dir\obs-plugins`. Since the folder is not persisted, users have to manually copy their custom plugins to the new location on each update.
The problem is this folder also contains files that do need to be updated and merely persisting the folder effectively keeps these files outdated.
A possible solution is persisting `obs-plugins` and implicitly forcing Scoop to place new files in `obs-plugins.original` whose contents are then copied back to `obs-plugins`, overwriting older versions.
=> obs-studio: Persist and preserve plugins

bucket/qq.json
=> qq: Add version 9.7.3.28946

bucket/ventoy.json
https://github.com/ventoy/Ventoy/releases/tag/v1.0.89
> 2. Fix the issue that Ventoy2Disk_X64.exe can not run under altexe directory.
> 3. Fix the issue that VentoyPlugson_X64.exe exit silently.
Closes #10682
=> ventoy: use altexes directly from directory

bucket/discord.json
The URL in the manifest uses the domain `discordapp.com` which redirects to `discord.com`, probably an old domain.
=> discord@1.0.9010-15: update homepage url

bucket/qbittorrent-enhanced.json, bucket/qbittorrent.json
App uninstaller has been moved back to app root folder in latest version.
- Closes #10535
- Closes #10665
- Closes #10667
=> qbittorrent(-enhanced): Fix installation scripts

bucket/vscode.json
Every time I reinstall, I want to use reg to add VSCode to the right-click menu. However, the terminal always breaks at inconvenient places, making this operation particularly cumbersome. So I hope to add appropriate line breaks to fix this problem.
Closes #10710
=> vscode: Add line break for note

bucket/mambaforge.json, bucket/miniconda3.json
Closes #10522
note that this version drops support with 32bit. same with anaconda. I have created a corresponding PR in versions bucket to reflect changes.
Closes #10498 
Closes #10420
Closes #10572 
the newest conda installer requires the installation directory to be empty. so I temporarily moves the installer to the upper directory (same with "current" link) to solve the issue
=> conda-series: fix installation error, update to the latest version

bucket/raspberry-pi-imager.json
In #9680 the executable name was changed from a `-` separator to a `_`. It looks like this was just a typo in the release process of that specific version. Now we are back to `-`.
=> raspberry-pi-imager@1.7.4: Revert file name change

bucket/anaconda3.json, bucket/mambaforge.json, bucket/miniconda3.json
=> conda-series: add pre_install check; update installer

bucket/anaconda3.json
=> anaconda3: Fix setup.exe not found error

bucket/kicad.json, deprecated/kicad-lite.json
KiCad version 7.0.0 onwards will not support 32bit architecture. They are no longer releasing builds targeting i686. This breaks the autoupdate and checkver fields of the KiCad manifest.
The current [KiCad ](https://www.kicad.org/download/)manifest uses a regex based checkver on the kicad.org downloads page. This seems to have broken for version 7.0.0, which was just released. The download URL also uses the European mirror from CERN which can be quite slow.
I updated the KiCad manifest to take advantage of the Github app release feature built into Scoop for version checking and auto-updating.
KiCad releases are published on the GitHub source code mirror repository https://github.com/KiCad/kicad-source-mirror/
This will allow checkver to use the "github" key.
I also made the new cli …
=> Kicad@7.0.1: Update manifest to use github release (Closes #10573)

bucket/vt-uploader.json
=> vt-uploader: Fix `url`, `hash`, and remove `pre_install`.

bucket/azurestorageexplorer.json
Azure storage explorer from 1.30.0 onwards will only use the new naming convention. The current storage explorer manifest uses the old file name scheme for url download and autoupdate. This will break in the upcoming major releases.
I have updated the storage explorer manifest to use the new naming convention.
Closes #10747
=> azurestorageexplorer@1.28.1 use new naming conventions

bucket/streamlink.json
Fixes streamlink that was stuck on 5.1.2-1 due to streamlink changing from `py310` naming to `py311` naming after an update to python version.
My first ever PR in GitHub, but it should be fine.
=> streamlink: Update to version 5.3.1-1 and fix auto-update

bucket/sweethome3d.json
Closes #10937 #10547
Problem solved by not unzipping the folder SweetHome3D-macosx.app.
=> sweethome3d: fix decompress error

bucket/powertoys.json
Power Toys 0.69 now supports a User Only installation, which Scoop should use by default. This does not require admin privileges to install and should avoid a UAC popup when installing by Scoop.
This requires updating the hash check regex and the downloaded filename.
I will work on a PR for this, updating the powertoys.json manifest.
Relates to #10912
=> Update Powertoys 0.69.0 to use User Installer

bucket/ios-webkit-debug-proxy.json
=> ios-webkit-debug-proxy: Update to version 1.9.0 and fix autoupdate

bucket/autohotkey.json
Closes #10270
It looks like https://www.autohotkey.com is using Cloudflare as the CDN provider, which may cause the download to fail, so we go to Github Release to download the file and get the hash from the original URL
=> autohotkey: Download from Github Release

bucket/etcher.json
This tool usually goes by the name "balena etcher"/"balenaEtcher", but balena was not in the name or description, meaning that it wouldnt be found if you searched for "balena etcher".
No issue.
=> etcher: Update description

bucket/playnite.json
It's used in plugin: "Extra Metadata Loader"
=> Playnite: add "ExtraMetadata" and "Themes" to persist folders

bucket/freeplane.json
there was a minor update from `1.10.6` to `1.10.6u1`
=> Freeplane: Update to version 1.10.6u1 & Fix checkver

bucket/clash-mini.json
clash-mini: fix `shortcuts`
```
Creating shortcut for Clash.Mini (Clash.Mini.exe) failed: Couldn't find \scoop\apps\clash-mini\current\Clash.Mini.exe
```
=> clash-mini: fix `shortcuts`

bucket/maple.json
The upstream has used new package format ```.msixbundle``` instead of ```.appxbundle```. Using the original manifest will cause error like ```Add-AppxPackage: Cannot find path 'path\to\scoop\apps\maple\0.8.1.0\maple.appxbundle' because it does not exist.```.
This PR changes all strings ```.appxbundle``` to ```.msixbundle``` and this app manifest can be normally installed and uninstalled.
Closes #10606
=> maple@0.8.1.0: fix path cannot be found error

bucket/mp3tag.json
Replace the contents of mp3tag.json with the corrected version, which I found here, https://raw.githubusercontent.com/anderlli0053/DEV-tools/master/added_to_official_repository/mp3tag_fixed.json As described in https://github.com/ScoopInstaller/Extras/issues/10166 mp3tag does not work correctly without this change. Thanks @anderlli0053 for including the fix in your repo.
Closes #10166 on the Extras repo.
=> Fix mp3tag json, issue 10166

bucket/textadept.json
Fixes issue with renamed folder within provided zip
Closes #11023
=> textadept: 11.4 fix extract_dir name ".win" vs ".win32"

bucket/cryptomator.json
Cryptomator doesn't work without WinFsp. It runs but unlocking vaults crashes the app. The official website's download includes it as a third-party driver. I'd even lean towards using the `depends` instead of `suggest` prop. 
To be discussed.
=> cryptomator: Add WinFsp as a suggestion/requirement

bucket/clash.mini.json
Rename from `extras/clash-mini`
Fix shortcuts
Closes #XXXX
Relates to #11011
=> clash.mini(clash-mini): Add version 0.2.2 

bucket/sikulix.json, bucket/x64dbg.json
This PR adds support for installing [SikuliX](https://sikulix.github.io/), a really cool UI-based robotic process automation tool. SikuliX makes it really easy to automate just about anything on a computer. My thought is that it would get more usage if it was easier to install. As of today, all you need to do is download a JAR file and run it with Java, but who has time for that? I have wanted to do scoop install sikulix for years. Hopefully my dream will come true soon...
=> SikuliX: Add version 2.0.5

bucket/kotlin-interactive-shell.json
Added kotlin-interactive-shell.json to the bucket
=> kotlin-interactive-shell: Add version 0.5.2

bucket/hterm.json
Adding hterm in its current version 0.8.9 to the bucket
=> hterm: Add version 0.8.9

bucket/xc.json
- Add arm64 version.
- Update homepage.
=> xc@0.3.0: Add arm64 architecture

bucket/fastcopy.json
- Update to version 5.0.2
- Update (un)install scripts
1. Concise
2. Remove `tskill explorer`-like as it may interrupt what the user doing
3. Use (un)install functions of the program itself
`checkver` temporarily invalidated, probably accessed the cache.
Closes #11069
=> fastcopy: Update manifest

bucket/ausweisapp2.json
Relates to https://repology.org/repository/scoop/problems
Homepage link https://www.ausweisapp.bund.de/en/ausweisapp2-home/ is [dead](https://repology.org/link/https://www.ausweisapp.bund.de/en/ausweisapp2-home/) (Connect timeout (60 seconds)) for more than a month and should be replaced by alive link (see other packages for hints, or link to [archive.org](https://archive.org/) as a last resort).
=> ausweisapp2: Update homepage

bucket/akelpad.json
Relates to https://repology.org/repository/scoop/problems
Project | Package name | Maintainer | Problem
-- | -- | -- | --
akelpad | akelpad | - | Download link https://downloads.sourceforge.net/project/akelpad/files/AkelPad%204/4.9.8/AkelPad-4.9.8-bin-eng.zip is dead (HTTP 404) 				for more than a month and should be replaced by alive link (see other packages for hints).
akelpad | akelpad | - | Download link https://downloads.sourceforge.net/project/akelpad/files/AkelPad%204/4.9.8/x64/AkelPad-4.9.8-x64-bin-eng.zip is dead (HTTP 404) 				for more than a month and should be replaced by alive link (see other packages for hints).
akelpad | akelpad | - | Download link http://akelpad.sourceforge.net/files/tools/AkelUpdater.zip is a permanent redirect to its HTTPS counterpart …
=> akelpad: Fix download url

bucket/ao.json
Relates to https://repology.org/repository/scoop/problems
Homepage link https://klaussinani.tech/ao/ is [dead](https://repology.org/link/https://klaussinani.tech/ao/) (DNS error: domain name not found) for more than a month and should be replaced by alive link (see other packages for hints, or link to [archive.org](https://archive.org/) as a last resort).
=> ao: Fix homepage and update checkver

bucket/apache-directory-studio.json
Relate to https://repology.org/repository/scoop/problems
1. Homepage link http://directory.apache.org/studio/ is a permanent redirect to its HTTPS counterpart https://directory.apache.org/studio/ and should be updated. 
2. https://www.apache.org/dist redirect to https://downloads.apache.org
=> apache-directory-studio: Update urls

bucket/anyburn.json
Although the version number hasn't changed, the available file has been updated and has a new hash. Manually fixing what checkver missed...
=> AnyBurn@5.6: Fix md5 hash

bucket/b1.json
As the upstream SSL certificate has expired for more than 1 month, switch to http to ensure proper update and download of the software.
=> b1: Downgrade to http

bucket/p4v.json
Apparently this installer changed upstream:
```
Checking hash of p4vinst64.msi ... ERROR Hash check failed!
App:         extras/p4v
URL:         https://cdist2.perforce.com/perforce/r23.1/bin.ntx64/p4vinst64.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    f4cd6cbd5ee622fc543222ed19dbdd82520e9ca8d84160a3753660fd2b3ceea1
Actual:      77dc21705c1e6817eed02b6e44243f97bdfc6386c41fdb02f5af9c8c3bc9fc6c
```
=> p4v@2023.1-2431464: Fix hash

bucket/slack.json
```
slack: couldn't match '<h2>Slack ([\d.]+)' in https://slack.com/intl/en-cn/release-notes/windows
```
=> slack: Fix checkver

bucket/yumi-exfat.json
yumi-exfat: couldn't match 'YUMI-exFAT-([\d.]+)\.exe' in https://www.pendrivelinux.com/yumi-multiboot-usb-creator/
=> yumi-exfat: Update to version 1.0.1.6a and fix checkver

bucket/ubports-installer.json
ubports-installer: couldn't match 'ubports-installer_([\w.-]+)_win_x64\.exe' in https://github.com/ubports/ubports-installer/releases
=> ubports-installer: Update to version 0.9.10-beta and fix autoupdate

bucket/uniextract2.json
uniextract2: couldn't match 'download/v([\w.-]+)/(?<filename>\w+\.zip)' in https://github.com/Bioruebe/UniExtract2/releases
=> uniextract2: Fix checkver

bucket/islc.json
islc: couldn't match '/content/intelligent-standby-list-cleaner-v(?<link>\d+)-released(?:.|\n)+Intelligent standby list cleaner [Vv](?<version>[\d.]+) Released' in https://www.wagnardsoft.com/ISLCw
=> islc: Fix checkver

bucket/f3d.json
f3d: 2.0.0 (scoop version is 1.3.1) autoupdate available
Autoupdating f3d
Downloading f3d-2.0.0-win64.zip to compute hashes!
VERBOSE: GET with 0-byte payload
VERBOSE: received 6072-byte response of content type application/json
VERBOSE: Content encoding: utf-8
URL https://github.com/f3d-app/f3d/releases/download/v2.0.0/f3d-2.0.0-win64.zip is not valid
ERROR Could not update f3d, hash for f3d-2.0.0-win64.zip failed!
=> f3d: Update to version 2.0.0 and fix autoupdate

bucket/coppeliasim.json
coppeliasim: couldn't match 'CoppeliaSim_Edu_V(\d+)_(\d+)_(\d+)?(_rev[\d]+)?_?Win\.zip' in https://www.coppeliarobotics.com/downloads
=> coppeliasim: Fix checkver

bucket/tlaplus-toolbox.json
tlaplus-toolbox: couldn't match 'TLAToolbox-([\d.]+)-win32\.win32\.x86_64\.zip' in https://api.github.com/repos/tlaplus/tlaplus/releases/latest
=> tlaplus-toolbox: Update to version 1.8.0 and fix checkver

bucket/status.json
status: 0.11.0-621f0c (scoop version is 0.10.0-9ae594) autoupdate available
Autoupdating status
Searching hash for StatusIm-Desktop-v0.11.0-621f0c.7z in https://github.com/status-im/status-desktop/releases/download/0.11.0/StatusIm-Desktop-v0.11.0-621f0c.sha256
Could not find hash in https://github.com/status-im/status-desktop/releases/download/0.11.0/StatusIm-Desktop-v0.11.0-621f0c.sha256
Downloading StatusIm-Desktop-v0.11.0-621f0c.7z to compute hashes!
VERBOSE: GET with 0-byte payload
VERBOSE: received 6544-byte response of content type application/json
VERBOSE: Content encoding: utf-8
URL https://github.com/status-im/status-desktop/releases/download/0.11.0/StatusIm-Desktop-v0.11.0-621f0c.7z  is not valid
ERROR Could not update …
=> status: Update to version 0.11.0-621f0c and fix autoupdate

bucket/rufus.json
The latest version changes the main binary to x64, so I added the x86 and arm64 binaries: https://github.com/pbatard/rufus/releases/tag/v4.0
Also dropped using the portable version that only exists for the main binary as the regular version functions identically when a config file is present as mentioned here: https://github.com/pbatard/rufus/wiki/FAQ#user-content-What_is_the_difference_between_the_portable_and_the_regular_version
>...the ONLY difference the "portable" version of Rufus has with the "regular" one, which is that the "portable" version will create a rufus.ini by default (so that you don't have to do it yourself, if you want to use Rufus in portable mode), whereas the regular version doesn't.
`pre_install` already creates the config file, so it should function the same.
=> rufus: Add arm64 architecture

bucket/kdiff3.json
KDE doesn't release with fixed filenames, thus the checkver regex needs to be updated to match also the latest file name.
=> kdiff3: Update to version 1.10.1

bucket/snappy-driver-installer-origin.json
=> snappy-driver-installer-origin: Remove `extract_dir`

bucket/obs-studio.json
obs-studio: couldn't match 'OBS-Studio-([\d.]+)-Full-x64\.zip' in https://obsproject.com/download
=> obs-studio: Update to version 29.1 and fix autoupdate

bucket/coretemp.json
the plugins folder should be persistent.
=> coretemp: plugins folder should be persistent

bucket/kdenlive.json
kdenlive: couldn't match 'kdenlive-([\d.\-]+)_standalone\.exe' in https://kdenlive.org/en/download/
=> kdenlive: Update to version 23.04.0a and fix checkver

bucket/rider.json
Adds support the ARM64 version of Rider for Windows.
=> rider: Add arm64 support and Switch to zip

bucket/picocrypt.json
App was stuck on 1.29 version
Update to 1.32
Fix autoupdate
=> picocrypt@1.32: fix autoupdate

bucket/obs-studio.json
- obs-studio: couldn't match `OBS-Studio-([\d.]+)-Full.zip` in [obsproject.com/download](https://obsproject.com/download)
changed it to `OBS-Studio-([\d.]+)(-Full)?.zip` in case they change the naming scheme back to include `-Full`
- Updated to `29.1.1`
=> obs-studio: Update to version 29.1.1 and fix autoupdate

bucket/powertoys.json
Updates PowerToys to 0.70.0 and adds missing hardlinks instructions for the new utilities.
Disclaimer: I'm the dev lead on PowerToys.
=> powertoys: Update to version 0.70.0 and add hardlinks

bucket/windows-terminal.json
The latest release added an official portable mode
https://github.com/microsoft/terminal/releases/tag/v1.17.11391.0
https://learn.microsoft.com/en-ca/windows/terminal/distributions#windows-terminal-portable
=> windows-terminal: Switch to portable distribution

bucket/filezilla-server.json, bucket/filezilla.json
Readd checkver/autoupdate by switching the sources to Chocolatey. This would remove the need for someone to actively upload the binaries to the Binary repo.
Relates to https://github.com/ScoopInstaller/Binary/issues/20
=> filezilla: Update manifests and change source

bucket/kanata-cmd.json, bucket/kanata-with-cmd.json, bucket/kanata.json
Add kanata version 1.3.0 to Extras. Kananta is a software keyboard remapper written in Rust.
=> kanata: add version 1.3.0

bucket/azurestorageexplorer.json
With 1.30.0, Storage Explorer for Windows is now a 64-bit application. The current storage explorer manifest uses the 32-bit name for url download and autoupdate. This PR updates the url with the new 64-bit installer name for 1.30.0.
I have updated the storage explorer manifest to use the new naming convention.
=> azurestorageexplorer@1.30.0 use 64-bit installer with 1.30.0

bucket/antimicrox.json
Graphical program used to map keyboard buttons and mouse controls to a gamepad.
AntiMicroX is a fork of AntiMicro (https://github.com/AntiMicro/antimicro). The original project is no longer being developed.
I'll leave the decision to the maintainers if this deprecates the existing antimicro manifest.
=> antimicrox: Add version 3.3.4

bucket/teamviewer-qs.json
Checkver regex needed to be updated to match new current version DOM.
Update download url to match with `teamviewer` one and depend on `$majorVersion`.
=> teamviewer-qs: Update to version 15.43.6 and fix checkver & download url

bucket/firefoxpwa.json
PWAsForFirefox needs some registry keys to function correctly. This PR adds those keys in `post_install` and removes them in `post_uninstall`. More details are [here](https://github.com/filips123/PWAsForFirefox/issues/358#issuecomment-1604703606).
Additionally, I've changed the description and added notes to be consistent with other PWAsForFirefox packages.
There is still one remaining issue PWAsForFirefox won't be able to locate 7-Zip installed via Scoop. This will be fixed in the next PWAsForFirefox version. More details are [here](https://github.com/filips123/PWAsForFirefox/issues/358#issuecomment-1605643236).
Closes #11321
=> firefoxpwa@2.6.2: Add required registry keys

bucket/kubelogin.json
`kubelogin` needs a binary called `kubectl-oidc_login`.
c.f. https://github.com/int128/kubelogin#setup
> If you install via GitHub releases, you need to put the kubelogin binary on your path under the name kubectl-oidc_login so that the [kubectl plugin mechanism](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) can find it when you invoke kubectl oidc-login. The other install methods do this for you.
=> kubelogin: add kubectl-oidc_login bin

bucket/jpegview-fork.json
Adds a [fork of JPEGView](https://github.com/sylikc/jpegview) to the bucket.
JPEGView is a lean, fast and highly configurable image viewer/editor with a minimal GUI. 
This fork is the de facto successor to the original project. It adds new features (such as support for new image formats), bug fixes, translations, and more. Additionally, this project is active, with 1.1k stars, 380 commits (roughly just as many as the original), and 11 releases since it started around 3 years ago in November 2020.
The original project had its [last release in 2018-02-24](https://sourceforge.net/projects/jpegview/files/jpegview/), and is widely considered to be abandoned. There has been no communication from the original developer. Note that this original project is also in this bucket at …
=> jpegview-fork: Add version 1.2.45

bucket/ridnacs.json
This PR updates the manifest for RidNacs to the version 3.0 of the application. I did not create an issue beforehand as I didn't find a correct template for it, so please let me know if I should do that.
There hasn't been any updates for this application in many years and they have slightly changed the layout of the download page after releasing 3.0, so I didn't add a checkver.
Also, I am kinda lost in their versioning now, cause they used to do proper semver before, now they're using two numbers for the version, and the application says it's actually 1.0.8053, so in the manifest I just set 3.0.0.
=> RidNacs: update to 3.0.0

bucket/breitbandmessung.json
Desktop app from the German Bundesnetzagentur to validate the internet speeds provided by the ISP.
=> breitbandmessung: Add version 3.3.0

bucket/detect-it-easy.json
Dark mode properly works in the qt6 version
=> detect-it-easy: switch to qt6 version

bucket/inkscape.json
`Can't shim 'bin\inkscape.com': File doesn't exist.`
It had been renamed to `inkscapecom.com`
=> inkscape: fix bin

bucket/aegisubdc.json
Remove AssDraw3 from shortcut list as it no longer exists.
=> aegisubdc: Fix shortcuts

bucket/tracy.json
Tracy is a profiler that I personally use for analyzing video game performance. The client library can already be found on vcpkg so making the graphical tool available on scoop is a big help.
- [✔️ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> Tracy: Add version 0.9.1

bucket/arcadedb.json
This PR adds ArcadeDB, an OSS successor to OrientDB, multimodal high-performance database with HA capabilities.
Closes #11638
Comments on manifest
ArcadeDB is written in Java and comes with a structure that's similar to a lot of Java projects.
It contains two scripts `console.bat` and `server.bat` that are unfortunately very generic names, that's why I decided to come up with two shims with `arcadedb-` prefix. Also set `ARCADEDB_HOME` environment variable is a huge convenience required by launch scripts and position of following folders.
Folders `config`, `database` and `log` are persisted so they don't disapper between updates.
=> arcadedb: Add version 23.6.1

bucket/crunchy-cli.json
With the [v3 release](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0) of [crunchy-cli](https://github.com/crunchy-labs/crunchy-cli), the naming scheme of the release binary got changed, as well as the license, description and required dependencies. This PR adjusts the crunchy-cli manifest to those changes.
=> crunchy-cli: Update to version 3.0.0

bucket/archi.json
It seemed like the zip file could be downloaded with just the `major.minor` version but the `.SUMSSHA1` file can't, and the hash is was wrong anyway.
=> archi: fix URL and hash

bucket/firefoxpwa.json
The PWAsForFirefox (firefoxpwa) project now has a new website. This PR updates the homepage URL in the Scoop package.
Because it's quite a simple change, I haven't created a new issue about this. I can create it if this is really needed.
=> firefoxpwa@2.7.3: Update the homepage

bucket/jetbrains-toolbox.json
JetBrains-toolbox v2.0.x changed the way how the install path is used.
- Before apps are installed to `$current\apps`
- Through migration, the apps are migrated to `$current`
- Due to the app honoring the setting of `installation` path
So change the setting to `$current\apps` is the simple solution on code perspective. But a few manual setup is needed:
- Clear the migrated apps directories from `$current`
- Remove that particular version and reinstall is easier.
- Back-up then clear persisted `apps` directory, then reinstall all tools.
Relates to #11740
=> Fix #11740 - make persist work with v2.0.x migrated install paths

bucket/netradio.json
Adds NetRadio.xml settings persistence.
=> Added NetRadio.xml (settings and saved stations) persistence.

bucket/hwinfo.json
Added HWiNFO64_KEY.txt to the persist in HWiNFO so user's license key is saved between updates
Closes #XXXX
=> Added HWiNFO key persistence

bucket/ipfilter-updater.json
Fixes `Could not find 'IPFilter'! (error 16)` for v3.0.3-beta.
```
Installing 'ipfilter-updater' (3.0.3-beta) [64bit] from extras bucket
Loading IPFilter.msi from cache
Checking hash of IPFilter.msi ... ok.
Extracting IPFilter.msi ... Exception: D:\Scoop\apps\scoop\current\lib\core.ps1:638
Line |
638 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Could not find 'IPFilter'! (error 16)
```
=> ipfilter-updater.json: Fix `extract_dir`

bucket/oranda.json
Adding `oranda`, a developer tool/static site generator to build landing pages for your projects fast.
Closes #11779
=> oranda: Add version 0.3.1

bucket/roundedtb.json
Repo URL has moved once again to https://github.com/RoundedTB/RoundedTB
=> roundedtb: Update `url`

bucket/zeal.json
Zeal v0.7.0 has been released. It has different file name format for portable builds, and there will be no 32-bit builds.
P.S. I am maintainer of Zeal. 
~Closes #XXXX~ I can create an issue, but feels like an overkill.
=> zeal: Update to version 0.7.0

bucket/snappy-driver-installer-origin.json
Config file renamed to sdio.cfg as of v1.12.14.755 - https://www.glenn.delahoy.com/downloads/sdio/changelog.txt
=> snappy-driver-installer-origin@1.12.16.757: Rename config file

bucket/vscode.json
Removes the remaining 32 bit architecture sections from the manifest.
Supersedes #12154
Closes #12147
=> #12147 update vscode.json to 1.84.0, remove 32 bit architectures

bucket/mcomix.json
This merge request updates MComix to the newest version. The new version's ZIP file no longer contains a MComix-x.x.x subfolder, so the manifest is slightly simplified.
=> mcomix: Update to version 3.0.0, Remove `extract_dir`

bucket/calibre-normal.json
=> calibre-normal@7.0.0:  Path error, unable to install

bucket/bruno.json
This PR adds the bruno manifest.
Closes #11969
=> bruno: add version 1.2.0

bucket/emule-community.json
=> emule-community@0.70a: fix extract_dir not set to the current version

bucket/taiga.json
_also made the manifest match `versions` more._
The reason for this is because inside the `data` dir, `db\anime-relations.txt` (https://github.com/erengy/anime-relations) and `theme` can receive updates relatively often, and `theme` is not very user customizable.
Relates to [#1353](https://github.com/ScoopInstaller/Versions/pull/1353)
=> taiga: Make `persist` explicit

bucket/monero.json
Good to have an in-path persist option, as opposed to making scoop users have to choose a dir outside of the install dir, which makes their installs less portable
`settings.ini` and `monero-wallet-gui.log` are stored here regardless of where you store anything else
=> monero: Add `monero-storage` to `persist`

bucket/quiterss.json
Old link went to bad gateway.
I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> Update quiterss.json homepage link

bucket/twinkle-tray.json
- Update `pre_install` scripts to adapt for new file path in package installer
- Move 64bit exclusive content to `architecture` field
=> twinkle-tray: Update pre_install scripts

bucket/bulk-crap-uninstaller.json
Changed the download url from osdn to github due to the osdn website not functioning. 
Changed the hash extract url from osdn to sourceforge to make updating the package easier for the **github-actions** bot.
=> Update bulk-crap-uninstaller to version 5.7

bucket/zaproxy.json
ZAP is no longer part of OWASP: https://www.zaproxy.org/blog/2023-08-01-zap-is-joining-the-software-security-project/
Closes #12028
=> zaproxy: Update shortcut

bucket/fluidsynth.json
Add some notes on how to use DLLs.
Closes #12055
```powershell
> scoop install ./fluidsynth.json
Installing 'fluidsynth' (2.3.4) [64bit]
Loading fluidsynth-2.3.4-win10-x64.zip from cache.
Checking hash of fluidsynth-2.3.4-win10-x64.zip ... ok.
Extracting fluidsynth-2.3.4-win10-x64.zip ... done.
Linking ~\scoop\apps\fluidsynth\current => ~\scoop\apps\fluidsynth\2.3.4
Creating shim for 'fluidsynth'.
'fluidsynth' (2.3.4) was installed successfully!
Notes
-----
This manifest contains the barebones FluidSynth installation.
For appropriate programming DLLs, add `~/scoop/apps/fluidsynth/current/bin` to PATH.
For example, executing `$env:Path += ";$(Resolve-Path '~/scoop/apps/fluidsynth/current/bin')"` will add it to PATH for the
current shell.
```
Relates to #11280
=> fluidsynth@2.3.4: Add notes about DLLs

bucket/imageglass.json
https://imageglass.org/news/introducing-the-new-imageglass-version-9-88
Breaking changes
- User config files are now in the JSON format: igconfig.json. ImageGlass 9 cannot import settings from version 8.
- Similarly, theme and language pack also updated to use JSON format. You can download theme packs for version 9 at Download / Theme packs.
- For power users:
- Version 9 uses Per-user setting model which is different from Per-machine setting of version 8:
- The app settings are now saved in the %LocalAppData% folder. Refer to Docs / App configuration for more information.
- The app registry uses HKEY_CURRENT_USER for file type associations and app protocol.
- igtasks.exe has been removed.
- All commands in igcmd.exe have been reworked. Visit Docs / Command line utilities for the updated …
=> imageglass@9.0.7.1125: Fix manifest for v9

bucket/sumatrapdf.json
- Upgrade package from `3.4.6` to `3.5.2` (latest)
- Fix `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` from scoop https client. Error with current `3.4.6` URL:
```bash
Installing 'sumatrapdf' (3.4.6) [64bit] from extras bucket
The SSL connection could not be established, see inner exception.
URL https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip is not valid
```
=>  sumatrapdf@3.5.2: fix current URL SSL error and upgrade package

bucket/musicbee.json, bucket/teraterm.json
OSDN is currently unstable, so [current redistribution is via GitHub](https://github.com/TeraTermProject/osdn-download/releases).
=> teraterm@5.0: Switch to github release

bucket/tuxguitar.json
TuxGuitar was setup only to install on 32bit versions of windows, fixed the json to allow for installation on x86_64 and fixed the malicious homepage URL.
Closes #12082
=> tux-guitar: Fix install on x64, fix malicious homepage url

bucket/hysteria.json
hysteria: Update to version 2.1.1
- fix checkver
- and add arm64
=> hysteria: Update to version 2.1.1

bucket/wabt.json
wabt 1.0.34 renamed wasm-opcodecnt.exe to wasm-stats.exe. Manifest updated to reflect this change.
=> wabt: Fixed shim creation error in 1.0.34

bucket/wireshark.json
The WireShark download URL format has changed.
Replaced the old URL with the new WireShark download URL for scoop autoupdate.
=> Wireshark@4.0.10: Update wireshark.json for scoop autoupdate to 4.2.0 url.

bucket/ngspice.json
current hash value is wrong this pr fixed hash check
=> Ngspice: fixed ngspice-41_64.7z hash

bucket/insomnia.json
Used to be MIT, is Apache 2.0 since https://github.com/Kong/insomnia/commit/11b354ce7c728498b71cb0ce10087177c6d5dca3
=> Insomnia@8.3.0: Update license to Apache 2.0

bucket/firefoxpwa.json
This specifies repository URL for checkver, so that the package can be autoupdated properly.
Because it's quite a simple change, I haven't created a new issue about this.
=> firefoxpwa: Specify repository for checkver

bucket/focus.json
- Add arm64 version.
- Add `hash` section.
=> focus@1.4.1: Add arm64 version

bucket/audacity.json
Since Audacity 3.4.0, new releases use different suffixes for bit, which break compatibility with the current manifest and makes auto-update non-functional. This should fix "404 Not Found" error and update the manifest to the latest program version as well.
=> audacity: Fixes download URLs and updates to version 3.4.1

bucket/electrum.json
Auto-update was broken in the 4.4.3 release cycle, this PR fixes both that and updates the current release to the most recent version.
=> electrum: Update to version 4.4.6 and fix autoupdate

bucket/qownnotes.json
Also removes the "bin" shortcut, as it's not a CLI utility and never runs from $PWD (the .bat script causes it to change directories), making it fairly useless.
Closes #12346
=> qownnotes@23.11.3: Make a shortcut for the exe directly

bucket/emeditor.json
They add a font link containing `v36` in their [download page](https://support.emeditor.com/en/downloads)'s header, which breaks checkver.
Using `<td>v([\\d.]+)` instead of `v([\\d.]+)` should fix it.
=> emeditor: Fix checkver & Update to 23.0.4

bucket/cura.json
Update Cura to version 5.6.0, and update the autoupdate url to the new format introduced with 5.5.0.
=> cura: Update to version 5.6.0 and fix autoupdate

bucket/teraterm.json
Closes #12387
1. Remove trailing comma
and additionally,
2. Replace old OSDN homepage url
3. Replace sha1 hash value
=> teraterm: url and format fixes (#12387)

bucket/mobaxterm.json
Closes #12229
This is a partial fix for persist issue in `mobaxterm` package. The app deletes and re-creates the files to update them on app close. This fix can only handle the occasion when the app got updated.
=> mobaxterm: Work around persist issue

bucket/ueli.json
New home is now https://ueli.app/
=> ueli@8.27.0: update homepage URL

bucket/keepass-plugin-keeautoexec.json
New manifest for the official KeePass plugin KeeAutoExec
---
I've tested locally the install, update, forced update and uninstall.
=> keepass-plugin-keeautoexec: Add version 2.6

bucket/wireshark.json, scripts/wireshark/enable-usbpcap.ps1
Closes #11545
Script is also triggered on `post_install`, in the event that USBPcap has previously been installed in the system.
=> Wireshark: Added notes & script to enable USBPcap.

bucket/avspmod.json
AvsPmod's newer builds use the `AvsPmod_64` folder for the 64-bit builds of their install ZIPs.
This bucket still uses the older `AvsPmod` folder, even for 64-bit, so i fixed it.
=> avspmod: Fixed extract-dir, so it can support both 32-bit and 64-bit ZIPs.

bucket/screentogif.json
- Add arm64 version.
Closes #12435.
=> screentogif@2.40: Add arm64 version

bucket/logseq.json
- Fix autoupdate (looks like version hard-coded by accident in dfd8544).
Relates to #12514.
=> logseq@0.10.3: Fix autoupdate

bucket/apifox.json
- Fix `checkver` to prevent repetitive upgrade-downgrade updates, possibly caused by CDN or whatever (see screen below):
- Update to version 2.4.8.
=> apifox: Update to version 2.4.8, fix checkver

bucket/insomnium.json
This pr adds the fork of Insomnia, Insomnium. After Insomnia begun to require account logins, Insomnium was created which converted the REST client to an offline only software.
Closes #11980
=> insomnium: Add version 0.2.3-a

bucket/beyondcompare.json
According to the [official documentation](https://documentation.help/BeyondCompare4/command_line_reference.html), `BCompare.exe` should be added to `PATH`.
Relates to ScooterSoftware/bcompare-vscode#2
=> beyondcompare@4.4.7.28397: Shim `BCompare.exe`

bucket/clumsy.json
- Fix checkver.
- Remove hash section from autoupdate (since hashes not provided more).
- Update to version 0.3.
Closes #12389.
=> clumsy: Update to version 0.3, fix checkver

bucket/fancontrol.json
Currently, the upstream distributes builds for .NET 4.8, .NET 7.0, and .NET 8.0 LTS. This PR adds another negative lookahead in `checkver.regex` not to match the .NET 7.0 build. Consequently, the `autoupdate` process should select the .NET 8.0 LTS build, avoiding both the .NET 4.8 and .NET 7.0 builds from the release.
=> fancontrol@177: switch to .NET 8.0 LTS build

bucket/scribus.json
Old unstable finally graduated to stable. 1.6 branch is new stable, 1.7 branch new devel will start soon. (Scribus uses an even/odd system for stable/unstable).
=> scribus: update to version 1.6.0 (new stable branch)

bucket/qtemu.json
It seems reporting hash error using the issues tab only make a lot generate [a](https://github.com/ScoopInstaller/Extras/issues/12552) [new](https://github.com/ScoopInstaller/Extras/issues/12571) [random](https://github.com/ScoopInstaller/Extras/issues/12572) [hash](https://github.com/ScoopInstaller/Extras/issues/12552) instead of actually fixing the error...
I fixed hash for the `qtemu@2.1` package here.
=> Fix hashes for qtemu@2.1

bucket/windows-terminal.json
Replace a hard install failure with a warning when the WIndows OS version requirementes are not met.
This allow to install using scoop on a computer not meeting runtime requirements (older or WSL), and use on a compliant one.
=> windows-terminal: warn instead of fail in case of insufficient Windows OS version

bucket/notepadplusplus.json
Closes #12589
When there is a `plugins.original` folder after updating the notepadplusplus package, than the content of that folder is copied over to the persistent `plugins` folder.
=> notepadplusplus: fixes issue where plugins that were shipped with package when updating notepadplusplus are not updated

bucket/determined.json
This PR adds the Determined AI CLI tool to Scoop.
It was previously excluded from Extras due to a dependency on Python and Pip.
However, it has since been re-built as a standalone binary.
=> Determined AI CLI

bucket/shadowexplorer.json
ShadowExplorer allows you to browse the Shadow Copies created by the Windows Vista / 7 / 8 / 10 / 11 Volume Shadow Copy Service
Closes #XXXX
=> shadowexplorer: Add version 0.9

bucket/alacritty.json
Alacritty moved from yml config file to toml and the config file is no longer included in the github releases so I had to remove the persistent config
=> alacritty: Update to version 0.13.1

bucket/scribus.json
The regex for checkver was temporarily changed to something inferior that did work in the meantime. This should work better and follows what it used to be before the change to the new stable branch.
=> scribus: small correction checkver regex

bucket/protege.json
This PR adds a manifest file for Protégé.
Closes #12294
=> protege: Add version 5.6.3

bucket/mqtt-cli.json
[mqtt.cli](https://hivemq.github.io/mqtt-cli/) is a full MQTT 5.0 and MQTT 3.1.1 compatible command line interface for MQTT clients which uses the [HiveMQ MQTT Client API](https://github.com/hivemq/hivemq-mqtt-client).
=> mqtt-cli: Add version 4.22.0

bucket/video-compare.json
it is suggested in the README: https://github.com/pixop/video-compare#practical-tips, costs nothing to add it 👍
=> video-compare@20240107: Add send to shortcut

bucket/boilr.json
Added [BoilR](https://github.com/PhilipK/BoilR).
This manifest does not handle the persistence: (BoilR writes its settings to %APPDATA%/BoilR. I didn't know how to remap.)
It also used just uses the skewed version scheme of BoilR (having `v.x.x.x` Tags instead of `vx.x.x`). Since scoop will just work fine with it, I didn't bother writing a complex regex. This is also why the version number currently starts with a dot.
Closes #12171
=> BoilR: Add version 1.9.4

bucket/gcc-aarch64-none-elf.json, bucket/gcc-aarch64-none-linux-gnu.json, bucket/gcc-arm-none-linux-gnueabihf.json
=> gcc-aarch64-none-elf/gcc-aarch64-none-linux-gnu/gcc-arm-none-linux-gnueabihf: Add version 13.2.rel1

bucket/hub-tool.json
This PR adds a manifest for hub-tool, a CLI tool for interacting with the Docker Hub. Does not seems to fit Main bucket criteria since it has lower than 500 stars.
=> hub-tool: Add version 0.4.5

bucket/exifglass.json
[ExifGlass](https://github.com/d2phap/ExifGlass) is an EXIF metadata viewing tool, designed to work seamlessly with ImageGlass 9, but can also be used as a standalone software on your computer.
- persist: none
=> exifglass: Add version 1.3.0.0

bucket/restfox.json
Add [Restfox](https://github.com/flawiddsouza/Restfox) - an offline-first, minimalistic alternative to `postman`/`insomnia`/`hoppscotch`.
Closes #12065.
=> restfox: Add version 0.3.2

bucket/calibre.json
Use the temporally directory from environment variables.
Closes #11367
=> Calibre: Fix path too long problem

bucket/rsgain.json
This PR adds an initial manifest for [rsgain](https://github.com/complexlogic/rsgain), which is currently only available in a few [community buckets](https://scoop.sh/#/apps?q=rsgain&s=0&d=1&o=false).
There are [no existing issues or PRs](https://github.com/search?q=org%3AScoopInstaller%20rsgain&type=code) for rsgain.
=> rsgain: Add version 3.3

bucket/streamlink.json
`streamlink>=6.5.1-1` is now based on py312
----
----
I'm the dev of the Streamlink project and its Windows builds.
All py311 builds were bumped to py312, which broke your autoupdate config here:
- https://github.com/streamlink/windows-builds/blob/6.5.1-1/CHANGELOG.md
- https://github.com/streamlink/windows-builds/releases/tag/6.5.1-1
=> streamlink: Update to version 6.5.1-1, fix autoupdate

bucket/cnping.json
Minimal Graphical IPV4 Ping/HTTP Ping Tool.
https://github.com/cntools/cnping
=> cnping: Add version 1.0.0

bucket/appflowy.json
Appflowy has been updated to v4.3, and not packaged as a zip any more. [change](https://github.com/AppFlowy-IO/AppFlowy/pull/4404#issue-2083001140)
change manifest to use innosetup
Closes #12647
=> appflowy@0.4.2: uprgade  to 0.4.3

bucket/freecad.json
update version form 0.20.2-2 to 0.21.2
adapt manifest to install according to new release artifact structure
- archive name changed
- archive contains subdirectory with additional release infos which is truncated by pre_install script
=> freecad@0.21.2: adapt manifest to new release artifact structure

bucket/space.json
Adds a new manifest for the space CLI, which is yet another disk space usage tool, written in Rust (for fun and learning).
=> space: Add version 0.1.2

bucket/mcomix.json
This pull request updates MComix to version 3.1.0: https://sourceforge.net/p/mcomix/news/2024/01/changelog---mcomix-310/
=> mcomix: Update to version 3.1.0

bucket/vesktop.json
this PR adds the [Vesktop App](https://github.com/Vencord/Vesktop) to this bucket
this json file is basically just mirrored from https://github.com/anderlli0053/DEV-tools/blob/master/bucket/vesktop.json and https://github.com/okibcn/ScoopMaster/blob/master/bucket/vesktop.json 
as I think Vesktop should be in one of the official repos; Extras being the most fitting.
Closes https://github.com/Vencord/Vesktop/issues/82
=> vesktop: Add version 1.5.0

bucket/opera-gx.json
* updated checkver regex to only match versions starting with 3-digits.
* update manifest to latest version
Closes #12628
=> opera-gx: update to v106.0.4998.49

bucket/s3browser.json
S3 Browser is a freeware Windows client for [Amazon S3](http://aws.amazon.com/s3/) and [Amazon CloudFront](http://aws.amazon.com/cloudfront/). It can also be used for other S3-compatible object storage.
Closes #12297
=> S3browser: Add version 11.5.7

bucket/wslinternals.json
Add wsl-perf.exe to wslinternals and updates to version 0.0.14
=> wslinternals: Add wsl-perf.exe and update version

bucket/vidiot.json
vidiot: 0.3.38 (scoop version is 0.3.37) autoupdate available
Autoupdating vidiot
Could not find hash in https://sourceforge.net/projects/vidiot/files
Downloading Vidiot-0.3.38-win32.zip to compute hashes!
=> vidiot: Update to version 0.3.38 and fix autoupdate

bucket/gitkraken.json
On [GitKraken's download page](https://www.gitkraken.com/download), 32 bit binaries are no longer available.
They were however, available previously.
Closes #12708
=> gitkraken: Update to version 9.11.0, drop 32bit support

bucket/komac.json
> Komac has been fully rewritten in [Rust](https://www.rust-lang.org/)! Because of this, Komac v2 is incompatible with Komac v1. If you have Komac v1 installed, please uninstall it before installing Komac v2.
=> komac: Update to version 2.0.1

bucket/syncthingctl.json
Add [syncthingctl](https://github.com/Martchus/syncthingtray#using-the-command-line-interface) - command line utility to control Syncthing.
Closes #11662.
=> syncthingctl: Add version 1.4.12

bucket/delapp.json
I use some external json tools on buckets - they are not as forgiving as scoop's json parser.
=> delapp: extra comma in manifest

bucket/geode-sdk-cli.json
Closes #11955 
Command line application for Geode SDK, the Geometry Dash modding framework.
=> geode-sdk-cli: Add version 2.7.1

bucket/fspy.json
Add version 1.0.3 of `fspy`, an open source still image camera matching tool.
Closes #11814
=> fspy: Add version 1.0.3

bucket/bt.json
New version of bt changed the configuration file name, current `persists` setting no longer works as expected.
Relates to #11925
=> bt@3.7.2: Update persist

bucket/gisto.json
Add [Gisto](https://github.com/Gisto/Gisto) - cross-platform gist snippets management desktop application.
Closes #10293.
Supersedes #10294, closed since the author [accidentally removed branch](https://github.com/ScoopInstaller/Extras/pull/10294#issuecomment-1458752555).
=> Gisto: Add version 1.13.4

bucket/dxwnd.json
The version of dxwnd V2_06_00_build starts with V, but the past and latest versions are v, which invalidates the url obtained by autoupdate. 
This PR fixes this v issue, updates the checkver rules for the latest version v2_06_02f_build, and updates to the latest version v2_06_02f_build.
=> dxwnd: Update to version 2.06.02f and fix autoupdate

bucket/ytmdesktop.json
Since ytmdesktop got a [major update from 1.x to 2.x](https://github.com/ytmdesktop/ytmdesktop/issues/1139) with many changes would like to submit PR for review instead of simply update the version:
- switch to nupkg;
- update to version 2.0.0;
- update license.
=> ytmdesktop: Update to version 2.0.0, switch to nupkg

bucket/hunt-and-peck.json
-  [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
I didn't use "checkver": "github" because the release page doesn't contain "v..." and the default regex doesn't fit.
=> hunt-and-peck: Add version 1.7

bucket/rtss.json
The previous update was not correct. Instead of version 7.3.5, version 7.3.4 was installed.
Also removed more installer files.
=> rtss@7.3.5: Fix url, hash

bucket/benchmark-launcher-cli.json, bucket/blender-benchmark-cli.json
=>  blender-benchmark-cli: Add version 3.1.0

bucket/usbimager.json
Updated the hash value to match the correct one based on the information from the original repository at https://gitlab.com/bztsrc/usbimager/-/blob/binaries/sha256checksums.txt. The corrected hash is now "7C57380C050F186E420AA60A15A0F16B047539160D98BC2B7CAE97882FF992CA"
=> USBImager@1.0.10: Fix hash

bucket/kicad.json
Fixing a typo in the shortcuts that would cause the shim linking to fail.
=> kicad@7.0.11: Fix shortcuts

bucket/hexchat.json
As per [The Final Release](https://hexchat.github.io/news/2.16.2.html) notification from the author:
> This will be the last release I make of HexChat. The project has largely been unmaintained for years now and nobody else stepped up to do that work.
> ...
> I am going to move all data that I can to be hosted on Github, so all documentation, installers, and dependencies will be there until the end of Microsoft.
Thereby
- update to version 2.16.2;
- switch to using artifacts from GitHub releases.
=> hexchat: Update to version 2.16.2, switch to github releases

bucket/thorium.json
Updates the manifest to support the new versioning in the thorium repo. Now looks for SSE3 version in the release to maintain support for older cpus as before, also adds architecture properties.
=> thorium: Update to version 121.0.6167.204, fix autoupdate & checkver

bucket/sfsu.json
- Added arm64 architecture support
- Use direct exe downloads rather than 7z archives
=> sfsu@1.8.6: Add arm64 arch, use direct exe download urls

bucket/prusaslicer.json
prusaslicer: updated to version 2.7.2 and updated filename and hash to match
prusaslicer changed their filename and took out -signed
I have updated this file bucket/prusaslicer.json to fix this
Closes #12889
Relates to #12889
=> prusaslicer: Update to version 2.7.2, fix checkver and autoupdate

bucket/adwcleaner.json
Uses official bins from Malwarebytes instead of the mirror, previously a mirror (which's currently out of date, and causing an error) was used because prior to the Malwarebytes acquisition, the official bin was only acquirable via the toolslib site, which required a js generated query param.
Closes #12908
=> adwcleaner: Fix `autoupdate`

bucket/czkawka-gui.json
Updates czkawka-gui to new version while still using the gtk gui as the slint ui is still experimental
=> czkawka-gui: Update to 7.0.0

bucket/supersonic.json
Added [Supersonic](https://github.com/dweymouth/supersonic), a lightweight cross-platform desktop client for Subsonic and Jellyfin music servers.
Closes #12956
=> Supersonic: Add version 0.9.1

bucket/fancontrol.json
Fancontrol changed assets naming scheme as of V183
FanControl_net_8_0.zip changed to FanControl_$version_net_8_0.zip
=> fancontrol@v183: fix zip name

bucket/gitify.json
gitify now uses dots instead of dash in the exe released bundle
Closes #12980
=> gitify@5.0.0: Fix bundle name

bucket/sleek.json
The download URL of sleek changed slightly. This PR changes the download URL & the update URL.
Closes #12994
=> sleek@2.0.12: Update download URL

bucket/mesonlsp.json
Rename manifest since project rewritten in C++ instead of Swift.
Manifest was already updated accordingly in 2de79bc.
Relates to JCWasmx86/mesonlsp#49.
=> mesonlsp@4.1.3: Rename from swift-mesonlsp to mesonlsp

bucket/ttdl.json
The PR adds a new package - ToDo List (TTDL) manager using plain text todo.txt format. The binary, documentation and an  example configuration file are included in an archive.
My request: https://github.com/ScoopInstaller/Extras/issues/13013
Closes #13013
=> ttdl: Add version 4.2.1

bucket/gitify.json
It seems they  switch back (fix) so previous fix at #12981 needs to be reverted
=> gitify@5.1.0: Fix bundle name

bucket/clashtui.json
The file structure of versions after clashtui v0.2.0 is different from the previous versions, so modification is needed.
=> clashtui: Update to version 0.2.0

bucket/ida-free.json
This pull request updates the hash type in the manifest file for the ida-free package to align with the information provided on the official ida-free website, which is sha-256 now.
=> ida-free: Update manifest

bucket/qefi-entry-manager.json
=> qefi-entry-manager: Add version 0.3.0

bucket/umi-ocr-paddle.json, bucket/umi-ocr.json
Update the format of version tag
=> umi-ocr: Update to version 2.1.1, fix checkver and autoupdate

bucket/kodi.json
Update kodi to v21.0
checkver now uses actual filenames instead of title (which omitted `.0` from `21.0`)
=> kodi: Update to version 21.0

bucket/tts-voice-wizard.json
Updates the suggested runtime package from `extras/windowsdesktop-runtime-lts` (now 8.0) to `versions/windowsdesktop-runtime-6.0`.
=> tts-voice-wizard: update suggested runtime package

bucket/keepassxc.json
Fixes missing runtime error
https://keepassxc.org/docs/#faq-msvc-runtime-missing
=> keepassxc@2.7.7: Add vcredist suggest

bucket/gnucash.json
Fixes wrong GnuCash link of version 5.6 which was replaced.
=> gnucash: Fix version 5.6

bucket/love.json
Installing 'love' (11.5) [64bit] from extras bucket love-11.5-win64.zip (4.3 MB) [================================================================================] 100% Checking hash of love-11.5-win64.zip ... ERROR Hash check failed!
App:         extras/love
URL:         https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    cc71dbc24a9eb65aa988d3f0dc77d090f340e14ed32bbbc9e7bfaf1988cd0455
Actual:      ba6e56be2685e53c817749c4a5007f51137136fe5a3ab64920508babc2e74369
Please try again or create a new issue by using the following link and paste your console output: https://github.com/ScoopInstaller/Extras/issues/new?title=love%4011.5%3a+hash+check+failed
Updated Hash to the correct values
=> love@11.5: Fix hash

bucket/ghidra.json
Add `GHIDRA_INSTALL_DIR` environment variable used by many plugins.
=> ghidra: add GHIDRA_INSTALL_DIR environment variable

bucket/dbeaver.json
Fix download urls for dbeaver, the old domain (download.dbeaver.com) is not available anymore.
- Closes #13127
- Closes #13115
=> dbeaver: fix download url

bucket/jetbrains-toolbox.json
Starting with version 2.3 the installer of the jetbrains-toolbox has a new format in the file system. This requires to first extract the content of the installer (portable executable format) and then again extract the application content from a zip file.
With the proposed fix the broken installer of version 2.3.0.30876 works again.
Closes #13139
=> jetbrains-toolbox@2.3.0.30876: add pre_install to reflect new installer structure of version 2.3

bucket/argyllcms.json
Whether intentional or not by the author of the software, spec2cie.exe is no longer a part of the bin dir, making the installation through Scoop fail.
This simple change to the manifest should fix that.
Closes #13147
=> argyllcms@3.2.0: Remove non-existent bin (spec2cie.exe)

bucket/autohotkey.json
Fixes reported errors during autohotkey updates.
Closes #13075 .
=> autohotkey@2.0.13: Fix pre_uninstall script

bucket/komf.json
Currently komf run behaviour is not consistent with komga, this PR will make it consistent by configuring config folder on installation directory as config directory and persist it like komga (https://github.com/ScoopInstaller/Extras/blob/master/bucket/komga.json#L15)
Closes #XXXX
=> komf: make run behaviour same as komga

bucket/krita.json
Added a "*" to the Remove-Item expression, so it won't error if the file does not exist.
Closes #13220
=> krita@5.2.2: Fix install errors on removing a non-existent file

bucket/pkg-config-lite.json
Adds pkg-config-lite (pkg-config for windows without glib dependency). Version is newer than pkg-config version included in main bucket.
Adding to extras as I didn't feel this met the "a reasonably well-known and widely used developer tool" criteria of the main bucket since this is a "fork" of pkg-config
=> pkg-config-lite: Add version 0.28-1

bucket/redshift-tray.json
...because I will no longer upload releases to GitHub.
Check versions and download from Codeberg, instead of GitHub.
=> redshift-tray: get releases from Codeberg

bucket/theia-ide.json
* Note: checkver returns `1.49.1`, download-url is at `1.49.100` so, used in manifest is `$version00` in hopes that future versions will follow the same pattern.
* Version specific download link for theia (for use in `"autoupdate"`) https://projects.eclipse.org/projects/ecd.theia/downloads -> https://download.eclipse.org/theia / ide / latest / windows
* Dealing with NSIS pkgs: examples at https://github.com/search via: `user:scoopinstaller path:bucket/*.json "\"extract_dir\": \"$P"` https://github.com/ScoopInstaller/Extras/blob/d48d63f0bf/bucket/android-messages.json#L10-L18
* `checkver: github` from https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases
Close: https://github.com/ScoopInstaller/Extras/issues/13272
=> theia-ide: Add version 1.49.100

bucket/pipp.json
Attempt to fix unavailable `pipp` installations download:
- broken update from Excavator log:
> pipp: couldn't match 'Windows Installer \(v([\d.]+)\)' in https://sites.google.com/site/astropipp/downloads
- site and download locations unavailability reported by users: cgarry/ser-player#15, [link](https://www.cloudynights.com/topic/880084-pipp-download-location-seems-unavailable/), [link](https://www.reddit.com/r/AskAstrophotography/comments/14hg05c/the_link_to_download_pipp_isnt_working_anymore/).
Binaries are still available via [Wayback Machine archive](https://web.archive.org/web/20230604160403/https://sites.google.com/site/astropipp/downloads) ([x86](https://web.archive.org/web/20230604160535if_/https://3670d42b-a-62cb3a1a-s-sites.googlegroups.com/site/astropipp/downloads/pipp_install_x …
=> pipp@2.5.9: Fix urls, disable updates

bucket/tidal.json
```
Running pre_install script...Remove-Item:
Line |
2 |  Remove-Item "$dir\lib"
|  ~~~~~~~~~~~~~~~~~~~~~~
| Cannot find path '~\scoop\apps\tidal\2.37.8\lib' because it does not exist.
```
=> tidal: Fix preinstall

bucket/komorebi.json
Add `komorebi-gui.exe` which will be part of `v0.1.26`
=> komorebi: Add komorebi-gui.exe

bucket/go-chromecast.json
go-chromecast is a nice CLI tool written in Golang to manage chromecast eligible devices (e.g. Smart-TVs, STBs, etc.)
=> go-chromecast: Add version 0.3.1

bucket/heynote.json
Add heynote 1.7.0 -  A dedicated scratchpad for developers 
https://github.com/heyman/heynote
Closes #12986 
(copied from the `upscayl` manifest: https://github.com/ScoopInstaller/Extras/blob/master/bucket/upscayl.json)
=> heynote: Add version 1.7.0

bucket/alacritty.json, scripts/alacritty/install-context.reg, scripts/alacritty/uninstall-context.reg
Adds a bundled registry file to optionally add an "Open Alacritty here" context menu entry just as Alacritty's own installer[^1] does.
Closes #12983
[^1]: https://github.com/alacritty/alacritty/blob/master/alacritty/windows/wix/alacritty.wxs#L41-L49
=> alacritty@0.13.2: Add Open with Alacritty context menu

bucket/owncloud.json
Created an app manifest for the ownCloud desktop client. Since the clients are still very similar, I used the manifest of Nextcloud as blueprint.
Closes #13229
=> owncloud: Add version 5.2.1.13040

bucket/umi-ocr-paddle.json
Relates to #13404, [commit/0858b881c40f1977fe57dd3531babc4bbf75827e](https://github.com/ScoopInstaller/Extras/commit/0858b881c40f1977fe57dd3531babc4bbf75827e)
The Hash in `bucket/umi-ocr.json` has been corrected. This PR is intended to fix the Hash in `bucket/umi-ocr-paddle.json`.
=> umi-ocr-paddle@2.1.2: Fix hash

bucket/media-downloader.json
Add [media-downloader](https://github.com/mhogomchungu/media-downloader), a Qt/C++ front end to yt-dlp, youtube-dl, gallery-dl, lux, you-get, svtplay-dl, aria2c, wget and safari books..
Closes https://github.com/ScoopInstaller/Extras/issues/11167
=> media-downloader: Add version 4.7.0

bucket/imageglass.json
imageglass no longer releases package files for arm64
=> imageglass: Update to version 9.1.6.14, remove arm64 version

bucket/wait4x.json
Add Wait4X v2.14.1, Wait4X allows you to wait for a port or a service to enter the requested state, with a customizable timeout and interval time.
Closes #13463
=> wait4x: Add version 2.14.1

bucket/yarr.json
Adding https://github.com/nkanaev/yarr feed reader.
Closes #13055
=> yarr: Add version 2.4

bucket/buildcache.json
This PR updates the buildcache package to point at GitLab. The GitHub link is outdated as the project moved to GitLab.
Also bumps the version to 0.30.1
The current GitLab version has only 12 stars which no longer qualifies to appear in the Extras bucket. However it did qualify before when it was hosted on GitHub. Unsure if we want to move it elsewhere; it is a dev tool.
=> buildcache: Update to version 0.30.1, switch to gitlab releases

bucket/horizon-eda.json
The executable is now in a `bin` subdirectory. I was not able to update to 2.6.0 before. This now works.
This PR also removes the `"bin"` section, as it is a GUI program, which does not really take CLI arguments. At least that I'm aware of.
=> horizon-eda@2.6.0: fix shortcut path, remove bin

bucket/materialgram.json
[materialgram](https://github.com/kukuruzka165/materialgram) is a [Telegram Desktop](https://github.com/telegramdesktop/tdesktop) fork with Material Design and other improvements.
Closes #13331
=> materialgram: Add version 5.1.7.1

bucket/cyberchef.json
PowerShell doesn't like the wildcard in the input path.
=> cyberchef@10.18.9: fix pre_install script

bucket/grafana.json
Add `grafana-cli.exe` to `bin` so Scoop adds it to PATH.
Tested by installing edited manifest file locally.
```pwsh
PS > & $(Try{$psEditor.GetEditorContext().CurrentFile.Path}Catch{$psISE.CurrentFile.FullPath}) -App 'grafana'
grafana: 11.1.0
Installed apps matching 'grafana':
Installing 'grafana' (11.1.0) [64bit] from 'C:\Users\olav.birkeland\OneDrive\IT\Code\PowerShell\CLI\Scoop\Scoop-ManifestAuthoring\grafana.json'
Loading grafana-11.1.0.windows-amd64.zip from cache
Checking hash of grafana-11.1.0.windows-amd64.zip ... ok.
Extracting grafana-11.1.0.windows-amd64.zip ... done.
Linking ~\scoop\apps\grafana\current => ~\scoop\apps\grafana\11.1.0
Creating shim for 'grafana-cli'.
Creating shim for 'grafana-server'.
Persisting conf
Persisting data
'grafana' (11.1.0) was installed …
```
=> grafana@11.1.0: Add `grafana-cli` to `bin`

bucket/mpc-hc-fork.json
Updates the MPC-HC to latest version (v2.3.2)
=> mpc-hc-fork: Update to version 2.3.2.1

bucket/halloy.json
Fixes the error:
DEBUG[1720354523] "Failed to parse manifest file: $filepath (error: $_)" = Failed to parse manifest file: <redacted>\scoop\buckets\extras\bucket\halloy.json (error: Exception calling "Parse" with "1" argument(s): "'0x0D' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 15 | BytePositionInLine: 51.") -> <redacted>\scoop\apps\scoop\current\libexec\scoop-search.ps1:69:13
The script was broken in https://github.com/ScoopInstaller/Extras/commit/451f8728dab7c9d2b34372caf5525570a6c6efac, because I guess the auto-update script doesn't escape newlines in JSON properly.
=> halloy@2024.8: fix installer script

bucket/vesktop.json
Vesktop (portable) can now store configuration in the same folder as executables.
This should make scoop preserve the program data.
Bonus: arm64 architecture detection.
=> vesktop@1.5.3: Add arm64 build, persist Data folder

bucket/hwinfo.json
Relates to #11759
HWiNFO64_KEY.txt is a file, not a folder.
If this file exists but does not have a valid license, hwinfo reports an error.
=> hwinfo: Fix HWiNFO64_KEY.txt persistence

bucket/photodemon.json
=> photodemon@2024.7: Fix extract_dir

bucket/picocrypt.json
Picocrypt recently moved their repository to https://github.com/Picocrypt (as seen in the [readme](https://github.com/HACKERALERT/Picocrypt/blob/main/README.md))
=> picocrypt: Change repo and update to version 1.37

bucket/powertoys.json
I'm a dev lead in PowerToys. Proof in : https://github.com/microsoft/PowerToys/blob/main/COMMUNITY.md#powertoys-core-team
We wrongly released the 0.82.1 tag as "V0.82.1" instead of "v0.82.1". We've just corrected that. Downloads should now contain lowercase "v": https://github.com/microsoft/PowerToys/releases/tag/v0.82.1
This PR reflects that correction.
Relates to #13612
=> powertoys@0.82.1: Fix for the tag change

bucket/vnote.json
Drop 32 bit support because Qt6 only comes with 64 bit in Windows environment. https://doc.qt.io/qt-6.2/windows.html
To install the runtime libraries on the end-user's system, you need to include the appropriate Visual C++ Redistributable Package (VCRedist) executable with your application and ensure that it is executed when the user installs your application.
=> vnote: Update to version 3.18.1

bucket/etcher.json
Update etcher manifest to latest version:
- update autoupdate url to latest naming convention
- remove `architecture` block as latest version is 64-bit only
- remove `installer` fields as latest version is available in zip file format
Closes #13640
=> etcher: Update to version 1.19.21

bucket/ultravnc.json
Change the folder names in the json to match the ones on the zip source.
Closes #13650
=> ultravnc@1.4.3.6: Fix extract_dir

bucket/kasts.json
Add manifest for [Kasts](https://apps.kde.org/kasts/), desktop & mobile podcast application from KDE.
Closes #11379
=> kasts: Add version 24.05-3241

bucket/ocenaudio.json
- Removed 32 bit support
- Download link changed
Closes #13680
=> ocenaudio@3.14: Fix download urls

bucket/kcc.json
KCC wasn't installing for me, turns out it is a portable .exe file and not an InnoSetup installer, so I've updated it to just use it directly. I've also added the shortcut in `autoupdate` as it uses the version in the filename. Tested locally and installs fine.
=> kcc@6.1.0: Remove innosetup, add CLI tools

bucket/inky.json
Zip structure has changed and `extract_dir` isn't needed anymore, so this PR removes it. Also, this adds an Inky shim to allow launching the GUI app from the command line, because that's handy.
Closes #13689
=> inky@0.15.1: Fix extraction configuration, add CLI shim

bucket/eraser.json
Closes #13705
The msi files have a new `PFiles64`/`PFiles` intermediate directory, parent of the `Eraser` one, since v6.2.0.2994 while not up to v6.2.0.2993.
=> eraser@6.2.0.2994: Fix msi ExtractDir

bucket/openai-translator.json
The main exe had been rename to app.exe
=> openai-translator@0.4.32: fix shortcuts

bucket/halloy.json
The folder in the MSI has changed name in this release, I have updated "extract_dir" to the new path
Closes #13733
=> halloy@2024.9: Fix extract_dir

bucket/kdiff3.json
Update the binary name according to KDE changes.
Closes #13303
=> kdiff3: Update to version 1.11.2

bucket/localsend.json
Updates the license to match the latest release (https://github.com/localsend/localsend/issues/1634)
=> localsend@1.15.4: Change MIT to Apache-2.0 license

bucket/zotero.json
Closes #13821
Relates to https://github.com/ScoopInstaller/Versions/pull/1918 https://github.com/ScoopInstaller/Extras/pull/13864
Update zotero6 to zotero7, and move zotero to Versions bucket.
=> zotero: Update to 7.0.2, fix checkver

bucket/armcord.json
Title says it all, fixes armcord versioning plus adds arm64 support.
Closes #13883
=> armcord@3.3.0: Fix autoupdate, add arm64 support

bucket/clion.json, bucket/datagrip.json, bucket/goland.json, bucket/idea-ultimate.json, bucket/idea.json, bucket/phpstorm.json, bucket/pycharm-professional.json, bucket/pycharm.json, bucket/rider.json, bucket/rubymine.json, bucket/webstorm.json
Jetbrains apps are not auto updating well due to `$matchHead` returning only first two or three digits seperated by a dot (e.g. `3.7.1-rc.1` = `3.7.1`, ` 3.7.1.2-rc.1` = `3.7.1` or `3.7-rc.1` = `3.7`)
Currently we have 4 digits versions, for example: [IDEA Ultimate 2024.2.0.2](https://download.jetbrains.com/idea/ideaIU-2024.2.0.2.win.zip) this PR address the issue using `$matchVer`
Closes #13863
=> (chore): matchVer instead of matchHead in jetbrains apps

bucket/tracy.json
The way that tracy organized its release artifacts has changed with v0.11.0
Relates to #10942
=> tracy@0.11.1: Tracy artifacts changed slightly 

bucket/oss-browser.json
The oss-browser repository has changed the default branch to `develop`. Checkver does not detect the new version with the current manifest file.
=> oss-browser: Update to version 1.19.0, fix checkver & autoupdate

bucket/discord-rpc-extension.json
- 32-bit support has been dropped
- Add icon to shortcut from https://github.com/lolamtisch/Discord-RPC-Extension/blob/master/WindowInstaller/logo.ico
=> discord-rpc-extension: Update to version 0.3.0

bucket/s3browser.json
It seems that since recent versions the GUI executable file is renamed from `s3browser-win32.exe` to `s3browser-ui.exe`
=> S3Browser@11.9.5: Fix shortcut

bucket/enpass.json
The regex of enpass `checkver` does not match the latest web page
Closes #14004
=> enpass: Fix regex and update version 6.11.3.1771

bucket/backrest.json
Adds a manifest for the Backrest software. Tested with a local and global installation and uninstallation. Also checked the manifest updates automatically.
Closes #13978
=> Backrest: Add version 1.5.0

bucket/gitextensions.json
- Added x64 `architecture` values
- Updated `checkver.regex` to match new naming scheme
- Added x64 `architecture` to `autoupdate` section with new URL pattern
Closes #14021
=> gitextensions@5.0.0.17897: Update to x64 and new naming

bucket/tsukimi.json
From v0.12.2 persist directories are no longer needed.
=> tsukimi@0.12.2: Fix persist

bucket/koodo-reader.json
The original repository has changed from https://github.com/troyeguo/koodo-reader to https://github.com/koodo-reader/koodo-reader. Although Github will handle the redirect for now, it's still necessary to match the latest change. Also the app has a new dedicated website at https://www.koodoreader.com. The old website could be sunset at any time.
=> koodo-reader@1.7.0: Update urls

bucket/foobar2000.json
Closes #11871 #13123
Additional info for reviewers:
- `uninstall.exe` was removed from package installer
- scripts for renaming `playlists` folder was for previous versions and no longer compatible with version 2.0 and above
=> foobar2000: Update installer script for version 2.0 and above

bucket/shutup10.json
ShutUp10 doesn't seem to use a .ini file anymore, but a .cfg (XML) file. This changes the persist instruction accordingly.
Closes #XXXX
=> shutup10: Change .ini to .cfg

bucket/onecommander.json
This allows us to run a few commands from the [cli](https://onecommander.com/help/3._Full_reference_guide/Starting_from_Command_line.html)
=> onecommander@3.89.1.0: Add bin section

bucket/esearch.json
The author of esearch change the executable name from "eSearch" to "e-search" in commit https://github.com/xushengfeng/eSearch/commit/7fdea38080970b5e1eb9cf93521be8c9fb570b34.
Therefore, change it in esearch.json is necessary.
Before this patch, command `scoop install esearch` will cause an error
$bin = (Get-Command $target).Source
~~~~~~~~~~~~~~~~~~~
CategoryInfo          : ObjectNotFound: (eSearch.exe:String) [Get-Command], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
After this patch, command `scoop install esearch` will be ok, and esearch will be installed successfully.
=> esearch: change executable name of esearch

bucket/goofcord.json
Add [GoofCord](https://github.com/Milkshiift/GoofCord), a standalone Discord client
=> GoofCord: Add version 1.7.1

bucket/pari-gp.json, bucket/pari.json
Added PARI/GP version 2.17.0 to Extras bucket
=> pari-gp: Add version 2.17.0

bucket/zebar.json
This adds an auto-updating recipe for [zebar](https://github.com/glzr-io/zebar)
Closes #14041
=> zebar: Add version 2.2.2

bucket/komorebi.json
Ensures that the license accurately reflects the [new license used for v0.1.29](https://github.com/LGUG2Z/komorebi/blob/v0.1.29/LICENSE.md).
=> komorebi@0.1.29: Update license

bucket/mpv.json
Adds the urls for aarch64 mpv builds and autoupdate
=> mpv: Add arm64 builds

bucket/wecom.json
```
Installing 'wecom' (4.1.30.6008) [64bit] from 'extras' bucket
Loading WeCom_4.1.30.6008.exe from cache
Extracting WeCom_4.1.30.6008.exe ... done.
Running installer script...done.
Linking D:\scoop\apps\wecom\current => D:\scoop\apps\wecom\4.1.30.6008
Creating shortcut for WeCom (WXWork.exe)
Running post_install script...Remove-Item: Cannot find path 'D:\scoop\apps\wecom\current\$PLUGINSDIR' because it does not exist.
done.
```
Closes #XXXX
=> wecom: Remove post_install script

bucket/whkd.json
Adds support for `whkd`'s aarch64 binaries.
=> whkd: Add ARM64 builds

bucket/git-credential-manager.json
git-credential-manager: The "GitCredentialManager" Github org has been renamed to "git-ecosystem". Update manifest URLs to match.
- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> git-credential-manager: Update urls

bucket/bambu-studio.json
Added an initial manifest to install Bambu Studio (https://github.com/bambulab/BambuStudio).
The versioning is quite strange but it seems the settled (tickets regarding versioning got closed).
=> bambu-studio: Add version 01.09.02.57

bucket/thunderbird-esr.json
Add thunderbird-esr to have 2 different app manifests, one for thunderbird and one for its esr versions only, as suggested by @aliesbelik.
Closes #14123 
Relates to #14203
=> thunderbird-esr: Add version 128.3.2esr

bucket/firewallappblocker.json
=> firewallappblocker@1.9: Fix `url`

bucket/streamlink.json
- Update to 7.0.0-1
- Drop x86
- Fix autoupdate
- Update suggested packages
----
`x86` has been dropped in `7.0.0-1`:
https://github.com/streamlink/windows-builds/blob/7.0.0-1/CHANGELOG.md
I also added `extras/mpv` to the suggested packages.
=> streamlink: Update to version 7.0.0-1

bucket/rawtherapee.json
Updates to 5.11 (which is now an `.exe`)
Builds: https://www.rawtherapee.com/shared/builds/windows/
=> rawtherapee: Update to version 5.11

bucket/openai-translator.json
The shortcut is "OpenAI Translator.exe" now, other than "app.exe".
=> openai-translator@0.4.33: Fix shortcut

bucket/onecommander.json
This is my first effort at updating anything greater than a URL or a typo for the Scoop project.
If I did a good job, please thank me.
If I did a bad job, please thank me for my attempt and be kind in your help to show me how I can do better in the future!
Please note that I've marked this as "relate to #14342" instead of completely fixing it, because getting the latest version required a manual update of the Scoop manifest.  The Scoop manifest auto-update mechanism is not working.  I'm not sure if that's an oversight of the upstream developer, if the official `checkver` URL changed, or if another reason applies.
Relates to #14342
=> onecommander: Update version to 3.91.1.0

bucket/sirikali.json
https://github.com/mhogomchungu/sirikali/releases/tag/1.7.0
>```
>Note on Windows builds:
>
>   SiriKaliQt6-1.7.0 builds are 64 bit and have minimum requirement of windows 10.
>   SiriKali-1.7.0 builds are 32 bit and have minimum requirement of windows 7.
>```
=> sirikali: Add 64bit arch

bucket/stellarium.json
Stellarium already supports Windows ARM64 architecture, but hasn't be added to the scoop bucket yet.
=> Stellarium@24.3: add arm64 version

bucket/inbac.json
Added an initial manifest to install [inbac](https://github.com/weclaw1/inbac), fast interactive image cropping tool.
=> inbac: Add version 2.1.0

bucket/syncthingtray.json
fix config file syncthingtray.ini persist
=> syncthingtray: fix config persist

bucket/another-redis-desktop-manager.json
Updated download and checkver URLs to match new naming scheme from the developer.
Closes #14444
=> another-redis-desktop-manager: Fix download and autoupdate URLs

bucket/paint.net.json
Persists the `UserFiles` directory, which contains files such as palettes and effect presets.
=> paint.net@5.1: Add `UserFiles` to persist

bucket/localsend.json
Localsend json was missing bin section, so it couldn't be started from command line.
Adding bin section to add to path.
Closes #14466
=> localsend@1.16.1: Add "bin" section to add to PATH

bucket/freedownloadmanager.json
URLs correction ~~6.20.0.5510~~
Update the URLs to 6.24.2.5857
Update hashes
URL has changed to https://dn3.freedownloadmanager.org
=> freedownloadmanager: Update to 6.24.2.5857

bucket/waterfox.json
They removed G from new versions, so checkver and autoupdate was not working
Closes #14449
=> Waterfox: repair checkver and autoupdate

bucket/qq-nt.json, bucket/qqnt.json
Closes https://github.com/ScoopInstaller/Extras/issues/13886
Closes https://github.com/ScoopInstaller/Extras/issues/12803
Closes https://github.com/ScoopInstaller/Extras/pull/12866
Closes https://github.com/ScoopInstaller/Extras/pull/11546
Relates https://github.com/ScoopInstaller/Extras/pull/11329 
Relates https://github.com/ScoopInstaller/Extras/pull/11554 
seem like the script in https://github.com/ScoopInstaller/Extras/pull/11546 is not valid for current version qqnt, I'm not add persist script in my PR.
=> qq-nt: Add version 9.9.16.241121

bucket/fvm.json
Update fvm to use FVM_CACHE_PATH instead of FVM_HOME since this has changed in [fvm 3.0.0](https://github.com/leoafarias/fvm/releases/tag/3.0.0).
=> fvm: Update env var to FVM_CACHE_PATH instead of FVM_HOME

bucket/freecad.json
Update [freecad](https://github.com/FreeCAD/FreeCAD/releases) to version 1.0.0
=> freecad: Update to version 1.0.0

bucket/clash-verge-rev.json
clash-verge-rev: Update to Version 2.0.1
Because the portable version has many problems, releases no longer provides a portable version
replace `portable` version with setup.exe
Relates to #13429 #13397 
Closes #14464
=> clash-verge-rev: Update to Version 2.0.2

bucket/clash-verge-rev.json
The shortcuts name was wrong. Also, the services must be uninstalled, or it will prevent to remove related files.
Relates to https://github.com/ScoopInstaller/Extras/pull/14460#issuecomment-2510626853
Closes #14495
Closes #14500
=> clash-verge-rev: Fix shotcuts name and uninstall script

bucket/tinynvidiaupdatechecker.json
Since tinynvidiaupdatechecker requires the .net desktop runtime, I added it as a suggestion.
Sorry for not creating an issue before submitting, it seemed so easy of a change so might as well.
=> tinynvidiaupdatechecker@1.19.1: added .net runtime as suggestion

bucket/musicbee.json
Fixes the URL From Major Geeks for music bee, may want to look into a different source for the package if the hash changes again.
Closes #14486
=> musicbee: fix download url from majorgeeks

bucket/wsl2-distro-manager.json
Closes #14539 
It just patches the manifest with the right url. And next auto update should be ok for 1.8.16
However, if the project do another time a patch release like this, then the problem from #14539 will happen again. 
Though it seems enough to do that for now to no complexify the manifest.
=> wsl2-distro-manager@1.8.15: fix link to windows patched version

bucket/v2rayn.json
Remove 32 bit support as the project no longer ships 32bit
fix 64bit and arm64 downloads by adjusting download names
update to 7.2.3
Closes #14474
=> v2rayn: Remove 32 bit, fix 64bit and arm64 downloads, update to 7.2.3

bucket/sysinternals.json
- fix Scoop manifest
- checkver script, regex, replace
- {64bit,32bit} bin, removed ctrl2cap.exe which is no longer part of the suite
Closes #14593
The URL used in the "checkver" no longer works and in fact produces a 404 response; so the assumed version '2024.7.23' (in the manifest stays fixed till eternity) is stale - unfortunately the existing checkver script does not care to check for any errors:
Furthermore the utility "ctrl2cap.exe" is no longer part of the suite.
- checkver old ; the URL no longer works (I imagine for quite some time); now the only reason why installation fails is that "ctrl2cap.exe" is no longer part of the suite and installation fails upon shim creation
OLD: 
https://github.com/ScoopInstaller/Extras/blob/0a413e614e6387b350791850b32c53fa613a73d7/bucket/sysinternals …
=> SysInternals: Fix Manifest

bucket/beaver-notes.json
Hash extraction on autoupdate broke when author changed formatting of the SHA256 checksums in the GitHub release info.
* Last working version 3.6.0: <https://github.com/Beaver-Notes/Beaver-Notes/releases/tag/3.6.0>
* Broke on current version 3.7.0: <https://github.com/Beaver-Notes/Beaver-Notes/releases/tag/3.7.0>
Could not use `$baseName` because filename of artifact vs. in the list of SHA256 checksums does not match, ref:
* <https://github.com/Beaver-Notes/Beaver-Notes/issues/268>
=> beaver-notes@3.7.0: Fix hash extraction on autoupdate

bucket/nilesoft-shell.json
Closes #14637 
nilesoft-shell is stuck on version 1.9.15 because the installer url's have changed. This PR updates the manifest to change the download & autoupdate urls to the correct location, ensuring 1.9.18 is pulled correctly & also adds an arm64 build.
=> nilesoft-shell: Update to version 1.9.18

bucket/xl-converter.json
Since v1.1.0 ( <https://github.com/JacobDev1/xl-converter/releases/tag/v1.1.0> ) XL Converter now:
* Has a portable .7z version, so we don't have to use the Inno .exe installer.
* Does not require VCRedist anymore, so we can remove `"depends": "extras/vcredist2022"`.
=> xl-converter@1.1.0: Use portable version and remove dep on VCRedist

bucket/glazewm.json
- `glazewm.json` now installs GlazeWM [v3.7.0](https://github.com/glzr-io/glazewm/releases/tag/v3.7.0), featuring performance improvements and support for `.msi` installations on x64 and ARM64 devices. 
- The manifest has been updated to use the `.msi` installation method, as the `.exe` installer does not appear to work with Scoop, likely due to administrative permission requirements.
https://github.com/ScoopInstaller/Scoop/issues/5809
this is still an issue.. If the user needs GlazeWM to run in UIAccess mode then they can choose to install glazewm-np.json which I've also sent a pull request for on nonportable official. 
Closes #14401, #14112 and #13963
Relates to [comment on glazewm open issues](https://github.com/glzr-io/glazewm/issues/645#issuecomment-2514472050)
=> glazewm: Update to version 3.7.0

bucket/clash-verge-rev.json
=> clash-verge-rev: Fix config dir

bucket/calibre.json
Fixes the problem of regular user unreadable calibre install. 
Comments from issue
> 
> Possible Solution
> The problem is its being unpacked in Temp storage and then moved.
> The temp storage of the Administrator accoun to does not give files Users readable permissions.
> 
> I have fixed this in a pull-request by running this afterwards:
> 
> Icacls $dir /t /c /reset
> 
> I have tested it on my environment and it works fine.
> 
> I have also tested behaviour of windows writing files to temp-storage, and then manually copying to scoop-install-dir, and can see that all files and folders recursively do not get the user-readable permission after copy, so a recursive reset is required.
> 
> I'm running an up2date win11.
> 
Scoop and Buckets Version
Closes #14282
- [x ] I have read the …
=> Fix bad  permissions of calibre when installing as administrator - issue #14282

bucket/godot.json
This defaults godot to the console binary. I found it strange that `godot --help` did nothing - since scoop is a terminal installer I think being console-first makes sense. If this is too breaking (not sure if anyone's depending on that behavior) we could also just add `godot-cli` as the console alias.
Closes: #13248 
Related: #13484 (draft) -- I don't address portability in this PR
=> godot: default to console

bucket/ds4windows.json
DS4Windows is now maintained here:
https://github.com/schmaldeo/DS4Windows
=> DS4Windows@3.3.3: Update to v3.9.2 and switch to maintained fork

bucket/librewolf.json
Removed excessive `Remove-Item` function calls, and spaced things out more in an attempt to make it somewhat readable.
=> librewolf: Simplify pre_install

bucket/everythingtoolbar.json
EverythingToolbar supports two modes: Deskband mode (which has been discussed before in #8958) and Launcher mode. This PR adds the launcher variant of EverythingToolbar, which merely requires unpacking of the installer.
Relates to #8958
=> everythingtoolbar: Add version 1.4.1

bucket/7tt.json
This mirrors the installer's startup handling, `post_install` is preferred as `$dir` won't set version numbers.
=> 7tt: Add startup entry

bucket/ultravnc.json
This PR add 
1. a `pre-install` hook in combination with a `persist` section to persist the `options.vnc` and `UltraVnc.ini` settings.
2. a `post-install` hook to install the `SecureVNCPlugin64.dsm` plugin if present in the persist folder
=> ultravnc@1.4.3.6: Persist settings and secure encryption plugin

bucket/ultraiso.json
Please append a URL fragment(#/) to change extension of downloaded file from php to exe.
Otherwise, a file with php extension will be downloaded and installation will fail.
=> ultraiso@9.7.6.3860: Append a URL fragment(#/)

bucket/clash-nyanpasu.json
Remove `pre_uninstall`
Closes #XXXX
```
PS C:\Users\xxx> scoop uninstall -p clash-nyanpasu
Uninstalling 'clash-nyanpasu' (1.6.1).
Running pre_uninstall script...Start-Process:
Line |
2 |  Start-Process "$dir\resources\uninstall-service.exe" -Wait -Verb 'Run …
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| This command cannot be run due to the error: An error occurred trying to start process 'D:\scoop\apps\clash-nyanpasu\1.6.1\resources\uninstall-service.exe' with working directory 'C:\Users\xxx'.
done.
```
There is no such `uninstall-service.exe` in the current version
=> clash-nyanpasu@1.6.1: Remove `pre_uninstall`

bucket/josm.json
> This is mostly so we stop getting tickets where any of the following are true:
> * User is missing a required JVM argument
Related info:
* https://josm.openstreetmap.de/ticket/23355
* https://josm.openstreetmap.de/ticket/23489
=> josm@19096: Add missing JVM arguments to fix startup error

bucket/vscode.json, scripts/vscode/install-github-integration.reg, scripts/vscode/uninstall-github-integration.reg
This pull request addresses an annoying issue where Visual Studio Code (vscode) installed via the 'Extra' bucket is not recognized by GitHub Desktop. Consequently, users are unable to open files in vscodedirectly from the GitHub Desktop interface using the right-click context menu.
Inspired by https://github.com/desktop/desktop/issues/13798#issuecomment-1687374045, this pull request adds two reg files for installing/uninstalling github-vscode integration, and updates vscode.json to replace variables in reg files in each installation.
Closes #12555
=> vscode: Add GitHub integration

bucket/opera.json
opera.exe from the *version* directory is copied to the *root* directory and will be used instead of launcher.exe.
Closes #14596
Relates to #14513
- [✓] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> opera@115.0.5322.119: Issue with launcher.exe has been solved

bucket/capframex.json
The version naming style changes from $version to $version_release.
Closes #14664
=> capframex@1.7.4: Update download & autoupdate urls

bucket/totalcommander.json
**TotalCommander** *x32* and *x64* executables are stored in versioned subfolders matching the `$cleanVersion` *checkver* variable, instead of *win* folder:
https://totalcommander.ch/1150/tcmd1150x64.exe
https://totalcommander.ch/1150/tcmd1150x32.exe
vs
http://totalcommander.ch/win/tcmd1150x64.exe
http://totalcommander.ch/win/tcmd1150x32.exe
=> totalcommander: Fix download and autoupdate links

bucket/kmeans-colors.json
Closes #14623
It says on the `README.md` that the crate is licensed under either MIT or Apache. How can I reflect this fact on the manifest? Currently I used only "MIT" for the field.
=> kmeans-colors: Add version 0.6.0

bucket/podman-desktop.json
Add the ability to preserve and purge data/config for Podman Desktop.
This PR also covered the migration process.
=> podman-desktop: Add data/config persist

bucket/proton-mail-export.json
Adds proton-mail-export tool, a cli software to export (or restore) all your emails.
Closes #11420
=> proton-mail-export: Add version 1.0.4

bucket/open-tv.json
=> open-tv: Add version 1.3.0

bucket/sourcegit.json
Closes #14729
> You can create a data folder next to the SourceGit executable to force this app to store data (user settings, downloaded avatars and crash logs) into it (Portable-Mode). Only works on Windows.
=> sourcegit: Update post_install and persist

bucket/stirling-pdf.json
Using JAR file to launch Stirling-PDF
- Closes https://github.com/ScoopInstaller/Extras/issues/14662
=> stirling-pdf: Use JAR to launch app

bucket/totalcommander.json
After update TotalCommander this file got lost and all connections are gone.
=> totalcommander: Add sftpplug.ini to persist

bucket/beaver-notes.json
New changes from Beaver Notes v3.7.0 -> v3.8.0:
* ARM64 and X64 are now in the same `.exe` file.
* Checksum is now in a dedicated `checksums.sha256` file in GitHub releases.
I also noticed the persisted `data` directory was not in use.
And making a shortcut with `--user-data-dir="$dir\data"` seemed to work, but Beaver Notes would give an error message each time it launched.
Ref:
* <https://github.com/Beaver-Notes/Beaver-Notes/issues/268>
* <https://github.com/Beaver-Notes/Beaver-Notes/issues/271>
* <https://github.com/Beaver-Notes/Beaver-Notes/issues/273>
=> beaver-notes@3.8.0: Fix checkver + hash extraction + installer logic

bucket/glazewm.json
addresses https://github.com/glzr-io/glazewm/issues/951
=> glazewm@3.8.1: Fix wrong binary added to PATH

bucket/chatterino.json
Format of Chatterino portable download path has changed
=> chatterino: fix checkver, update to 2.5.2

bucket/lightbulb.json
Hi, I've just noticed that the license field for `lightbulb` is wrong. There was a [license change](https://github.com/Tyrrrz/LightBulb/commit/a8b9582b1cb8d706bf8a619442fb8de86ef5961e) from GPL to MIT. This PR updates the info in the bucket.
=> lightbulb: Correct license

bucket/schismtracker.json
In 20241225, schism had changed the name of the binary from i686 to i386, to reflect the architecture change (i686 is Pentium Pro or newer, i386 is much more broad).
=> schismtracker: Update to version 20250202

bucket/godot-mono.json
Defaults to the console shim of Godot Mono, similar to https://github.com/ScoopInstaller/Extras/pull/14268
=> godot-mono: Default to console

bucket/openai-translator.json
The shortcut name has been changed from `OpenAI Translator.exe` to `app.exe`.
=> openai-translator@0.4.32: fix shortcuts file name

bucket/fork.json
The latest version of the fork modified the file structure of the installation package, and this pull request has addressed the issue.
=> fork@2.6.0: fix extract_dir

bucket/musicbee.json
Updated majorgeeks url, longterm a better source is needed in future that doesn't get deactivated frequently.
Closes #14955
=> musicbee: fix url for 3.5.8698

bucket/cherry-studio.json
Cherry Studio has 3.4k+ stars: https://github.com/CherryHQ/cherry-studio 
Note: cherry-studio has a standard installer but it stores user data in AppData. For portable processment, I use the (un)installer script and it might seems a little bit elaborate.
=> cherry-studio: Add version 0.9.24

bucket/hoppscotch.json
"Hoppscotch.exe" to "hoppscotch-desktop.exe" to fix the shortcut,
=> hoppscotch@25.2.0-0: change the executable name

bucket/miniconda3.json
=> miniconda3: update to version 25.1.1-2

bucket/synfig-studio.json
- Updated `synfig-studio` to version 1.5.3
- Changed download URLs to use GitHub Releases instead of FossHub
- Updated SHA256 hashes
=> synfig-studio: Update to version 1.5.3

bucket/cromite.json
I added Cromite browser to the bucket. Cromite is a fork of Chromium, that has cross-platform binaries, including Android. It is a great addition along Thorium, ungoogled-chromium, Woolyss, and so.
=> cromite: Add version 134.0.6998.89

bucket/prusaslicer.json
updated the checkver to use github
updated the autoupdate URL
updated to PrusaSlicer to 2.9.1
=> prusaslicer: Update to version 2.9.1

bucket/wait4x.json
The repository address of Wait4X changed from "https://github.com/atkrad/wait4x" to "https://github.com/wait4x/wait4x".
=> Wait4X: Change the repository address

bucket/tailscale.json
Fix the problem that raise `Could not find 'Tailscale'! (error 16)` exception during extracting the MSI installer.
Closes #15172
=> tailscale@1.82.0: Fix could not find 'Tailscale'

bucket/zaproxy.json
Both 2.16 and now 2.16.1 [require Java 17+](https://www.zaproxy.org/docs/desktop/releases/2.16.0/#update-to-a-minimum-of-java-17).
=> zaproxy@2.16.1: Suggest Java 17

bucket/ipfs-desktop.json
The name of the Windows Setup exe has changed in v0.42.0.
=> ipfs-desktop@0.42.0: Use new setup package name

bucket/naps2.json
Fixes the autoupdater that has been broken for several months, and updates to latest version.
=> NAPS2: Update to version 8.1.2, fix autoupdate

bucket/duplicati.json
- update version to latest build
- update regex to use `stable` release since `beta` has been retired
- a separate manifest can be created for `canary` if desired but is not included here
- support for 32-bit and 64-bit architectures
- license is MIT now
Closes #14856
=> duplicati@2.1.0.5: update to stable release, add architecture, change license

bucket/vcxsrv.json
removed 32bit installer, updates to current version
Closes #15167
=> vcxsrv: Update to version 21.1.16.1, deprecate 32bit version

bucket/sdl2-image.json, bucket/sdl2-mixer.json, bucket/sdl2-ttf.json, bucket/sdl2.json
This pull request includes updating `checkver` for SDL and its related packages' 2.x releases correctly, not for v3 releases.
Closes #15128
=> sdl2(-image|-mixer|-ttf): Update checkver and pin to 2.x releases

bucket/ghidra.json
as of [this commit](https://github.com/NationalSecurityAgency/ghidra/commit/966e6fddf3e77e21fac27a9ecf79976066443bdf) during the development of Ghidra 11.2, the minimum JDK version was bumped from 17 to 21.. I just noticed that the Scoop manifest for this one was not updated.
=> ghidra: fix minimum JDK version

bucket/syncthingtray.json
Adds ARM64 support to syncthingtray manifest
Closes #14894
=> syncthingtray: Add arm64 version

bucket/gitify.json
Gitify 6.3.0 filename has changed from the previous `Gitify-Setup-6.2.0.exe` to `Gitify.Setup.6.3.0.exe`. This PR fixes it and the autoupdate URL as well.
=> gitify@6.3.0: fix filename that has changed

bucket/xan.json
This fixes xan updates (one of the previous versions do not provide executables and the file names changed). Also, it gets the checksums which are not included in the releases.
Closes #15370
- [X ] Use conventional PR title: `<manifest-name[@version]|chore>: <general summary of the pull request>`
- [X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)
=> xan@0.49.3 - Fix update and added checksums

bucket/exifglass.json
Closes #15365
Maybe we have an alternative workaround for keeping dotnet version detection... For now, I've set `checkver` with `github` instead.
=> exifglass: Update `checkver` and `autoupdate`

bucket/gramps.json
as the naming convention of the file has changed it was not able to autoupdate, it has been fixed
=> gramps@6.0.1: Fix autoupdate

bucket/windowsdesktop-runtime-lts.json
The latest version of `windowsdesktop-runtime-lts` is now `8.0.15`.
- Update `windowsdesktop-runtime-lts` to version `8.0.15` & fix `checkver`.
Closes #15436
=> windowsdesktop-runtime-lts: Update to version 8.0.15, fix checkver

bucket/musicbee.json
Closes #15454
This PR tweaks the `pre_install` script, and adds a `post_install` script for MusicBee. The changes properly persist directories (BBplugins, Equaliser, Plugins, and Skins) that previously were only copied into MusicBee's persisted directory, but not symlinked back into the application directory, thus not properly persisting the data.
While persisting skins was my main concern, it was little extra work to ensure the other 3 directories mentioned were properly persisted as well. See #15454 for more details.
The `post_install` script loops over the 4 directories mentioned above and copies their contents into the same directories in the persisted data directory to ensure that if default content within them is ever updated, we get a copy in our persisted data.
Perhaps worth …
=> musicbee: improve persistence

bucket/processing4.json
This pull request aims to fix autoupdate for the package `processing4` and update it right away, as well as adjust to new zip context. This has been tested on my personal bucket https://github.com/itsHardStyl3r/scoop-personal/commit/510bc9d8d1f1faff48beb1a79dddeebdb2beebf4 with Excavator commit https://github.com/itsHardStyl3r/scoop-personal/commit/de0dcd17c3f41048e1284be81657337afb226f1c.
4.4.4 is the latest version as of writing this, verified at https://github.com/processing/processing4/releases.
Closes https://github.com/ScoopInstaller/Extras/issues/15491.
=> processing4@1297-4.3.4: Update autoupdate url and package

bucket/betterbird.json
According to website, betterbird 128 is stable now. Regex fixed to "esr" to stick to ESR releases only.
=> betterbird: Bump to 128

bucket/pdfarranger.json
related to 
```
Extracting pdfarranger-1.12.0-windows-portable.zip ... Exception: G:\Applications\Scoop\apps\scoop\current\lib\core.ps1:889
Line |
889 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Could not find 'pdfarranger-1.12.0'! (error 16)
```
Modified the `extract_dir` field from `pdfarranger-1.12.0` to `pdf arranger-1.12.0`
=> pdfarranger@1.12.0: fix extract_dir

bucket/googlechrome.json
Reference: https://scoop.sh/UpdateTracker/googlechrome/chrome.min.xml (content update: https://github.com/ScoopInstaller/UpdateTracker/commit/f7bbf67ac8d543a717d4f16f8d2b11deb3baa716)
Related work: ScoopInstaller/Versions#2355 , ScoopInstaller/Versions#2356 and ScoopInstaller/Versions#2357  
Add _uncompressed before .exe
As the installer is not compressed, we can get Chrome-bin directly from dl.7z . So the install process is just to copy files inside Chrome-bin to $dir then remove Chrome-bin
Closes #15630
Closes #15631 (duplicated)
Closes #15632 (duplicated)
Closes #15636 (duplicated)
Closes #15643 (duplicated)
Closes #15645 (duplicated)
=> googlechrome@137.0.7151.120: Fix download URL

bucket/blender.json
Update executable name to blender-launcher.exe in blender.json.
Closes #15648
=> blender@4.4.3: Update executable name to blender-launcher.exe

bucket/cryptomator.json
update the extract_dir
```
Line |
889 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Could not find 'Cryptomator'! (error 16)
```
---
=> cryptomator@1.17.0: fix extract_dir

bucket/rabbitmqadmin-ng.json
Related to the following:
rabbitmq.json
Replacement for:
rabbitmqadmin.json
=> rabbitmqadmin-ng: Add version 2.2.1

bucket/qbittorrent-enhanced.json
fix the error message:
```
Extracting qbittorrent_enhanced_5.1.1.10_x64_setup.exe ... done.
Running pre_install script...Remove-Item: Cannot find path 'G:\Applications\Scoop\apps\qbittorrent-enhanced\5.1.1.10\uninst.exe' because it does not exist.
```
=> qbittorrent-enhanced@5.1.1.10: fix pre_install

bucket/sonic-pi.json
Removes `qt` from shortcut path.
Closes #15680
=> sonic-pi@4.6.0: fix shortcut path

bucket/roughgrep.json
As all the files are now in the root of the archive, extract_dir is no longer necessary
Closes #15705
=> roughgrep@3.16.2: remove extract_dir

bucket/emacs.json
This adds a shim for emacsclient, which is required for editor integration where the client process should not exit until server buffers have finished.
Closes #15714
=> emacs@30.1: Add shim for emacsclient

bucket/v2rayn.json
- `v2rayn@7.12.7`: Remove reliance on Xray core, since it is [contained](https://github.com/2dust/v2rayN/wiki/Release-files-introduction) in v2rayN releases.
Relates to #14692
Closes #15726
Closes #15728
=> v2rayn@7.12.7: Remove reliance on Xray core

bucket/mpc-be.json, bucket/mpc-hc-fork.json
Both manifests suffered from the well-known issue that "persist" always creates directory junctions by default.
=> mpc-be|mpc-hc-fork: Fix intended hardlinks becoming junctions

bucket/raspberry-pi-imager.json
At https://github.com/ScoopInstaller/Extras/commit/752e62ef03298ebb9882d118e840b797355e17f3, `#/dl.7z` in `url` is removed, in order to use innosetup. But `autoupdate/url` still has `#/dl.7z`. So, autoupdate breaks this manifest. This PR fixes `url` and `autoupdate/url` to remove `#/dl.7z`.
Closes #15768.
=> raspberry-pi-imager@1.9.5: Fix `autoupdate/url` to reflect `url` change.

bucket/aida64extreme.json
aida64extreme: Upgrade download & update links to use HTTPS
=> aida64extreme: Upgrade download & update links to use HTTPS

bucket/caesium-image-compressor.json
caesium-image-compressor: Upgrade homepage to HTTPS
=> caesium-image-compressor: Upgrade homepage to HTTPS

bucket/codeblocks-mingw.json
codeblocks-mingw: Uprade homepage to use HTTPS
=> codeblocks-mingw: Upgrade homepage to use HTTPS

bucket/exifglass.json
- `exifglass@1.9.0.0`: Fix extract_dir.
Closes #15940
=> exifglass@1.9.0.0: Fix extract_dir

bucket/electronmail.json
- `electronmail@5.3.2`: Fix shortcut issue. [The executable is renamed back to `electron-mail`](https://github.com/vladimiry/ElectronMail/releases/tag/v5.3.2).
Closes #15941
=> electronmail@5.3.2: Fix shortcut issue

bucket/qq.json
- `qq`: Update to version 9.7.25.29411, fix checkver.
Closes #15928
Relates to #15917
=> qq: Update to version 9.7.25.29411, fix checkver

bucket/sejda-pdf.json
=> sejda-pdf@7.8.8: remove extract_dir, app now resides in the zip root

bucket/session.json
- Switch to the actual repo.
- Update to latest version.
As indicated in the [deprecation note](https://github.com/oxen-io/session-desktop#repository-deprecated):
> This repository is now deprecated. However, Session Desktop is still actively developed [here](https://github.com/session-foundation/session-desktop). This is in line with announcements from [Session](https://getsession.org/blog/introducing-the-session-technology-foundation) and the [OPTF](https://optf.ngo/blog/the-optf-and-session), indicating that the OPTF has handed over the stewardship of the Session Project to the [Session Technology Foundation](https://session.foundation/), a Swiss-based foundation dedicated to advancing digital rights and innovation.
=> session: Update to version 1.16.6, switch to the actual repo
